### ISSUE TITLE
After showing the Fluxion logo, imminently exits

### ISSUE THREAD

**Issue by thebeastgamer25** [deltaxflux/fluxion#1]
Kail linux, with all dependencies

**Comment by Jason66Wang** [comment]
Having the same issue with the latest version, just updated it today

**Comment by beew0lf** [comment]
Having the same issue with the latest version.....imminently exits.

**Comment by sam0hack** [comment]
Yes, I also tested with kali and Ubuntu both have the same problem.

**Comment by beew0lf** [comment]
Latest rev. [137]

root@kali:~/fluxion#

**Comment by dennishrv** [comment]
updated today, now it shuts down as soon as it starts

**Comment by sam0hack** [comment]
@deltaxflux Please fix this issue. I'll Create deb package for it.

**Comment by pinnamanivenkat** [comment]
The Script is incomplete. As there are files missing in the package. 
Access to previous version would be helpful in resolving the errors

**Comment by Biggregw** [comment]
Yes i think some of the files are missing. 
Worked fine yesterday.

**Comment by thebeastgamer25** [comment]
Yep, we gotta fix this

**Comment by sam0hack** [comment]
Does anyone have last working version?

**Comment by beew0lf** [comment]
@sam0hack no...It appears to be automatically updated....

**Comment by thebeastgamer25** [comment]
@everyone https://github.com/wi-fi-analyzer/fluxion

**Comment by alihasanmogal** [comment]
fake ap not create any one help me

**Comment by alihasanmogal** [comment]
plzzzz guys help me all step is complate but last moment fake ap not create

**Comment by dennishrv** [comment]
@thebeastgamer25 upon launching it updates to ver 137 and keep crashing on launch

**Comment by thebeastgamer25** [comment]
Dangit. @deltaflux come on buddy we need you

**Comment by alihasanmogal** [comment]
any one sloved why not create fake ap???

**Comment by thebeastgamer25** [comment]
NO. DONT SPAM US. PLEASE

**Comment by hugetechabhishek** [comment]
I have the old version of fluxion master if anyone want that he or she can ping me at fb.com/hugetechabhishek

I give give that file at fb
![image](https://cloud.githubusercontent.com/assets/26200456/23587391/da160ec8-01d0-11e7-8b92-395eef80ce57.png)

**Comment by thebeastgamer25** [comment]
@hugetechabhishek can't u just upload it to Dropbox?

**Comment by sam0hack** [comment]
@hugetechabhishek can you tell me it's version or revision?

**Comment by alihasanmogal** [comment]
@hugetechabhishek plz share ur whatsapp number i am also india i have some problems so plz tell me ur number

**Comment by sam0hack** [comment]
@hugetechabhishek Sorry can't share my number publically.

**Comment by iberelrj** [comment]
Same to me

**Comment by thebeastgamer25** [comment]
@hugetechabhishek JUST UPLOAD IT TO DROPBOX. PLEASE.

**Comment by sam0hack** [comment]
@thebeastgamer25 I uploaded revision 121 it's working fine on Kali https://github.com/sam0hack/fluxion

**Comment by thebeastgamer25** [comment]
@sam0hack thanks man

**Comment by alihasanmogal** [comment]
It working any new update???

**Comment by sam0hack** [comment]
Just added the Debian package in the https://github.com/sam0hack/fluxion/ repository if anyone wants to install fluxion in the system download the https://github.com/sam0hack/fluxion/raw/master/DEB/fluxion.deb deb package and After installing run fluxion-Installer for installing dependencies and run fluxion for using fluxion.

**Comment by alihasanmogal** [comment]
plz code show @sam0hack

**Comment by sam0hack** [comment]
@alihasanmogal code show?

**Comment by alihasanmogal** [comment]
how to .deb file use or replace?

**Comment by alihasanmogal** [comment]
i dnt knw what u say brother plz tell me again what is .deb file and more plz brother

**Comment by alihasanmogal** [comment]
@sam0hack PLZ HELP WHY NOT CREATE FAKE AP I USE TPLINK ADAPATER PLZ HELP ME BROTHER

**Comment by sam0hack** [comment]
Debian package or .deb file is an application for Debian based systems. Sometimes it's time-consuming to go to fluxion folder whenever you want to run it. If you installed fluxion .deb you can run it from anywhere. In other words, It's something like installing .apk app in you android phone

**Comment by alihasanmogal** [comment]
@sam0hack not create fake ap plz help me buddy...

**Comment by sam0hack** [comment]
@alihasanmogal I'm not sure about TPLINK adapters I'm using alfa awus051nh v2, and it's working awesome even I'm using my neighbor's internet right now. ;)

**Comment by alihasanmogal** [comment]
lol @sam0hack everything is super in fluxion brother atlast moment fake ap is not create

**Comment by sam0hack** [comment]
@alihasanmogal these are some troubleshooting tips. #1 Update latest wifi adapter drivers #2 restart system. #3 try to update/ upgrade OS maybe kernel too.

**Comment by alihasanmogal** [comment]
@sam0hack can u connect my pc and check the problem.???

**Comment by Hitman14** [comment]
Has this been resolved yet?

**Comment by protosot** [comment]
Nope. I tried reinstalling and the installer is not a part of the package either, so I think he is working on it.

**Comment by Asux3** [comment]
Hi
This latest version fluxion (v136)
https://github.com/Asux3/fluxion

**Comment by deltaxflux** [comment]
**Short expression:**
I shut down the original fluxion repo because of the law in Germany. It was **not** a spontaneous reaction more or less it was planned since February. The public  version will brick all other fluxion versions, because fluxion should not longer be public. 

**@everyone 
Please don't fork this project and share old files. It would be a pleasure for me.** 

Something about the new script: 
The only thing what the script does is: 

1. Delete Files

- Fluxion folder
- Tmp directory
- Handshake and pwlog folder
- Backups 

If you want to use it please use it private making this public again is against the License Agreement. Good luck !

**Comment by thebeastgamer25** [comment]
Alright guys, close all mirrors. If you need a mirror, please PM me
