### ISSUE TITLE
can't open fake login page

### ISSUE THREAD

**Issue by kushujus** [deltaxflux/fluxion#100]
victim's computer can't open fake login page when trying to open google.com, facebook.com, youtube.com and other website with secure connection.

**Comment by aquilabianca8** [comment]
Same problem..

Il giorno 06 set 2016, alle ore 00:16, kushujus <notifications@github.com<mailto:notifications@github.com>> ha scritto:


victim's computer can't open fake login page when trying to open google.com<http://google.com>, facebook.com<http://facebook.com>, youtube.com<http://youtube.com> and other website with secure connection.

-

**Comment by strasharo** [comment]
SSL is not supported.

**Comment by kushujus** [comment]
Before 4 weeks was everything ok. Now SSL is not supported :)

**Comment by aquilabianca8** [comment]
First, Deltaxflux: great work, congratulations!??

Do you any way to fix support SSL..?

Thanks in advance;)

Il giorno 06 set 2016, alle ore 18:54, kushujus <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Before 4 weeks was everything ok. Now SSL is not supported :)

-
