### ISSUE TITLE
they shutdown all the wlan

### ISSUE THREAD

**Issue by ReneTejeda** [deltaxflux/fluxion#101]
i have two wireless adapter,  one to use to fluxion (wlan1) and the other to connect a network (wlan0) to use VNC, 
but when i scan for wifi networks in fluxion, they shutdown wlan0 and lost my vnc connection.

what i can do ?

i'm using raspbian, raspberry pi 3. all works great except this. thanks

**Comment by strasharo** [comment]
https://github.com/deltaxflux/fluxion/issues/90
