### ISSUE TITLE
error at scanning

### ISSUE THREAD

**Issue by theoneandonly-vector** [deltaxflux/fluxion#103]
#########################################################                    #                                                       #                    #      FLUXION 0.23    < Fluxion Is The Future >        #
# by Deltax, Strasharo and ApatheticEuphoria            #                    #                                                       #                    #########################################################
wc: /tmp/TMPflux/dump-01.csv: No such file or directory
/opt/fluxion/fluxion: line 1154: [: -le: unary operator expected             cat: /tmp/TMPflux/dump-01.csv: No such file or directory                     expr: syntax error
                        WIFI LIST                                             ID      MAC                      CHAN    SECU     PWR   WPS ESSID
grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory                                          grep: lines:: No such file or directory
grep: '/tmp/TMPflux/dump-01.csv': No such file or directory
  1)    head: invalid number of lines: '/tmp/TMPflux/dump-01.csv'             100%

 (*)Active clients

        Select target. For rescan type r
      #>

**Comment by deltaxflux** [comment]
Take a look at a issue #99
