### ISSUE TITLE
Realtek RTL8187 Problems

### ISSUE THREAD

**Issue by jackditto** [deltaxflux/fluxion#104]
I am not sure why exactly this isn't working, but whenever I try to run Fluxion using my Realtek RTL8187 adapter, I get the error:

at0: ERROR while getting interface flags: No such device
SIOCSIFADDR: No such device
at0: ERROR while getting interface flags: No such device
SIOCSIFNETMASK: No such device
SIOCADDRT: Netwrork is unreacheable

I am sure this adapter supports injection/ AP support. I have another, smaller adapter that works just fine with Fluxion, but obviously the larger one is ideal. Is anybody else having a similar problem? I am running Kali 2016.1 (brand new) so I know I did not mess anything up. Any help is appreciated, thanks!

**Comment by deltaxflux** [comment]
Well i personally don't use this card but I agree with you monitor mode is supported.

When did you get the error after selection the channel? Let's see if it is a issue by fluxion or that the wifi card is unsupported. 

You can check the fix at the issue #99

**Comment by strasharo** [comment]
Are you able to launch airbase-ng manually with this adapter and does it work for you?
