### ISSUE TITLE
After Obtaining IP,opening Login Page and Automatically disconnecting ,then reconnecting. loop

### ISSUE THREAD

**Issue by kumareshr** [deltaxflux/fluxion#105]
Hello,

Thanks for your program,am facing some kind issue with login page : 

After start fake evil-twin AP,User get a IP by DHCP but when user clicks or open a login page ,It automatically disconnects the connections and reconnecting,accidentally I installed PHP7, After refereed past threads,I repalced with php7 with php5 but issue still remains same, I looking for your suggestions ,I want to make it clean.

Thanks :100:

**Comment by deltaxflux** [comment]
Well if I understand you correctly the users which join the fake Ap get disconnected. Have you Tried another login page?

**Comment by kumareshr** [comment]
I tried ,am facing the same issue ..any other suggestions.. Thanks :+1:

**Comment by deltaxflux** [comment]
Fix: https://www.mediafire.com/?29ykik8kj17wwe3

**Comment by deltaxflux** [comment]
Is it working ?

**Comment by kumareshr** [comment]
sorry still not checked ,sure I will give give feedback after I tried that fix ..

**Comment by deltaxflux** [comment]
ok good
