### ISSUE TITLE
WPA KEY RETRIEVAL

### ISSUE THREAD

**Issue by orphee225** [deltaxflux/fluxion#106]
Hi !
After few days using your wonderful Fluxion, I noticed that we can get WPA keys only from connected client's browsers. In the case of android users that only connect from FacebookAPP or InstagramAPP...
Is there a way to force them using their mobile's web browser ? 
or
just make a kind of popup window in order to let them type the wpa key ?

**Comment by deltaxflux** [comment]
They already get a message called sign in. After they file auto redirect to the site

**Comment by orphee225** [comment]
Okay, thanks !

**Comment by deltaxflux** [comment]
Here what it looks like: 

![android](https://1.bp.blogspot.com/-voQjwf9sJpM/V77xyMYRoRI/AAAAAAAABsk/iqwJEGsPuxEezL6nZ-_bm_GCb2_B14GIwCLcB/s1600/Smartphone%2Bstep.jpeg)
