### ISSUE TITLE
Client not connecting to Fake AP - Fluxion Ver 0.23 Rev. 50 on Kali Rolling 2016.2.3

### ISSUE THREAD

**Issue by Schwarzhund** [deltaxflux/fluxion#107]
Fluxion: Ver 0.23 Rev. 50 on Kali Rolling 2016.2.3 (kernal release Ver 4.6.0-kali1-amd64) running in VMware. (Using **php5-cgi**).

Since I'm still unable to get clients to connect to the Fake AP, I set up a Fluxion test lab with:
	A test AP configured with:
		- a visible SSID
		- WPA2-PSK with AES
		- Low transmit power
	_A single Windows test client_ located 16 m from the test AP.
	Kali Laptop with TX-power=27dBm & directional antenna 0.5 m from Client.

**Steps:**
1) Manually connected client to the test AP. (verified connection to test AP via router management interface).
2) Started Fluxion.
3) After Ctrl-C in airodump-ng window, the networks list shows my test AP, but does NOT show * to indicate that the test AP has an active client. (Does "active client" mean the same as "connected client"?)
4) From the networks list I selected my test AP. 
5) Used "Fake AP" option with Aircrack-ng.
6) Chose "Web Interface"
7) I got a handshake very quickly:
![capturing data](https://cloud.githubusercontent.com/assets/20869864/18408684/084511ca-76eb-11e6-87ea-4b59e3923ede.JPG)

9) Test client is now disassociated from the test AP.
10) "WiFi Information" window shows NO clients online.
11) I tried to manually connect the test client to the fake AP, but it would not connect, even if I shutdown the test AP!
![no associated client](https://cloud.githubusercontent.com/assets/20869864/18408695/287df33a-76eb-11e6-9ff4-e2df268af25f.JPG)

Is this an issue, or am I doing something wrong?

**Comment by deltaxflux** [comment]
Well at the moment I don't detect any issue. Are you sure that the fake AP is generated correctly. 

Edit: scan with another device if the AP is generated correctly e. G. Scan with a mobile device. 

Yes active clients means clients which are at the moment connected.

**Comment by deltaxflux** [comment]
Well i don't read the text after the pictures. Try to reinstall dhcpd server and see what it brings. Another thing what is curious is that there are clients connected to the network.

**Comment by Schwarzhund** [comment]
OK, I will reinstall dhcpd server and take another look today. Please keep this thread open. Thanks :)

**Comment by Schwarzhund** [comment]
Well, Using an Android client I manually re-connected to the Fake AP many times, but never got the password. l emailed you  a screen recording (deltax.fluxion@gmail.com) that might give you some clues? (You'll see more activity after the first 10-15 seconds).

**Comment by Schwarzhund** [comment]
After:
      **apt-get update
apt-get dist-upgrade
      apt-get install isc-dhcp-server -y**
Does dhcp server need to be manually configured, or does Fluxion handle the configuration?

**Comment by deltaxflux** [comment]
Try to comment line 3875

**Comment by deltaxflux** [comment]
Fix: https://www.mediafire.com/?29ykik8kj17wwe3

**Comment by Schwarzhund** [comment]
@deltaxflux: I replaced the ver 0.23 rev 50 _fluxion_ shell script with the new one on https://www.mediafire.com/?29ykik8kj17wwe3. (323,848 bytes). 

1. Will this link always be the location of the latest stable working build?

2.  Above you said, "Try to comment line 3875". I'm assuming that meant before the Fix: https://www.mediafire.com/?29ykik8kj17wwe3 , correct? 

3. Are there any lines in this new script that must be commented?

Vielen Dank!

**Comment by HKHAN16** [comment]
Hello deltaflux, i have installed fluxion on my usb persistent Kali Linux 64 bit 2016.2 and had same issue.

Any idea?
