### ISSUE TITLE
line 1154: [: -le: unary operator expected

### ISSUE THREAD

**Issue by chadgrant** [deltaxflux/fluxion#108]
I just cloned a few minutes ago ...

#########################################################
#                                                       #
#      FLUXION 0.23    < Fluxion Is The Future >        #
# by Deltax, Strasharo and ApatheticEuphoria            #
#                                                       #
#########################################################

wc: /tmp/TMPflux/dump-01.csv: No such file or directory
./fluxion: line 1154: [: -le: unary operator expected
cat: /tmp/TMPflux/dump-01.csv: No such file or directory
expr: syntax error
                        WIFI LIST

 ID      MAC                      CHAN    SECU     PWR   ESSID

grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines:: No such file or directory
grep: ‘/tmp/TMPflux/dump-01.csv’: No such file or directory
  1)    head: invalid number of lines: ‘/tmp/TMPflux/dump-01.csv’                         100%

 (*)Active clients

        Select target. For rescan type r
      #>

**Comment by deltaxflux** [comment]
is manually monitor injection supported ?

**Comment by CalibroZero** [comment]
The same thing happens to me with the same card

**Comment by ReneTejeda** [comment]
the same thing happens to me with tp-link WN722N

**Comment by CalibroZero** [comment]
I just installed everything on a new machine, with the same alpha card and the problem seems to have disappeared

**Comment by deltaxflux** [comment]
So I can close the issue ?

**Comment by ReneTejeda** [comment]
yes. for some unknown reason is working now
