### ISSUE TITLE
"create a SSL certificate" after handshake..?

### ISSUE THREAD

**Issue by aquilabianca8** [deltaxflux/fluxion#111]
Hello! :)

My system:
- PC mobile with Kali Rolling usb live persistence (no VM)
- USB card Alfa AR9271
- Fluxion 0.23 rev.51 

1) After captured handshake, i type option 1 (check handshake) and appears this issue:
![1](https://cloud.githubusercontent.com/assets/17140111/18453203/72869496-793e-11e6-837c-f262daf131cc.jpg)

2) Then type option 1 (create a SSL certificate) and the FAKEDNS windows don't start:
![2](https://cloud.githubusercontent.com/assets/17140111/18454053/81b19aca-7942-11e6-9c71-920e4a8e7e50.jpg)

3) And after don't appears FAKE LOGIN to type the password..

Any suggestions?

Thanks in advance;)

**Comment by deltaxflux** [comment]
Well Fakedns is working. However the issue " is not a issue " because it will check if there is any pem file for ssl. If there isn't any it will redirect you to the page. Try the last version. Let's see. However I think that it is not a issue created by fluxion

**Comment by deltaxflux** [comment]
I fix now that the ssl certificate will generated every time

**Comment by aquilabianca8** [comment]
Ok deltaxflux: next time i will try and i will inform you!
Thanks!??

Il giorno 13 set 2016, alle ore 19:53, deltax <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Well Fakedns is working. However the issue " is not a issue " because it will check if there is any pem file for ssl. If there isn't any it will redirect you to the page. Try the last version. Let's see. However I think that it is not a issue created by fluxion

-

**Comment by aquilabianca8** [comment]
Ok deltaxflux: next time i will try and i will inform you!
Thanks!????

Il giorno 13 set 2016, alle ore 20:14, deltax <notifications@github.com<mailto:notifications@github.com>> ha scritto:


I fix now that the ssl certificate will generated every time

-

**Comment by smiki217** [comment]
im having same issue. i used fluxion over 30 times and it worked perfectly, but since version 0.51, and now even when version 0.52 came out, it doesnt work for me. i connect with my device to the fake ap that i created, but it never shows me the fake page it used to show, and therefore making it impossible for me to get the password. can you please explain me if im doing something wrong (but like i said i used fluxion too many times), or there is a bug in the new versions?

**Comment by aquilabianca8** [comment]
Since Fluxion become rev.52, deltaflux has fixed SSL iusse. Fine.

However, now i'm in the same iussue of smiki217:
i connect with my device to the fake ap that i created, but it never shows me the fake page it used to type password, therefore it's impossible for me to get the password..

Any suggest? I'm doing some wrong?

Il giorno 14 set 2016, alle ore 19:23, smiki217 <notifications@github.com<mailto:notifications@github.com>> ha scritto:


im having same issue. i used fluxion over 30 times and it worked perfectly, but since version 0.51, and now even when version 0.52 came out, it doesnt work for me. i connect with my device to the fake ap that i created, but it never shows me the fake page it used to show, and therefore making it impossible for me to get the password. can you please explain me if im doing something wrong (but like i said i used fluxion too many times), or there is a bug in the new versions?

-
