### ISSUE TITLE
how to add new sites for login page

### ISSUE THREAD

**Issue by acer1528** [deltaxflux/fluxion#112]
How to add new sites login pages in script....nd TP LINK upgrade site login page isn't showing in script...pls help...thank u

**Comment by BrunoX11** [comment]
I am with the same problem, i need run TP-LINK page, so how to start? Because I translate for my language (Portuguese Brazilian) but i can't put the page to run... sorry my english and thank u guys!

**Comment by deltaxflux** [comment]
But it to the Site folder. Modify the function ConnectionRESET  function. Add a function for your login page. Copy all file to $DUMP_PATH/data

**Comment by l3op** [comment]
Don't forget to add form that redirect to check.php in your index.htm.
Sample:
<form action="check.php" method="POST">
	<input type="password" value="" name="key1" id="key1" />
	<input id="btnSubmit" type="submit" value="Submit"/>
</form>

**Comment by Session2** [comment]
this script is great ! the problem is that I am new to the world of Linux and still have trouble with a lot of things.After a day of sadness I write to you . Can you upload files somewhere modified to allow newcomers like me to shoot them down. thank you in advance for your help :)
