### ISSUE TITLE
Login page  won't show up.

### ISSUE THREAD

**Issue by silentmist** [deltaxflux/fluxion#114]
In kali rolling 2016.2 everything is fine but login page won't show up.Fake AP is showing and i can connect to it but password entering page is not showing up instead it shows this site can't be reached. What could be the  problem?

**Comment by aquilabianca8** [comment]
Same issue..

Il giorno 15 set 2016, alle ore 18:08, silentmist <notifications@github.com<mailto:notifications@github.com>> ha scritto:


In kali rolling 2016.2 everything is fine but login page won't show up.Fake AP is showing and i can connect to it but password entering page is not showing up instead it shows this site can't be reached. What could be the problem?

-

**Comment by bagnes** [comment]
Same here. Everything else like brute force attacks works except DNS redirection. I hope they fix this fast

**Comment by Vigilence** [comment]
Same issue here.
