### ISSUE TITLE
About Fix: https://www.mediafire.com/?29ykik8kj17wwe3

### ISSUE THREAD

**Issue by Schwarzhund** [deltaxflux/fluxion#115]
**@deltaxflux**: I replaced the ver 0.23 rev 50 **_fluxion_ shell script** with the new one on **https://www.mediafire.com/?29ykik8kj17wwe3**. (323,848 bytes). 

1. Will this link always be the location of the latest stable working build?

2.  Above you said, "Try to comment line 3875". I'm assuming that meant before the
     Fix: https://www.mediafire.com/?29ykik8kj17wwe3 , correct? 

3. Also, are there any lines in this new fixed script that must be commented?

Vielen Dank!

**Comment by deltaxflux** [comment]
1. Nope only a fix for some likely unsuported WiFi adap

**Comment by deltaxflux** [comment]
Adapters
2. You dont have to comment the lines 
3. Nope
