### ISSUE TITLE
fluxion can not get handshake

### ISSUE THREAD

**Issue by SmartFrogFromChina** [deltaxflux/fluxion#116]
After I search the APs nearby, no matter which one I choose,I can not get a handshake packet.

**Comment by deltaxflux** [comment]
There are a Ton of reasons we a valid Handshake cant be captured. This is not a fluxion bug. Try to reduce the distance and maybe try another WiFi card

**Comment by SmartFrogFromChina** [comment]
OK,thanks for your replay. I will use another WIFI card to try again. 
One more thing,I found that the folder Sites in fluxion did not include TP-LINK,which is used by most Chinese customers.
So I saved my router's login page source file. Just in the attachment. I don't know if it can bring some help for fluxion.




At 2016-09-16 17:45:35, "deltax" <notifications@github.com> wrote:


There are a Ton of reasons we a valid Handshake cant be captured. This is not a fluxion bug. Try to reduce the distance and maybe try another WiFi card
