### ISSUE TITLE
NO Fake Login Page (Fluxion 0.23 ver52)

### ISSUE THREAD

**Issue by Schwarzhund** [deltaxflux/fluxion#119]
Hi, I see there's no **password Login page** after my Android client automatically connects to the Fake AP. Here's a screenshot after the FakeAP connection, and also screenshots of the client's status before and after the attack using "pyrit" + "deauth all" (or any other Fake AP option). 

(Also noticed that "Clients Online:" in the WI-FI information terminal shows the Android client, but it keeps disappearing and reappearing every 5-6 seconds(?). Don't know if that's related to the same issue...) Thank you.
![fluxion 0 23-52](https://cloud.githubusercontent.com/assets/20869864/18605903/8efe543e-7c53-11e6-830f-dc8f2b9762fc.JPG)
![connectedfakeap](https://cloud.githubusercontent.com/assets/20869864/18605905/a7ef5ce0-7c53-11e6-8585-780de22295a6.png)
![fakeap stats](https://cloud.githubusercontent.com/assets/20869864/18605911/cf16b408-7c53-11e6-83db-d323f0d098bd.png)

![realap stats](https://cloud.githubusercontent.com/assets/20869864/18605910/c8a9d046-7c53-11e6-8af2-4dc4d8be8841.png)

**Comment by l00s3** [comment]
use the backup version. ./flux_rev-51.backup while waiting for the fix. :)

**Comment by aquilabianca8** [comment]
Same issue..
We must wait for the next fix, i suppose..

Il giorno 17 set 2016, alle ore 10:35, l00s3 <notifications@github.com<mailto:notifications@github.com>> ha scritto:


use the backup version. ./flux_rev-51.backup while waiting for the fix. :)

-

**Comment by bagnes** [comment]
How to use backup version when is not downloaded?? Its says ./flux_rev-51.backup :No such file or directory

**Comment by ReneTejeda** [comment]
probably you're trying a https page,  try only with http!

**Comment by aquilabianca8** [comment]
I just tryed HTTPS or HTTPS; but is the same issue..

Il giorno 18 set 2016, alle ore 06:06, ReneTejeda <notifications@github.com<mailto:notifications@github.com>> ha scritto:


probably you're trying a https page, try only with http!

**Comment by l3op** [comment]
Could you upload the files so i can check it.

**Comment by sohrab96** [comment]
i have this problem too. please somebody help me. what is this  ./flux_rev-51.backup ??
its not work. what should i download exactly ?

**Comment by deltaxflux** [comment]
Use the stable version

**Comment by Schwarzhund** [comment]
I moved to the **_Stable Version_** of Fluxion using:

**sudo rm -rf ~/fluxion
sudo git clone https://www.github.com/deltaxflux/fluxion.git
cd fluxion
sudo ./Installer.sh
sudo rm -rf ~/fluxion/fluxion
sudo cp -r ~/fluxion/stable/fluxion ~/fluxion/
sudo ./fluxion**


These are the versions of the relevant installed **packages**:

**php5-cgi**		5.6.7+dfsg-1

**lighttpd**		1.4.39-1

**isc-dhcp-server**	4.3.4-1

**hostapd**		1:2.5-2+v2.4-2

I confirmed that I'm using the actual Stable Fluxion script: 7285 lines, 327.6 kB (327,631 bytes).
But again, as shown below, the client is connected to the FakeAP... but there is still **NO Login Page**.
I tried choosing different login pages, but all are **404**.

**_I'm really not sure what more to do at this point..._**
![stable-version-no-login](https://cloud.githubusercontent.com/assets/20869864/18813137/3be2b5ce-82a2-11e6-9634-0e7ec5adff51.JPG)

**Comment by Ka0tik** [comment]
What rev are you using? I don't have any issues with rev 54.

**Comment by Schwarzhund** [comment]
I used the **Stable Version** as I indicated above, i.e., /fluxion/stable/fluxion from a fresh Rev 54 git clone . 
Still no login page. 

**_Deltax_** - do you have any solution to recommend?

Thanks

**Comment by deltaxflux** [comment]
Well no - the stable and the normal version works flawlessly. The only option I saw is to rebuild your system.

**Comment by Vigilence** [comment]
Also having this issue.  Collected handhake smoothly. 

Choose webinterface Xfinity.  I attempted to connect to fake ap and when I do nothing happens.  No login page, nothing is redirected when entering urls.  

Nothing.

Using todays latest revision both beta and unstable.  Results are the same.
