### ISSUE TITLE
fluxion script not working

### ISSUE THREAD

**Issue by pauperis** [deltaxflux/fluxion#120]
Running fluxion on Bash 4.3.42 (GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
) throws the following error:
fluxion: line 210: syntax error near unexpected token `<'
fluxion: line 210: `readarray -t webinterfaces < <(echo -e "Web Interface'

The following are the step by step commands needed to get the previous error:

# git clone https://github.com/deltaxflux/fluxion.git
Cloning into 'fluxion'...
remote: Counting objects: 1585, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1585 (delta 0), reused 0 (delta 0), pack-reused 1582
Receiving objects: 100% (1585/1585), 10.71 MiB | 98.00 KiB/s, done.
Resolving deltas: 100% (851/851), done.
Checking connectivity... done.

# cd fluxion/
# ls
Installer.sh  LICENSE  README.md  Sites  add.py  airmon  fluxion  remove.py

# sh fluxion
fluxion: line 210: syntax error near unexpected token `<'
fluxion: line 210: `readarray -t webinterfaces < <(echo -e "Web Interface'

**Comment by pauperis** [comment]
Hi, were you able to reproduce the issue? I fetched latest commits by pulling on master branch and same issue still persists. Did you give it a try after your commit?

**Comment by aquilabianca8** [comment]
Same issue still persist after update (update today by GitHub)..

Il giorno 18 set 2016, alle ore 22:24, Pau Peris <notifications@github.com<mailto:notifications@github.com>> ha scritto:

still persists. Did you give it a try after your commit?
