### ISSUE TITLE
had another version

### ISSUE THREAD

**Issue by bobce79** [deltaxflux/fluxion#121]
the latest version keeps looping with aquiring ip.. so the fake AP doesn't work.. not an issue.. just presented for you to look on it :)

**Comment by aquilabianca8** [comment]
The Last version don't work..
The fake login page not appear..

Il giorno 19 set 2016, alle ore 20:24, bobce79 <notifications@github.com<mailto:notifications@github.com>> ha scritto:


the latest version keeps looping with aquiring ip.. so the fake AP doesn't work.. not an issue.. just presented for you too look on it :)

**Comment by Schwarzhund** [comment]
**Does anybody know the most recent stable Rev # that works all the way to the fake login page?**
