### ISSUE TITLE
How to use Fluxion without an Internet connection

### ISSUE THREAD

**Issue by Schwarzhund** [deltaxflux/fluxion#122]
First of all, thanks for all your great work on this project!

If I understand correctly, the Fake AP option requires that the attacker machine must have an upstream Internet connection via Ethernet cable. But since so much of wireless pentesting is done in situations where an Ethernet port is not available (e.g., testing from outside of a target building, war driving, etc.) this really limits the full potential of the Fake AP option. 

If it's possible, would you consider supporting some type of functionality that doesn't require Ethernet to use the Fake AP option in Fluxion?

If not, perhaps you could provide some advice for a work-around for this? All I can come up with is to somehow integrate a 2nd wireless interface in Fluxion that would connect to a nearby OPN AP to establish an internet connection, although the downsides would be security issues as well as a likely unreliable WiFi connection.

Thanks for your help.

**Comment by strasharo** [comment]
Fluxion doesn't need an upstream internet connection at all. It sinkholes all of the traffic to a fake login page asking for credentials.

**Comment by Schwarzhund** [comment]
I guess I misunderstood it as being based on a MitM model. Thanks for the clarification. 
And BTW, as of Rev 52 we're still not seeing this mythical **fake login page** ;-) 
Any progress on that issue... ? Or in the meantime can you point us to a stable working rev that presents the login page?
Thanks, man.
