### ISSUE TITLE
Fake page does not appear

### ISSUE THREAD

**Issue by aquilabianca8** [deltaxflux/fluxion#123]
Hello great deltaxflux,

My system:
Notebook with Kali Linux 2.0 (usb live persistent)
Wi-Fi card usb Alfa (ar9271 chipset)

Five minute ago, i update Fluxion (by github) to Last fix.

Fluxion work fine, but the fake login page don't appear in my smartphone (iPhone) and in my PC desktop (iMac) too..

Any suggest?

Thanks in advance

**Comment by deltaxflux** [comment]
#128
