### ISSUE TITLE
not working on ssl connection

### ISSUE THREAD

**Issue by silentmist** [deltaxflux/fluxion#124]
Its not working on ssl connection. But works fine on other pages.

**Comment by deltaxflux** [comment]
Because i have removed it, because the lighttpd wasn't Setup correctly. In the Test folder there is a ssl fix

**Comment by SNDTiger** [comment]
How ??? i tried to replace fluxion and airmon scripts by the scripts in the tests folder but not working :(

**Comment by SNDTiger** [comment]
what is the removed part in fluxion script (concerning the ssl part)
