### ISSUE TITLE
NO fake login page is displayed 

### ISSUE THREAD

**Issue by devrajashwin** [deltaxflux/fluxion#125]
hey this project has again came across the same problem 
this project is working great,
1> its automatically connecting to fake ap ,
and 
2>deauth is working really good 

but the major problem is its "not displaying the fake login page" after the user get connected to "fakeAp".

**Comment by deltaxflux** [comment]
Well so you have the **latest version**? In general this version works flawless for me. Everything is working (for me).  So I don't know where the problem is but here are some general improvents 
Reinstall: hostapd, isc-dhcp-server, fakedns, lighttpd

**Comment by devrajashwin** [comment]
every thing is already installed with  latest versions,

**Comment by deltaxflux** [comment]
Which distro do u use ? This was tested on parrot 3.1

**Comment by devrajashwin** [comment]
iam using debain (kali rolling)

**Comment by deltaxflux** [comment]
Kali 1.. No wonder why it isn't working. 
You can use the deb too https://sourceforge.net/projects/wififluxion/files/?source=navbar

**Comment by devrajashwin** [comment]
thanx ,
lets hope this will work fine for me ............

**Comment by deltaxflux** [comment]
It is recommended to update your kali or use parrot because you don't get the latest packets

**Comment by devrajashwin** [comment]
ok thanx.

hey i have an idea, 
why not implement some more new things ,
like mitm (man in the middle attack),like spoofing,
and etc in this project ,
so that user can do mitm within this project ,

**Comment by deltaxflux** [comment]
It is a wifi cracker mitm is not on point

**Comment by aquilabianca8** [comment]
I'm in the same issue: after the Fluxion update (to day), the fake login page NOT appear..

I'm using Kali 2.0

Il giorno 21 set 2016, alle ore 15:51, devrajashwin <notifications@github.com<mailto:notifications@github.com>> ha scritto:


ok thanx.

hey i have an idea,
why not implement some more new things ,
like mitm (man in the middle attack),like spoofing,
and etc in this project ,
so that user can do mitm within this project ,

-

**Comment by devrajashwin** [comment]
hey ,
do u know how to use stagefright metaphor,

if yes plz let me know ,check oot this link its on github

https://github.com/NorthBit/Metaphor

**Comment by deltaxflux** [comment]
I will check it out. I have now uploaded a stable version, with the same revision than the latest one. I even have cloned the git again and it is working pretty well

**Comment by deltaxflux** [comment]
Really: https://github.com/NorthBit/Metaphor/issues/14 ?

**Comment by aquilabianca8** [comment]
Deltaxflux: today i tryed to test Fluxion in Kali 2016.2 (new relise), but the fake login page don't work :(


Il giorno 21 set 2016, alle ore 22:29, deltax <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Really: NorthBit/Metaphor#14<https://github.com/NorthBit/Metaphor/issues/14> ?

-

**Comment by deltaxflux** [comment]
I Upload the Old Version
