### ISSUE TITLE
Fake AP does not appear when I scan wifi!

### ISSUE THREAD

**Issue by danhvo97** [deltaxflux/fluxion#128]
In rev-53 everything still okay but in rev-54 when I came to the final step, the open fake AP didn't appear and I couldn't find it by my phone or other computer. Please help me! I'm sure that I did all correct

**Comment by deltaxflux** [comment]
https://github.com/deltaxflux/fluxion/tree/master/stable

**Comment by danhvo97** [comment]
I don't know why but it still not working!

**Comment by aquilabianca8** [comment]
Me too.. :(

Il giorno 23 set 2016, alle ore 16:37, danhvo97 <notifications@github.com<mailto:notifications@github.com>> ha scritto:


I don't know why but it still not working!

-

**Comment by SiNaPsEr0x** [comment]
dont work!!!
