### ISSUE TITLE
No fake login page on Desktop?

### ISSUE THREAD

**Issue by Ka0tik** [deltaxflux/fluxion#129]
When I connect to the fake AP on my desktop, I don't get any password page, just tells me there is no internet. It seems like my computer does not connect to the AP properly since I do not see anything in the terminals and the client number does not change.

It does work on my phone, however. So this makes me wonder some people would not be able to access the page to restore their connection and may not realise about using their phone.

Any advice please?

Thanks.

**Comment by Schwarzhund** [comment]
Hi, just a few quick questions:

1. Does **https://github.com/deltaxflux/fluxion/tree/master/stable** 
and 
**https://sourceforge.net/projects/wififluxion/files/?source=navbar** contain the same release **(Ver 0.23 rev 54)**?

2. Does 0.23-54 show the Login page?

3. Are there any issues using Fluxion on **Kali Rolling 2016.2.3 (kernal release Ver 4.6.0-kali1-amd64)**, and if there are issues, what would you recommend?

4. Which location will always contain the most current stable working release in the future?

**Thank you!**

**Comment by deltaxflux** [comment]
1. They are nearly the same. The only different is that I have the revision changed to 54 ( on github) on sourceforge still (53) 
2. Well it is working for me .) But you should still use the stable version
3. I don't know because I personally don't use it anymore. I recommend parrot
4. In the stable github branche

Edit: the debs are more or less for this kind of person who want to

**Comment by Ka0tik** [comment]
Why was my question hijacked and not answered?

**Comment by Schwarzhund** [comment]
Thanks for the clarifications. I think I'll switch to **Parrot**.

(Sorry Ka0tik, I mistakenly posted on the wrong thread)

**Comment by Vigilence** [comment]
I also can't connect to any login page on my desktop when connecting to fake AP.  Also, when attempting to connect to fake AP on android tablet I get a 404 message.

**Comment by Vigilence** [comment]
Using the default generic webpage option works on the tablet, but loads very slowly, around 10 seconds or so.  Connecting to fake ap with laptop doesn't work.  I can sometimes connect but nothing loads, no redirects nothing.  Other times I can't connect at all.
