### ISSUE TITLE
[Request]  Video Demo 

### ISSUE THREAD

**Issue by deltaxflux** [deltaxflux/fluxion#13]
Can someone make a Video?

**Comment by naflan121** [comment]
Does this script requires 2 adapters?

**Comment by deltaxflux** [comment]
It depence on the attacking methote, but in the most cases not

**Comment by naflan121** [comment]
ok then i should try, how to install this on kali 2 may b i can come out with a video

**Comment by deltaxflux** [comment]
It is not very difficult at all:
1) Download Zip 
2) Extract the files 
$ sudo unzip fluxion-master
3) go in the folder 
cd flux-master
4) sudo ./fluxion

optional you can mv the files in the bin folder

**Comment by strasharo** [comment]
Or via git:

```
apt-get update
apt-get install git-core
git clone https://github.com/deltaxflux/fluxion.git
cd fluxion
sudo ./fluxion

```

**Comment by deltaxflux** [comment]
i think the git way is faster :)

**Comment by strasharo** [comment]
It's the more convenient way to do it, so you can obtain updates by simply issuing "git pull" in the main directory.

**Comment by deltaxflux** [comment]
Yes but I prefer the GUI because I have don't get into a typical git workflow. So this is a question of personal preference.

**Comment by 3lk3n1313** [comment]
Hello i want to give you an idea for the index.html . you could use the mana -toolkit indexs see here https://github.com/sensepost/mana/tree/master/apache/var/www/portal portal. It's very complete and you can get mores credentials and password , You can put as an alternative to get other credentials besides wpa keys etc ... sorry by my english It's no my native lenguage.

**Comment by bobce79** [comment]
https://postimg.org/image/iwevi70q5/

**Comment by deltaxflux** [comment]
@bobce79 i fixed the problem :)
I forgotte to add a fi after a if-condition

**Comment by Quest33** [comment]
Kali 1.1.0a, please?

**Comment by deltaxflux** [comment]
give me the output please

**Comment by Quest33** [comment]
I do not have any output, was rather asking for Kali 1.1.0a compatibility <> fluxion ;)

**Comment by deltaxflux** [comment]
I think there isn’t a compatibility problem  with kali 1.1.0.a but I don’t test it yet because 
I use Kali 2016, good luck

**Comment by strasharo** [comment]
We're currently tasting it only on Kali rolling, version 1 of Kali is already EOL.

**Comment by deltaxflux** [comment]
For more informations check flux located in the old folder. Flux was the beginning

**Comment by PNPtutorials** [comment]
You can check out this demo video of Fluxion tool:-
Thanks to the creator 💯 
https://www.youtube.com/watch?v=xzv5Vy9ghrg
