### ISSUE TITLE
error while getting interface card 

### ISSUE THREAD

**Issue by riphunter00** [deltaxflux/fluxion#130]
![img_2089](https://cloud.githubusercontent.com/assets/22396780/18789838/13a4d3ae-81ca-11e6-97eb-ead796ba405b.JPG)
error while getting interface card after selection English/netgear etc.And DHCP window not appearing .

**Comment by jackditto** [comment]
I have the same problem as you and I think it might have something to do with the wireless card. Are you using an Alfa AWUS036H? @riphunter00

**Comment by riphunter00** [comment]
@jackditto Yes , I am using  Alfa AWUS036H.If it's a problem with wireless adapter does anyone know how to fix it!?

**Comment by deltaxflux** [comment]
#99
