### ISSUE TITLE
Getting issue while scanning

### ISSUE THREAD

**Issue by tvajjhala** [deltaxflux/fluxion#131]
grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines:: No such file or directory
grep: ‘/tmp/TMPflux/dump-01.csv’: No such file or directory
1) head: invalid number of lines: ‘/tmp/TMPflux/dump-01.csv’ 100%

I have read issue #99 and I know this isn't my wireless card issue as it is capable of doing monitor mode injection. How do I fix this? I read at the bottom something about using VNC but i am not familiar with this.

**Comment by deltaxflux** [comment]
Use another wifi card :)
