### ISSUE TITLE
Fake AP with Internet Connection

### ISSUE THREAD

**Issue by duard** [deltaxflux/fluxion#134]
Its possible my Fake AP has my internet connection ? My android connected to WiFi but no internet access to browse any website. 

And my Android show a message "No Internet Access Detected, wont automatically reconnect" .

**Comment by Session2** [comment]
Hi duard.Could you upload the modified script from you to see it and test it?

**Comment by duard** [comment]
I just clone this repository and run.
I created a new site, everything works fine.
I just want the Internet Connection because Android Clients shows that message : 

"No Internet Access Detected, wont automatically reconnect"

**Comment by deltaxflux** [comment]
Use the stable version :) Lighttpd is only on some devices supported. 
`cd; cd ~/fluxion/stable; sudo cp -r ~/fluxion/airmon ~/fluxion/stable; sudo cp -r ~/fluxion/site/ ~/fluxion/stable/`

After that **run**
`sudo chmod +x fluxion`
`sudo ./fluxion`
