### ISSUE TITLE
No Login Page served using https://github.com/deltaxflux/fluxion/tree/master/stable

### ISSUE THREAD

**Issue by Schwarzhund** [deltaxflux/fluxion#137]
Hoping to get a Login page, I replaced the Ver 0.23 rev 54 Fluxion script with the one on:
**https://github.com/deltaxflux/fluxion/tree/master/stable**
ln my test lab I have an android client successfully connected to the Fake AP and browsing sites.      Unfortunately, there is still no Login page served.
[Kali Rolling 2016.2. - kernal release Ver 4.6.0-kali1-amd64, and all dependencies up-to-date.]

_**If anyone has ever actually obtained a Login page, please share your configuration & steps with us!**_
**_Thanks_**
![github com-deltaxflux-fluxion-tree-master-stable-fail](https://cloud.githubusercontent.com/assets/20869864/18805933/f22b3c44-81cf-11e6-9709-35400f564141.JPG)

**Comment by deltaxflux** [comment]
You have to replace the current version of fluxion with the stable version in the main directory 
`sudo  rm -rf ~/fluxion/fluxion; sudo cp -r ~/fluxion/stable/fluxion ~/fluxion/`
