### ISSUE TITLE
Fake Login Page not work

### ISSUE THREAD

**Issue by sohrab96** [deltaxflux/fluxion#138]
the login page does not load on fake ap. what should i do ???

i have kali 2 and i installed php7. i can't install php5-cgi

when i type "sudo apt-get install php5-cgi" , i get this error:

E: Package 'php5-cgi' has no installation candidate

![2016-09-24_011604](https://cloud.githubusercontent.com/assets/20831792/18807466/bb5e6b8e-8254-11e6-813b-0656262eb034.jpg)

**Comment by gorebrau** [comment]
Try sudo apt-get install php-cgi .

**Comment by sohrab96** [comment]
this command will install the php7 version, and the fake login page will not load.

 i wanna install php5 version.

is there any version of kali which support php5 ? please note that. thanks

**Comment by strasharo** [comment]
Currently fluxion works with both php 5 and php 7.
