### ISSUE TITLE
mon0, ./fluxion: line 1070: ./airmon: No such file or directory

### ISSUE THREAD

**Issue by maarc93** [deltaxflux/fluxion#140]
I got this error on fresh installed Kali 2016.2:
mon0, ./fluxion: line 1070: ./airmon: No such file or directory
./fluxion: line 1071: ./airmon: No such file or directory
There are no wireless cards, quit...

**Comment by deltaxflux** [comment]
Use the stable version of fluxion? Have u copied the file in the directory? Looks like not. 
To fix that:
`sudo cp -r ~/fluxion/airmon ~/fluxion/stable`

**Comment by maarc93** [comment]
nope, that is not fixing the problem. I copied to stable directory files that you suggested but still the same error.

`root@kali:~/Desktop/fluxion/stable# ls -l
total 356
-rwxr-xr-x  1 root root  34479 Sep 24 13:55 airmon
-rwxr-xr-x  1 root root 327631 Sep 24 13:52 fluxion
drwxr-xr-x 13 root root    260 Sep 24 13:56 Sites
`

**Comment by deltaxflux** [comment]
Are you using a VM ?. what is if you run airmon alone?
`sudo ./airmon`

**Comment by maarc93** [comment]
Tried booting from USB flash drive and Virtualbox.
airmon is showing this:

root@kali:~/Desktop/fluxion# ./airmon 

Interface	Chipset		Driver
wlan0		Ralink RT2870/3070	rt2800usb - [phy0]

**Comment by deltaxflux** [comment]
So which version do you use ? this in the stable branch ?

**Comment by deltaxflux** [comment]
#137

**Comment by maarc93** [comment]
FLUX 0.23 (rev.  54). I tried #137 but still the same error.

**Comment by deltaxflux** [comment]
You know that you need to move in the directory before you execute it?

wrong: 
`sudo ./fluxion`
right
`cd ~fluxion; sudo ./fluxion`

However if this doesn't work for u, here are instructions how to setup it correctly:
`sudo rm -rf ~/fluxion`
`sudo git clone https://www.github.com/deltaxflux/fluxion.git`
`cd fluxion`
`sudo ./Installer`
`sudo ./fluxion`

If you want to use the stable version of fluxion follow the instructions at issue 137.

**Comment by maarc93** [comment]
I did that multiple times. I have no clue why the error is still showing. Tried internal and external wifi card.

**Comment by deltaxflux** [comment]
Well this is confusing furthermore that airmon show your wifi cards. Give me the output from 
`iwconfig`
`sudo ./airmon`

**Comment by maarc93** [comment]
![screenshot from 2016-09-24 18-22-22](https://cloud.githubusercontent.com/assets/7533848/18809476/c5cfa558-826b-11e6-8c2f-08a1eb24bb23.png)

![screenshot from 2016-09-24 18-23-19](https://cloud.githubusercontent.com/assets/7533848/18809447/deb10496-826a-11e6-983a-6fe4d460644e.png)

**Comment by deltaxflux** [comment]
I don't see the issue yet

**Comment by deltaxflux** [comment]
Well the problem is maybe:
That your wireless card don't support monitor mode for that check issue #99

**Comment by Am3Group** [comment]
I had this issue just today! You must have fluxion in the /root folder. It cannot be located or used on the Dekstop.

**Comment by deltaxflux** [comment]
Nope,  it doesn't matter where you place the folder as long as you move in the directory and it neasary that you don't have only the fluxion script,  the airmon-ng and the Sites folder is also required.

**Comment by genemaka** [comment]
Ok, look at this I'm dealing with this issue and my wireless card actually supports monitor mode. I think Fluxion just keep trying to work with **mon0** but I always use **eth1** with Aircrack suite. How can I tweak Fluxion to work with **eth1**?
