### ISSUE TITLE
Does anyone have a solution to this problem?

### ISSUE THREAD

**Issue by Session2** [deltaxflux/fluxion#141]
![screenshot from 2016-09-24 15-24-01](https://cloud.githubusercontent.com/assets/22253968/18808810/f45cbc0e-8274-11e6-8119-995a18c08cfa.png)
![screenshot from 2016-09-24 15-27-28](https://cloud.githubusercontent.com/assets/22253968/18808809/f45b702e-8274-11e6-80ab-66ccddb972f2.png)

**Comment by deltaxflux** [comment]
Upgrade TP Link is currently not working
