### ISSUE TITLE
While capturing handshake can't use menu.

### ISSUE THREAD

**Issue by Ka0tik** [deltaxflux/fluxion#143]
While waiting to capture a handshake I can't press a number to go back and do something else, I have to Ctrl+C to stop and restart the whole process each time.

Thanks.

**Comment by deltaxflux** [comment]
Yeah, I make this menu responsible again. I will upload this tomorrow

**Comment by Pietro0101** [comment]
I have a problem with fluxion when capturing the handshake will not let me type options on the menu and I have to press Ctrl + C to exit and start another network scanner I would like to help me please thanks

**Comment by deltaxflux** [comment]
Use the stable version, I will reopen the issue if I found a solution
