### ISSUE TITLE
Possible get UTF-8 Login Page?

### ISSUE THREAD

**Issue by Ferritung** [deltaxflux/fluxion#144]
My language no in list.
What I can do to use UTF-8 for other language?

**Comment by deltaxflux** [comment]
Which language do you want ?

**Comment by Ferritung** [comment]
Many thanks you, I have already done itself.
Thank you for Fluxion, you great person.

**Comment by strasharo** [comment]
Fixed in https://github.com/deltaxflux/fluxion/commit/dd6a463ac8e4fcca5032867014b295c258c20ef8
