### ISSUE TITLE
Please delete this ticket! It's from old rev.44 "Sign in page don't reload if password is incorrect!"

### ISSUE THREAD

**Issue by userdsp** [deltaxflux/fluxion#145]
Webpage not available

The webpage at http://connectivitycheck.gstatic.com/check.php might be temporarily down or it may have moved permanently to a new web address.

Suggestions:

Make sure you have a data connection
Reload this webpage later
Check the address you entered

**Comment by deltaxflux** [comment]
Please use the stable version if you have problems with the advanced lighttpd server
