### ISSUE TITLE
Fake AP Handshake Capture Menu is corrupted - flux 0.23 Rev 0.54

### ISSUE THREAD

**Issue by Mrslimon** [deltaxflux/fluxion#149]
when i try to **capture the handshake**
either with **Hostapd - airbase-ng** 
the menu is _not working_ correctly

if  i choose **deauth Mdk3**
fluxion **restart** at the point of _selecting interface_
then **not opening airodump-ng** - 
other attack continue and open Airodump-ng

if i choose**" check for handshake"**
it hang for while then reload
if i choose **" choose another type of attack"**
attack just hang up and reload again - same one
if i choose **" choose another network ., back "** 
hang up and not respond at all 

using Kali Linux rolling 2.0 updated 
Thank you for the great work - one of the best projects around

**Comment by deltaxflux** [comment]
Thank you for your detailed report. Firstly do you meant "capturing handshake"  the check method which is pyrit or aircrack or do you mean the hotspot mode? I will take a look tomorrow. Stay updated

**Comment by Mrslimon** [comment]
didn't try aircrack really -- i was using pyrit method
but i did try to capture the handshake manually and enter the path - rest of the script worked perfectly 
going to check if aircrack work correct or not 
* checked now - same problem occur with aircrack-ng -

**Comment by SiNaPsEr0x** [comment]
on last step for check the key don't work... and the page of fakelogin is more more slow for the device connect on the fake AP... why

**Comment by aquilabianca8** [comment]
The fakelogin page don't work yet.. :(

> Il giorno 28 set 2016, alle ore 17:39, SiNaPsE <notifications@github.com> ha scritto:
> 
> the page of fakelogin

**Comment by SNDTiger** [comment]
still not working and i can't get any handshake with both methods plzz hhelpp
And good work continue ;)

**Comment by deltaxflux** [comment]
Use the stable version
