### ISSUE TITLE
FakeAP with hostapd is currently broken (launches empty xterm after choosing the language)

### ISSUE THREAD

**Issue by strasharo** [deltaxflux/fluxion#15]
Impossible to launch FakeAP with hostapd currently, user gets empty xterm after choosing the language. I'm currently git bisecting in order to find the bad commmit.

**Comment by strasharo** [comment]
0b70739c11c9aba0e9163ed3222101d930f557e8 is the first bad commit
commit 0b70739c11c9aba0e9163ed3222101d930f557e8
Author: William Todt <deltaxflux@users.noreply.github.com>
Date:   Sat Mar 12 23:42:07 2016 +0400

    Update fluxion

:040000 040000 8d9d143deac5b633abe3d545ad8a30c211ade076 1407968fbc24580c1df480f03cc5d4255d744a36 M	kali

**Comment by strasharo** [comment]
Currently we have a paste of the whole script twice:
https://github.com/deltaxflux/fluxion/blob/master/fluxion#L2810

I think we really should revert this commit.

**Comment by deltaxflux** [comment]
that is why, i want to replace the flux against fluxion because fluxion will work on older aircrack-ng versions to so i decide to copy and past it because the flux file was already exicutible. It change now the files so hopefully xterm should work :)

**Comment by strasharo** [comment]
If you need to make some file executable just give me a shout and I'll do it for you.
Issue is resolved now.
