### ISSUE TITLE
Problems with the menu fluxion to capture the handshake

### ISSUE THREAD

**Issue by Pietro0101** [deltaxflux/fluxion#151]
I can not access the menu when it captured the handshake have to press Ctrl + C and start again ... And when this window capturing the handshake that this network desautenticando I would like you to help me close thanks .... By the way very program too good

**Comment by strasharo** [comment]
Before posting a ticket make the effort to check if there isn't already one posted for that particular issue:
https://github.com/deltaxflux/fluxion/issues/143
