### ISSUE TITLE
Android clients force users to sign into a browser before Fluxion shows Login page

### ISSUE THREAD

**Issue by Schwarzhund** [deltaxflux/fluxion#152]
I realize there is probably no way to get around this, because the message is built into the Android OS, but it means many victims may be suspicious and select "**Don't Sign In**". I think this may be the main reason we often don't get the password.

Maybe someone smarter than me can come up with a solution?

![fluxion-browser-sign-in](https://cloud.githubusercontent.com/assets/20869864/18974484/19db6de0-8658-11e6-9346-352b093e85df.png)
![fluxion-browser-options](https://cloud.githubusercontent.com/assets/20869864/18974584/bcc0b8e4-8658-11e6-82b5-e35e4ffd05bb.png)

**Comment by strasharo** [comment]
That's normal behavior, fluxion doesn't provide internet connectivity to the clients. What do you expect to happen in this case? In order to capture the credentials it has to trap a browser session in order to present the login page.
