### ISSUE TITLE
Why mismatch MAC-address AP between FakeAP?

### ISSUE THREAD

**Issue by Ferritung** [deltaxflux/fluxion#154]
Why mismatch MAC-address AP between FakeAP?
for example:
00:00:00:00 -- AP
00:00:00:10 -- FakeAP

Thank you for your greater work.

**Comment by strasharo** [comment]
One octet is changed, because otherwise if the BSSID is the same for both access points, you'll end up with mdk3 deauthenticating clients from the fake AP as well instead of only jamming the target AP.
