### ISSUE TITLE
Dauth doesn't work

### ISSUE THREAD

**Issue by ShaharLahav** [deltaxflux/fluxion#155]
Hi,
All the steps working really good, I am getting the handshake and all and the fake AP starts as well.
But, in the last step when the AP starts and the deauth stage starts i see everything like in the pictures but the clients dont really disconnect not like in the handshake stage.
Is this because we try to set a new AP and deauthenticate another ? 
Thanks in advance !

**Comment by strasharo** [comment]
Is there any output in the mdk3 window?

**Comment by ShaharLahav** [comment]
Yes, there is the usual output: 
Disconnecting XX:XX:XX... From XX:XX:XX..
..
..
..
..
And so on.

**Comment by strasharo** [comment]
Then you're either out of the range of the clients or your adapter transmit power is way too weak to reach them.

**Comment by ShaharLahav** [comment]
But then when I try to deauthenticate with airplay it works.

**Comment by landx** [comment]
im too...
deauth not working... i've to used deauth with aireplay then it work to deauth all of client...
but it not work with mdk deauth with this fluxion...

and i've tried deauth with aireplay when fluxion mdk3 runiing, and aireplay not working :|

why?? :o
