### ISSUE TITLE
Fluxion auto updates to latest unstable version

### ISSUE THREAD

**Issue by Vigilence** [deltaxflux/fluxion#158]
If you try to download stable version it updates to beta version on each run.

**Comment by deltaxflux** [comment]
Well this is not confirmed because revision is equal. If you have problems delete the if clause and add 
FLUX_DEBUG=1. This disable the update function

**Comment by theakhil007** [comment]
please can you explain in detail how to disable auto update 'cause i am new to all this stuff, where to delete if clause and add
FLUX_DEBUG=1 to disable update please let me know thanks in advance!!
