### ISSUE TITLE
Doesn't receive password from the web page

### ISSUE THREAD

**Issue by shidox6** [deltaxflux/fluxion#159]
Everything is going well. AP starts, deauth are sending.
But when trying to input correct password and submit nothing happens. Seems like fluxion doesn't catch it. 
Handshakes used from fluxion.
S400 lenovo laptop, Network controller: Intel Corporation Centrino Wireless-N 2230 (rev c4)

**Comment by deltaxflux** [comment]
Use the stable version and read the README file
