### ISSUE TITLE
Not Sure if Client Deauth working Correctly on Hostapd

### ISSUE THREAD

**Issue by ApatheticEuphoria** [deltaxflux/fluxion#16]
On the initial scan,it shows Active clients on my target network."(*)" But once the Hostapd attack is up and running it doesnt appear to be Deauthing any clients on the target network. And so noone joins the fake Ap. Also,it appears,that the FakeAp spoofs its mac to the same Mac as the Target Network. Perhaps this is the issue.

See image here:
XXXXXXXXXXXXXXXX

It says the Mac is the same as the target...

The whole time mdk3 does nothing to the target.

**Comment by strasharo** [comment]
I can confirm that everything works. The mac is not the same, the fifth octet of the MAC is different from the original one, everything else is the same.

**Comment by ApatheticEuphoria** [comment]
Ok thankyou. But why isnt it deauthing any clients from the target in the mdk3 window?

**Comment by strasharo** [comment]
Can you do a `cat /tmp/TMPflux/mdk3.txt` during the run to confirm if the BSSID of the target is there, please?

**Comment by ApatheticEuphoria** [comment]
Sure,be back soon.

**Comment by ApatheticEuphoria** [comment]
Gave me this: 6C:B0:CE:2F:E8:AF Same as Fake Ap Mac?

**Comment by strasharo** [comment]
I think this is actually the BSSID of your target. I have even confirmed that 6C:B0:CE:2F:E8:AF belongs to an ATT network located near "The Tailgaters Warehouse", right? :) You can confirm the MAC of your fake AP by checking the current MAC address of your main network adapter ( the one which should be in "Master" mode in the iwconfig output).

**Comment by ApatheticEuphoria** [comment]
Ok...so why is the FakeAp window showing the BSSID of my Target?
I can confirm with Macchnager -s that the Macs are different. You are correct. BUT...for some reason,even though the wifi monitor displays clients for the target access point,no deauthing is happening.

**Comment by strasharo** [comment]
Can you send me a screenshot of what you call the "FakeAP window"?

**Comment by ApatheticEuphoria** [comment]
Its the same one as i posted earlier. The actual title is "Wifi Information" i believe.

**Comment by strasharo** [comment]
Well, it displays your current target information, so yes, there you have the BSSID of your target and not of the Fake AP. A place where you can view the BSSID of your FakeAP bssid is the beginning of the hostapd output for example. If you think it will be useful I can patch it to display both BSSIDs on the info window in order to avoid confusion, but generally I think nobody cares about the fakeAP BSSID. :)

**Comment by ApatheticEuphoria** [comment]
Nah. Its fine how it is i guess. I just dont understand why im not deauthing any clients. I understand now the Macs are different so that cant be the issue here...

**Comment by strasharo** [comment]
Also, a quite common scenario. Once you start the attack the adapter gets locked onto the channel that the AP is currently running on. Once the folks start being disconnected, they quite often go ahead and restart their AP. So if the channel is set to auto it will most probably change, but you're still locked on to the old channel, so you are no longer monitoring the clients properly. I'm still thinking of a convenient mechanism to overcome this situation but meanwhile I'm resolving it by running mdk on a separate adapter and leaving it to hop between channels freely, so it can catch up with the changing channel.

**Comment by strasharo** [comment]
Also, mdk is sending deauth only when it sees actual data packets flowing from/to the AP, so if there's no data traffic passing through currently you'll see no authentication at all. You can confirm if that's the cae by running airodump-ng in a separate windows (assuming you lock it on to the proper channel and point it to mon0), so you can see if the data packets on the network increase in count. If their count doesn't change this means that there's no traffic currently.

**Comment by ApatheticEuphoria** [comment]
Okay,i know that for the 1st part that the channel on this particular router is not changing upon reboot.
As for there being no traffic,that may well be the issue.

**Comment by strasharo** [comment]
On which step is that, trying to obtain the handshake?

**Comment by ApatheticEuphoria** [comment]
Nope,actually,during the handshake part of the script mdk3 seems to be performing well.(Tested on a different test network though) Its when im actually running the FakeAP,im not seeing any clients deauthenticated even though on the Target Selection Screen it has the "(*)" meaning there are clients connected. Im going to go back and test the trying to get the handshake on this test network. See if mdk3 still doesnt deauth any clients.
