### ISSUE TITLE
failed channel scan

### ISSUE THREAD

**Issue by timbo72** [deltaxflux/fluxion#160]
Hi guys, after channel selection i hit the following wall,

    FLUXION 0.23    < Fluxion Is The Future >        
 by Deltax, Strasharo and ApatheticEuphoria            

wc: /tmp/TMPflux/dump-01.csv: No such file or directory
./fluxion: line 1203: [: -le: unary operator expected
cat: /tmp/TMPflux/dump-01.csv: No such file or directory
expr: syntax error

                        WIFI LIST
 ID      MAC                      CHAN    SECU     PWR   ESSID

grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines:: No such file or directory
grep: '/tmp/TMPflux/dump-01.csv': No such file or directory
  1)    head: invalid number of lines: '/tmp/TMPflux/dump-01.csv'                         100%

 (*)Active clients
        Select target. For rescan type r
      #>

*slightly edited for formatting*

I've trolled though the closed issues list but I can't find anything that really applies.

Kali ARM rolling
Raspberry Pi 3 
TP-Link TL-WN722N

Any help would be great

**Comment by strasharo** [comment]
Are you running fluxion via a graphical session or just console?

**Comment by timbo72** [comment]
@strasharo Terminal

@deltaxflux not sure why this issue got closed?

**Comment by strasharo** [comment]
You need a graphical session (a running X server) in order to use fluxion.

**Comment by timbo72** [comment]
Ah! Thanks!

**Comment by strasharo** [comment]
If you're connecting to the RPI remotely (via ssh), you can use the X forwarding option (ssh -X) in order to forward it to a locally running X server.

**Comment by timbo72** [comment]
ooh, good one, thanks again!
