### ISSUE TITLE
Wireless card Alfa Awus036NH when used with Fluxion causes Kali 2016 to Freeze.

### ISSUE THREAD

**Issue by Vigilence** [deltaxflux/fluxion#161]
Tested with [Kali 2016.2](https://www.kali.org/downloads/) 64-bit in VMWare as well as the latest Virtual Box.  I have tried both the Alfa AWUS036H and Alfa AWUS036NH and the NH variant has issues with fluxion.

Both of these cards are fully compatible with Kali and fully support monitor mode.  

The [Alfa AWUS036H](http://www.alfa.com.tw/products_show.php?pc=34&ps=92) works fine, but when trying to use the [Alfa AWUS036NH ](http://www.alfa.com.tw/products_show.php?pc=34&ps=21) card with the fluxion script Kali will freeze and become unresponsive.  You can make it up to the language selection but when you choose the 036NH card kali will freeze.  

![screenshot 105](https://cloud.githubusercontent.com/assets/16742086/19019540/c00c39c6-8859-11e6-82f8-850fc942c0f7.png)
![screenshot 103](https://cloud.githubusercontent.com/assets/16742086/19019538/b82c50ba-8859-11e6-877c-e78489c650cc.png)

You will have to force quit VMWare or Virtual Box in order to restart Kali.

Fluxion is fully updated when attempting to use the script.
![screenshot 107](https://cloud.githubusercontent.com/assets/16742086/19019605/7ca8010e-885b-11e6-920d-52dfc0fb6b54.png)

This has been tested in both the unstable branch and then by moving the airmon and site folder into the stable folder as per instructed.

Unfortunately I can't use the stable branch because fluxion discovers no wireless cards.
![screenshot 109](https://cloud.githubusercontent.com/assets/16742086/19019630/0c5b1930-885c-11e6-9c49-041361e81718.png)

However, testing the airmon script that is inside the stable folder does list my wireless card (Alfa AWUS036NH).
![virtualbox_kali linux 2016 2_02_10_2016_04_25_19](https://cloud.githubusercontent.com/assets/16742086/19019556/09afacf2-885a-11e6-845c-2a5da25e19d9.png)

Both of these cards have been tested and used with the original Linset, [the Musket Team version of Linset](https://forums.kali.org/showthread.php?24630-WPA-Phishing-with-linsetmv1-1-sh-A-Musket-Team-Field-Version-Release&highlight=linset), and a [new English variation of linset ](https://forums.kali.org/showthread.php?33012-Linset-English-version-for-all-versions-of-kali-linux&highlight=linset) being worked on, as well as the [LinsetColores](https://www.dropbox.com/s/qxmitdkdd9rm7c4/linset-2016?dl=0) Variation.

**Comment by strasharo** [comment]
Try this:
https://github.com/deltaxflux/fluxion/issues/91

**Comment by Vigilence** [comment]
Why is this closed if the bug still exists as per #91 which was also closed abruptly?

**Comment by strasharo** [comment]
If you're not happy with the development of an open source product, you can always fork it and improve it as you wish.

**Comment by Vigilence** [comment]
It has nothing to do with me being happy with the development.  

I am not used to issues being closed with out them actually being fixed code wise.  Maybe I am used to other github projects and how they are being managed.

No offense meant to anyone.

**Comment by Vigilence** [comment]
As per strasharos suggestion editing the following lines in the main fluxion script

`line 1039: rmmod -f "$WIFIDRIVER" &>$flux_output_device 2>&1
line 1046: modprobe "$WIFIDRIVER" &>$flux_output_device 2>&1`

by putting a # in front of each line temporarily fixes the issue.

`#line 1039: rmmod -f "$WIFIDRIVER" &>$flux_output_device 2>&1
#line 1046: modprobe "$WIFIDRIVER" &>$flux_output_device 2>&1`

I would propose adding this resolution to the wiki until its resolved coding wise.

**Comment by strasharo** [comment]
Let's keep the discussion in the other thread, as I'm gathering data about the issue from multiple affected parties.
