### ISSUE TITLE
Installation Xterm Windows require force close

### ISSUE THREAD

**Issue by Vigilence** [deltaxflux/fluxion#164]
Having setup this program several times in a kali linux fresh environment I noticed that all the update and installation windows that popup don't close by themselves requiring you to force close them.  There is no indication of anything being installed and completed until you force close the xterm window.  I don't know if this effects the installation of the required addons if you accidentally close the window before installation is complete.   Which may in part effect the performance of the script itself.

**Comment by Vigilence** [comment]
I can confirm that xterm is indeed the issue when trying to install fluxion.  If you follow the instructions in the wiki you will download the nightly branch on the main page the .23 installer.sh script is very different then the .22 installer script as the latter uses xterm.

These xterm windows don't close automatically in kali and require force closing.  I figure this may interrupt the installation of any script it's working on.  There is no indication the installations are complete until after you force close the xterm window.

That's when you get a "done" message and then the script downloads and attempts to install the next required component.

![screenshot 113](https://cloud.githubusercontent.com/assets/16742086/19026163/6e2c8b32-88f0-11e6-9c2d-129d7fe33156.png)

I went ahead and manually downloaded version .22 (stable) and everything installed fine in the gnome-terminal.  Window shows when things are down downloading, and when done being installed however it doesn't install php5-cgi.

![screenshot 117](https://cloud.githubusercontent.com/assets/16742086/19027025/8bf5cf16-88fa-11e6-9225-451fc0e7751e.png)
![screenshot 116](https://cloud.githubusercontent.com/assets/16742086/19027026/8bf7e544-88fa-11e6-91a7-4a28a03256d8.png)

**Comment by Vigilence** [comment]
If using the installer.sh in the newest build the window will just stay open, no auto close, no indication anything has installed.   You have to force close to move forward or else the window will stay where it's at forever and the script will not move forward.

![screenshot 120](https://cloud.githubusercontent.com/assets/16742086/19027271/9ccf8992-88fc-11e6-876f-fe8453afa74f.png)
![screenshot 119](https://cloud.githubusercontent.com/assets/16742086/19027272/9cd45210-88fc-11e6-8e88-6f51e33c051a.png)

**Comment by Vigilence** [comment]
Only after manually closing the installation window do you get a done message.

![screenshot 121](https://cloud.githubusercontent.com/assets/16742086/19027308/1098aed0-88fd-11e6-82f5-7f6e532b4b31.png)

**Comment by strasharo** [comment]
Try changing INSTALLER_DEBUG=1 at the beginning of the script to 0.
