### ISSUE TITLE
Can you help me to add russian language to your script?

### ISSUE THREAD

**Issue by kuklofon** [deltaxflux/fluxion#165]
A lot of people on my channel and on forum wants to add russian language to the script. Not to all script, just to the moment , when the user enters his password. When we write russian words in code, we have problems with encoding. Can you help us? 
I can give you russian text to add in your script.

**Comment by shidox6** [comment]
I have posted here https://github.com/shidox6/fluxion/blob/patch-1/rus_text.txt

**Comment by strasharo** [comment]
Попытаюсь пофиксить. ;-)

**Comment by kuklofon** [comment]
о, это было бы очень круто. Скрипт толковый, но русскому человеку надо писать на русском, а то хрен он что введёт

**Comment by caiyong09** [comment]
Hello, everybody. I want to have a problem?

I chose web, DHCP server does not seem to work. DHCP did not open the window, resulting in the customer service has been acquired IP address;

My operating system is Ubuntu 16.04, how to solve?

Thank you

**Comment by Ferritung** [comment]
Скрипт толковый, кроме одного, что не отслеживается смена канала настоящей точки.
Вы можете сутками ждать результата от толкового скрипта, а в это время жертва будет сидеть на другом канале.
Можно наблюдать за этим вручную, но как это назвать толковым скриптом.

**Comment by strasharo** [comment]
Добавил, протестируйте пожалуйста. :)

**Comment by shidox6** [comment]
Thanks works perfect ! :)
