### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by wermaxta** [deltaxflux/fluxion#166]
Hi I'm wondering how to start Fluxion GUI.
PLS Help me.
Thank  you :))))

**Comment by wermaxta** [comment]
My OS is Kali Linux 2016.2
Thank you

**Comment by Vigilence** [comment]
I don't think the [GUI is ready](https://github.com/deltaxflux/fluxion/projects) or even in the script itself.

If you want to test the script follow the instructions [here](https://github.com/deltaxflux/fluxion/wiki/Tutorial).

**Comment by wermaxta** [comment]
Sorry for my question but what is this thank you:)
https://camo.githubusercontent.com/e78563f1b93d8537fa63d61f2b95be94056f459a/687474703a2f2f7331322e706f7374696d672e6f72672f64706c70647a6d6e782f53637265656e73686f745f61745f323031365f30395f32345f31335f35325f35382e706e67

**Comment by wermaxta** [comment]
i see this on Fluxion main page 
Thank you :)

**Comment by Vigilence** [comment]
It's a mock-up for what they have planned for the GUI.  I don't think its ready for testing as the script is still command line oriented.

**Comment by wermaxta** [comment]
Thank you Vigilence :)
Thank you very much :)

**Comment by Vigilence** [comment]
Your Welcome :D

**Comment by generalR36** [comment]
will it be available soon?

**Comment by strasharo** [comment]
We don't plan to develop GUI interface at this point. Pull requests are welcome though.
