### ISSUE TITLE
[Suggestion] Add a message to close the airodump window not main window when done scanning networks.

### ISSUE THREAD

**Issue by Vigilence** [deltaxflux/fluxion#167]
I would advise adding a message to close the airodump window after you are satisfied with the scan otherwise beginners may close the actual script window instead.  Perhaps editing the script to close the airodump window automatically when the first ctrl+c is pressed (in the script window) would help out tremendously or adding a message with minor instructions in main window after airodump window is launched.

![screenshot 128](https://cloud.githubusercontent.com/assets/16742086/19051604/955e6554-8981-11e6-82cd-98bb3fd51260.png)
![screenshot 127](https://cloud.githubusercontent.com/assets/16742086/19051605/9561c348-8981-11e6-9348-480a0331e588.png)

**Comment by strasharo** [comment]
If the user lacks such common sense, he shouldn't be using this script in first place.
