### ISSUE TITLE
[Suggestion] Have captured handshakes listed in handshake window.

### ISSUE THREAD

**Issue by Vigilence** [deltaxflux/fluxion#168]
It would make it easier to use captured handshakes It would be cool if they were listed in the handshake window so you can easily select them instead of typing their location each time.  Since they are all stored in the handshake folder, it would just list the contents and have the user select the appropriate .cap file similar to the way access points are listed when you have closed the airodump window.

This would be a quality of life improvement.
![screenshot 137](https://cloud.githubusercontent.com/assets/16742086/19051810/4a97c21c-8982-11e6-8fa3-7fca3bcdbc80.png)
.

**Comment by strasharo** [comment]
Pull requests are welcome.
