### ISSUE TITLE
Fluxion Site testing Results.

### ISSUE THREAD

**Issue by Vigilence** [deltaxflux/fluxion#169]
I started testing the script websites and thought it would be useful to write my findings down in case it may be of use to the developers or anyone having problems with using a particular site during Evil Twin AP setup.  

I have tested the script several times and overall it works very well.  The script scans for networks, deauths the ap and its clients, collects and verifies the handshake; all without an issue.  The problem arises when creating the fake AP.  Some issues are from the site being used, and others may be with the script itself.  

Overall if using a mobile device for testing you will see the script works fine with the exception of a few sites that give a 404 error, or don’t display correctly due to no images being show.  If trying to connect to the fake ap using a windows 10 laptop then you won’t get anywhere as I haven’t seen a login page popup.  Nor does typing in the browser redirect you to the login page as it would if you were connected to an internet hotspot.  

This test has been done with the latest updated version of Fluxion.
![screenshot 126](https://cloud.githubusercontent.com/assets/16742086/19052457/e4a00c64-8984-11e6-89bb-e9f34185bf5d.png)

**Bottom line:**  I couldn’t get fluxion to work with my laptop but had success with my tablet.

Below are my results testing each site using both a windows 10 laptop and android tablet.

**ENGLISH (Neutral)**
Connecting to the fake AP with the android tablet is fairly easy, however it takes exactly 20 seconds for the login page to show up.  Considering the page isn’t graphic heavy this is an issue.  Victims wait for webpages to open that long.  People will wait around 3 seconds before trying something different thus rendering the attack null.

The connecting the fake AP is steady and constant, no disconnects or reconnects unless you cancel connection yourself.
	
Entering the password also takes a very long time for the page to load and move forward anywhere between 6 -26 seconds.   When it finally loads I get a message saying the password is incorrect, which is true.  

If I were to skip the login window and open a browser and connect to a url I am (very slowly) redirected to the login page, which is a nice touch.

![screenshot_20161003-135108](https://cloud.githubusercontent.com/assets/16742086/19052078/71353cf0-8983-11e6-9116-51a004bb1b9f.jpg)
![screenshot_20161003-133212](https://cloud.githubusercontent.com/assets/16742086/19052082/71597926-8983-11e6-80b1-d04516f44980.jpg)
![screenshot_20161003-132812](https://cloud.githubusercontent.com/assets/16742086/19052079/715538d4-8983-11e6-92a6-12fae286b73b.jpg)
![screenshot_20161003-132602](https://cloud.githubusercontent.com/assets/16742086/19052081/71570c54-8983-11e6-807e-3c11552d90c9.jpg)
![screenshot_20161003-132559](https://cloud.githubusercontent.com/assets/16742086/19052080/7156963e-8983-11e6-98f6-14c54c6794b2.jpg)
![screenshot_20161003-132529](https://cloud.githubusercontent.com/assets/16742086/19052084/71c24500-8983-11e6-9bfb-c1009e3f200b.jpg)
![screenshot_20161003-135156](https://cloud.githubusercontent.com/assets/16742086/19052085/720b8210-8983-11e6-9c20-a62e2a3906a7.jpg)

Not working when connected via windows 10 laptop.  Nothing loads and no redirects when using browser.

![screenshot 146](https://cloud.githubusercontent.com/assets/16742086/19052650/93c530c0-8985-11e6-9a17-64f913777cdf.png)
![screenshot 145](https://cloud.githubusercontent.com/assets/16742086/19052649/93c2ea04-8985-11e6-9ea7-f827d499eab4.png)

**NETGEAR**
Connecting using an Android device results in a very fast page load time.  Around 3 seconds and the page fully loads!
Entering an incorrect password also loads the next page very fast.  There are a few page errors that need correcting.  Some of the English is still in Spanish and the help button has some errors displayed inside it.  The help button, when pressed, shows another page with an image of the sticker that is on the back of the router where the password is located, very impressive.  Aside from the minor errors, this page is very well made.

If I were to skip the login window and open a browser and connect to a url I am quickly redirected to the login page, which is a nice touch.

![screenshot_20161003-140900](https://cloud.githubusercontent.com/assets/16742086/19052149/abbe8908-8983-11e6-8456-1cfc905ae622.jpg)
![screenshot_20161003-140913](https://cloud.githubusercontent.com/assets/16742086/19052159/ba0cd208-8983-11e6-8e9d-6a76bf174d86.jpg)

Connecting to the page using my windows 10 laptop results in nothing.  No login page opens, and the connection states there is no internet.  If I were to type in the url bar a website, nothing happens and no redirects to the login page are made, instead I get a connection reset error in the browser.  Meanwhile the android device is still displaying the webpage correctly.

**Belkin (English)**

This page also loads very fast.  However, there are some minor errors still seen.  The please help has some of the Spanish question marks (?) still attached to it.  The help page also loads very fast and displays another image of the back of the router, where the password is located.   Overall well-made page.  Page requires minor cleaning up.

If I were to skip the login window and open a browser and connect to a url I am quickly redirected to the login page, which is a nice touch.

Connecting to the fake AP using windows 10 laptop again results in nothing happening.  No login page opens up and urls typed in the browser offers no redirect.  Webpage gives a DNS Probe Started.

![screenshot_20161003-141231](https://cloud.githubusercontent.com/assets/16742086/19052196/e0db21dc-8983-11e6-8bcc-3852bb676dd6.jpg)
![screenshot_20161003-141226](https://cloud.githubusercontent.com/assets/16742086/19052197/e0e98df8-8983-11e6-95dc-69804aa04f67.jpg)

**ARRIS**
This page loads very fast but has many errors.  The page itself is currently unusable.  See image.
Again, the page doesn’t work on my windows 10 laptop.
![screenshot_20161003-142256](https://cloud.githubusercontent.com/assets/16742086/19052279/23b65526-8984-11e6-887c-1c37a9473c57.jpg)

**VERIZON**
This page results in a 404 error when being viewed on a tablet.  Login doesn’t work on Windows 10 laptop.  
![screenshot_20161003-143248](https://cloud.githubusercontent.com/assets/16742086/19052320/555d99a4-8984-11e6-8c9d-5b6ac930bc5a.jpg)

**XFINITY**
This page results in a 404 error when being viewed on a tablet.  Login also doesn’t work on my windows 10 laptop.

![screenshot_20161003-150802](https://cloud.githubusercontent.com/assets/16742086/19052323/57a435ec-8984-11e6-8fdf-26da9b48cfc4.jpg)

**HUAWEI**
Loads fairly fast at less than 2 seconds.  The please help has the Spanish question marks which can easily be fixed.  Entering the password causes the page to load fairly slowly.    The help page works well and loads fairly fast at around 3 seconds.  The image loads fine.  Overall nicely done page.  

If I were to skip the login window and open a browser and connect to a url I am quickly redirected to the login page, which is a nice touch.

![screenshot_20161003-151420](https://cloud.githubusercontent.com/assets/16742086/19052360/75435ef2-8984-11e6-9051-97783cc8af72.jpg)
![screenshot_20161003-151256](https://cloud.githubusercontent.com/assets/16742086/19052359/7542c15e-8984-11e6-9382-3f6ddf2a313b.jpg)

Again, on PC nothing works.

**SPANISH (Default)**
Like the default English page, this page loads very slowly and in a similar amount of time (20s).  Other than the Spanish text, it is visually the same as the English page.  Entering the password loads the page very slowly at around another 15-20 seconds and sometimes much longer.  
If I were to skip the login window and open a browser and connect to a url I am (very slowly) redirected to the login page, which is a nice touch.

Not working when attempting to connect to AP via windows 10 laptop.  Nothing loads, no redirects, nothing.

![screenshot_20161003-152901](https://cloud.githubusercontent.com/assets/16742086/19052373/8493d80a-8984-11e6-8b82-9b5f1dee0ab5.jpg)
![screenshot_20161003-152340](https://cloud.githubusercontent.com/assets/16742086/19052372/8491bce6-8984-11e6-8f9d-8eb6f78f112d.jpg)

**NETGEAR (SPANISH)**
Like the English Netgear page everything looks really great and loads very fast. Skipping the login page and trying to connect to a webpage via a browser redirects to the login page.

The help page loads very fast and displays nicely similar to that of the English version.

Again, nothing working on my PC.

![screenshot_20161003-153814](https://cloud.githubusercontent.com/assets/16742086/19052391/95d7e714-8984-11e6-84a4-489e7580a4ae.jpg)
![screenshot_20161003-153758](https://cloud.githubusercontent.com/assets/16742086/19052390/95d72dc4-8984-11e6-82b0-bf8ed5deed01.jpg)

**ARRIS (SPANISH)**
Loads very fast.  The help page also loads fast and displays correctly.  Browser redirects work.
Not testable on PC since can’t connect to AP.

![screenshot_20161003-154326](https://cloud.githubusercontent.com/assets/16742086/19052398/a12bbbfe-8984-11e6-87ef-722c4e3d199c.jpg)
![screenshot_20161003-154149](https://cloud.githubusercontent.com/assets/16742086/19052397/a12a87fc-8984-11e6-8d4e-82891d95f8fa.jpg)

**VODAFONE (SPANISH)**
Loads very fast.  There are a few errors with displaying the host essid, mac and current channel.  Help page works great and loads fast.  Browser redirects work fine.  

No connection via PC.

![screenshot_20161003-154730](https://cloud.githubusercontent.com/assets/16742086/19052430/bc75bbda-8984-11e6-9fca-5e1539a42b2c.jpg)
![screenshot_20161003-154719](https://cloud.githubusercontent.com/assets/16742086/19052429/bc751554-8984-11e6-8b55-a54cf2fdd914.jpg)
![screenshot_20161003-154707](https://cloud.githubusercontent.com/assets/16742086/19052426/bc739d00-8984-11e6-9f18-2ad778547842.jpg)
![screenshot_20161003-154516](https://cloud.githubusercontent.com/assets/16742086/19052427/bc7430a8-8984-11e6-922a-93dabc8d9c7a.jpg)

**Comment by strasharo** [comment]
Everything besides "ENGLISH (Neutral)" is currently WIP.

**Comment by Vigilence** [comment]
Are the connections issues related to my PC or the script itself?

**Comment by strasharo** [comment]
The script itself is not serving the access point. The access point is being created using hostapd/airbase-ng depending on the wireless chipset being used. There are no customizations for mobile devices, so it doesn't matter what type of device are you using to connect. I'm conducting most of the testing using a laptop and I have no issues with the connectivity.

**Comment by Vigilence** [comment]
Are you using windows 10 as well?

**Comment by strasharo** [comment]
Windows 7 and Fedora.

**Comment by Schwarzhund** [comment]
**Great work, Vigilence. I have not yet seen a login page when testing for iPhone and MacOS clients. Have you noticed this, too?**

**Comment by Vigilence** [comment]
@Schwarzhund I have an iphone saved away, I'll take it out and test the pages again.  I don't have a macOS but can test the pages in VMWare.

**Comment by Vigilence** [comment]
I went ahead and decided to see what was the issue with my PC as I had tested Fluxion with a virtual windows 10 and it was working fine.

**I did two things to resolve the issue:**

1. I went ahead and did a full network reset.  Check the pictures included to see how.
![screenshot 159](https://cloud.githubusercontent.com/assets/16742086/19088860/14f7aaae-8a46-11e6-88f8-3f92a992e8c2.png)
![screenshot 160](https://cloud.githubusercontent.com/assets/16742086/19088861/14f8d5aa-8a46-11e6-91ea-0092849a8b9f.png)
![screenshot 164](https://cloud.githubusercontent.com/assets/16742086/19088862/14fa25c2-8a46-11e6-9df6-b1d30b44d759.png)
![screenshot 165](https://cloud.githubusercontent.com/assets/16742086/19088859/14f69808-8a46-11e6-9edf-12a2d52b5495.png)





2. Secondly, I went ahead and reset the default program for internet browsing.  I first tried cortona but that has issues with opening up mitm pages (at least for me), so I went ahead and changed all browser related settings to default to Internet Explorer.  
![screenshot 166](https://cloud.githubusercontent.com/assets/16742086/19088940/5a1c91b2-8a46-11e6-9f32-6cf9b2158fa0.png)


I retested fluxion with my laptop and everything works fine now.   The default English option (choice 1) still loads very slowly (around 30 seconds) but it at least works.  See attached pic.
  
![screenshot 158](https://cloud.githubusercontent.com/assets/16742086/19088953/65af672a-8a46-11e6-9260-98d86652789e.png)


I'll be retesting the sites again with my laptop and posting pictures for anyone curious as to what they may look like on a PC browser, and if they are currently usable.

**Comment by Vigilence** [comment]
@strasharo Any tips for me so I can attempt to fix the verizon login page?  The index page itself loads fine when clicking on it, the files load fine in the temp data folder and the file structure matches the files in the fluxion script and the index page itself.
