### ISSUE TITLE
New Attack Options Currently Not Functioning

### ISSUE THREAD

**Issue by ApatheticEuphoria** [deltaxflux/fluxion#17]
WPS-SLAUGHTER gives Error:
` ./fluxion: line 1057: wps-wifi-monitor: command not found`

Wifite Gives the Error: 
```
 Traceback (most recent call last):
  File "wifite.py", line 3, in <module>
    from py.Configuration import Configuration
ImportError: No module named py.Configuration
```

Wifi-Phisher(Although i only tested this with 1 attacked adapter) gives the Error:   
```
               _  __ _       _     _     _               
              (_)/ _(_)     | |   (_)   | |              
     __      ___| |_ _ _ __ | |__  _ ___| |__   ___ _ __ 
     \ \ /\ / / |  _| | '_ \| '_ \| / __| '_ \ / _ \ '__|
      \ V  V /| | | | | |_) | | | | \__ \ | | |  __/ |   
       \_/\_/ |_|_| |_| .__/|_| |_|_|___/_| |_|\___|_|   
                      | |                                
                      |_|                                
                                                         
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "wifiphisher.py", line 948, in <module>
    sniffing(mon_iface, targeting_cb)
  File "wifiphisher.py", line 414, in sniffing
    sniff(iface=interface, prn=cb, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 561, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 455, in __init__
    self.ins.bind((iface, type))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device

```

**Comment by strasharo** [comment]
What is the point to include wifiphisher in this script?

**Comment by ApatheticEuphoria** [comment]
More customizable phishing pages.

**Comment by ApatheticEuphoria** [comment]
Remove it if you think its not worth it,but then,i suggest making the Fake login page more customizable/different types of pages.

**Comment by strasharo** [comment]
I think that both wifiphisher and fluxion are overlapping in functionality, they just take different approaches to solve the same task, so in my opinion it's pointless to have both in one place. Including a customized page is a good idea, maybe we can work on that in the future.

**Comment by ApatheticEuphoria** [comment]
Fair enough. You should go ahead and remove it then. =)

**Comment by ApatheticEuphoria** [comment]
Do you have a Telegram Account? id like to have agroup chat there for this porject... Deltax and I are already communicating in a room.

**Comment by strasharo** [comment]
Let me obtain one, never used it before. I'm mostly a XMPP person. :-)

**Comment by strasharo** [comment]
I have registered there, same username as here.

**Comment by ApatheticEuphoria** [comment]
Trying to create a Fluxion group and then ill add everyone. Its being difficult right now though. Sorry. xP

**Comment by ApatheticEuphoria** [comment]
I seem to be unable to create a group. =( Perhaps you can create one and add me,same username as here...
