### ISSUE TITLE
wps slaugher no Disabling interfaces wlan2 wlan3 etc..

### ISSUE THREAD

**Issue by 3lk3n1313** [deltaxflux/fluxion#170]
fluxion after use wps slaugher no disabling interfaces wlan2 wlan3 etc.. ,only disabling wlan1.

**Comment by ApatheticEuphoria** [comment]
Meh...no one ever wrote the other adapters into the exit script. Simple fix. We'll get to it when we can.

**Comment by caiyong09** [comment]
Hello, everybody. I want to have a problem?

I chose web, DHCP server does not seem to work. DHCP did not open the window, resulting in the customer service has been acquired IP address;

My operating system is Ubuntu 16.04, how to solve?

Thank you

**Comment by deltaxflux** [comment]
fixed on the dev version
