### ISSUE TITLE
Wifi Monitor Not showing any AP 

### ISSUE THREAD

**Issue by bfheythem** [deltaxflux/fluxion#173]
after choosing my interface (1) wlan0) then starting to scan all channels i got no AP shown 
it  used to work just fine but suddenly i faced this pbm 

i think it's because when trying to start monitor mode it's defined as "mon0" in fluxion 
however the correct one is "wlan0mon" which works perfectly in another terminal with airodump

**Comment by bfheythem** [comment]
![screenshot from 2016-10-08 21-12-57](https://cloud.githubusercontent.com/assets/22716581/19215661/ae821e84-8d93-11e6-8a7d-681c92364e3c.png)
see i think it's beacause monitor mode interface is named mon0 instead of wlan0mon

**Comment by owaisahmad11** [comment]
Facing same issue, Please let me know steps to resolve this issue

**Comment by Zoddex** [comment]
I experience this same issue. What I do is to execute airmon-ng start wlan0 **before** running fluxion. I believe this is an issue depending on your WLAN card as I have tried on several computers (Kali USB) and seems to work fine on most.
