### ISSUE TITLE
FAKE LOGIN PAGE DON'T APPEAR

### ISSUE THREAD

**Issue by aquilabianca8** [deltaxflux/fluxion#174]
Great Deltax and Strasharo,

i did try start Fluxion Rev.56 and works fine; but today try again with Fluxion Rev.58 and it doesn't work: the fake login page don't appear, therefore i can't entro the password..

My system:
-PC notebook
-Kali linux Rolling 2016.2 usb live persistent (no VM)
-With usb Alfa AR9271 chipset

Any suggest?

Thanks in advance;)

**Comment by Vigilence** [comment]
Try deleting the fluxion folder and reinstalling.

**Comment by strasharo** [comment]
Which login page are you using and with what Alfa adapter? AWUS036NHA?

**Comment by aquilabianca8** [comment]
I'm using iPhone to connect to fake AP and work; but then, when try open a new page (with Safari) don't appear fake login page, remain a withe page...

I'm using AWUS036NHA..

Il giorno 09 ott 2016, alle ore 00:58, strasharo <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Which login page are you using and with what Alfa adapter? AWUS036NHA?

-

**Comment by deltaxflux** [comment]
Do you try the dev version or the stable one ?

**Comment by aquilabianca8** [comment]
At the moment no.
Where can i find them exactly?

Il giorno 09 ott 2016, alle ore 19:19, deltax <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Do you try the dev version or the stable one ?

-

**Comment by aquilabianca8** [comment]
I tried to overwrite fluxion with fluxion stable (copy from dev folder), but still never work: the fake login page not appear.. I missed a few step..? 
Can you explain me (step by step) how to install dev version or the stable one?

Thanks in advance;)

**Comment by gabrig** [comment]
Hi everybody.
First of all, thank you deltaxflux for this.. It's amazing!!

@aquilabianca8 the login page doesn't appear automatically to me too, but I have to go to my "home" ip. I mean, when open the browser, I have to digit 192.0.0.1. Then the login page appear and I can enter the password.
Let us know if this works for you or you still have a problem. Or install it again (I've just downloaded it and it works).

Now, I have a question too, @deltaxflux : is there a way to let the fake router login page appear automatically? I need to see it once I open the browser. 
Maybe there is a way to launch the browser once the computer automatically connect to the fakeAP, setting the router address as home page, so it is the first thing that appear.

I'm new to this, hope everyone can take this as a suggestion and not as a critique!
And again, your work is amazing! Thank you!
G.

**Comment by aquilabianca8** [comment]
I installed Fluxion again, and now it works..

The another important thing, It would be to make automatically appear the fake login page when we connect to the fake AP..

Great work anyway.
Thanks a lot Deltaxflux and Strasharo! ;))

**Comment by strasharo** [comment]
There's no way to trigger a browser launch on the client side. All we can do is launch a captive portal which redirects all of the web traffic to itself, so once the client tries to browse something it will trap the request and show the login page.
