### ISSUE TITLE
No Access Points when Scanning 

### ISSUE THREAD

**Issue by bfheythem** [deltaxflux/fluxion#177]
when i start wifi monitor to scan all the channels for AP , Iget a blank page 
im using 
Kali 2016.2 (rolling)
all needed feature are installed 
when try the injection mode manually or using other tools it works fine 
I think it's a problem with the "mon0" interface instead of "wlan0mon " recognized by the system

**Comment by strasharo** [comment]
What's the point in opening multiple tickets for the same issue?
https://github.com/deltaxflux/fluxion/issues/173

**Comment by bfheythem** [comment]
sorry but i got no answer thats why ;)
