### ISSUE TITLE
Fluxion freezes after select external card

### ISSUE THREAD

**Issue by juanxito91** [deltaxflux/fluxion#178]
Hi!

I just installed VMWare Virtual Machine and Kali Linux with Fluxion (rev 59). 

Everything works fine, except that when I need to select my external card for start to search wireless connections, the virtual machine freezes.

When I use the command "airmon-ng", also appears my external card. No problem with it.

I have seen other issues the same, about changing some strings in "fluxion file" (line 1039 and line 1046), but I have no idea how to edit that lines with Kali Linux Terminal (I don't have installed any notepad for open the "fluxion" file in that Kali Linux).

Any help?

Thanks.

**Comment by strasharo** [comment]
What wireless adapter are you using, what's the chipset and which is the driver?

**Comment by juanxito91** [comment]
DRIVER: rt73usb		
CHIPSET: Ralink Technology, Corp. RT2501/RT2573

**Comment by strasharo** [comment]
Are you able to inject with it (aireplay-ng -9 on the monitor interface)?

**Comment by juanxito91** [comment]
No, I'm not able...

root@kali:~# aireplay-ng --test
No replay interface specified.
"aireplay-ng --help" for help.

or the same option as you told me:

root@kali:~# aireplay-ng -9
No replay interface specified.
"aireplay-ng --help" for help.

**Comment by l3op** [comment]
Set the interface into the monitor mode first and try to inject
`aireplay-ng -9 wlan0mon`

**Comment by strasharo** [comment]
Use the airmon script bundled with fluxion. 
./airmon start wlan0
It should create an interface called mon0
Then try aireplay-ng -9 mon0

Post the output from the steps above here.

**Comment by juanxito91** [comment]
Now seems it works good the injection :-) but still the virtual machine freeze when I select "wlan0".

root@kali:~/Desktop/fluxion# aireplay-ng -9 mon0
11:15:48  Trying broadcast probe requests...
11:15:49  Injection is working!
11:15:50  Found 3 APs

11:15:50  Trying directed probe requests...
11:15:50  18:A6:F7:67:71:2E - channel: 1 - 'TP-LINK_712E'
11:15:51  Ping (min/avg/max): 4.110ms/20.740ms/41.344ms Power: -68.53
11:15:51  30/30: 100%

11:15:51  F4:F2:6D:48:59:20 - channel: 1 - 'TP-LINK_5920'
11:15:52  Ping (min/avg/max): 1.501ms/11.248ms/22.698ms Power: -90.92
11:15:52  24/30:  80%

11:15:52  F8:D1:11:CE:A2:BC - channel: 1 - '218'
11:15:53  Ping (min/avg/max): 2.762ms/11.257ms/20.304ms Power: -86.79
11:15:53  29/30:  96%


![sin titulo](https://cloud.githubusercontent.com/assets/18647477/19240937/e1bbb358-8f0c-11e6-9ece-305ad248646b.png)

**Comment by strasharo** [comment]
Pull the latest version and retry.

**Comment by juanxito91** [comment]
New version v62 works perfect and no freezes!!!

Thanks so much, buddy! 💯 😄

**Comment by strasharo** [comment]
Great. I see that you're from Spain, do you speak Spanish by any chance? I need assistance with the translation of some strings for the web interface.

**Comment by juanxito91** [comment]
Yes, I'm spanish.

Send me the strings to translate, and I will translate 😃 😄

**Comment by strasharo** [comment]
Let's discuss it in this thread:
https://github.com/deltaxflux/fluxion/issues/82
