### ISSUE TITLE
SIOCSIFADDR:  NO SUCH  device

### ISSUE THREAD

**Issue by babarqb** [deltaxflux/fluxion#179]
i use rev 60  but i have major issue i dont know where is problem. Every thing look ok but at last step where i select website number then it took few second and then show few error just one second and then open other window but my fake ap  not created  what should i missing ??

at0; error WHILE geting interface flags: no such device 
SIOCSIFADDR:  NO SUCH  device
at0: error error WHILE geting interface flags: no such device 
SIOCSIFNETMASK   NO SUCH  device
SIOCADDRT: NETWORK IS UNREACHABLE

**Comment by deltaxflux** [comment]
What wireless adapter are you using?

**Comment by babarqb** [comment]
I use two Adapter first Alpha AWUS036H(which is not supported for AP) and second TPLink  TL-WN722N(supported AP). I got error when i use AWUS036H. But with TPlink it works very well but i cant get internet with that i use Vmware and kali linux on window with bridge connection. I dont know how fluxion get internet from eth0. Is it automated that fluxion get internet or some manual configuration. One think more AWUS036NH show in iwconfig but not connect to any SSID. And at last thanks for response.

**Comment by deltaxflux** [comment]
As u said, the alpha is not supported for AP
