### ISSUE TITLE
Web Interface related :(

### ISSUE THREAD

**Issue by real-stone** [deltaxflux/fluxion#181]
All web interfaces shows or ask Vitim to enter WPA Passphrase,, my suggestion is that make that from WPA Pass to Wifi Password, because it is easily understand for n00bs and  low level user. Basic user don't know the wifi terminology, that what is WEP,WPA and WPA2. and one more thing that victim is not automatically connected to our fake access point..

Kindly do some work on it,,  :+1: 

over all Fluxion is marvelous :+1:  +1:

**Comment by strasharo** [comment]
Fluxion is targeted only for WPA networks, it doesn't even support WEP. And I donk't think it really matters if it's WPA 1 or 2, it's all a WPA password.
