### ISSUE TITLE
No such file /tmp/TMPflux/dump-01.csv

### ISSUE THREAD

**Issue by nvnhan** [deltaxflux/fluxion#183]
Hello!
When I scanning ap with fluxion, have this issue
Please help me, thanks!

wc: /tmp/TMPflux/dump-01.csv: No such file or directory
./fluxion: line 1270: [: -le: unary operator expected
cat: /tmp/TMPflux/dump-01.csv: No such file or directory
expr: syntax error
                        WIFI LIST 

 ID      MAC                      CHAN    SECU     PWR   ESSID

grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines:: No such file or directory
grep: ‘/tmp/TMPflux/dump-01.csv’: No such file or directory
  1)	head: invalid number of lines: ‘/tmp/TMPflux/dump-01.csv’	 	   100%	 

 (*)Active clients

        Select target. For rescan type r
      #>

**Comment by strasharo** [comment]
What wireless adapter are you using?

**Comment by l3op** [comment]
It's not related to any sort of network thing! The thing is the temp directory Keeps cleaning itself! So, Please check you settings. 

![screenshot from 2016-10-11 01-14-07](https://cloud.githubusercontent.com/assets/12974004/19259528/330e854a-8f8b-11e6-904b-906c09383194.png)

**Comment by nvnhan** [comment]
Broadcom BCM43142

**Comment by deltaxflux** [comment]
This card don't support monitor mode.  Buy another one

**Comment by vividuaelsaphe** [comment]
I am getting the same problem. I am using a RALINK adapter RT3290 and it does support monitor mode and I was used Fluxion, but when I rebooted and opened Fluxion the same error as the OP seems to pop up.

Here's my iwconfig:

`wlan0     IEEE 802.11bgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=0 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
`

**Comment by strasharo** [comment]
Does it support injection and what driver is it using?

**Comment by vividuaelsaphe** [comment]
I do believe it does, because I was able to have a couple of successful Handshakes to create the Fake AP. Suddenly it all stopped working. My copy of Kali is new (I installed Fluxion on my first boot into Kali). Haven't installed any drivers for RT3290 yet (doesn't Kali do this automatically?). Here's my ifconfig:

`eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.12  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::2e59:e5ff:fe9f:bb72  prefixlen 64  scopeid 0x20<link>
        ether 2c:59:e5:9f:bb:72  txqueuelen 1000  (Ethernet)
        RX packets 49231  bytes 54331922 (51.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 36981  bytes 3794578 (3.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 32  bytes 1744 (1.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 32  bytes 1744 (1.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`

**Comment by strasharo** [comment]
Your ifconfig output doesn't even contain a wireless adapter.

**Comment by vividuaelsaphe** [comment]
My ifconfig -a does:

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.12  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::2e59:e5ff:fe9f:bb72  prefixlen 64  scopeid 0x20<link>
        ether 2c:59:e5:9f:bb:72  txqueuelen 1000  (Ethernet)
        RX packets 54351  bytes 58569191 (55.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 41874  bytes 4305558 (4.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 32  bytes 1744 (1.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 32  bytes 1744 (1.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether 1c:3e:84:6c:34:a4  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by vividuaelsaphe** [comment]
The problem got fixed. How? I just did a reboot. But I would still like to know why this happened? What exactly is in the csv file?

**Comment by strasharo** [comment]
Nothing has changed, apparently there's some issue on your system.
