### ISSUE TITLE
IMPORTANT: FLUXION 0.23 UNSTABLE (last stable version 0.22)

### ISSUE THREAD

**Issue by kandarpgautam** [deltaxflux/fluxion#184]
### Which version of fluxion are you using?
0.23 (latest)

### What distribution of Linux (including the version) are you running it on?
kali rolling 2016.2

### What wireless adapter are you using?
internal  (previous versions of fluxion worked fine with it.)

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
<???>

### General description of your issue along with the steps to reproduce it
ERROR 1: FLUXION SHOWS THESE MESSAGES MANY TIMES:
 
/root/Downloads/fluxion-master/fluxion: line 1141: ./airmon: No such file or directory
/root/Downloads/fluxion-master/fluxion: line 1142: ./airmon: No such file or directory
There are no wireless cards, quit...

FIX: problem gets fixed by typing this in new terminal ( airmon-ng check kill, airmon-ng start wlan0 )

CONCLUSION: airmmon-ng is not being executed properly in fluxion 

ERROR2: NO FAKE WIFI IS CREATED TO WHICH VICTIM CAN CONNECT WHILE DEAUTH IS 
WORKING PROPERLY
NOTE: i have used earlier versions of fluxion too and they worked completely fine.hence this version i.e. FLUXION 0.23 (latest) is unstable.

**Comment by strasharo** [comment]
Do you have the airmon script in the directory with fluxion?

**Comment by kandarpgautam** [comment]
wait let me try once again thanks for the support
