### ISSUE TITLE
Fake AP created well but no Login page show in android

### ISSUE THREAD

**Issue by babarqb** [deltaxflux/fluxion#186]
rev 65

Kali 2

I have not show login page while creating Fake ap  with fluxion. i dont know where is problem when i create ap with default hostapd.conf it work greate but when with fluxion every thing is ok accept internet and nor i show website mention fluxion wizard . Although its work well on Apple safari please tell me what i do i test it on Galaxy 5. One more thing when i use 192.168.1.1 then its works please what i do that every request redirect into 192.168.1.1  i am confused

**Comment by strasharo** [comment]
The DHCP server instructs the connecting host to use 192.168.1.1 as a DNS, where we have a fake python DNS server, which responds to all requests with 192.168.1.1. If you're using a custom DNS server on the device instead of the one provided by the DHCP server redirection will not work.

**Comment by x-achref-x** [comment]
and how to install your fake python DNS server . because i let him install every think he need and the page don't show in android

**Comment by strasharo** [comment]
It's already bundled with the script. Do you see a windows which contains the string pyminifakeDfluxassNS ?

**Comment by x-achref-x** [comment]
Yeah , every think work perfectly " i test it on my network " only in android the page don't show , ween i ask for 192.168.1.1 but if i ask for google.com she told me that there is no connexion , but in an other pc it show even if i ask for google.com .
so the problem is only in android 
My phone ; Samsung Galaxy S5+

**Comment by strasharo** [comment]
Can you confirm what's the DNS server used by the device?

**Comment by x-achref-x** [comment]
by the android device or by the linux ?

**Comment by strasharo** [comment]
The Android device obviously.

**Comment by x-achref-x** [comment]
DNS1: 192.168.1.1
DNS2: 0.0.0.0
Netmask : 255.255.255.0
and in fakeDNS windows show : Google.com > 192.168.1.1 
but in the navigateur don';t show the page

**Comment by strasharo** [comment]
There must be something in the Galaxy configuration which overrides the DNS requests. Tested with multiple other Android devices and the issue is not present there.

**Comment by bobfelix89** [comment]
Same happening here. Everything goes great till my clients tried to browsing. The fakeDNS is not redirecting to anything. Even when I try to type 192.168.1.1 on their browsers, nothing happens. I tried with iOS, chromeOS, Windows 10 and Linux. I'm using a VM to run fluxion.

**Comment by J0rd40** [comment]
@bobfelix89 Man, first hello, I just want to tell you, that's exactly what happens to me in rev 98 of Fluxion 0.23.
