### ISSUE TITLE
Language post. Add your language you wish to add here

### ISSUE THREAD

**Issue by Bexian** [deltaxflux/fluxion#188]
I wolud like to translate fluxion in italian if possible, but i cannot find the files to translate. Where are them?

**Comment by juanxito91** [comment]
Go here and translate the strings:

https://github.com/deltaxflux/fluxion/issues/82

**Comment by Bexian** [comment]
thanks for the quick response. i saw it and the site has alredy been translated. i wanted to translate the program not the site

**Comment by strasharo** [comment]
We already have an Italian translation submitted, but it wasn't merged yet. Could you, please, confirm that the following translation is correct and doesn't contain any syntax/grammatical errors?

function Italian {
	header_setinterface="Seleziona un'interfaccia"
    setinterface_error="Nessuna schede di rete WiFi, chiudo..."

    #
    header_choosescan="Selezione Canale"
    choosescan_option_1="Tutti i Canali"
    choosescan_option_2="Definisci Canale/i"
    #
    scanchan_option_1="Canale Singolo"
    scanchan_option_2="Canali Multipli"
    #
    header_scan="WIFI Monitor"
    #
    header_scanchan="Scansone dell'Obiettivo"
    #
    header_askAP="Seleziona Opzione d'Attacco"
    askAP_option_1="FakeAP - Hostapd ("$red"Consigliato!)"
    askAP_option_2="FakeAP - airbase-ng (Connessione Lenta)"
    askAP_option_3="WPS-SLAUGHTER - Attacco Bruteforce al Pin WPS"
    askAP_option_4="Bruteforce - (Richiede handshake)"
    #
    header_askauth="MODALITA' DI VERIFICA DELLA PASSWORD"
    askauth_option_1="Handshake ("$red"Consigliato!)"
    askauth_option_2="Wpa_supplicant(Rischio di Insuccesso)"
    #
    header_deauthforce="Controllo dell'Handshake"
    deauthforce_option_1="aircrack-ng (Possibilità di Errori)"
    #
    header_deauthMENU="*Cattura dell'Handshake*"
    deauthMENU_option_1="Controllo handshake"
    #
    handshakelocation_1="posizione dell'handshake  (Esempio: $red$WORK_DIR.cap$transparent)"
    handshakelocation_2="Premi ${yellow}INVIO$transparent per avanzare"
    #
    header_webinterface="Seleziona la tua scelta"
    header_ConnectionRESET="Seleziona la pagina di Login"
    #
    general_back="Indietro"
    general_error_1="Non_Trovato"
    general_case_error="Opzione Sconosciuta. Scegli di nuovo"
    general_exitmode="Pulisco e Chiudo"
    general_exitmode_1="Disabilito l'Interfaccia Monitor"
    general_exitmode_2="Disabilito l'Interfaccia"
    general_exitmode_3="Disabilito "$grey"l'invio dei pacchetti"
    general_exitmode_4="Pulisco "$grey"iptables"
    general_exitmode_5="Ripristino "$grey"tput"
    general_exitmode_6="Riavvio il "$grey"Network-Manager"
    general_exitmode_7="Pulizia conclusa positivamente!"
    general_exitmode_8="Grazie di utilizzare fluxion"
    #
    selection_1="Client attivi"
    selection_2="Seleziona Obiettivo. Per effettuare una nuova scansione reti premi$red r$transparent"

**Comment by Bexian** [comment]
i see some error, can you post the english version too? so i can check the context and other translation problem.

**Comment by Bexian** [comment]
I have found the English version and this are my corrections. Hope this help, let me know 
if Italian option will be added Thanks.


setinterface_error="Nessuna scheda di rete trovata, chiusura..."
header_scanchan="Scansione dell'Obiettivo"
general_exitmode="Pulizia e chiusura"
general_exitmode_7="Pulizia avvenuta con successo!"
general_exitmode_8="Grazie per aver utilizzato fluxion"
selection_1="Dispositivi connessi"
selection_2="Seleziona Obiettivo. Per effettuare una nuova scansione delle reti premi$red r$transparent"

**Comment by strasharo** [comment]
Translation added, please check. Also, could you, please, confirm that the following strings are correct?

```
DIALOG_WEB_INFO_IT="Per motivi di sicurezza, immettere la chiave WPA per accedere a Internet"
DIALOG_WEB_INPUT_IT="Inserisci la tua password WPA:"
DIALOG_WEB_SUBMIT_IT="Invia"
DIALOG_WEB_ERROR_IT="Errore: La password non &egrave; corretta!"
DIALOG_WEB_OK_IT="La connessione sar&agrave; ripristinata in pochi istanti."
DIALOG_WEB_BACK_IT="Indietro"
DIALOG_WEB_ERROR_MSG_IT="Campo obbligatorio."
DIALOG_WEB_LENGHT_MIN_IT="La password deve essere superiore a {0} caratteri"
DIALOG_WEB_LENGHT_MAX_IT="La password deve essere inferiore a {0} caratteri"

```

**Comment by condor666** [comment]
French language :


Can someone (a native speaker) translate the following strings to Chinese, please?

DIALOG_WEB_INFO_ZH="Pour des raisons de sécurité, entrez votre clé WPA"
DIALOG_WEB_INPUT_ZH="Entrez votre clé WPA:"
DIALOG_WEB_SUBMIT_ZH="Soumettre"
DIALOG_WEB_ERROR_ZH="Erreur: Le mot de passe entré est incorrect!"
DIALOG_WEB_OK_ZH="Votre connection va être restaurée dans un instant."
DIALOG_WEB_BACK_ZH="Retour"
DIALOG_WEB_LENGHT_MIN_ZH="Le mot de passe doit avoir plus de 7 caractères"
DIALOG_WEB_LENGHT_MAX_ZH="Le mot de passe doit avoir moins de 64 caractères"

**Comment by Bexian** [comment]
Yes, i confirm that those strings are correct

**Comment by deltaxflux** [comment]
@condor666 French is already added

**Comment by userdsp** [comment]
Bulgarian :)

**Comment by strasharo** [comment]
За уеб-а най-вероятно ще добавя превод, но интерфейса умишлено избягвам да го превеждам, че ще се напълни с деца, бакшиши и тираджии, които го ползват на поразия и после ще трябва да давам обяснения при Кибер Явор. ;-)

**Comment by strasharo** [comment]
@condor666 Thanks, will correct the current strings with your submission.
@deltaxflux The current text appears to be somewhat garbled.

**Comment by strasharo** [comment]
@condor666 could you, please, translate this string as well?
`DIALOG_WEB_ERROR_MSG_ENG="This field is required."`

**Comment by condor666** [comment]
DIALOG_WEB_ERROR_MSG_ENG="Ce champ est requis."

**Comment by deltaxflux** [comment]
@condor666 merci :)

**Comment by userdsp** [comment]
Hahah блсгодаря ти :) Не знам защо, ама клиентите ми не получават sign in
request когато ползвам скрипта от телефона си, а преди работеше :/
