### ISSUE TITLE
Editing/adding login page templates?

### ISSUE THREAD

**Issue by Fyod** [deltaxflux/fluxion#189]
v0.23/Kali

I would like to edit or add a new login page, but when I do, it doesn't show up in the fake login choice list. Could you share a quick way to add new ones? Thanks for the great tool.

**Comment by dynyly** [comment]
regards
in the video the whole process is also as add a new menu

https://www.youtube.com/watch?v=Ez7tJCvwqfk

**Comment by dynyly** [comment]
9:45 minutes seconds later to add to menu

**Comment by NikosVlagoidis** [comment]
i added the TP-link-update from the Sites that comes with the package but when i select the menu it looks like loading the interface but nothing happens. any clue?

**Comment by Fyod** [comment]
Thank you for the video. I have the same problem as Nikos, it loads but the Captive Portal never comes up (TPLINK upgrade page).

**Comment by Fyod** [comment]
So the pages need to be .htm, not .html.
Now that that works, the last thing is that the password in TPLINK upgrade isn't posted anywhere. Possible a problem with the javascript?

**Comment by NikosVlagoidis** [comment]
maybe that's why they don't include it

**Comment by strasharo** [comment]
These are still under development, pull requests are welcome.
