### ISSUE TITLE
Kali network-manager

### ISSUE THREAD

**Issue by deltaxflux** [deltaxflux/fluxion#19]
If think network-manager is correct but still, kali don’t found any wifi after launching fluxion 
Today I change network-manager to networkmanager may it work but i don’t think so...

**Comment by strasharo** [comment]
The network manager service in Kali is called network-manager:

```
root@kalif:~# dpkg -L network-manager | grep -i init.d
/etc/init.d
/etc/init.d/network-manager
root@kalif:~# 
```

What's the point of changing the service name when the script doesn't find any device? Even if they were locked by Network Manager the script should still be able to find it, the device discovery has nothing to do with it.

Is airmon able to enumerate devices?
