### ISSUE TITLE
No fake ap, Deauth and handshake work fine 

### ISSUE THREAD

**Issue by paxblueribbon** [deltaxflux/fluxion#190]
### Which version of fluxion are you using?
.23 Rev 65

### What distribution of Linux (including the version) are you running it on?
Kali Rolling 64 bit

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Alfa Awus036h (rtl8187) 

### Which is the driver for it?
not sure the answer, was plug and play

### Does it support injection ( output of aireplay-ng -9)
yes. Injection is working

### General description of your issue along with the steps to reproduce it
no fake ap is created. Deauth works. Went through the steps like normal, gathered a handshake, when it launched the actual attack (after choosing the router interface)  I got the error 
at0: ERROR while getting the interface flags: no such device 
SIOCSIFADDR: No such device
at0: ERROR while getting the interface flags: no such device 
SIOCSIFNETMASK: No such device 
SIOCADDRT: Network is unreachable

**Comment by paxblueribbon** [comment]
Looking through the wiki tutorial a few of things stand out to me... 1. It doesn't ask me which type of attack I'd like to do.  2. It doesn't open DHCP window when spoofing.  It opens the other three.  3. Where does it store handshakes once it receives them?  I'm trying different changes and it's cumbersome to collect a handshake every time I need to retry something

**Comment by strasharo** [comment]
It looks that there is a problem creating the fake AP. Generally your chipset is incompatible with hostapd and there's an explicit setting for it to use airbase-ng. Are you able to launch an AP manually using airbase-ng?

**Comment by strasharo** [comment]
https://github.com/deltaxflux/fluxion/issues?utf8=%E2%9C%93&q=is%3Aissue%20at0
