### ISSUE TITLE
Attack doesn't work for Android 6.0

### ISSUE THREAD

**Issue by robsonbarreto3** [deltaxflux/fluxion#191]
### Which version of fluxion are you using?
0.23

### What distribution of Linux (including the version) are you running it on?
Kali 2.0

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Intel Corporation Centrino Ultimate-N 6300 

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
Yes
ioctl(SIOCSIWMODE) failed: Device or resource busy
21:09:37  Trying broadcast probe requests...
21:09:37  Injection is working!
21:09:38  Found 4 APs

21:09:38  Trying directed probe requests...
21:09:38  00:04:DF:D2:8A:6F - channel: 11 - 'Torcida Jovem'
21:09:38  Ping (min/avg/max): 1.408ms/3.665ms/9.552ms Power: -78.43
21:09:38  30/30: 100%

21:09:38  00:1D:1A:0B:50:6C - channel: 11 - 'Evo-W301AR'
21:09:44   0/30:   0%

21:09:44  78:44:76:5C:58:CB - channel: 11 - 'duarte/duarte'
21:09:51   0/30:   0%

21:09:51  E8:94:F6:9B:D3:90 - channel: 13 - 'SEP'
21:09:51  Ping (min/avg/max): 1.180ms/15.188ms/101.797ms Power: -75.59
21:09:51  29/30:  96%

### General description of your issue along with the steps to reproduce it
<???>
I am testing fluxion with Android 6.0 as client of my Wireless Network. 
>I use Hostpad to create my fake access point 
>aircrack-ng to check handshake
>Deauth all clients with mdk3
>And using Web Interface attack

But I saw that this process change my wireless interface mac adress to same mac adress of my Wireless Network, and with this Android 6.0 doesn't make a distinction of Access Points, and so the attack does not work. This method don't work without wireless interface mac adress change?

**Comment by strasharo** [comment]
Check the readme:

"The MAC address of the fake access point is different than the original"

The mac address of the fake access points differs by one octet from the original in order to prevent fluxion deauthenticating clients from itself during the jamming session.

**Comment by robsonbarreto3** [comment]
Tks, i look again and this is really right, sorry!
Still my fake ap doesn't appear. Any idea what might cause this?

**Comment by strasharo** [comment]
What do you mean by "doesn't appear." Did you try to browse a webpage using the browser of the device?

**Comment by robsonbarreto3** [comment]
"Does not Appear" = just was not created. I scan wireless connections with my laptop and AP not appear in the list, the same happens when i seek the wireless connections from my android device. My adapter supports injection (tested it with aireplay-ng -9) and Access Point too (created an AP with airbase-ng). AP created with airbase is displayed correctly in my laptop and android device.

**Comment by deltaxflux** [comment]
Well if it work with airbase-ng use it

**Comment by robsonbarreto3** [comment]
So, when i use airbase-ng without fluxion, access point work fine, but when i use with fluxion, access pont wasn't created. Please help me fix it, fluxion is a great tool, and i want use! :)

**Comment by robsonbarreto3** [comment]
So, when i use airbase without fluxion, my access point works, but, when i use airbase with fluxion my access point was not created. After get the handshake, i choose web attack and  login page interface, and i receive this error:

![screenshot from 2016-10-13 13-18-40](https://cloud.githubusercontent.com/assets/22801798/19357777/97967170-9162-11e6-84ff-492b7cab9463.png)

I use this command to create my acess point just with airbase (whithout fluxion interface): 
airbase-ng -e teste  -c 6 -P wlan0

**Comment by robsonbarreto3** [comment]
Guys, i try attack a new router and now attack works. I will get infos about old router, and post here, if you want. Tks for your time!
