### ISSUE TITLE
nmap installed but fluxion says it's not!

### ISSUE THREAD

**Issue by PyraxV** [deltaxflux/fluxion#192]
### Which version of fluxion are you using?
0.23
### What distribution of Linux (including the version) are you running it on?
Ubuntu 16.04

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Netgear 3100v3 

### Which is the driver for it?
Netgear-A6210

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
I ran the command ./Installer.sh and it said everything was ok when installing but when I ran ./fluxion it told me that nmap was not installed. Yet, if I opened up a terminal and typed "nmap" the commands would pop up.

**Comment by deltaxflux** [comment]
Please comment line 489. Fluxion check if nmap is in the folder.
To double check it again if it is installed type
$ dpkg -l | grep "nmap"

**Comment by strasharo** [comment]
nmap must be in your $PATH, otherwise it will not detect it.
