### ISSUE TITLE
FAKE LOGIN PAGE DON'T APPEAR

### ISSUE THREAD

**Issue by aquilabianca8** [deltaxflux/fluxion#194]
### Which version of fluxion are you using?
0.23 rev.65

### What distribution of Linux (including the version) are you running it on?
Kali Linux 2016.2 (Last relise)

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Alfa AWUS036NHA (chipset Arheros AR9271)

### Which is the driver for it?
ath9k_htc

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
Step by step:
1-start Fluxion (it's ok)
2-get handsheke (it's ok)
3-select N.1 fakeAP-Hostapd (it's ok)
4-select N.1 aircrack-ng (it's ok)
5-select N.1 Deauth all (it's ok)
6-get Handshake and select N.1 Check handshake (it's ok)
7-select N.1 Web Interface (it's ok)
8-select N.4 Italian (it's ok)
9-connect to fake AP (it's ok)
10-try to open any web page (using Safari with my iPhone) BUT THE LATTER DOESN'T READDRESS TO FAKE LOGIN PAGE; they remain all white web pages ..

Any suggest?

Thanks in advance;)

**Comment by donbalon4** [comment]
Hi, did you try with google.com ?
I'm getting blank pages except with google.com

**Comment by aquilabianca8** [comment]
I did try olso with "www.google.com<http://www.google.com>", but same issue too. Blank pages..

Il giorno 14 ott 2016, alle ore 04:59, Daniel Ojeda <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Hi, did you try with google.com<http://google.com> ?
I'm getting blank pages except with google.com<http://google.com>

-

**Comment by Parshuram2** [comment]
This issue has not been resolved.. everything works..but the login page.
I have php5
Kali 1.1 Rolling
Could this be a issue with Lighttpd configuration.
What is the correct configuration for it?
Many people have this Login Page doesn't appear issue..including me.
