### ISSUE TITLE
Сохранение неверных вводов 

### ISSUE THREAD

**Issue by Ferritung** [deltaxflux/fluxion#195]
В процессе работы Флуксион проверяет правильность ввода пароля.
Однако, неверные вводы тоже нужно посмотреть.
Не могли бы вы сделать лог неверных вводов для полноты картины.
Спасибо.
ЗЫ
Пишу по-русски, ибо, видел, как вы отлично на нём общаетесь.

**Comment by strasharo** [comment]
Посмотри в /root/pwlog . ;-)

**Comment by Ferritung** [comment]
Угу, посмотрел, пишет.
Так вот в последней 65 версии появилась следующая байда.
Работает через раз, то есть, при наборе рамблера приходит голая страница Логин пейдж, без CSS, пустая фрамуга с текстом. Туда если ввести пароль, то он нигде не сохраняется и в логах не отмечается. А если пытаться зайти на одноклассники, то приходит прекрасная страница с CSS, со звёздочками и введённая байда везде отмечается.
Такая шняга появилась впервые, с момента ввода русскоязычной страницы.
Не могу представить где косяк, и почему это происходит через раз.
Проверял это на двух разных компах.
ЗЫ 
Ещё момент, если запускать с WIFIslax, то из коробки он не обновляется до текущей версии, а только где-то до 44 что-ли в таком плане.
А если ставить через гитклон, то сразу обновляется до 65, до текущей.
ЗЫЗЫ
Третий момент, если пытаться заходить на майл ру, то страница виснет и Логин Пейдж не дождаться.
Если удалить весь кеш и историю из браузера, то данная проблема исчезает..
