### ISSUE TITLE
Can't install Bully or Mdk3

### ISSUE THREAD

**Issue by Ali3n0id** [deltaxflux/fluxion#196]
### Which version of fluxion are you using?
0.23

### What distribution of Linux (including the version) are you running it on?
GalliumOS 2 (Based on Ubuntu 16.04)

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Intel Corporation Wireless 7260 (rev bb)

### Which is the driver for it?
iwlwifi

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
Cannot install 'Bully' or 'Mdk3', the installer doesn't install it. Have tried manually installing to not avail.

**Comment by strasharo** [comment]
Have you added the Kali repos?

**Comment by HashikDonthinei** [comment]
Hey,Man i am having the same problem did you find a solution ?

**Comment by deltaxflux** [comment]
while running the Installer?

**Comment by linux-modder** [comment]
Same issue on Fedora 24/25 with Intel Corporation PRO/Wireless 3945ABG [Golan]

**Comment by fweil91940** [comment]
Which version of fluxion are you using? 0.23
What distribution of Linux (including the version) are you running it on? Raspbian (Deb Jessie, running properly wifite, first deployed as a LAMP distro on a Raspberry PI3).

What wireless adapter are you using? RealTek USB amplified WiFi with driv. 2011_0719_RT3070_RT3370_RT5370_RT5372_Linux_STA_V2.5.0.3_DPO including support for MT7601 chipset
Does it support injection ( output of aireplay-ng -9) yes, works using wifite monitor mode enabled

When launching ./Installer.sh, says OK for all except Bully and Mdk3 ('Installing' status left.) Then when running ./fluxion have not installed messages for both, all other components OK.

I red much posts and pages about fluxion and could understand that it can exist a solution by porceeding some patches in O/S but can't figure out what and how on my installation.

I also tried to install on a Kali standard distribution deployed on a Windows based phys. machine and VBox inside. Does not the same results, but have also components with same not installed messages.

My question is what is going wrong  depending on exact content of distro ? It seems that hardware is not the reason it fails as I can use all wifi tools I know (being either in a regular Kali or in a Debian (x64) or  Raspbian (armhf)).

Does it exist any way to debug that I could not figure out ?

KRgrds

**Comment by Pridey12** [comment]
Same here i have some troubles with mdk3 and bully

im using

Wlan) Intel Corporation PRO/Wireless 3945ABG [Golan]

Toshiba satelite a200

and i have a edimax wlan usb

**Comment by linux-modder** [comment]
Lenovo Flex4  intel wifi and Fedora 25

**Comment by UET-Boy** [comment]
Fluxion Version: 3
Sytem Model: Dell Inspiron 3542
Distribution: Ubuntu 16.04 LTS
Wireless Card: QCA9565 / AR9565 Wireless Network Adapter
Driver: ath9k
It worked fine when I ran Kali Linux live via USB. But after installation, it's not getting installed properly on Kali or Ubuntu.
