### ISSUE TITLE
Несколько моментов вдогонку

### ISSUE THREAD

**Issue by Ferritung** [deltaxflux/fluxion#197]
Там топик вы закрыли, пришлось продолжение сюда постить в новый.

Угу, посмотрел, в логи пасс пишет нормально.
Так вот в последней 65 версии появилась следующая байда.
Работает через раз, то есть, при наборе рамблера приходит голая страница Логин пейдж, без CSS, пустая фрамуга с текстом. Туда если ввести пароль, то он нигде не сохраняется и в логах не отмечается. А если пытаться зайти на одноклассники, то приходит прекрасная страница с CSS, со звёздочками и введённая байда везде отмечается.
Такая шняга появилась впервые, с момента ввода русскоязычной страницы.
Не могу представить где косяк, и почему это происходит через раз.
Проверял это на двух разных компах.
Сейчас перепроверил, на англоязычной странице Логина такая же байда, может придти страница без КСС и ничего не сохранится и даже число попыток ввода не изменится.
То есть, в зависимости от запрашиваемого сайта может придти такой глюк.

ЗЫ
Ещё момент, если запускать с WIFIslax, то из коробки он не обновляется до текущей версии, а только где-то до 44 что-ли в таком плане.
А если ставить через гитклон, то сразу обновляется до 65, до текущей.
ЗЫЗЫ
Третий момент, если пытаться заходить на майл ру, то страница виснет и Логин Пейдж не дождаться.
Если удалить весь кеш и историю из браузера, то данная проблема исчезает..

**Comment by strasharo** [comment]
1,3 - Кеш на SSL страницу, потому и зависает. 
2 - Обратитесь к разработчикам Wifislax, мы тут не причем.
