### ISSUE TITLE
install.sh

### ISSUE THREAD

**Issue by caishuhao2000** [deltaxflux/fluxion#2]
I can't find install.sh.
And the url you give: https://raw.githubusercontent.com/deltaxflux/fluxion/master/install/install.sh
shows 404 not found.

**Comment by Biggregw** [comment]
Can confirm file no longer exists. Worked fine yesterday.
Great tool btw

**Comment by pical** [comment]
please help me after installation fluxion not see iinerface only have this:       
         ⌠▓▒▓▒   ⌠▓╗     ⌠█┐ ┌█   ┌▓\  /▓┐   ⌠▓╖   ⌠◙▒▓▒◙   ⌠█\  ☒┐    
         ║▒_     │▒║     │▒║ ║▒    \▒\/▒/    │☢╫   │▒┌╤┐▒   ║▓▒\ ▓║    
         ≡◙◙     ║◙║     ║◙║ ║◙      ◙◙      ║¤▒   ║▓║☯║▓   ♜◙\✪\◙♜    
         ║▒      │▒║__   │▒└_┘▒    /▒/\▒\    │☢╫   │▒└╧┘▒   ║█ \▒█║    
         ⌡▓      ⌡◘▒▓▒   ⌡◘▒▓▒◘   └▓/  \▓┘   ⌡▓╝   ⌡◙▒▓▒◙   ⌡▓  \▓┘    
        ¯¯¯     ¯¯¯¯¯¯  ¯¯¯¯¯¯¯  ¯¯¯    ¯¯¯ ¯¯¯¯  ¯¯¯¯¯¯¯  ¯¯¯¯¯¯¯¯  

                     FLUX 0.25 (rev.  137) by  deltax
            Page: https://github.com/deltaxflux/fluxion 
                              Latest rev. [137]

root@unknown:~/fluxion# 

nothing more wtf

**Comment by alihasanmogal** [comment]
fake ap not create any one help me plzzz

**Comment by alihasanmogal** [comment]
plzzzz guys help me all step is complate but last moment fake ap not create

**Comment by iberelrj** [comment]
Same to me...

**Comment by yonex3** [comment]
![screen1](https://cloud.githubusercontent.com/assets/26184161/23587483/6247203a-01ad-11e7-9283-5d5d7c0366cc.png)

**Comment by tuthieu** [comment]
yonex3,
chmod +x fluxion then ./fluxion

**Comment by sam0hack** [comment]
@caishuhao2000 @Biggregw @pical @iberelrj You can use this version https://github.com/sam0hack/fluxion It's tested and working also you can install it's Debian package
