### ISSUE TITLE
Fluxion needs a procedure to release ports 80 and 53 if they're used by another app.

### ISSUE THREAD

**Issue by xdavidhu** [deltaxflux/fluxion#202]
### Which version of fluxion are you using?
0.23, rev. 65

### What distribution of Linux (including the version) are you running it on?
Raspbian GNU/Linux 8 (jessie)

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TP-LINK TL-WN722N, Atheros AR9271

### Which is the driver for it?
ath9k

### Does it support injection ( output of aireplay-ng -9)
Yes, its working correctly.

12:53:56  Trying broadcast probe requests...
12:53:56  Injection is working!
12:53:58  Found 2 APs

12:53:58  Trying directed probe requests...

### General description of your issue along with the steps to reproduce it
When I start the fake AP for the web interface, the fakeDns window does not start at all, so because of this, the captive protal is not working. (interestingly osx detects the portal, but IOS or Android, is not)

(All the needed packages are installed, any every other feature is working so far. And also if i go to 192.168.0.1, the page is working, and I can enter the password)

**Comment by strasharo** [comment]
Can you check if there's something else occupying port 53?
sudo netstat -ntp | grep :53

**Comment by xdavidhu** [comment]
Nothing is on port 53, but i was able to screenshot the windows (it disappears after 0,5 sec) before it closed.
![screen shot 2016-10-16 at 14 17 46](https://cloud.githubusercontent.com/assets/18151245/19417377/843aa402-93ab-11e6-930b-10dc0154532d.jpg)

**Comment by strasharo** [comment]
The error implies the same fact, there's something using the port which prevents it from binding to it. 
Try again with "netstat -tulpn | grep :53" and look closely. You can also check it using fuser:
`sudo fuser 53/udp
sudo fuser 53/tcp`
I don't have raspbian around to check it, but I suspect it might be dnsmasq, which is commonly being bundled with these distributions.

**Comment by xdavidhu** [comment]
Yeees, thank you, I found it with fuser. Tor used port 53. Now its working perfectly.

Great tool, keep it up! 👍

**Comment by strasharo** [comment]
That's very interesting, why is tor running as a DNS server, is it some custom conf or the system is prepared for transparent routing? :D 
Anyway, this is a great reminder that I should put some procedures in the script to ensure that the ports it wants to use are free. :)

**Comment by xdavidhu** [comment]
To be honest, i dont know why its using that port, i just installed it with apt-get. :)
But yes, it would be nice if fluxion would offer to kill these processes for you.

**Comment by deltaxflux** [comment]
It do that already 

`killall $(netstat -lnptu | grep ":53" | grep "LISTEN" | awk '{print $7}' | cut -d "/" -f 2) &> $flux_output_device`

**Comment by strasharo** [comment]
Obviously in this case it didn't work out, so I'll replace it with something else that actually works.

**Comment by strasharo** [comment]
Fixet in the commit above.
