### ISSUE TITLE
Q: Controll RPI by phone while using fluxion? (feature-request)

### ISSUE THREAD

**Issue by xdavidhu** [deltaxflux/fluxion#203]
When I am outside, I connect to my raspbery pi by creating a hotspot on my phone, where the pi connects automaticly.
I have 2 wireless interfaces.
The pi is connected to my phone on wlan0.
The problem is that if I select wlan1 in fluxion, it will kill all of the interfaces, and the vnc (connection to the hotspot) will close. And the only thing I can do is to restart the pi.

I know this is not a problem with fluxion, but it would be great if you would have the opportunity to use the other interfaces while using this.
(because this means that you either need to use a laptop or get a monitor and keyboard to use it with rpi, so its not really portable)

**Comment by strasharo** [comment]
How do you bring up that interface, NetworkManager?

**Comment by xdavidhu** [comment]
Uh, no, when i start the pi, they are already started. The problem happens when i select any interface in fluxion. (I use the default dhcpdui, and wpa_supplicant)

**Comment by strasharo** [comment]
I know what's the situation, my question is what does manage your network interfaces there, NetworkManager or the Debian "networking" service? These are two completely different things.
If you're not sure try typing:
```
nmcli c
nmcli d

```

**Comment by xdavidhu** [comment]
Nope, i dont have NetworkManager installed, so it will be the Debian one.

**Comment by userdsp** [comment]
In android phones is the same, but if I turn on and the off airplane mode wlan0 and mobile internet start working again :)

**Comment by RPIKal** [comment]
Same for me here :-)

Kali linux 2.1.2 ARM IMG on Raspberry pi 3

wlan0 is the built in wifi of the Pi
wlan1 is my USB Alfa adapter

wlan0 look in the /etc/network/system-connection folder for known wifi and then connect to it

So the pi can be in a remote location and i can connect back to it using VNC or SSH

But when i try to use fluxion to interact with AP near the raspberry using wlan1, it kills all network connection and vnc server gets shutdown..

Sorry if my text isn't really comprehensive , english isn't my native language !

What could i change to prevent fluxion from messing with wlan0 ?

Thanks you very much by the way for the great work you did !

**Comment by RPIKal** [comment]
Sorry but i couldn't find the lines you indicated when i go to the line 1041 i get : 
`   selection_2="Selecteaza tinta. Pentru rescanare tastati$red r$transparent"
    setinterface `

I think the lines i was supposed to find are : 
`
	#unblock interfaces
	rfkill unblock all

	# Collect all interfaces in montitor mode & stop all
	KILLMONITOR=`iwconfig 2>&1 | grep Monitor | awk '{print $1}'`

	for monkill in ${KILLMONITOR[@]}; do
		#airmon-ng stop $monkill >$flux_output_device **// ( The one to comment ? )**
		echo -n "$monkill, "
	done

`
I'm using kali linux on Raspberry Pi 3 and Network-Manager handle my wlan0 connection which need to remain connected while using fluxion :)

Will keep experimenting in the mean time if i find the answer by my self i will let you know :)

Have a great week end

**Comment by RPIKal** [comment]
Found it :-)

Just comment theses lines in fluxion's script : 
`#for nagger in "${naggysoftware[@]}"; do
		#	killall "$nagger" &>$flux_output_device
		#done`

Now i just get a quick reconnection when i exit fluxion but wlan0 connect right back so it's fine for me :)

Thanks again

**Comment by SwordStroker** [comment]
I'll try that when i get home @RPIKal :)

**Comment by strasharo** [comment]
If you get rid of this procedure it will leave your adapters being used by dhclient and the network manager in place, which will result in the adapters being unmanageable by fluxion. Prior disabling it you must ensure that your adapter and the monitor interface that's being created are excluded from your network manager.

**Comment by deltaxflux** [comment]
This is more or less a pointless issue

**Comment by RPIKal** [comment]
Yes i forgot to add that i added wlan1 and wlan1mon to my /etc/network/interfaces first if that what you meant

**Comment by strasharo** [comment]
Yes, that's the first part of the solution. Also, you need to ensure that the interfaces don't change names when plugged. This can be achieved by reserving their names using an udev rule.
For example. Create the following file if there isn't already one created by your distribution:
/etc/udev/rules.d/75-persistent-net.rules
```
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="aa:aa:aa:aa:aa:aa", ATTR{type}=="1", KERNEL=="wlan*", NAME="wlan1"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="bb:bb:bb:bb:bb:bb", ATTR{type}=="1", KERNEL=="wlan*", NAME="wlan2"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="cc:cc:cc:cc:cc:cc", ATTR{type}=="1", KERNEL=="wlan*", NAME="wlan3"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="dd:dd:dd:dd:dd:dd", ATTR{type}=="1", KERNEL=="wlan*", NAME="wlan4"

```
Just replace the dummy MAC addresses with the addresses of your wlan adapters. This way you can ensure that the adapter names persist during reboots and they don't change numbers.

Then as you mentioned, you need to exclude the adapters used with fluxion from being managed by the network manager by placing the following lines in /etc/network/interfaces

```
iface wlan0 inet manual
iface wlan0mon inet manual
iface mon0 inet manual

```
And of course remove any other entries referencing the specific adapters. Also, please not that fluxion is using a custom airmon script, which is creating the monitoring interface as mon0 and not as wlan0mon, so you need to exclude mon0 from being managed.

**Comment by sukeshj26** [comment]
Kali linux 2.1.2 ARM IMG on Raspberry pi 3

wlan0 is the built in wifi of the Pi
wlan1 is my USB Alfa adapter

wlan0 look in the /etc/network/system-connection folder for known wifi and then connect to it

So the pi can be in a remote location and i can connect back to it using VNC or SSH

But when i try to use fluxion to interact with AP near the raspberry using wlan1, it kills all network connection and vnc server gets shutdown..

Sorry if my text isn't really comprehensive , english isn't my native language !

What could i change to prevent fluxion from messing with wlan0 ?

Thanks you very much by the way for the great work you did !
I tried that code no use not working  please help me

**Comment by sukeshj26** [comment]
I had commented those two lines also
