### ISSUE TITLE
DeAuth. Not working at all. please help.

### ISSUE THREAD

**Issue by abdorahmanmahmoudd** [deltaxflux/fluxion#205]
### Which version of fluxion are you using?
0.23 the latest version.

### What distribution of Linux (including the version) are you running it on?
Kali linux 2 2016

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Intel Wifi adapter ( internal one ).

### Which is the driver for it?
Wlan0

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
Fluxion runs properly until the point of getting the handshake. So it does not Death any clients so i can't get the handshake. I tried to get it with aireplay-ng directly and it works fine.
second point that in the FakeAp process no clients DeAuth again. when i run airdump-ng it shows that all station still associated with the AP so Fluxion Do not Deauth at all.
helpful point : in the MDK3 Deauth window in the FakeAP process. it shows that the script start to deauth clients on channel -1. i do not know why i got this. 
Thanks to help me.   
@deltaxflux  @strasharo

**Comment by strasharo** [comment]
You're out of range. mdk3 reacts only when it sees data packets being transmitted between the client and the access point, while aireplay just shoots them blindly.

**Comment by abdorahmanmahmoudd** [comment]
Hi, 
Thanks for your reply :) .
But in my case i was testing my own router and Mobile So they are all close to each other and not out of range issue. 
please help me.

**Comment by lexie143** [comment]
i have same problem mdk3 not working when attack is progress i remember i set first the 33 dbm of my wifi card and i observed i boot my pc the mac address of my pc and my usb wifi card adapter is changed automatically i think that is the problem or restricted  country regulation code i dont know please help.
