### ISSUE TITLE
DeAuth. Not working at all.

### ISSUE THREAD

**Issue by abdorahmanmahmoudd** [deltaxflux/fluxion#206]
### Which version of fluxion are you using?
0.23 the latest version.

### What distribution of Linux (including the version) are you running it on?
Kali Linux 2 2016

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Intel WiFi adapter ( internal one ).

### Which is the driver for it?
Wlan0

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
Fluxion runs properly until the point of getting the handshake. So it does not Death any clients so i can't get the handshake. I tried to get it with aireplay-ng directly and it works fine.
second point that in the FakeAp process no clients DeAuth again. when i run airdump-ng it shows that all station still associated with the AP so Fluxion Do not Deauth at all. i'm testing my router with my mobile and my family devices connected to it. So they are all close to each other and the network is active. A lot of data packets are transmitting. 
helpful point : in the MDK3 Deauth window in the FakeAP process. it shows that the script start to deauth clients on channel -1. 
Thanks to help me.

@strasharo @deltaxflux

**Comment by userdsp** [comment]
Same here. Wifi wn722n used on nethunter device.

**Comment by strasharo** [comment]
@userdsp , в /tmp/TMPfluxion/mdk3.txt има ли го MAC-а на AP-то?

**Comment by userdsp** [comment]
Има го и всичко от страна на fluxion изглежда ОК, но клиентите не се деауторизират.

**Comment by userdsp** [comment]
В една предна версия бях редактирал fluxion да не спира rmnet0 и тогава си спомням, че ми беше направило същият проблем. Да не би да има нещо общо със тикет #203

**Comment by abdorahmanmahmoudd** [comment]
why you are ignore me guys !!

**Comment by strasharo** [comment]
Преди драмата беше, че на някои дистрибуции липсваше по дефолт strings и не проверявахме дали въобще го има при старта. Което от своя страна водеше до празен mdk3.txt и съответно се пускаше mdk-то без никакъв таргет. После добавих чека за strings и се приключи с проблема. Не би трябвало да има нещо общо със спирането на мрежата. Ако пуснеш само mdk-то отделно с таргет проблемната мрежа работи ли? И има ли разлика ако го пуснеш на физическа машина вместо на Нетхънтъра?

**Comment by abdorahmanmahmoudd** [comment]
English please .

**Comment by userdsp** [comment]
Извинявай моя грешка! Същият е проблема, аз видях, че мак адреса го има като файлове cap...и др.  в /tmp/TMPfluxion, но /tmp/TMPfluxion/mdk3.txt не, че е празен, а го няма изобщо.

**Comment by userdsp** [comment]
До 54 версия ако не се лъжа за нея, всичко беше ок при мен.

**Comment by strasharo** [comment]
Странна работа. Имаш ли "strings" командата в дистрибуцията?

**Comment by userdsp** [comment]
Имам я.

**Comment by strasharo** [comment]
Пробвай докато е пуснато всичко и се очаква да deauth-ва да изпълниш следното:
`strings /tmp/TMPfluxion/dump-02.csv | cut -d "," -f1,14 | grep -h "$Host_SSID" | cut -d "," -f1`
Само замени $Host_SSID със SSID-а на таргета.

**Comment by userdsp** [comment]
Изкара ми списък с маковете на всички сканирани АП, а не само на тази от ssid

**Comment by strasharo** [comment]
aircrack-а ти от пакет на Кали ли е или е билдван на ръка от сорс?

**Comment by userdsp** [comment]
От кали е.

**Comment by strasharo** [comment]
Може ли да ми дадеш output-а от:
```

dpkg -l aircrack-ng
airodump-ng --help | head -3
```
Както и копие от CSV файла. Мисля, че трябва да може да се закачи тук в issue-то, ако не стане кажи да ти пратя мейл.

**Comment by abdorahmanmahmoudd** [comment]
I'm the issue owner and i get ignored :D why you dummy kids

**Comment by gabrig** [comment]
They are trying to solve the problem. He asked to have a log, in order to verify, if I'm not wrong. I think they will tell you when have answers. 
In any case, I follow the thread, since I have problems with handshake too.

**Comment by abdorahmanmahmoudd** [comment]
okay. thanks to clarification.

**Comment by userdsp** [comment]
@strasharo Всичко е инсталирано от инсталатора на fluxion. Преди малко направ х чисто нова инсталация на кали чрез Linux Deploy и това е скрийншот на инфото което ми поиска.

![screenshot_20161018-155852](https://cloud.githubusercontent.com/assets/7585552/19478589/d2e30b8e-954b-11e6-9cf9-1974dced84e8.png)

**Comment by strasharo** [comment]
По време на скринйшота mdk3.txt пак ли липсва? Виждам, че deauth-ва правилния MAC, явно е там все пак?

**Comment by userdsp** [comment]
Тично тогава гледах, иначе цялата /tmp е празна

**Comment by strasharo** [comment]
Все някъде си е записало файловете за да функционира, да не би да минава нещо да ги бърше? Можеш ли да смениш в началото на скрипта това:
`DUMP_PATH="/tmp/TMPflux"`
на това:
`DUMP_PATH="/var/tmp/TMPflux"`

И след това да го пуснеш отново да видиш дали файловете ще са налични в новата локация?

**Comment by userdsp** [comment]
![screenshot_20161018-175259](https://cloud.githubusercontent.com/assets/7585552/19483086/c3274a56-955b-11e6-94ac-1686bd75cce1.png)

**Comment by userdsp** [comment]
И там не се появява този текстов файл.

**Comment by strasharo** [comment]
А останалите файлове там ли са или цялата /var/tmp е празна?

**Comment by userdsp** [comment]
Всичко е там и deauth mdk3 работи, но не и deauth all. Тоест всичко се държи еднакво преди и след промяната на темп директорията.

**Comment by userdsp** [comment]
Преди време имаше същият тикет ако не се лъжа беше заради версията на питон и след коментирането на няколко реда всичко тръгваше.

**Comment by strasharo** [comment]
Питон се ползва само за инсталирането на dependencies, основният скрипт не го ползва. След малко ще го проверя на практика какво се е счупило, че през деня нямах възможност. Значи последно всичко е там, но mdk3.txt файла го няма?

**Comment by userdsp** [comment]
Да mdk3.txt  се появява ако ръчно кънектна клиента няколко пъти за да запише handshake след което се създава фишинг мрежата и както и mdk3.txt

**Comment by userdsp** [comment]
Ако избера първата опция deauth all тогава mdk3.txt го няма, появява се ако избера втората опция deauth all [mdk3], или ако по случайност handshake се запише след deauth all и после се стартира клонирането на мрежата

**Comment by userdsp** [comment]
На vmware всичко работи 👍 но е хубаво да е ок и на мобилките :)

**Comment by userdsp** [comment]
Да направя ли видео, ако не си ме разбрал?

**Comment by strasharo** [comment]
Така и трябва да е по принцип, файла се пише или като избереш mdk3 при deauth или ако вече имаш handshake и тръгнеш да палиш AP-то. И в двата случая файла се ползва само от mdk3, aireplay атаките не го ползват. Когато е там съдържа ли мак адреса на access point-а?

**Comment by userdsp** [comment]
Да но deauth all без mdk3 (първата опция) преди си работеше. Последно ползвах версия 54 и там е ок.

**Comment by strasharo** [comment]
Аааа, сега те разбрах вече. Аз през цялото време си мислих, че mdk-то не работи. :D (фейспалм, сори). Чакай да видя какво се е омазало.

**Comment by deltaxflux** [comment]
while starting the fake AP check if the mdk3.txt is empty 
`sudo cat /tmp/TMPflux/mdk3.txt`

**Comment by strasharo** [comment]
@deltaxflux , waiit, I'll handle it, it's about deauth all and not mdk3.

**Comment by userdsp** [comment]
No its not empty. I'm telling mdk3 its ok, but the first deauth all option don't work at mobile devices anymore. I was used v54 and there bouth works perfectly.

**Comment by deltaxflux** [comment]
@strasharo @userdsp ok

**Comment by strasharo** [comment]
Ако избереш опция 3 работи ли? Като цяло нищо не се е променило, просто при опция 1) се пуска deauth на broadcast адреса, докато на 3 е същото само, че го изпраща таргетирано към определени клиенти. Като цяло опция 1) не е от най-рентабилните, зависи какъв клиент имаш.

**Comment by strasharo** [comment]
Ако мислиш, че има някаква разлика в поведението между виртуалката и мобилния, може да сравниш с какви опции се цъка aireplay-ng като избереш опция 1). Просто докато върви направи:
`ps -ef  | grep -i aireplay-ng | grep -v grep`
Би трябвало аргументите да са еднакви. Ако и на двете места аргументите са еднакви докато върви, но на едното работи, а на другото не, значи е другаде проблема. Може просто на мобилния даа не му стига ток да захранва адаптера и да излъчва не достатъчно силно. Като цяло нямам опит с адаптери вързани към мобилни устройства.

**Comment by userdsp** [comment]
Ясно стана какво се случва. 1 и 3 не могат да кикнат лаптопа ми, но изхвърлят другите андроиди :)

**Comment by userdsp** [comment]
Аз от виртуалката тествам върху мобилките и заъова не съм се усетил :)

**Comment by strasharo** [comment]
При 1) като цяло много зависи от операционна система и конкретен driver за wireless-а. Понеже изпраща на brodacast, а не към конкретни клиенти и масово се случва просто да се игнорира особено от windows-и, понеже не е насочено към конкретния клиент. А за 3 предполагам не му стига пауъра нещо. Оптималния вариант е mdk3, понеже реагира на дата пакети и изпраща deauth към конкретни клиенти. 3 ползвам в случай, че няма трафик в момента и просто принудително ги разкачам.

**Comment by abdorahmanmahmoudd** [comment]
Okay you closed the issue and we didn't understand anything . please answer in English.

**Comment by userdsp** [comment]
@abdorahmanmahmoudd you must use "deauth all mdk3" only and it will work perfectly.

**Comment by hemwahdan** [comment]
Why mdk3 still not working  ?

**Comment by Jetskixd** [comment]
yeah mine too, its working when capturing handshake then if the fakeAP created the mdk3 is not disconnecting any clients.

**Comment by Jetskixd** [comment]
it is stable for the previous version but i don't know how to install the previous version

**Comment by hemwahdan** [comment]
@Jetskixd  Your are right ^

**Comment by hemwahdan** [comment]
@deltaxflux  we need Solution

**Comment by hemwahdan** [comment]
@abdorahmanmahmoudd  بزمتك ينفع الي بيعملو فينا الاجانب :D

**Comment by Jetskixd** [comment]
yeah @deltaxflux  we need solution but i think you're busy hahaha.  @hemwahdan  do you know how to install the previous version ? coz its working properly last night then an automatic update happened every time i open the fluxion, an anyone who knows to disable update ?

**Comment by hemwahdan** [comment]
@deltaxflux i don't know :(

**Comment by hemwahdan** [comment]
@Jetskixd  I don't know :(

**Comment by Jetskixd** [comment]
@hemwahdan  it's ok lets wait deltaxflux and his mates to fix this bug.

**Comment by hemwahdan** [comment]
i'm waiting and i will try to fix bug too

**Comment by Jetskixd** [comment]
good luck man, if you've fixed it please tell me on how to fix it ok? thank you. and @deltaxflux  can you teach me on how to edit the web interface of the fakeAP because i want it to be more trusted by clients by editing it and putting the logo of their router or modem.

**Comment by deltaxflux** [comment]
@Jetskixd please check if the mdk3.txt file is empty 

`sudo cat /tmp/TMPflux/mdk3.txt`

**Comment by Jetskixd** [comment]
wait i'll check it. should i run the fluxion ?

**Comment by strasharo** [comment]
Do the check while mdk3 is running and it's supposed to be deauthenticating.

**Comment by Jetskixd** [comment]
![4](https://cloud.githubusercontent.com/assets/15819628/19546787/6222ee1c-9647-11e6-8806-f65d290d3a86.png)

**Comment by Jetskixd** [comment]
last night its disconnecting clients like that. should i do the in that phase ? thank you everyone for responding

**Comment by deltaxflux** [comment]
@Jetskixd do u get a output from this command ?

**Comment by deltaxflux** [comment]
If not use this command to resolve it 
`strings /tmp/TMPflux/dump-02.csv | cut -d "," -f1,14 | grep -h "$Host_SSID" | cut -d "," -f1 | awk '{if (NR!=1) {print}}' > /tmp/TMPflux/mdk3.txt`

**Comment by Jetskixd** [comment]
do i need to the that every time in that phase ?

**Comment by Jetskixd** [comment]
i'm currently reinstalling it i will post the output ASAP.

**Comment by hemwahdan** [comment]
mdk3 is empty :-1: 
![screenshot from 2016-10-20 16-20-39](https://cloud.githubusercontent.com/assets/10759173/19547141/1cd3e974-965b-11e6-8b7b-6e37ae2570ff.png)

**Comment by strasharo** [comment]
Just pushed a new version. Update it and try again.

**Comment by Jetskixd** [comment]
@hemwahdan  did you try to type the string thingy that deltaxflu said?

**Comment by hemwahdan** [comment]
yes , but mdk3 still empty
@Jetskixd

**Comment by strasharo** [comment]
I pushed a new version **update it** and try again.

**Comment by Jetskixd** [comment]
@hemwahdan  there's an update !!!! they'd fix it. @strasharo  & @deltaxflux  thank you so much :D

**Comment by strasharo** [comment]
Does the fix work?

**Comment by hemwahdan** [comment]
Thanks ^^ 
@deltaxflux

**Comment by strasharo** [comment]
Can someone confirm if the fix that I pushed resolves the issue?

**Comment by Jetskixd** [comment]
still downloading... @hemwahdan  does it fix ?

**Comment by Jetskixd** [comment]
@strasharo i will test it ASAP when the download is complete.

**Comment by hemwahdan** [comment]
yes @deltaxflux  New update work mdk3 @strasharo

**Comment by Jetskixd** [comment]
there's another bug i don't know if  this is a bug. but i think 1 function is missing in fake AP.  the time that i'm using linset. the user is disconnected and the linset is forcing the client to connect to the fake AP. i'd test it on my own router and cellphone as  i can see its not pulling the client to connect to the fake AP. any suggestion ?

**Comment by Jetskixd** [comment]
it's just disconnecting the client. and it works fine. but to automatically connect to the fake AP is not which i think a big advantage and help to the fluxion's users. (to guide their victim)

**Comment by Jetskixd** [comment]
btw does vmware affects it ? because i'm running it on vmware i hope you'll respond thanks.

**Comment by strasharo** [comment]
It's not dragging clients automatically as it doesn't need to. There's no point in doing that because you need to have the user present in order to enter his password.

**Comment by Jetskixd** [comment]
i mean if they won't see that there's a mirror and auto-connect to the fake AP there's a big chance to enter his password.

**Comment by Jetskixd** [comment]
and i think that's how linset work before as i remember. correct me if I'm wrong thanks.

**Comment by strasharo** [comment]
It never worked this way.

**Comment by Jetskixd** [comment]
ow sorry, i thought it was. i didn't use it for a long time haha. thanks pal.
