### ISSUE TITLE
Handshake problem

### ISSUE THREAD

**Issue by gabrig** [deltaxflux/fluxion#208]
Hi, currently running v.0.23 rev 69.
I have two main problems when trying to run "FakeAP - Hostpad":
1) I can't upload the handshake file, both writing the location and drag and drop the file in the window. It says "file not found", while I have it.
2) When I try to get the handshake in fluxion, the program open Only the window with Deauth process. I remember that in a previous version there were 2 windows open, one like the airodump and one for deauth.

Can you please help me?
Thank you very much

**Comment by strasharo** [comment]
1) You must specify the full path to the handshake.
2) You must choose a type of deauth in order to have a deauth window open, it's not being done automatically.

**Comment by gabrig** [comment]
Hi, thanks for reply!
1) ok, solved with "locate". I forgot a dot.
2) I have choosen all the methods, but still coming up only the deauth window for every deauth mode (the one with red lines)

**Comment by strasharo** [comment]
That's the expected behavior. If you want a constant deauth choose mdk3.

**Comment by gabrig** [comment]
Nono it's only that I remembered that in the past there were two windows when trying to get the handshake. And that I had to stop the process when I got it. Now how can I know if I got the Handshake? Does the program stops by itself?
Thank you
