### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by WhiteSniper** [deltaxflux/fluxion#209]
### Which version of fluxion are you using?
latest

### What distribution of Linux (including the version) are you running it on?
2016.1

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
tp link 

### Which is the driver for it?
latest

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
i want you to creat update.py that will update all files in fluxion because downloading it again and again is not that good so please make a script that will automatically update all files and changes and bugs fixes my English  is not good so dont make fun of me 

Thanks

**Comment by deltaxflux** [comment]
**The file is only 344 kb big**. So in this case pointless. If you really want that change please fell free to make a pull request.

**Comment by strasharo** [comment]
Feel free to update via git instead.
