### ISSUE TITLE
Quote (" ESSID ") in the Fake AP's ESSID

### ISSUE THREAD

**Issue by Sujangml** [deltaxflux/fluxion#212]
### Which version of fluxion are you using?
<???> FLUX 0.23 (rev.  71)

### What distribution of Linux (including the version) are you running it on?
<???>
Kali LInus 2016.2
### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<???>I Don't know about this

### Which is the driver for it?
<???>I Don't know about this.

### Does it support injection ( output of aireplay-ng -9)
<???>
yes
### General description of your issue along with the steps to reproduce it
<???>The issue is only in one wifi network. In all other networks that i have tried it worked fine. THe name of the network is Suvancmc but fake AP has got name " Suvancmc " with quote. Only this network has got the problem all other network are fine n fluxion worked on all other network except this one.
![screenshot from 2016-10-14 11-35-51](https://cloud.githubusercontent.com/assets/22924595/19502092/2321f23a-95ca-11e6-9ff4-3dd1217bf578.png)

**Comment by deltaxflux** [comment]
Looks like the Essid is "Suvancmc".

**Comment by Sujangml** [comment]
yaa but the Essid would be better without  quote. this might be some where doubtful....
