### ISSUE TITLE
There are no wireless card, quit...

### ISSUE THREAD

**Issue by stezan** [deltaxflux/fluxion#213]
### Which version of fluxion are you using?
The last version, 73

### What distribution of Linux (including the version) are you running it on?
4.6.0-kali1-amd64 - Kali Linux

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Model No: TL-WN725N
Chipset: Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter

### Which is the driver for it?
Driver: 8881eu

### Does it support injection ( output of aireplay-ng -9)
i got an error:
ioctl(SIOCSIWMODE) failed: Invalid argument
ioctl(SIOCSIWMODE) failed: Invalid argument
Error setting monitor mode on wlan0
(Is it because i have to set wireless card in monitor mode?)

### General description of your issue along with the steps to reproduce it
Kali linux detects my wireless card, and i can surf on the internet, but when i select the language in the fluxion menu, it responds me that there are no wireless card and so it quit.
It's a problem of the wifi adapter? How i could resolve it?
Thank you all!

**Comment by deltaxflux** [comment]
Your wireless card is not supported

**Comment by stezan** [comment]
Could you tell me the cheapest model supporter?
Thank you so much

**Comment by strasharo** [comment]
TL-WN722N is the best and cheapest choice. It has Atheros chipset.

**Comment by nikcerne** [comment]
Im getting this same error with the TL-WN722N

**Comment by teabag178** [comment]
im getting the same issue and my wireless cards do detect but my HDD crash and after i reinstall this  problem started

**Comment by deltaxflux** [comment]
@nikcerne and @teabag178 please create a new issue with your spezific problem
