### ISSUE TITLE
Best Wireless card

### ISSUE THREAD

**Issue by Mcburnie** [deltaxflux/fluxion#214]
Deltasflux what wireless card would you recommend for maximum effect. The issues with the 
ALFA AWUS036H seem to have been fixed right?

**Comment by deltaxflux** [comment]
I check it again but this card seems to work. If you want to read the full post [here](https://forums.kali.org/showthread.php?3816-Working-Hardware-ALFA-AWUS036H-500mW-(Realtek-RTL8187L-rtl8187))

**Comment by strasharo** [comment]
The best and cheapest choice would be TL-WN722N.

**Comment by Mcburnie** [comment]
Which card would you recommend personally deltax? Thanks alot!

**Comment by deltaxflux** [comment]
As already @strasharo said the TL-WN722N you get the value for the price.
