### ISSUE TITLE
Fluxion Tutorial Suggestion: Actually tell us how to select

### ISSUE THREAD

**Issue by Rojikku** [deltaxflux/fluxion#216]
In the fluxion tutorial, on the wiki, please add a line indicating that you need to close the scan window to get to the selection menu. This is not behavior one would generally predict, and it would be very helpful for it to be more obvious.

**Comment by deltaxflux** [comment]
Next time we add a feature which automatically cook your food

**Comment by Rojikku** [comment]
I don't see what your issue with the suggestion is.

**Comment by deltaxflux** [comment]
@Rojikku u don't understand jokes. Please buy a [rice cooker](https://www.amazon.com/rice-cookers/b?ie=UTF8&node=678540011) instead of using fluxion
