### ISSUE TITLE
Mdk3 not working 

### ISSUE THREAD

**Issue by hemwahdan** [deltaxflux/fluxion#217]
Mdk3 notworking i tried on kail linux rolling 2 and wifislax 4.11.0
didn't work at all ,but work only when i wanna get handshake 
i tried mdk3 on linset , i'ts works 
my network card is qualcomm atheros ar9285
![screenshot from 2016-10-20 15-07-01](https://cloud.githubusercontent.com/assets/10759173/19545960/bdea2e6e-9650-11e6-9f15-5998d9d573bd.png)

**Comment by deltaxflux** [comment]
#206

**Comment by strasharo** [comment]
Is the file /tmp/TMPfluxion/mdk3.txt present during the run and if yes what are its contents?

**Comment by Zemnexx** [comment]
Notice this issue occurring after updating Kali linux. On a fresh install using older packages, works normal. Can repeat this issue consistently by updating Kali.
