### ISSUE TITLE
Index.htm rendered without styles and scripts

### ISSUE THREAD

**Issue by slava-nikulin** [deltaxflux/fluxion#218]
### Which version of fluxion are you using?
0.23 (rev 74)

### What distribution of Linux (including the version) are you running it on?
Kali 2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Model: TP-Link TL-WN821N v3; Chipset: Atheros AR7010+AR9287

### Which is the driver for it?
ath9k_htc

### Does it support injection ( output of aireplay-ng -9)
Injection is working

### General description of your issue along with the steps to reproduce it
When I connect to the fake AP, I'm redirected to the page with these errors in console.
![capture](https://cloud.githubusercontent.com/assets/7102004/19607368/bf83dbec-97e2-11e6-9ce1-c751d6f17071.PNG)

Also, scripts do not work too, and form submitting as well.
I guess, this is lighttpd error.

**Comment by Ferritung** [comment]
TO slava-nikulin
https://github.com/deltaxflux/fluxion/issues/197

**Comment by strasharo** [comment]
As @Ferritung said it think it's most probably cache in your browser, fluxion can't do much about it.

**Comment by slava-nikulin** [comment]
It's not cache, guys. If it was a cache, ctrl+r would help. I think, problem is in fakedns redirect settings: all requests are redirected to the index, or it can be some lighttpd bug.
I'll try to investigate and fix, but I doubt that I will succeed, cause it is not my area.

**Comment by strasharo** [comment]
@Ferritung does Russian work for you?
