### ISSUE TITLE
Android error on connectivity.android.com/generate_204 while using Arris fakeap

### ISSUE THREAD

**Issue by iamtrying-127times** [deltaxflux/fluxion#219]
### Which version of fluxion are you using?
23 rev 74

### What distribution of Linux (including the version) are you running it on?
Kali 4.7.0 Debian 5.4.1 20160904

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
D-Link AirPlus G DWL-G122 Wireless USB Adapter(rev.C) #2 
RT2571W
(for now, next week i will get a new one, and test it. I will post results)

### Which is the driver for it?
Rt73usb

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
Testing fluxion with an android phone, got an error after connect it with FakeAp Hostapd, while using Arris-ENG login page. The default languages pages loads correctly.
In android browser, appears connectivitycheck.android.com/generate_204  and error in page layout.

**Comment by strasharo** [comment]
Arris is under development, use some of the interfaces labeled as "NEUTRA".

**Comment by deltaxflux** [comment]
Every other login page is bonus

**Comment by iamtrying-127times** [comment]
Hi. Can you turn it back? ARRIS ENG was working good with pc connection.
