### ISSUE TITLE
help plees colabaration

### ISSUE THREAD

**Issue by dynyly** [deltaxflux/fluxion#221]
regards

1 forgive him for not doing as they should but I do not understand share add to ghitub so small updates:
Added movement fluxion logo and color corrected for better appearance
Modified interfaces possibility
English, Spanish, Italian, potuges; frances

netgeart
huawei
arris
vodafone
ability to add different languages  by collaborators

Added verizon interface (English, Spanish, Italian, fraces, portuges)
Added TPLINK interface (English, Spanish --posibilidad of more languages through collaboration)

Estruturado selecion menu interfaces for better selecion

Please appreciate someone who added code to ghitub
(I go crazy I do not hear as upload code to share updates, fear of spoiling all)

Can anyone upload it help?
it is not necessary now, if when you have time and want collaborator
I would give updates to share, but I need contributor to climb ghitub

**Comment by deltaxflux** [comment]
_You want to be a collaborator ?_

**Comment by strasharo** [comment]
![dafuq-did-i-just-read-meme](https://cloud.githubusercontent.com/assets/3337997/19621890/e91e3db8-98a4-11e6-97f2-ce053487baf8.jpg)

**Comment by dynyly** [comment]
Hello
thanks for answering :
sorry if not aking good bad translator
I want to share small improvements but not entiedo upload files to guitub
Would you be kind enough to add improvements?
 I thought that'd be tired of my messages
------------
Animated logo fluxion with better resolution color
interfaces 4 languages
Arriss
Vodafone
Netgear
Huawei

Menu interfaces improved to better interface selecion

Added Tp-link (English language, Spanish)
Verizon added 4 languages
possibility of translations collaboration of all web interfaces
------
It is a lot of code for, message

https://mega.nz/#!LMAz3CzR!plyXegJFwj9zdTjFl8URm8K7Hm8nmvPmC5GtyQe8ZjY

2016-10-22 20:20 GMT+02:00 deltax <notifications@github.com>:

**Comment by dynyly** [comment]
thanks for answering:
Pedia help someone climb new code (do not understand ghitub)
I have given to deltax new things
I hope not bother by my lack of knowledge about ghitub

2016-10-22 21:14 GMT+02:00 strasharo <notifications@github.com>:

**Comment by Vigilence** [comment]
He's basically saying that he has modified and improved certain aspects of fluxion but doesn't know how to use github very well.  He's been working on it daily and if you check out [his fork of fluxion](https://github.com/dynyly/fluxion) you can see what he is working on.  Dynyly is a native Spanish speaker and doesn't speak English very well.


@dynyl [Check ](https://www.youtube.com/watch?v=UMhskLXJuq4)this out to learn some of the basics of github, you can youtube the rest yourself in spanish.

@dynyl [Comprobar] (https://www.youtube.com/watch?v=UMhskLXJuq4) esto para aprender algunos de los fundamentos de GitHub, puede youtube el resto a sí mismo en español.


Also you can use [google translate](https://translate.google.com/) for assistance in typing in English.

También se puede utilizar [google translate] (https://translate.google.com/) para la asistencia en escribir en Inglés.

**Comment by deltaxflux** [comment]
Vigilence thank you for your explanation. Mhm, there might be a reason why we don't answere.

**Comment by Vigilence** [comment]
@deltaxflux NP :D.
