### ISSUE TITLE
Fluxion is reseting default colors in command prompt.

### ISSUE THREAD

**Issue by waldek0990** [deltaxflux/fluxion#224]
Which version of fluxion are you using?
<0.23>
What distribution of Linux (including the version) are you running it on?
kali 2.0
What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
ALFA AWUS036H
Which is the driver for it?
I don't know (not important now)
Does it support injection ( output of aireplay-ng -9)
yes
General description of your issue along with the steps to reproduce it
Fluxion is destroying colors in cmd prompt. ie. I had a red color of root@host:~# and now all is white. I strongly belive the fluxion caused this.

**Comment by deltaxflux** [comment]
And do you thing your are a hacker because you have changed the font color.

**Comment by strasharo** [comment]
Fluxion is not interacting in any way with your profile settings.

**Comment by waldek0990** [comment]
i belive it's a bug

**Comment by deltaxflux** [comment]
Yeah because it has nothing do to with your profile settings.

**Comment by waldek0990** [comment]
ok then. but i belive i have found another bug.
setting path to handshake doesn't work! i have to catch handshake every
time. ie. /root/handdhakes/handshake.cap fluxion says file_not_present.
