### ISSUE TITLE
Having trouble with Fluxion

### ISSUE THREAD

**Issue by forid786** [deltaxflux/fluxion#226]
### Which version of fluxion are you using?
<???>
77
### What distribution of Linux (including the version) are you running it on?
<???>
Kali 4.7.0 Debian 5.4.1 20160904
### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<???>
wlan0		ath5k		Qualcomm Atheros AR242x / AR542x Wireless Network Adapter (PCI-Express) (rev 01)
wlan1		rtl8187		Realtek Semiconductor Corp. RTL8187

### Which is the driver for it?
<???>
ath5k + rtl8187
### Does it support injection ( output of aireplay-ng -9)
<???>
aireplay-ng wlan1mon -9
12:40:39  Trying broadcast probe requests...
12:40:39  Injection is working!

[Then a list of nearby AP's]

### General description of your issue along with the steps to reproduce it
<???>
Been having a few issues, first one is with Fluxion actually deauthenticating itself. When the fake AP is spawned, it's completely cloning the real AC's mac address and running deauthentication attacks against itself. I manually tried stopping the deauthentication attack, however, I've been unable to get web pages out of the fake AP. On the screen I can see the fake DNS trying to redirect Android's 209 page to 192.168.1.1. But I cannot load it up on my phone and get it working.

Moving on, I tried WPS slaughter and reaver. It's gone to 90.90% completion and it's stuck trying the same pin. Not that the pin is failing or anything, I've searched online and apparently a few people are having the same issue, but no ones actually found a resolution. Would be glad if someone could help me out with this.

Thanks for the amazing work, makes life a lot easier having all the tools in a neat package.

**Comment by strasharo** [comment]
The fake AP MAC differs by one octet in the middle, beginning and end are the same.

**Comment by deltaxflux** [comment]
As you can read in the README

**Comment by forid786** [comment]
Either way I still seem to be getting disconnected from the Fake AP before I can even pull up the captive portal. As stated, my setup is above and I've tried from two Android devices and they're both disconnecting at exactly the same time leading me to believe that it's somehow deauthenticating. Any help would be much appreciated.

**Comment by slava-nikulin** [comment]
Why do you, guys close issues without fixing them?
@forid786  I've also get this bug, but it appears every second time. Try to update kali and relaunch script. It seems, that mdk3 thinks that fake AP and the real one are the same.

**Comment by Ferritung** [comment]
Какая разница, чего там думает MDK3.
Выключи его и делай через аерплей-ng, там можно указать два мака..
Данная прога требует знаний и конкретного подхода.
А вообще, МДК3 действительно дерьмо.
