### ISSUE TITLE
bash: ./fluxion: /bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by whitecocaine** [deltaxflux/fluxion#227]
### Which version of fluxion are you using?
<newest>

### What distribution of Linux (including the version) are you running it on?
<Kali 2016.2>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<Ralink corp. RT3290 Wireless 802.11n 1T/1R PCIe>

### General description of your issue along with the steps to reproduce it
Yesterday, when i work with Fluxion i had update and my fluxion is crashed. When i enter ./fluxion i have this communicate:

bash: ./fluxion: /bin/bash^M: bad interpreter: No such file or directory

I tried use flux_rev-78.backup, but not help:
Fluxion start, but after English language select:

./flux_rev-78.backup: line 1385: ./airmon: No such file or directory
./flux_rev-78.backup: line 1386: ./airmon: No such file or directory
There are no wireless cards, quit...

Yesterday all work fine before update.

**Comment by ozsteyr** [comment]
Its the way the fluxion script was saved, in a different OS. Open fluxion script in for example; droidedit free from playstore delete and replace a character; ie, delete a leter then replace with same letter then save.

**Comment by strasharo** [comment]
Re-download it, that commit was reverted.

**Comment by deltaxflux** [comment]
Yeah was my fault.
