### ISSUE TITLE
 dump-01.csv 

### ISSUE THREAD

**Issue by domeOo** [deltaxflux/fluxion#228]
### Which version of fluxion are you using?
0.23 (rev.78)

### What distribution of Linux (including the version) are you running it on?
Kali 64 bit v. 2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
AWUS036H RTL8187

### Which is the driver for it?
RTL8187

### Does it support injection ( output of aireplay-ng -9)
yes

root@kali:~/Desktop# aireplay-ng -9 wlan1
ioctl(SIOCSIWMODE) failed: Device or resource busy
^[[A^[[A13:05:30  Trying broadcast probe requests...
13:05:30  Injection is working!
13:05:32  Found 15 APs

13:05:32  Trying directed probe requests...
13:05:32  20:2B:C1:50:91:52 - channel: 6 - 'WLAN-915250'
13:05:33  Ping (min/avg/max): 3.542ms/39.278ms/56.429ms Power: -49.73
13:05:33  30/30: 100%

13:05:33  00:17:9A:59:9F:7D - channel: 6 - 'prettyfly4awifi'
13:05:34  Ping (min/avg/max): 3.909ms/24.413ms/53.542ms Power: -32.43
13:05:34  30/30: 100%

### General description of your issue along with the steps to reproduce it

1. Start Fluxion
2. Choose language
3. Choose Wifi device 
4. After a while press ctrl+c to stop wifi monitor
5. Get Error:

#                                                       #
#      FLUXION 0.23    < Fluxion Is The Future >        #
# by Deltax, Strasharo and ApatheticEuphoria            #
#                                                       #
#########################################################

expr: syntax error
                        WIFI LIST 

 ID      MAC                      CHAN    SECU     PWR   ESSID

grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines:: No such file or directory
grep: ‘/tmp/TMPflux/dump-01.csv’: No such file or directory
  1)	head: invalid number of lines: ‘/tmp/TMPflux/dump-01.csv’	 	   100%	 

i looked in tmp/TEMPflux........ for dump-01.csv and its there. 
So it cant be that the problem is the Wifi-Adapter

I think its related to #99

**Comment by deltaxflux** [comment]
#108 try to re clone the git. Sometimes magic happend
