### ISSUE TITLE
nethunter kali 2016 https not work fake ap

### ISSUE THREAD

**Issue by bygokhan37** [deltaxflux/fluxion#229]
hey dude https fake ap not work plsz fluxion update script

**Comment by deltaxflux** [comment]
SSL is not supported, only for devs

**Comment by bygokhan37** [comment]
but also at http routing it is not doing.
192.168.1.1 is working just as fake APs

**Comment by bygokhan37** [comment]
SSL on the anything could do that please

**Comment by deltaxflux** [comment]
SSL version is in the dev folder

**Comment by bygokhan37** [comment]
Arkadaşım anlamadım. ayrıntılı olarak SSL üzerinde açıklayınız. lütfen. teşekkür ederim yardım

**Comment by bygokhan37** [comment]
My friend I don't understand. explain in detail on SSL. please. help Thank you

**Comment by deltaxflux** [comment]
ONLY FOR DEVS

**Comment by bygokhan37** [comment]
http fake ap doesn't work but

**Comment by deltaxflux** [comment]
U don't follow the issue template

**Comment by bygokhan37** [comment]
hey dude http resquesta not work redirected not work kali linux
