### ISSUE TITLE
Change WPA key to Wifi Password 

### ISSUE THREAD

**Issue by WhiteSniper** [deltaxflux/fluxion#230]
### Which version of fluxion are you using?
latest

### What distribution of Linux (including the version) are you running it on?
2016.1

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Tp-link TL-WN722N

### Which is the driver for it?
latest

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
I live in area where people dont know that much about wireless so when i use fluxion they turn off their routers because they dont understand the WORD WPA KEY can i change that to WIFI PASSWORD??

**Comment by deltaxflux** [comment]
I don't think that is the problem

**Comment by slava-nikulin** [comment]
@WhiteSniper, open your "fluxion" script in text editor, find "DIALOG_WEB_INPUT_ENG" string and change its value to whatever you want.

**Comment by WhiteSniper** [comment]
@slava-nikulin  Thank you vary much
