### ISSUE TITLE
Clients' attemps are not captured/working

### ISSUE THREAD

**Issue by soulremover** [deltaxflux/fluxion#232]
### Which version of fluxion are you using?
latest

### What distribution of Linux (including the version) are you running it on?
kali 2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
alfa AWUS036H

### Which is the driver for it?
dont know

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
the clients are connecting allright on the fake AP but fluxion is not able to count/capture the attemps, hence cannot crack the password. i tested it on my home AP.

**Comment by deltaxflux** [comment]
Similar to #233
