### ISSUE TITLE
always says that your password is incorrect in web interface ! why ? 

### ISSUE THREAD

**Issue by loudjedi** [deltaxflux/fluxion#233]
### Which version of fluxion are you using?
latest

### What distribution of Linux (including the version) are you running it on?
2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
geant electronics adapter

### Which is the driver for it?
donno

### Does it support injection ( output of aireplay-ng -9)
<yes

### General description of your issue along with the steps to reproduce it
<???>
<???>

**Comment by deltaxflux** [comment]
Because the password is not correct. Open the pwlog file:
`cat /root/pwlog/[filename.txt]`
