### ISSUE TITLE
Handshakes not saved for some network

### ISSUE THREAD

**Issue by cipry0200** [deltaxflux/fluxion#236]
I notice that fluxion is not saving all **handshakes.cap**
I have tasted multiple networks (3) and for some I find the handshakes is not in **"/root/handsahkes/...** ". Even when it says that the handshakes is captured ( when I run fluxion), you can use it at that time-while **fluxion is running**. After you you **close the program** you have to _start over again because is no .cap file in handshakes dir._

**Comment by strasharo** [comment]
The handshake is saved once you successfully validate it using the menu. It's not being saved just by leaving airodump running.
