### ISSUE TITLE
Fake AP doesn't request to re-type the password

### ISSUE THREAD

**Issue by eugenekreger** [deltaxflux/fluxion#238]
### Which version of fluxion are you using?
0.23 rev. 85

### What distribution of Linux (including the version) are you running it on?
Ubuntu 16.10

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TP-LINK TL-WN722N AR9271

### Which is the driver for it?
plug & play

### General description of your issue along with the steps to reproduce it
Seems going ok through all stages, but stuck an the end. Fake AP becomes visible to other devices, but nothing is forcing to disconnect them from an original AP and reconnect to the fake one. Even if device is manually forced to connect to fake AP, it doesn't request a password and just connects to it with limited access meaning no Internet. What am I missing out?

**Comment by strasharo** [comment]
https://github.com/deltaxflux/fluxion/issues/27

**Comment by eugenekreger** [comment]
confused... is there supposed to be answer on my question?

**Comment by deltaxflux** [comment]
Obviously that:
 _There shouldn't be one. All of the traffic is being sinkholed to the built in captive portal via a fake DNS responder in order to capture the credentials._
