### ISSUE TITLE
submitting password on fake ap

### ISSUE THREAD

**Issue by Shiva7071007** [deltaxflux/fluxion#239]
### Which version of fluxion are you using?
85

### What distribution of Linux (including the version) are you running it on?
kali rolling

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
tplink wn722n

### Which is the driver for it?
default
### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
it is actually an additional feature than issue.Sometime while submitting the password on fake ap, it dont get matched with handshake captured .So there should be an option to view entered password wether they are coreect or wrong.

**Comment by deltaxflux** [comment]
Is already implemented 
/root/pwlog
