### ISSUE TITLE
channels

### ISSUE THREAD

**Issue by bobce79** [deltaxflux/fluxion#24]
if after scan i choose a network from channel 6 for example and after a while i see another network with more clients on channel 11, if i press 3 to change the attack, then 4 to rescan network, it remains locked to channel 6. i have to exit and restart the program to scan all channels. i used your program few months ago and never happened this. care to see what's wrong? thank you

**Comment by deltaxflux** [comment]
well this is the first time I heart about this problem... But I thought that I must add parts of the exitmode function. Thank you for the bug report!

**Comment by bobce79** [comment]
on live wifislax works without problems. in ubuntu still does that problem. remains locked on the last channel i try to get the handshake(of course, i'm talking about Linset) never tried on linux

**Comment by strasharo** [comment]
Could you, please, record a video of the reproduction if possible?

**Comment by deltaxflux** [comment]
Please create a Virtual machine with virtualbox and download the latest kali linux ( 2016 rolling). Setup the VM and run kali, try it with kali. I can’t record a video because it is a bit lagy (I tried it already) 
So I created a Post (hopefully I found one who ca

**Comment by deltaxflux** [comment]
Please create a Virtual machine with virtualbox and download the latest kali linux ( 2016 rolling). Setup the VM and run kali, try it with kali. 
I have never tried wifilax but I now that linset is more bugy than fluxion (pyrit handshake & dhcp server). Hopefully I solve the problem.. 
A video is helpful

**Comment by bobce79** [comment]
i won't touch rolling not even if they pay me. i updated once from sana, it crushed, then i did a fresh install, it crushed... the third problem was with ubuntu. used Katoolin and updated with rolling rep and crushed my install after the first reboot. so no more linux for me. at least not rolling. kali 1 was great, kali 2 was good, rolling.. thank you, but no thanks. in wifislax i used your fluxion, not the Linset inside(actually both, but fluxion was much faster and cleaner). i did an update on ubuntu and seems to work good now. no more channel lock. i gotta find some time for a video. maybe on week-end.

**Comment by deltaxflux** [comment]
I tried a older aircrack-ng version and it seems to be there. Hopefully we can make fluxion more powerful and thank you for your positive feedback ! I have to nice guys who support me @strasharo @ApatheticEuphoria and they help me a lot. So if you can do a video that would be nice because i tried one and it is a bit lagy... We you are using ubuntu and not linux mint (more stable and looks pretty sweet) katoolin work also :) What is If I would pay you 100$ ?

**Comment by bobce79** [comment]
hahah! now now i get paid for making a vid :)))

**Comment by deltaxflux** [comment]
no for using kali rolling as your main operating system

**Comment by bobce79** [comment]
naah! too much time to waste for only 100$ it will work until the first update. forget it

**Comment by aanarchyy** [comment]
Why centralize this to only work on one specific platform?
More diverse testers means more solid code.

Asking someone to set up a very specific environment and then test is kinda silly.
The script should be able to automatically set it's self up.
And on that note, i don't and wont use kali at all, poorly set up and constantly breaking.

I will get to testing this at some point, but not until i go through and see what it does.
I don't want this clearing my iptables on it's own or wanton killing processes automatically.

**Comment by bobce79** [comment]
yesterday i wanted to do the video you asked, but before that just tried your linset on my wireless. just so you know.. it disconnect my phone, but it's not connecting to the fake AP no matter what. i eliminated my own AP from the phone and connected directly to the fake no password one. nothing to do. keeps looping between coonecting and getting an ip address. so.. the bad news is that your program it's not working.well.. it does, but only until the most important thing. i tried the original Linset on live Wifislax and my phone made the fake connection right away. then i tried wifiphisher(the latest) and was working even better. got disconnected right away and presented the fake page perfectly. the only thing about wifiphisher is that it's not working that good with distant AP's. so, after couple hours of tests, as a result.. your fluxion works great on distances, very fast on disconnecting clients, but the fake AP is impossible to connect to. so.. my thought is that making a video of a program that doesn't work.. it's useless. happy coding my friend :)

**Comment by deltaxflux** [comment]
@aanarchyy I will contact you on skpe, I can't because I lost my skpe username

**Comment by deltaxflux** [comment]
@bobce79 I hope I will find the issue ( I think the network is down ). If you try using the web interface there are 4 windows, I guess. Look if in the top right hand side with the green front a massage pop up called wlan0 network is down

**Comment by bobce79** [comment]
to tell you the truth i deleted your version and now i use soter's updated on january. the only thing i modified there, was adding up to 20 deauth because it wasn't that fast getting the handshakes. but otherwise it's a good program. have a good one

**Comment by aanarchyy** [comment]
Ok, hope to hear from you soon...
In the meantime, i have firmware to reverse-engineer :-D

**Comment by deltaxflux** [comment]
@bobce79 ok good to now

**Comment by deltaxflux** [comment]
@aanarchyy there are more than one aanarchyy
aanarchyy01
aanarchyy26

**Comment by aanarchyy** [comment]
aanarchyy01 as it says in my HF sig

**Comment by deltaxflux** [comment]
OK right, maby I contact you in the afternoon

**Comment by cosimo2** [comment]
I use fluxion, it's all ok ( deauth ok, wpa handshake ok) but i can connect to the fake AP but the browser say: Connection offline, and fluxion not create a router page.
I use Awus036h (rtl8187l) in usb port (wlan0) ed atheros pci in (wlan1)
O.S. kali 2.0
Have you a suggest?

**Comment by jcy789** [comment]
HI
i use fluxion too ,everything is ok.but only my HUAWEI phone can connect to the facke AP
My Ipone 6 use no different it also connect ,but my XIAOMI(Android) just unconnected,can't connect to the fack AP
O.s is kali the best new
Have you a suggest ?
