### ISSUE TITLE
nethunter problemas

### ISSUE THREAD

**Issue by bygokhan37** [deltaxflux/fluxion#240]
Hi mate I'm using nethunter, but 192.168.1.1 doesn't give instructions either HTTP or HTTPS . please find a cure. he has also been at the PC, it works fine (fluxion)

**Comment by deltaxflux** [comment]
Please not that this attack is recommendet with an external wireless card. Connect it over otg.

**Comment by bygokhan37** [comment]
http routing fake apr trying but not working. WiFi card affiliated with OTG. http trying stable but no routing device

wn722n + otg hub

**Comment by bygokhan37** [comment]
192.168.1.1  fake ap is working.

http redirected not work.

**Comment by deltaxflux** [comment]
I think the problem is that you don't have the right versions on your nethunter device. **Run as root**
_Upgrade your packets_
`apt-get update && apt-get upgrade -y`
_Or check the versions_
`dpkg -l | grep "name"`

**Comment by maxygas** [comment]
When i run fluxion i get error: line 1394 /dev/fd/62 no such file or directory 
Its possible to solve this problem?
