### ISSUE TITLE
Don't open fake page

### ISSUE THREAD

**Issue by cacaocaca** [deltaxflux/fluxion#241]
### Which version of fluxion are you using?
FLUXION 0.23 (rev.  85) by  deltax

### What distribution of Linux (including the version) are you running it on?
Linux kali 4.7.0-kali1-686-pae #1 SMP Debian 4.7.8-1kali1 (2016-10-24) i686 GNU/Linux

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
 [1] wlan0		Intel 5100	iwlwifi "This is the wifi embed on my Notebook
      [2] wlan1		Atheros AR9271	ath9k  " This is usb adapter TL-WN722N"

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
Yes support injection 

### General description of your issue along with the steps to reproduce it
Sorry my launguage i m italian so the problem is 
1. If i choose on select interface 
       [1] wlan0		Intel 5100	iwlwifi 
      [2] wlan1		Atheros AR9271	ath9k 
and choose 1 he don t create the fake ap but if i choose 2 he create fake ap .
2.When create the fake app and i wait the " victim " i go on my android samsung and click on fake ap and open google chrome so when i open google chrome   appears in the search bar and so i text for example " ferrari" or " kali linux " for look if show me the fake page but the fake page dont  work he show me just I have no connection .. Instead if i find on search bar "blabla.it" " facebook.it" it work and show me the fake page right..  This happen think becouse when i text direct on chrome bar with android and text " ferrari" he redirect page search on google search and your sotware no are able to show me the fake page while if i test direct on one domain.com .it ecc it work .. 
------------------------------------
I'm very appreciate for your software and if you can update and fix this problem becouse nobody text the domain direct on google so is so hard that can work fine .. Good work and Congratulation for the software at all members.

**Comment by deltaxflux** [comment]
https direction is only supported for devs

**Comment by cacaocaca** [comment]
So i can t hope nothing on future that it work with google becouse is normal that peoples on phone or notebook find direct on google search and if this doesen t work 1 people of 100 have the fake login page that work.

**Comment by cacaocaca** [comment]
Any phone when you click on chrome mozilla or other and click on search bar and text some word " kali linux " he redirect on google search so if your fluxion don t work so is one little useless nobody click on search bar and text the full domain .. If you can fix it i send one start becouse is perfect but if you can t fix it no sorry becouse no is so helpful
