### ISSUE TITLE
you decide

### ISSUE THREAD

**Issue by dynyly** [deltaxflux/fluxion#242]
Animated perfect color
he left his choice
pages into various languages ;in fluxion fork in my account
I do not work branches ghitub much mess ......

red_color_slim="\033[0;031m"

function flying_saucer() {
	case $1 in
		1)
	              sleep 0.1 && echo -e "$red_color_slim " 
	              sleep 0.1 && echo -e "                                  ┌▓\  /▓┐                             "
                      sleep 0.1 && echo -e "         ⌠▓▒▓▒   ⌠▓╗     ⌠█┐ ┌█              ⌠▓╖   ⌠◙▒▓▒◙   ⌠█\  ☒┐    "
                      sleep 0.1 && echo -e "         ║▒_     │▒║     │▒║ ║▒              │☢╫   │▒┌╤┐▒   ║▓▒\ ▓║    "                
                      sleep 0.1 && echo -e "         ≡◙◙     ║◙║     ║◙║ ║◙              ║¤▒   ║▓║☯║▓   ♜◙\✪\◙♜    "
                      sleep 0.1 && echo -e "         ║▒      │▒║__   │▒└_┘▒              │☢╫   │▒└╧┘▒   ║█ \▒█║    "                       
                      sleep 0.1 && echo -e "         ⌡▓      ⌡◘▒▓▒   ⌡◘▒▓▒◘              ⌡▓╝   ⌡◙▒▓▒◙   ⌡▓  \▓┘    "
                      sleep 0.1 && echo -e "        ¯¯¯     ¯¯¯¯¯¯  ¯¯¯¯¯¯¯   └▓/  \▓┘  ¯¯¯¯  ¯¯¯¯¯¯¯  ¯¯¯  ¯¯¯    "
                      sleep 0.1 && echo -e ""${transparent}
		;;
		2)
			echo -e "$red_color_slim "
		       echo -e "                                                                       "
                       echo -e "         ⌠▓▒▓▒   ⌠▓╗     ⌠█┐ ┌█   ┌▓\  /▓┐   ⌠▓╖   ⌠◙▒▓▒◙   ⌠█\  ☒┐    "
                       echo -e "         ║▒_     │▒║     │▒║ ║▒              │☢╫   │▒┌╤┐▒   ║▓▒\ ▓║    "                
                       echo -e "         ≡◙◙     ║◙║     ║◙║ ║◙              ║¤▒   ║▓║☯║▓   ♜◙\✪\◙♜    "
                       echo -e "         ║▒      │▒║__   │▒└_┘▒              │☢╫   │▒└╧┘▒   ║█ \▒█║    "                       
                       echo -e "         ⌡▓      ⌡◘▒▓▒   ⌡◘▒▓▒◘   └▓/  \▓┘   ⌡▓╝   ⌡◙▒▓▒◙   ⌡▓  \▓┘    "
                       echo -e "        ¯¯¯     ¯¯¯¯¯¯  ¯¯¯¯¯¯¯             ¯¯¯¯  ¯¯¯¯¯¯¯  ¯¯¯  ¯¯¯     "
                       echo -e ""${transparent}
		;;
		3)
			echo -e "$red_color_slim "
		       echo -e "                                                                 "
                       echo -e "         ⌠▓▒▓▒   ⌠▓╗     ⌠█┐ ┌█   ┌▓\  /▓┐   ⌠▓╖   ⌠◙▒▓▒◙   ⌠█\  ☒┐    "
                       echo -e "         ║▒_     │▒║     │▒║ ║▒    \▒\/▒/    │☢╫   │▒┌╤┐▒   ║▓▒\ ▓║    "                
                       echo -e "         ≡◙◙     ║◙║     ║◙║ ║◙              ║¤▒   ║▓║☯║▓   ♜◙\✪\◙♜    "
                       echo -e "         ║▒      │▒║__   │▒└_┘▒    /▒/\▒\    │☢╫   │▒└╧┘▒   ║█ \▒█║    "                       
                       echo -e "         ⌡▓      ⌡◘▒▓▒   ⌡◘▒▓▒◘   └▓/  \▓┘   ⌡▓╝   ⌡◙▒▓▒◙   ⌡▓  \▓┘    "
                       echo -e "        ¯¯¯     ¯¯¯¯¯¯  ¯¯¯¯¯¯¯             ¯¯¯¯  ¯¯¯¯¯¯¯  ¯¯¯  ¯¯¯    "
                       echo -e ""${transparent}
		;;
		4)
			echo -e "$red_color_slim "
		       echo -e "                                                                 "
                       echo -e "         ⌠▓▒▓▒   ⌠▓╗     ⌠█┐ ┌█   ┌▓\  /▓┐   ⌠▓╖   ⌠◙▒▓▒◙   ⌠█\  ☒┐    "
                       echo -e "         ║▒_     │▒║     │▒║ ║▒    \▒\/▒/    │☢╫   │▒┌╤┐▒   ║▓▒\ ▓║    "                
                       echo -e "         ≡◙◙     ║◙║     ║◙║ ║◙      ◙◙      ║¤▒   ║▓║☯║▓   ♜◙\✪\◙♜    "
                       echo -e "         ║▒      │▒║__   │▒└_┘▒    /▒/\▒\    │☢╫   │▒└╧┘▒   ║█ \▒█║    "                       
                       echo -e "         ⌡▓      ⌡◘▒▓▒   ⌡◘▒▓▒◘   └▓/  \▓┘   ⌡▓╝   ⌡◙▒▓▒◙   ⌡▓  \▓┘    "
                       echo -e "        ¯¯¯     ¯¯¯¯¯¯  ¯¯¯¯¯¯¯  ¯¯¯¯  ¯¯¯¯ ¯¯¯¯  ¯¯¯¯¯¯¯  ¯¯¯  ¯¯¯    "
                       echo -e ""${transparent}
                             esac
	                     sleep 0.4
}
function print_animated_flying_saucer() {

	echo -e "\033[s"

	for i in `seq 1 8`; do
		if [ ${i} -le 4 ]; then
			saucer_frame=${i}
		else
			saucer_frame=$(($i-4))
		fi
		echo -e "\033[u"
		flying_saucer ${saucer_frame}
	done
} 
print_animated_flying_saucer

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ARES 

You can add interfaces fluxion ares to replace check.php by ares

add settings pg_hba.conf

sudo su -c 'echo "host all all 192.168.1.1 255.255.255.255 trust" >> /opt/metasploit/postgresql/data/pg_hba.conf'
sudo su -c 'echo "listen_addresses = '*'" >> /opt/metasploit/postgresql/data/postgresql.conf'
for kali is another direction but more or less the same

I do not work branches github

**Comment by deltaxflux** [comment]
I take a look on it later

**Comment by deltaxflux** [comment]
Please post this on the ares issue bord
