### ISSUE TITLE
Channels don't show up when "Scanning Channels"

### ISSUE THREAD

**Issue by MalicouZzHD** [deltaxflux/fluxion#244]
### Which version of fluxion are you using?
85

### What distribution of Linux (including the version) are you running it on?
Linux kali 4.7.0-kali1-amd64 #1 SMP Debian 4.7.8-1kali1 (2016-10-24) x86_64 GNU/Linux

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Intel Corporation Wireless 3165 (rev 81)

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
root@kali:~# aireplay-ng -9
No replay interface specified.
"aireplay-ng --help" for help.
root@kali:~#

### General description of your issue along with the steps to reproduce it
1. Open terminal
2. Type "cd fluxion/"
3. Type "./Installer.sh"
4. type "./fluxion"
5. Type "1" for "English"
6. Type "1" for "wlan0"
7. Type "1" for "All Channels"
8. Then an "XTerm" pops up
9. It USED to show all of the WiFi networks around, but now its just blank.

**Comment by deltaxflux** [comment]
Your wireless card is not supported
