### ISSUE TITLE
fluxion kills my wifi internet  connection

### ISSUE THREAD

**Issue by stefano099** [deltaxflux/fluxion#245]
### Which version of fluxion are you using?
 FLUXION 0.23 (rev.  86) 

### What distribution of Linux (including the version) are you running it on?
kali 2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

<Qualcomm Atheros AR9285 Wireless Network Adapter (PCI-Express) (rev 01)
 Alfa Awus 036nh

### Which is the driver for it?
Ralink RT2870/3070	rt2800usb wlan1
Atheros AR9285	ath9k wlan0
### Does it support injection ( output of aireplay-ng -9)
yes
### General description of your issue along with the steps to reproduce it
hello my problem is that fluxion kills my wifi internet connection to share, my kali system is connected with wlan0 to the router when i starting fluxion it kills my wifi conetction 

nmcli c
NAME            UUID                                  TYP              GERÄT 
FRITZ!Box 7412  94a5b3a3-35c5-4ab1-8aa1-80d7a1f77afd  802-11-wireless  wlan1 
Profil 1        31405b1d-e638-4583-95e7-8b0ea955c4a2  802-3-ethernet   eth0

**Comment by strasharo** [comment]
https://github.com/deltaxflux/fluxion/issues/203

**Comment by ossometal** [comment]
Kkkkkkk
