### ISSUE TITLE
Fake website will not work with certain sites

### ISSUE THREAD

**Issue by nm8800** [deltaxflux/fluxion#246]
### Which version of fluxion are you using?
<???>
Fluxion .23
### What distribution of Linux (including the version) are you running it on?
<???>
Kali 2.0 (UPDATED TODAY)
### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<???>
Alpha AWUS051NH
### Which is the driver for it?
<???>
rt2800usb
### Does it support injection ( output of aireplay-ng -9)
<???>
Yes
### General description of your issue along with the steps to reproduce it
<???>
I am successfully completing SOME attacks. I have experimented on both a laptop and android phone. However, I noticed that when I attempt to login to a website using HTTPS the fake website DOES NOT show up. From a previous post I noticed some discussion about it.

Is there a fix to this or anything I can do to cause HTTPS requests to get to the same password page?

Any help would be greatly appreciated. Really love this piece of software. A true work of art. Thanks again.

**Comment by strasharo** [comment]
HTTPS is not currently supported in the stable version.

**Comment by nm8800** [comment]
Ok thanks. Look forward to the HTTPS version.
