### ISSUE TITLE
Not getting any WPA Password

### ISSUE THREAD

**Issue by muhfath** [deltaxflux/fluxion#247]
### Which version of fluxion are you using?
0.23 ver 86 (Latest)

### What distribution of Linux (including the version) are you running it on?
Linux Kali 4.7.0 just updated (on VMWare)

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TL-WN722N Atheros AR9271

### Which is the driver for it?
ath9k

### Does it support injection ( output of aireplay-ng -9)
Yes, it does

### General description of your issue along with the steps to reproduce it
I try to get WPA pass of my own wifi. Everything is fine, the fake AP is running and fake login page opened when i connect to the fake AP. But when i submit my WPA pass, there is nothing happened and it just get back to the login page. The terminal shows 1 client (computer that i connect to the fake AP) but there is no attempt recorded when i submit WPA pass. So i think there is a problem collecting the submitted wifi pass.

I'm using english ver login page and trying to use the other language ver. But it still no attempt recorded when i submit my pass. I also check the /root/pwlog is empty.

Thanks

**Comment by muhfath** [comment]
Add info:
root@kali:~# dpkg -l | grep hostapd
ii  hostapd   1:2.5-2+v2.4-3+b1   amd64    IEEE 802.11 AP and IEEE 802.1X/WPA/WPA2/EAP Authenticator

The hostapd version readme file is 1:2.3-2.3 and i'm using different version. I don't know if this is the cause but maybe it will help for troubleshooting.

**Comment by muhfath** [comment]
Hey, i think i know the problem now.

It seems the fluxion can't capture the pass if the target is connecting to the fake AP using PC. My PC is Win 8.1 64 bit, i try to log in with both firefox and IE but no attempt captured.

After that i try to connect to the fake AP using my android phone. it worked and captured every pass that i submit. I try the fake login page on all browser in my android phone (firefox, chrome, and android stock browser) and it all worked.

**Comment by deltaxflux** [comment]
Erase your cache

**Comment by muhfath** [comment]
Hi deltaflux, thanks for the respond. I've been trying to erase my cache but it still not working in PC browser. I've try the fake login page using another several PC but it still can't record any password attempt.

Thanks
