### ISSUE TITLE
The application does not create fake access point

### ISSUE THREAD

**Issue by ossometal** [deltaxflux/fluxion#248]
### Which version of fluxion are you using?
0.23
rev 0.86

### What distribution of Linux (including the version) are you running it on?

4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling
GNOME 3.20.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

mt7601u		Ralink Technology, Corp. MT7601U

### Which is the driver for it?
/

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it

The application does not create fake access point

**Comment by deltaxflux** [comment]
The driver is not compatible

**Comment by ossometal** [comment]
Oh shit, Thanks for reply.
