### ISSUE TITLE
Fake AP is not made, and that maybe why I get no connections

### ISSUE THREAD

**Issue by hammi1** [deltaxflux/fluxion#249]
### Which version of fluxion are you using?
0.23 rev 87

### What distribution of Linux (including the version) are you running it on?
Linux Mint 18

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<wlp3s0 Intel 5100>

### Which is the driver for it?
iwlwifi

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
When I choose fakeAP with Hostapd and airebase, it looks like it is working, but using my phone I cannot find the fake network, which means it is not being broadcasted. How can I fix this?

Additionally, I get this error: (Warning: Tried to connect to session manager, None of the authentication protocols specified are supported).

Any help will be massively appreciated.

**Comment by deltaxflux** [comment]
Your wireless card is not supported.
