### ISSUE TITLE
video

### ISSUE THREAD

**Issue by bobce79** [deltaxflux/fluxion#25]
found some free time and done your video. on kali sana though.

**Comment by deltaxflux** [comment]
OK send me a emai with the video thanks

**Comment by bobce79** [comment]
uploaded on youtube as well

**Comment by bobce79** [comment]
won't go as email. sorry

**Comment by deltaxflux** [comment]
@bobce79 when do you upload the Video

**Comment by bobce79** [comment]
today
/watch?v=PLfihFNWY2Q
