### ISSUE TITLE
Fluxion doesnt allow using saved handshake file

### ISSUE THREAD

**Issue by hammi1** [deltaxflux/fluxion#250]
### Which version of fluxion are you using?
0.23, rev 87

### What distribution of Linux (including the version) are you running it on?
Linux Mint 18

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
wlp3s0 Intel 5100

### Which is the driver for it?
iwlwifi

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
When I type the location of handshake file, it says Not_Found!  File MAC
It then gives the right AP mac.

How can I make it accept the handshake file? It was saved from a previous session of Fluxion and isn't corrupted.
![screenshot from 2016-11-06 18-57-27](https://cloud.githubusercontent.com/assets/23297609/20040667/4a07bb9a-a453-11e6-95e2-7674af61eea9.png)

**Comment by deltaxflux** [comment]
Its a bug

**Comment by hammi1** [comment]
Thanks for replying - any ETA on when it could be fixed?

**Comment by deltaxflux** [comment]
With a bug with pyrit, we fix this later
