### ISSUE TITLE
Fluxion Question - ls: cannot access '/root/handshakes/*.cap': No such file or directory

### ISSUE THREAD

**Issue by CookieChomper** [deltaxflux/fluxion#252]
### Which version of fluxion are you using?
<0.23>

### What distribution of Linux (including the version) are you running it on?
<Kali GNU/Linux Rolling 64-bit>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<Intel 4965AGN>

### Which is the driver for it?
<iwl4965>

### Does it support injection ( output of aireplay-ng -9)
<not sure>

### General description of your issue along with the steps to reproduce it
<
cd Desktop
cd fluxion
sudo ./fluxion  (list of items all OK)
1 = English
1 = wlan0
1 = All Channels
ctrl+c (to stop)
4 = choose AP Target
2 = Fake AP - airbase-ng (slower connection)
1 = Handshake (Recommended)

ls: cannot access '/root/handshakes/*.cap' " No such file or directory
No Caps found...
handshake location (Example: /root/Desktop/fluxion.cap)
Press ENTER to skip

What am I missing here?

  >

**Comment by deltaxflux** [comment]
Simular to #250
