### ISSUE TITLE
Mdk3 issue in hotspot mode

### ISSUE THREAD

**Issue by dr-alibi** [deltaxflux/fluxion#253]
### Which version of fluxion are you using?
0.23 rev .87

### What distribution of Linux (including the version) are you running it on?
Kali Rolling

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Intel Co. Wireless 3160 rev. 93

### Which is the driver for it?
iwlwifi

### Does it support injection ( output of aireplay-ng -9)
Injection working. 

### General description of your issue along with the steps to reproduce it
The scenario is simple: I successfully initiate a process, monitor and handshake capture go fine, fake AP renders and works correctly and logs data to file. The only problem is mdk3 not deauthorising clients at all during the last step of the attack. It works using either airbase-ng and pyrit in the first part, and is correctly deauthorising and capturing handshake in either "deauth all" and "deauth all (mdk3)" modes. It configures dhcp and fake DNS with no problems but doesn't deauth any already connected or connecting client in hotspot mode.
P.S. Output of cat /tmp/TMPflux/mdk3.txt is the expected BSSID.

Thank you, hope it helps to fix a great tool up.

**Comment by strasharo** [comment]
mdk3 is a third party product, if you think it's not working, feel free to contact the author.

**Comment by dr-alibi** [comment]
I surely will, I just couldn't figure out this odd behaviour.  Thank you.
