### ISSUE TITLE
No deauth?

### ISSUE THREAD

**Issue by clebersleite** [deltaxflux/fluxion#256]
### Which version of fluxion are you using?
0.23

### What distribution of Linux (including the version) are you running it on?
Kali Linux 

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Qualcomm Atheros QCA9565 / AR9565

### Which is the driver for it?
ath9k

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
It's not happening deuath during the ap list process. I believe that is cause of no .cap file

**Comment by deltaxflux** [comment]
Your right, you are the developer

**Comment by clebersleite** [comment]
LoL, are you angry man? Take easy, I'm try to help..I'm developer too, not from this project...how you can decrypt the password with no handshake?, also, linset is working fine for me. That right, forget...bye!
