### ISSUE TITLE
fake ap problems

### ISSUE THREAD

**Issue by aliwaqas2323** [deltaxflux/fluxion#26]
i started the attack but fake access point was not created just to check that if my adapter supports to create a fake ap i manually created it using ghost phisher and airbase-ng and they both succesfully done the job so my question is that why linset is not creating the fake ap plz help

**Comment by deltaxflux** [comment]
can you make a video and send me over email. Would be helpful. I need more details e.g. AP Output

**Comment by bobce79** [comment]
as someone said, you should change 
index-file.names = ( \"index.htm\" )
into 
index-file.names = (\"index.html\" )

**Comment by deltaxflux** [comment]
@bobce79 I think that Change nothing, but lets see

**Comment by bobce79** [comment]
Just did a test. Adding the "l" was worse. And the page works just fine aliwakas. Try an update first on your OS.

**Comment by aliwaqas2323** [comment]
i have the latest version kali

**Comment by bobce79** [comment]
too bad. i did the test on kali sana. don't know rolling how it works(or IF it works)

**Comment by aliwaqas2323** [comment]
ok i will try to make the video as soon as possible

**Comment by aliwaqas2323** [comment]
plzzz check you mail @deltaxflux

**Comment by deltaxflux** [comment]
@aliwaqas2323 please check Tour mail

**Comment by aliwaqas2323** [comment]
the dhcp server is working but the fake is not creating
