### ISSUE TITLE
i use (lighttpd/1.4.39 (ssl) (Jan  3 2016 04:54:01) - a light and fast webserver)  BUT FakeSites don't work 

### ISSUE THREAD

**Issue by donkeykong7** [deltaxflux/fluxion#263]
### Which version of fluxion are you using?
<0.23 REV 87>

### What distribution of Linux (including the version) are you running it on?
<Linux kali 4.6.0-kali1-686-pae>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<Ralink RT2870/3070	rt2800usb>

### Which is the driver for it?
<Ralink RT2870/3070	rt2800usb>

### Does it support injection ( output of aireplay-ng -9)
<yes>

### General description of your issue along with the steps to reproduce it
<before this version the fake site work not now>

**Comment by deltaxflux** [comment]
How if the injection inself is not supported
