### ISSUE TITLE
dev/fd/62 no such file or directory

### ISSUE THREAD

**Issue by maxygas** [deltaxflux/fluxion#266]
### Which version of fluxion are you using?
<???>

### What distribution of Linux (including the version) are you running it on?
<???>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<???>

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
<???>

### General description of your issue along with the steps to reproduce it
<???>

**Comment by maxygas** [comment]
Fluxion version 0.23
Kali linux nethunter 
Alfa awus036nh 
When i run fluxion i get an error 
fluxion/fluxion line 1418: /dev/fd/62 no such file or directory

**Comment by deltaxflux** [comment]
Well a quick fix is that we create the directory. 
`ln -s /proc/self/fd /dev/fd`

Or udev was missing
`apt-get install udev`

**Comment by maxygas** [comment]
Thank you veeeery much now its working thank you



BlueMail<http://www.bluemail.me/r> -pal küldve

2016. nov. 13.-n, 14:00-kor, deltax <notifications@github.com<mailto:notifications@github.com>> ezt írta:

Well a quick fix is that we create the directory.
ln -s /proc/self/fd /dev/fd

Or udev was missing
apt-get install udev
