### ISSUE TITLE
Devices not connecting to fake AP

### ISSUE THREAD

**Issue by RonCan** [deltaxflux/fluxion#269]
### Which version of fluxion are you using?
FLUXION 0.23 rev.90

### What distribution of Linux (including the version) are you running it on?
Ubuntu 16.04

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
AR9285

### Which is the driver for it?
ath9k

### Does it support injection ( output of aireplay-ng -9)
`19:10:01  Trying broadcast probe requests...
19:10:01  Injection is working!
19:10:03  Found 3 APs

19:10:03  Trying directed probe requests...
19:10:03  C8:3A:y4:ee:tt:xx - channel: 1 - '1st Floor'
19:10:03  Ping (min/avg/max): 1.175ms/12.744ms/157.507ms Power: -49.67
19:10:03  30/30: 100%

19:10:03  C8:3A:35:48:6E:D1 - channel: 1 - 'USMAN MIAN'
19:10:04  Ping (min/avg/max): 1.212ms/14.086ms/197.841ms Power: -72.86
19:10:04  28/30:  93%

19:10:04  C8:3A:35:39:66:D9 - channel: 1 - 'Sadaqat786'
19:10:05  Ping (min/avg/max): 1.107ms/14.487ms/56.783ms Power: -91.52
19:10:05  29/30:  96%
`

### General description of your issue along with the steps to reproduce it
When the fake AP is created the devices don't get connected to the fake AP, they get stuck at `Obtaining IP address`. I'm attaching a screenshot of the log terminal windows
![screenshot from 2016-11-13 19-16-49](https://cloud.githubusercontent.com/assets/4863594/20246306/e03ed21a-a9d5-11e6-9bad-195e693885f5.png)

**Comment by RonCan** [comment]
On my Nexus4 running Nougat 7.1 the fake AP finally shows the message `IP configuration failure` but not on the other Amazon Fire 7 running Lollipop and on that it endlessly keeps trying to connect to the fake AP

**Comment by deltaxflux** [comment]
Well thanks for this detailed issue. Does the login page appear if you type manually 192.168.1.1 ?

**Comment by RonCan** [comment]
On my host computer, from where I'm running the attack, yes the page appears and when the password is typed I get success, the entered password. But on other devices, of course since the fake AP is not connected and keeps "Obtaining IP address" this page does not open

**Comment by RonCan** [comment]
Here's my AP log output, this is just my last piece in the puzzle, please look into this
`Configuration file: /tmp/TMPflux/hostapd.conf
Using interface wlp9s0 with hwaddr c8:3a:35:2c:de:88 and ssid "1st Floor"
wlp9s0: interface state UNINITIALIZED->ENABLED
wlp9s0: AP-ENABLED 
wlp9s0: STA 40:b0:fa:65:25:06 IEEE 802.11: authenticated
wlp9s0: STA 40:b0:fa:65:25:06 IEEE 802.11: associated (aid 1)
wlp9s0: AP-STA-CONNECTED 40:b0:fa:65:25:06
wlp9s0: STA 40:b0:fa:65:25:06 RADIUS: starting accounting session 5828C12B-00000000
wlp9s0: AP-STA-DISCONNECTED 40:b0:fa:65:25:06
wlp9s0: STA 40:b0:fa:65:25:06 IEEE 802.11: disassociated
wlp9s0: STA 40:b0:fa:65:25:06 IEEE 802.11: authenticated
wlp9s0: STA 40:b0:fa:65:25:06 IEEE 802.11: associated (aid 1)
wlp9s0: AP-STA-CONNECTED 40:b0:fa:65:25:06
wlp9s0: STA 40:b0:fa:65:25:06 RADIUS: starting accounting session 5828C12B-00000000
wlp9s0: AP-STA-DISCONNECTED 40:b0:fa:65:25:06
wlp9s0: STA 40:b0:fa:65:25:06 IEEE 802.11: disassociated
wlp9s0: STA 40:b0:fa:65:25:06 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
wlp9s0: STA 40:b0:fa:65:25:06 IEEE 802.11: authenticated
wlp9s0: STA 40:b0:fa:65:25:06 IEEE 802.11: associated (aid 1)
wlp9s0: AP-STA-CONNECTED 40:b0:fa:65:25:06
wlp9s0: STA 40:b0:fa:65:25:06 RADIUS: starting accounting session 5828C12B-00000001
wlp9s0: AP-STA-DISCONNECTED 40:b0:fa:65:25:06
wlp9s0: STA 40:b0:fa:65:25:06 IEEE 802.11: disassociated
wlp9s0: STA 40:b0:fa:65:25:06 IEEE 802.11: authenticated
wlp9s0: STA 40:b0:fa:65:25:06 IEEE 802.11: associated (aid 1)
wlp9s0: AP-STA-CONNECTED 40:b0:fa:65:25:06
wlp9s0: STA 40:b0:fa:65:25:06 RADIUS: starting accounting session 5828C12B-00000001
wlp9s0: interface state ENABLED->DISABLED
wlp9s0: AP-STA-DISCONNECTED 40:b0:fa:65:25:06
wlp9s0: AP-DISABLED 
nl80211: deinit ifname=wlp9s0 disabled_11b_rates=0`

**Comment by bygokhan37** [comment]
connecting to the fake AP breaks and then breaks again after 5 seconds after connecting it again

**Comment by bygokhan37** [comment]
now please find me a solution

**Comment by deltaxflux** [comment]
Well looks like your DHCP client don't support the redirection. I recommend to test if it does work with the old client ? 
Go to settings
About 
tape on the build nummer 20X
go back to dev
scroll down and enable use old dhcp

**Comment by RonCan** [comment]
Actually, it looks more like a problem with every device. I tried windows 10 and that had the same behaviour

**Comment by deltaxflux** [comment]
Which lighttpd and hostapd version do you have?

**Comment by RonCan** [comment]
I have the following

`hostapd v2.6`
`lighttpd/1.4.35 (ssl)`

It must also be noted that initially I had `hostapd v2.4` and decided to upgrade to see if it will fix my problem but it didn't

**Comment by RonCan** [comment]
I've noticed something, I booted a live Kali and fired it up, everything went smoothly and I noticed one difference. The difference is, on my current Ubuntu install, when fake AP is created, no DHCP xterm window appears while on Kali it does and that seems to be the issue. What would you advise I do?

**Comment by RonCan** [comment]
Awesome! I'm getting close, here are the contents of my `clientes.txt`
`Internet Systems Consortium DHCP Server 4.3.3
Copyright 2004-2015 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Can't open /tmp/TMPflux/dhcpd.conf: Permission denied

If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging..

exiting.`

**Comment by deltaxflux** [comment]
I recommend to downgrade your lighttpd and hostapd packets. However you can watch the conf with 
`cat /tmp/TMPflux/dhcpd.conf`

Or you copy the folder for later use
`sudo cp -r /tmp/TMPflux /root/`

**Comment by RonCan** [comment]
For some weird reason, even after I `chown` and become the owner of the conf file, move the file to another directory where I have complete control even then dhcp command shows the same permission denied error

**Comment by deltaxflux** [comment]
run as root?

**Comment by RonCan** [comment]
That was my first thought, didn't work

**Comment by deltaxflux** [comment]
better I help you on discord

**Comment by PoundXI** [comment]
For dhcpd permission issues visit at
https://help.ubuntu.com/community/isc-dhcp-server#Permission_issues_with_ISC-DHCP_server
This works for me on Ubuntu 14.04

**Comment by jabez007** [comment]
"Fixing" apparmor (using Pound's link) also worked for me.
