### ISSUE TITLE
No active clients and Connection Reset not working.

### ISSUE THREAD

**Issue by lucasheer** [deltaxflux/fluxion#27]
My problem with fake login page is, there are never any Active Clients available to Select Target.

However when I try connection reset-- I have a problem as well.
The DHCP window says a bunch of normal things, but then stops at Server starting service.
FAKEDNS just says "pyminifakeDNS:: dom.query. 60 IN A 192.168.1.1"
Deauth all [mdk3] SSID window just displays "Peridically re-reading blacklist/whitelist every 3 seconds.
Wifi Information says "Attemps....0" "Clients....0" and "clients online:"

A nice thing is that I have gotten farther with this than I did with linset. Thanks

**Comment by strasharo** [comment]
If there are no active clients on the target AP, what do you expect the script to do exactly, generate some by itself?

**Comment by lucasheer** [comment]
@strasharo That is the problem. There are plenty of devices in my house, and none of them get disconnected or connect to the AP. I however can start up a separate AP using airbase-ng.

If the devices don't connect automatically, then how can I get them to connect?

**Comment by strasharo** [comment]
This is a social engineering attack, so there's no point in dragging in devices automatically, as the user has to type in the password for the AP manually in the page anyway.

**Comment by lucasheer** [comment]
@strasharo I would like to be able to drag in devices :) Imagine if you could make a permanent connection with a device. You would be able to send it login forms, trigger the devices built in messaging, and basically do whatever you want.

My problem is that I think Fluxion isn't even creating an AP, and that if it is, no devices (even when my strength is stronger) will connect to it. I can even disconnect other devices using aireplay --deauth, and they wont connect to me.

When I use airbase, the AP is visible and i can get clients to connect to me.

I'm using my Lenovo X201's built in intel centrino 6200 iwlwifi card, which I have been told works for this sort of stuff; but do you think that's my problem?

**Comment by lucasheer** [comment]
@deltaxflux do you know why it isn't working for me?

**Comment by aliwaqas2323** [comment]
same here fluxion is not creating fake ap and i have also intel centrino advanced agn 6200 wifi adapter

**Comment by lucasheer** [comment]
@aliwaqas2323 yeah but it works for airbase, wonder if its using an older version or something

**Comment by aliwaqas2323** [comment]
yeah same here

**Comment by aliwaqas2323** [comment]
i manuall created it using airebase and it did it

**Comment by lucasheer** [comment]
Did you get fluxion to work? I need login page. @aliwaqas2323

**Comment by aliwaqas2323** [comment]
wait i have created the video that fake ap is not creating but dhcp server is working i am sending the video to you in few minutes

**Comment by aliwaqas2323** [comment]
what is your email i will send to you

**Comment by aliwaqas2323** [comment]
plzz send me your email i will personally send it to you

**Comment by pr31ocktt** [comment]
Hi I have the same problem, but before that solve this problem that I show below

Aircrack-ng ..... OK!
Aireplay-ng ..... OK!
Airmon-ng ....... OK!
Airodump-ng ..... OK!
Awk ............. OK!
Curl ............ OK!
Dhcpd ........... Not installed (isc-dhcp-server)
Hostapd ......... Not installed
Iwconfig ........ OK!
Not installed Lighttpd ........
Macchanger ...... OK!
Mdk3 ............ OK!
Php5-cgi ........ Not installed
Pyrit ........... OK!
Python .......... OK!
Unzip ........... OK!
Xterm ........... OK!

Ready finished running apt-get install Dhcpd, hostapd, Lighttpd, Php7-cgi all stay OK


The question is how can I do that (Dhcpd, hostapd, Lighttpd, Php5-cgi) ** ** are properly configured? After they are installed and that because of this may be affecting that stays starting DHCP and not the start FAKEDNS

**Comment by pr31ocktt** [comment]
@lucasheer You know that can i do for fix the problem?

**Comment by bygokhan37** [comment]
Yes I have this problem. routing is not working

**Comment by bygokhan37** [comment]
fake dns is problem
