### ISSUE TITLE
Fluxion doesnt allow using saved handshake file

### ISSUE THREAD

**Issue by Alucard9393** [deltaxflux/fluxion#272]
### Which version of fluxion are you using?
.23 rev. 91

### What distribution of Linux (including the version) are you running it on?
Kali GNI / Linux Rolling

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Ralink rt2870/3070

### Which is the driver for it?
iwlwifi

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it

everything worked well in the rev. 86, I returned to download the .zip but now was rev.91 and I appeared the following error

![captura de pantalla de 2016-11-13 19-37-02](https://cloud.githubusercontent.com/assets/23283787/20250855/0fc82ee8-a9d9-11e6-963e-4ca24ebec570.png)

**Comment by deltaxflux** [comment]
I have fixed it
