### ISSUE TITLE
 Why I can not find a fake ap in my android? 

### ISSUE THREAD

**Issue by jas502n** [deltaxflux/fluxion#273]
### Fill in the answers for all of the questions below, OTHERWISE YOUR TICKET WILL BE INSTANTLY CLOSED.
___________________________________________________________________________________________________________
### Which version of fluxion are you using?
 FLUXION 0.23 (rev.  91)
___________________________________________________________________________________________________________
### What distribution of Linux (including the version) are you running it on?
<???>
___________________________________________________________________________________________________________
### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<???>
___________________________________________________________________________________________________________
### Which is the driver for it?
<???>
___________________________________________________________________________________________________________
### Does it support injection ( output of aireplay-ng -9)
yes
___________________________________________________________________________________________________________
### General description of your issue along with the steps to reproduce it

in the vmware,i give a Wireless network card to vmware ，when it's  runinng,i am not foud a  
Forged ap in my android devices.  what should i do?
___________________________________________________________________________________________________________
 CH 13 ][ Elapsed: 1 min ][ 2016-11-13 23:08 ][ WPA handshake: 8C:F2:28:10:96:E2  
                                                                                  
 BSSID              PWR RXQ  Beacons    #Data, #/s  CH  MB   ENC  CIPHER AUTH ESSI
                                                                                  
 8C:F2:28:10:96:E2    0 100      635      640   14  13  54e  WPA2 CCMP   PSK  QWWW
                                                                                  
 BSSID              STATION            PWR   Rate    Lost    Frames  Probe        
                                                                                  
 8C:F2:28:10:96:E2  A8:1B:5A:4E:45:3F  -52    1e- 1e    71       60  QWWW          
 8C:F2:28:10:96:E2  30:52:CB:72:AF:FF  -54    1e- 1e   996      666  QWWW          
 8C:F2:28:10:96:E2  A4:5E:60:01:AD:14  -58    1e- 1e     0      100                
 8C:F2:28:10:96:E2  34:80:B3:DA:A7:1D  -42    0 - 1      0       17  QWWW          

__________________________________________________________________________________________________
23:08:36  Sending DeAuth to broadcast -- BSSID: [8C:F2:28:10:96:E2]
23:08:36  Sending DeAuth to broadcast -- BSSID: [8C:F2:28:10:96:E2

___________________________________________________________________________________________________
i] *Capture Handshake* 

Status handshake: 

      [1] Check handshake
      [2] Back (Select another deauth method)
      [3] Select another network
      [4] Exit
      #> 1
INFO WIFI

               SSID = QWWW / WPA2
               Channel = 13
               Speed = 54 Mbps
               BSSID = 8C:F2:28:10:96:E2 ( )
___________________________________________________________________________________________________

[i] Select your option

      [1] Web Interface
      [2] Bruteforce
      [3] Exit

#? 1
___________________________________________________________________________________________________
[i] Select Login Page

      [1]  English     [ENG]  (NEUTRA)
      [2]  German      [GER]  (NEUTRA)
      [3]  Russian     [RUS]  (NEUTRA)
      [4]  Italian     [IT]   (NEUTRA)
      [5]  Spanish     [ESP]  (NEUTRA)
      [6]  Portuguese  [POR]  (NEUTRA)
      [7]  Chinese     [CN]   (NEUTRA)
      [8]  French      [FR]   (NEUTRA)
      [9]  Turkish     [TR]   (NEUTRA)
      [10] Romanian    [RO]   (NEUTRA)
      [11] Hungarian   [HU]   (NEUTRA)
      [12] Arabic      [ARA]  (NEUTRA)
      [13] Greek       [GR]   (NEUTRA)
      [14] Czech       [CZ]   (NEUTRA)
      [15] Norwegian   [NO]   (NEUTRA)
      [16] Bulgarian   [BG]   (NEUTRA)
      [17] Serbia      [SRB]  (NEUTRA)
      [18] Polish      [PL]   (NEUTRA)
      [19] Indonesia   [ID]   (NEUTRA)
      [20] Dutch       [NL]   (NEUTRA)
      [21] Belkin      [ENG]
      [22] Netgear     [ENG]
      [23] Huawei      [ENG]
      [24] Verizon     [ENG]
      [25] Netgear     [ESP]
      [26] Arris       [ESP]
      [27] Vodafone    [ESP]
      [28] Back

#? 
___________________________________________________________________________________________________
[i] Attack in progress ..
                                       
      1) Choose another network
      2) Exit
 
      #> 
___________________________________________________________________________________________________
 ACCESS POINT:
    SSID............: QWWW
    MAC.............: 8C:F2:28:10:96:E2
    Channel.........: 13
    Vendor..........: 
    Operation time..: 00:23:03
    Attempts........: 0
    Clients.........: 0

  CLIENTS ONLINE:
     1) 192.168.1.101 xx:xx:xx:xx:xx:xx (unknown)  

__________________________________________________________________________________________________

**when it's  runinng,i am not foud a  
Forged ap in my android devices.** 
___________________________________________________________________________________________________

**Comment by deltaxflux** [comment]
You didn't fill out our issue template. This issue was closed automatically.

**Comment by deltaxflux** [comment]
Buy a compatible wireless card
