### ISSUE TITLE
Error on specific wifi names

### ISSUE THREAD

**Issue by NavjotSinghMinhas** [deltaxflux/fluxion#274]
### Which version of fluxion are you using?
0.23

### What distribution of Linux (including the version) are you running it on?
Ubuntu Mate, Raspberry

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TL-WN722N

### Which is the driver for it?
Automatic installation

### Does it support injection ( output of aireplay-ng -9)
Yes, works on all other wifi names

### General description of your issue along with the steps to reproduce it
Fluxion fails if wifi name ends with 
** :-)

for e.g. supponse wifi name is:
testwifiname ** :-)

You will get error grep: ‘/tmp/TMPflux/dump-01.csv’: No such file or directory.

**Comment by deltaxflux** [comment]
Thank you for your report. I will fix this soon as possible

**Comment by NavjotSinghMinhas** [comment]
Still the same, updated to rev 96.

![screenshot at 2016-11-20 17 39 18](https://cloud.githubusercontent.com/assets/8942810/20462679/dc47f7b2-af49-11e6-8d24-3b5163e32a9b.png)
![screenshot at 2016-11-20 17 39 47](https://cloud.githubusercontent.com/assets/8942810/20462688/f6da9288-af49-11e6-85fb-bb471520e982.png)
![screenshot at 2016-11-20 17 39 56](https://cloud.githubusercontent.com/assets/8942810/20462690/019b3664-af4a-11e6-936c-7eaf134818f7.png)

**Comment by deltaxflux** [comment]
if you navigate to /tmp/TMPFLUX can you confirm that there are files?

**Comment by deltaxflux** [comment]
And if you go somewhere else where you don't get a signal from the  **:) network. Is it working?

**Comment by deltaxflux** [comment]
Reopen if I get an answer

**Comment by NavjotSinghMinhas** [comment]
Yes, files are there.
Below are the screenshots and the Data dump

![screenshot at 2016-12-07 22_25_00](https://cloud.githubusercontent.com/assets/8942810/20980402/66c416fc-bcd6-11e6-9cee-42c92e387cfc.png)
![screenshot at 2016-12-07 22_25_10](https://cloud.githubusercontent.com/assets/8942810/20980403/66c56412-bcd6-11e6-99a5-e0e4296eeb4e.png)

**Comment by deltaxflux** [comment]
I noticed this bug on a mac book pro with a compatible wireless cards, at the moment I don't find the issue yet. Stay updated !
you can pass the scan if you type **skip** while you selecting your language

**Comment by deltaxflux** [comment]
Well this problem may happend if xterm don't allow to run as root

**Comment by NavjotSinghMinhas** [comment]
Can you please tell the steps for removing this problem, thanks for you efforts 👍

**Comment by NavjotSinghMinhas** [comment]
?

I always open fluxion with super user, can you tell the steps for removing this problem

**Comment by deltaxflux** [comment]
Do get an error if you type sudo xterm?

**Comment by NavjotSinghMinhas** [comment]
The terminal opens as superuser and i still get error

![screenshot at 2016-12-16 21 03 36](https://cloud.githubusercontent.com/assets/8942810/21268275/0902f7cc-c3d4-11e6-9f17-c084122572da.png)
![screenshot at 2016-12-16 21 03 46](https://cloud.githubusercontent.com/assets/8942810/21268285/16d6cedc-c3d4-11e6-95c2-5b9805b500a9.png)

**Comment by NavjotSinghMinhas** [comment]
didi you found the bug?

**Comment by NavjotSinghMinhas** [comment]
?

**Comment by deltaxflux** [comment]
Do you have permission for the tmp folder?
