### ISSUE TITLE
I can connect to the fake AP but I cannot login when I enter the password on the login page.

### ISSUE THREAD

**Issue by ibrahim-elshar** [deltaxflux/fluxion#276]
### Which version of fluxion are you using?
<97>

### What distribution of Linux (including the version) are you running it on?
<DISTRIB_ID=Kali
DISTRIB_RELEASE=2.0
DISTRIB_CODENAME=sana
DISTRIB_DESCRIPTION="Kali GNU/Linux 2.0"
PRETTY_NAME="Kali GNU/Linux 2.0 (sana)"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2.0 (sana)"
VERSION_ID="2.0"
ID_LIKE=debian
ANSI_COLOR="1;31"
>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<Ralink Technology, 802.11n USB>

### Which is the driver for it?
<modinfo rt2800usb
filename:       /lib/modules/4.0.0-kali1-amd64/kernel/drivers/net/wireless/rt2x00/rt2800usb.ko
license:        GPL
firmware:       rt2870.bin
description:    Ralink RT2800 USB Wireless LAN driver.
version:        2.3.0
author:         http://rt2x00.serialmonkey.com
>

### Does it support injection ( output of aireplay-ng -9)
<root@kali:~# aireplay-ng -9 wlan1mon
16:21:20  Trying broadcast probe requests...
16:21:22  No Answer...
16:21:22  Found 0 APs
>

### General description of your issue along with the steps to reproduce it
<I can connect to the fake AP but I cannot login when I enter the password on the login page.
Nothing happens at the login page also the number of attempts remains zero. I am trying it to my own network. I have successfully obtained a handshake and when I login i use the correct password.>

**Comment by strasharo** [comment]
Where do you expect to login?

**Comment by ibrahim-elshar** [comment]
When I type the password into the fake page i don't receive the password back
