### ISSUE TITLE
deauthentication not working and creating multiple fakeAP

### ISSUE THREAD

**Issue by dannyrock** [deltaxflux/fluxion#277]
### Which version of fluxion are you using?
<0.23>

### What distribution of Linux (including the version) are you running it on?
<Linux  4.8.0-kali1-amd64 #1 SMP Debian 4.8.5-1kali1 (2016-11-04) x86_64 GNU/Linux>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<
                description: Wireless interface
                product: Wireless 3165
                vendor: Intel Corporation
                physical id: 0
                bus info: pci@0000:02:00.0
                logical name: wlan0
                version: 81
                serial: xx:xx:xx:xx:xx:xx:xx:xx
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
     
>

### Which is the driver for it?
<
driver=iwlwifi driverversion=4.8.0-kali1-amd64 firmware=22.361476.0
>

### Does it support injection ( output of aireplay-ng -9)
<
"No"
13:12:22  Trying broadcast probe requests...
13:12:23  No Answer...
13:12:23  Found 0 APs
>

### General description of your issue along with the steps to reproduce it
<
i downloaded it it was working like charm,
the problem is caused by last two updates.
1)After first update
In.module ( "Spawns a MDK3 process, which deauthenticates all users connected to the target network, so they can be lured to connect to the FakeAP and enter the WPA password.")
after first update,
.A window of MDK3 starts but doesnt, "deauthenticates all users connected to the target network"
btw MDK3 de-auth still working while capturing handshakes 
2)After 2nd update
 The issue after first update is still there [does'nt deauth]
another issue is created
it started to create 10 or 15 fakeAP , instead of just 1
>
![15205737_1184930051601297_1876067081_o](https://cloud.githubusercontent.com/assets/8700031/20555324/3d8536a8-b183-11e6-94dd-3244b38e4791.png)

**Comment by deltaxflux** [comment]
weird
