### ISSUE TITLE
Python script with fluxion

### ISSUE THREAD

**Issue by big-empire** [deltaxflux/fluxion#278]
### Which version of fluxion are you using?
<???>

### What distribution of Linux (including the version) are you running it on?
<???>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<???>

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
<???>

### General description of your issue along with the steps to reproduce it
<???>

**Comment by big-empire** [comment]
The problem is I am trying to write a python script that runs fluxion but fluxion restarts again and again.
The code is:
import subprocess
Fluxion = subprocess.Popen("./fluxion")

**Comment by deltaxflux** [comment]
sudo ./fluxion
Why the heck do want to start a bash script in python ?

**Comment by deltaxflux** [comment]
#!/usr/bin/python

from os import system

commands = [
   "sudo ./fluxion"

]

for i in commands:
    system(i)
