### ISSUE TITLE
Does it work on thetered nets?

### ISSUE THREAD

**Issue by crazychem** [deltaxflux/fluxion#279]
### Which version of fluxion are you using?
FLUX 0.23 (rev.  98)

### What distribution of Linux (including the version) are you running it on?
Kali GNU/Linux Rolling 64-bit
GNOME Version 3.20.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Ralink RT2870/3070	

### Which is the driver for it?
rt2800usb

### Does it support injection ( output of aireplay-ng -9)
ioctl(SIOCSIWMODE) failed: Device or resource busy
02:01:08  Trying broadcast probe requests...
02:01:08  Injection is working!
02:01:10  Found 6 APs

### General description of your issue along with the steps to reproduce it
I got the handshake of my net (thetering from a Wiko Rainbow Android device), 
I entered the new open fake net with an android tablet
When I wrote the wifi password in the fake page, it told me invalid password.
I checked more than one time for the password of the thetered net (very simple, just 'passpass' without quotes).
In the fluxion window I can see the device connected to the net and the number of attempts.

Is it normal on thetered nets?
Do i have to do something different?
Do I have to give you anything else that could help you?

I already tried on different nets with physical AP, and the password catch worked.
I'm a newby in this, but I'm trying to learn by myself!
Thanks a lot!
Elio.

**Comment by deltaxflux** [comment]
Check the pwlog, there you can see all attempts 
`cat /root/pwlog/[SSID-BSSID.txt]`
