### ISSUE TITLE
Crash of Kali on Chromebook when leaving fluxion

### ISSUE THREAD

**Issue by flavbleach** [deltaxflux/fluxion#280]
### Which version of fluxion are you using?
0.23 rev 98

### What distribution of Linux (including the version) are you running it on?
Kali Linux 2 on Chromebook with Crouton

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Wireless internal chip only, no ethernet port.
Network controller [0280]: Intel Corporation Wireless 7260 [8086:08b1] (rev 6b)

### Which is the driver for it?
Network controller [0280]: Intel Corporation Wireless 7260 [8086:08b1] (rev 6b)

### Does it support injection ( output of aireplay-ng -9)
```
(kali-rolling)root@localhost:/home/*******#  aireplay-ng -9 wlan0       
ioctl(SIOCSIWMODE) failed: Device or resource busy
21:50:17  Trying broadcast probe requests...
21:50:19  No Answer...
21:50:19  Found 2 APs

21:50:19  Trying directed probe requests...
21:50:19  B0:B2:8F:XX:XX:XX - channel: 1 - 'Livebox-XXXX'
21:50:25  Ping (min/avg/max): 2.515ms/2.515ms/2.515ms Power: -87.00
21:50:25   1/30:   3%

21:50:25  Injection is working!
```

### General description of your issue along with the steps to reproduce it

> Hello,

First, here's my ifconfig output : 
```
(kali-rolling)root@localhost:/home/*******/Documents/fluxion/fluxion# ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 0  (Local Loopback)
        RX packets 5782  bytes 427075 (417.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5782  bytes 427075 (417.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.xx  netmask 255.255.255.0  broadcast 192.168.1.255
        ether e8:2a:ea:xx:xx:xx  txqueuelen 1000  (Ethernet)
        RX packets 686  bytes 342616 (334.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 728  bytes 166878 (162.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

1. I choose English as language.
2. All channels (during this step, my ifconfig stays the same)
3. I select the network I want.
4. FakeAP - Hostapd
5. When handshake found => Check handshake
6. **AND** When I choose "Web Interface" for the server to start, it **crashes (freez)**.

Moreover, when I choose to leave the program, wherever I want, my kali crash saying : 
```
Cleaning and closing
Disabling monitoring interface mon0
Disabling interface wlan0
**[Here It crashes]**
```

Thank you for your help. Have a great day.

**Comment by deltaxflux** [comment]
Don't use your internal wifi
