### ISSUE TITLE
Problem with captive portal page or login page

### ISSUE THREAD

**Issue by J0rd40** [deltaxflux/fluxion#281]
### Fill in the answers for all of the questions below, OTHERWISE YOUR TICKET WILL BE INSTANTLY CLOSED.

**### Which version of fluxion are you using?**
Fluxion 0.23 (Rev. 98)

**### What distribution of Linux (including the version) are you running it on?**
Kali GNU/Linux Rolling

**### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.**
Alfa AWUS036NEH, Ralink RT3070

**### Which is the driver for it?**
rt2800usb

**### Does it support injection ( output of aireplay-ng -9)**
Yes, it does

**### General description of your issue along with the steps to reproduce it**
Hello, so first of all, I'm writing this because Fluxion looks like a great program, one I would like to use and learn from. Although at this point, I really don't know what am I doing wrong! :cry:  So, what happens is that I can't see any fake captive form page, even if I type the address http://192.168.1.1/ into safari (iOS), android, a Windows PC or even typing localhost in the self hosting PC. 

What I usually do is: I go to fluxion folder, and I type the command: ./fluxion, thus making the program run, I choose the English language option [1], then I choose my Wireless Adapter, the Alfa on wlan1, after that I search for networks, everything fine with this and running smoothly, I can also get the handshake easily, but the problem is that after everything starts up just good, and even though the Fake DNS points everything I search on my victim to 192.168.1.1 there isn't any page there! :cry: 

Hope you can help me @deltaxflux, @strasharo and @ApatheticEuphoria!
The best regards, João Graça

**Comment by deltaxflux** [comment]
I think you card don't support master mode
