### ISSUE TITLE
Fluxion doesn't show clients of an access point ,But clients showing in Airodump-ng

### ISSUE THREAD

**Issue by thesmartraja** [deltaxflux/fluxion#282]
Version :  Fluxion 0.23 
Distribution of Linux  : Kali 2016 Rolling Gnome edition x86_64
Wireless Adapter   : TP-LINK TL-WN721N
Driver   : Bus 001 Device 002: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
aireplay-ng output :  

>  21:09:51  Trying broadcast probe requests...
> 21:09:51  Injection is working!
> 21:09:53  Found 1 AP 
> 21:09:53  Trying directed probe requests...
> 21:09:53  C0:A4:BC:B5:40:E5 - channel: 2 - 'Sanjai'
> 21:09:53  Ping (min/avg/max): 0.883ms/9.911ms/19.637ms Power: -43.07
> 21:09:53  30/30: 100%

 Hello Developers I like this program, Thanks for Developing this Wonderful automation MITM attack tool  ,   I am currently having this issue in fluxion 
Clients are connected to real AP ,and Receiving DATA Still they are Connected
But Users Not connected to FakeAP , aireplay-ng still going 
I tried mdk3 attack also but same problem , 
i waited for hours for new clients but nothing happen 
Please Fix this problem Soon ! 
I hope you understand my poor english 
If i was make an mistake Please tell me

**Comment by th3y3ll0wk1ng** [comment]
I'm also having this problem. Also using a TP-LINK TL-WN721N adapter, with Kali 2016 Rolling Gnome edition x86_64

After selecting language I don't get a choice in what nic to use, everything seems to work ok, the different networks are shown and I can select the one I want
Although it doesn't every have * next to target network to indicate clients are collected when I know they are
Then when I start the deauth process (both ways) no clients ever show so I can't capture handshake.
Viewing mdk3.txt shows the BSSID of the target network router.

strings /tmp/TMPflux/dump-02.csv | cut -d "," -f1,14 | grep -h "$Host_SSID" | cut -d "," -f1 | awk '{if (NR!=1) {print}}' > /tmp/TMPflux/mdk3.txt

^^ that command didn't help
Any suggestions? As I can see clients with airoplay 
Fluxion seems great, hope I can get it working properly!

**Comment by deltaxflux** [comment]
Reduce the distance

**Comment by deltaxflux** [comment]
It is a social engineering attack, the attack depends on the victims. If nobody wants to connect to the fakeAP, you don't have clients. Sometimes the hadware can't manage deauth and host an Access Point at the same time. If so please read the kernel wiki or use a second card to deauth but don't be an asshole

**Comment by th3y3ll0wk1ng** [comment]
Woah! How am i being an asshole? Im sure any problem im experiencing is relating to my mistake..
Anyway, i get what youre saying, but i dont understand why i am able to deauth clients usig airoplay but not on fluxion. I havent even got to the stage where the fake ap is out there, no clients are visible so no deauth packets are sendable. Im sure if i could see the clients (which i can do with other tools) i could send th deauth packets no problem.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Nov 29, 2016 at 7:15 AM +0000, "deltax" <notifications@github.com<mailto:notifications@github.com>> wrote:


It is a social engineering attack, the attack depends on the victims. If nobody wants to connect to the fakeAP, you don't have clients. Sometimes the hadware can't manage deauth and host an Access Point at the same time. If so please read the kernel wiki or use a second card to deauth but don't be an asshole

-

**Comment by deltaxflux** [comment]
The script is working flawless.  If you can't effort to buy a card which support that,  you have to use other tools.  In general what I meant with don't be an asshole: you don't shut continually deauth the WiFi from others. It is only for legal usage.  Repect laws in you country

**Comment by th3y3ll0wk1ng** [comment]
Christ you're a bundle of joy aren't you! Obviously I'm doing this on a network I own. Thanks a lot for the help mate!


________________________________

**Comment by deltaxflux** [comment]
Good luck
