### ISSUE TITLE
Fake AP and Fake DNS does not work.

### ISSUE THREAD

**Issue by HackerKK** [deltaxflux/fluxion#285]
### Which version of fluxion are you using?
fluxion ver.100
### What distribution of Linux (including the version) are you running it on?
Linux version 4.4.0-45-generic (buildd@lgw01-34) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) )
### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Qualcomm Atheros AR9285 Wireless Network Adapte

### Does it support injection ( output of aireplay-ng -9)
18:12:50  Trying broadcast probe requests...
18:12:50  Injection is working!
18:12:52  Found 2 APs

18:12:52  Trying directed probe requests...
18:12:52  F8:1A:67:C5:5A:F6 - channel: 7 - 'TP-LINK'
18:12:53  Ping (min/avg/max): 1.467ms/16.680ms/72.361ms Power: -76.24
18:12:53  29/30:  96%

18:12:53  D4:21:22:BA:68:B6 - channel: 7 - 'TP-LINK'
18:12:54  Ping (min/avg/max): 2.299ms/18.954ms/189.217ms Power: -41.97
18:12:54  29/30:  96%

### General description of your issue along with the steps to reproduce it
Anything can\`t connect to fakeap after start it. And fakedns don\`t retrieve any sites. But if i go to 192.168.1.1 in the browser at my laptop where fakeap is start, i can write wi-fi pass. After that fluxion have saving pass in the log. How to repair FakeAp and FakeDns?
lighttpd/1.4.35 (ssl) - a light and fast webserver
Build-Date: Apr 18 2016 15:36:10

**Comment by deltaxflux** [comment]
Check your driver before you ask:
https://gist.github.com/dudemeister/1434196
