### ISSUE TITLE
hi,

### ISSUE THREAD

**Issue by mrjesters** [deltaxflux/fluxion#286]
### Which version of fluxion are you using?
<???>

### What distribution of Linux (including the version) are you running it on?
<???>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<???>

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
<???>

### General description of your issue along with the steps to reproduce it
<???>

**Comment by mrjesters** [comment]
hi,
i just wanted to know if i could use fluxion on windows ?

**Comment by strasharo** [comment]
Only in a Linux virtual machine together with a compatible USB wireless adapter.
