### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by phatal** [deltaxflux/fluxion#287]
### Which version of fluxion are you using?
101
### What distribution of Linux (including the version) are you running it on?
Kali Rolling with full updates
### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
External tp link wn722n
### Which is the driver for it?
ath9k (if I understand right)
### Does it support injection ( output of aireplay-ng -9)
`06:01:22  Trying broadcast probe requests...
06:01:22  Injection is working!
06:01:24  Found 6 APs

06:01:24  Trying directed probe requests...
06:01:24  C4:3D:C7:85:D3:82 - channel: 1 - 'Free wifi'
06:01:25  Ping (min/avg/max): 1.138ms/19.392ms/49.200ms Power: -27.63
06:01:25  30/30: 100%

06:01:25  CA:3D:C7:85:D3:82 - channel: 1 - 'Welcome'
06:01:25  Ping (min/avg/max): 10.948ms/26.686ms/70.881ms Power: -28.00
06:01:25  30/30: 100%

06:01:26  00:01:FF:77:7D:A8 - channel: 2 - 'NTK1'
06:01:26  Ping (min/avg/max): 2.452ms/16.892ms/174.225ms Power: -85.72
06:01:26  29/30:  96%

06:01:26  00:24:01:AD:7B:01 - channel: 2 - '22'
06:01:27  Ping (min/avg/max): 5.559ms/21.536ms/124.316ms Power: -73.37
06:01:27  30/30: 100%

06:01:27  CC:5D:4E:5A:F2:4E - channel: 1 - 'wlh'
06:01:33   0/30:   0%

06:01:34  00:0F:02:5D:99:78 - channel: 2 - 'ViRus'
06:01:40   0/30:   0%
`
### General description of your issue along with the steps to reproduce it
At last part of attack, visitors count always 0, but in airodump-ng I see that someone connect, almost very often doesn't catch handshakes, (even with pyrit, which work perfectly at wifite), and one more, if at last step select "change network" more then twice, It is a very high probability that terminal with fluxion will hang.  Fluxion very useful tools, but this issues spoil all impression from it.

**Comment by deltaxflux** [comment]
I don't know if I misunderstand you but the clients counter is the counter for clients which are connected to the network
