### ISSUE TITLE
Version Check for update contains spaces

### ISSUE THREAD

**Issue by th3c0ldh3art** [deltaxflux/fluxion#289]
### Which version of fluxion are you using?
102

### What distribution of Linux (including the version) are you running it on?
┌─[root@anonymous]─[~]
└──╼ # cat /etc/lsb-release 
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Atheros AR9271	ath9k

### Which is the driver for it?
Kernel driver in use: iwlwifi

### Does it support injection ( output of aireplay-ng -9)
Yes
┌─[✗]─[root@anonymous]─[~]
└──╼ # aireplay-ng -9 wlan1
ioctl(SIOCSIWMODE) failed: Device or resource busy
22:03:20  Trying broadcast probe requests...
22:03:20  Injection is working!
22:03:22  Found 10 APs

### General description of your issue along with the steps to reproduce it
**Remove the space in between the version for this new update. or better implement some trimming for spaces, if you're keeping it with some intention.**

See below to understand fully.

```
┌─[root@anonymous]─[~]
└──╼ # revision_online="$(timeout -s SIGTERM 20 curl "https://raw.githubusercontent.com/deltaxflux/fluxion/master/fluxion" 2>/dev/null| grep "^revision" | cut -d "=" -f2)"

┌─[root@anonymous]─[~]
└──╼ # echo "$revision_online."
102		.

```
**I could have contributed but looks like I'm not allowed to.** 

**Anyways, good job.**

**Comment by deltaxflux** [comment]
thank you

**Comment by th3c0ldh3art** [comment]
> You're welcome!
