### ISSUE TITLE
fake ap not starting and the client is not disconnecting when the attack is launched

### ISSUE THREAD

**Issue by aliwaqas2323** [deltaxflux/fluxion#29]
only these 2 issues have left need updates to fix these @deltaxflux @strasharo @ApatheticEuphoria @Arccotangent

**Comment by deltaxflux** [comment]
@aliwaqas2323 as you should now. You **WIFI card** don’t support Fake AP. Never than less it support captching partly.

**Solve:**
_Buy a external WiIFI card ($10)_

**Comment by dimastt** [comment]
I have a external dongle usb card xl power with chip ralink 7601u in kali 2.0 rolling and got same problem my external detect in wlan1.dont enable a fake ap.please help me

**Comment by deltaxflux** [comment]
Maby the external wifi Card don't Support Fake AP. I do a quick Research for that
