### ISSUE TITLE
add custom login page

### ISSUE THREAD

**Issue by sjodi442** [deltaxflux/fluxion#294]
### Which version of fluxion are you using?
v0.23

### What distribution of Linux (including the version) are you running it on?
kalilinux

hei . can i add custom login page on fluxion ?

**Comment by deltaxflux** [comment]
Yes send me the login page

**Comment by droidhackhd** [comment]
I am adding custom page for a test 

After modifications script
I am get error syntax error
While selecting custom page 

Also I had set chmod +x 400 
And don't know where  the error occur

**Comment by deltaxflux** [comment]
All login pages must be copied in the data folder,  you find it : /tmp/TMPflux/

**Comment by marsalansiddiqui** [comment]
hey ! how to add login pages? just put it in sites folder? it will automatically detect or need to do some changing ?
