### ISSUE TITLE
handshake is captured always BAD!

### ISSUE THREAD

**Issue by userdsp** [deltaxflux/fluxion#295]
### Which version of fluxion are you using?
105

### What distribution of Linux (including the version) are you running it on?
Kali 2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
WN722N and AWUS036H

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
If I capture the handshake manually, aircrack can find the PASS KEY.  I'm testing over my own network!

**Comment by deltaxflux** [comment]
Use pyrit to check your handshake

**Comment by userdsp** [comment]
cap from Flkuxion capture:
root@kali:~/handshakes# pyrit -r mp-XX:XX:XX:XX:C1:02.cap analyze
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

Parsing file 'mp-XX:XX:XX:XX:C1:02.cap' (1/1)...
Parsed 3 packets (3 802.11-packets), got 1 AP(s)

#1: AccessPoint XX:XX:XX:XX:C1:02 ('mp'):
  #1: Station XX:XX:XX:XX:0d:27, 1 handshake(s):
    #1: HMAC_SHA1_AES, bad, spread 1
===================================================
cap from manual capture:
root@kali:~# pyrit -r mp-01.cap analyze
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

Parsing file 'mp-01.cap' (1/1)...
Parsed 76 packets (76 802.11-packets), got 1 AP(s)

#1: AccessPoint XX:XX:XX:XX:C1:02 ('mp'):
  #1: Station XX:XX:XX:XX:58:46, 9 handshake(s):
    #1: HMAC_SHA1_AES, good, spread 1
    #2: HMAC_SHA1_AES, good, spread 1
    #3: HMAC_SHA1_AES, good, spread 1
    #4: HMAC_SHA1_AES, good, spread 7
    #5: HMAC_SHA1_AES, good, spread 7
    #6: HMAC_SHA1_AES, good, spread 9
    #7: HMAC_SHA1_AES, workable, spread 1
    #8: HMAC_SHA1_AES, workable, spread 3
    #9: HMAC_SHA1_AES, workable, spread 11
  #2: Station XX:XX:XX:XX:0d:27, 1 handshake(s):
    #1: HMAC_SHA1_AES, good, spread 1

**Comment by userdsp** [comment]
Maybe you can add pyrit check funktion in Fluxion? Not only a handshake file check.     
One HMAC_SHA1_AES, workable, spread 1 is enough for cracking.

**Comment by deltaxflux** [comment]
Fluxion check if the handshake is valid and good,  it only use good files not workable
