### ISSUE TITLE
Handshake Not_found!

### ISSUE THREAD

**Issue by wongcheehong** [deltaxflux/fluxion#297]
### Which version of fluxion are you using?
0.23 (rev. 105)

### What distribution of Linux (including the version) are you running it on?
Kali GNU/Linux Rolling 64-bit

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Ralink Technology, Corp. RT2870/RT3070

### Which is the driver for it?
rt2800usb

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
When I enter the correct path of my handshake and press Enter, it show Not_Found! like picture blow.
![screenshot 61](https://cloud.githubusercontent.com/assets/11075969/20913406/a114fc38-bbb2-11e6-80cb-1b9f541159e6.png)

**Comment by deltaxflux** [comment]
If you have a different Mac it says that it don't found the file,  maybe I change the text.  The loop is a bug
