### ISSUE TITLE
Can not find a fake ap on any device

### ISSUE THREAD

**Issue by matty0005** [deltaxflux/fluxion#298]
### Which version of fluxion are you using?
0.23

### What distribution of Linux (including the version) are you running it on?
Ubuntu 16.04 LTS

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Qualcomm Atheros AR9285

### Which is the driver for it?
Driver = ath9k  Version = 4.4.0-53-generic

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
After you 'Check handshake', i selected 'Web Interface', i then selected english. a couple of windows pop up. The only one that doesnt pop up is the DHCP one. Also Fluxion seems to have created a fake AP, however the fake AP can't be seen by my ipad. 
However, i am able to create a hotspot outside of fluxion, and connect to it as normal.
Thanks

**Comment by deltaxflux** [comment]
Use a compatible wireless card
