### ISSUE TITLE
essid not showing for one network

### ISSUE THREAD

**Issue by olujche** [deltaxflux/fluxion#30]
Essid inside " " is not showing worh airodump.. maybe that is airodump bug.. Another thing, why is not posible to create captive portal that will auto load as soon as you connect to network? We have some public wifi hotspots (SBB ZONA) When you connect to it, you are displayed (in settings where you turn on wifi on android and see ap list) with their web page to sign up whit account, cuppon code etc... You dont need to open web browser and no need for dns spoofing. Is this posible with fluxion in future? BTW. This is rly best tool in many years, great work! I hope you will be awarded with fame soon.

**Comment by deltaxflux** [comment]
Can you be more specific :)
When is the Essid clear ?
Can you select a network ?
Which linux do u use?
Yeah auto load don’t work currently. If you saw our HF Post we already discuss this. Because on cached websites  e.g (google) it don't work. Lets see what the future brings
