### ISSUE TITLE
Cant open bc bully and mdk3 not installed

### ISSUE THREAD

**Issue by kidkart72** [deltaxflux/fluxion#300]
### Which version of fluxion are you using?
0.23

### What distribution of Linux (including the version) are you running it on?
ubuntu 16.04 lts

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
interal

### Which is the driver for it?
acer net book

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
I cant get the porgram to run because bully and mdk3 not installed. i have ran though the installer twice and cant get it to run. what do i need to do?

**Comment by deltaxflux** [comment]
Run following
`sudo apt-get update; sudo apt-get install bully -y; sudo apt-get install mdk3 -y`

**Comment by kidkart72** [comment]
I have ran the commands and its telling me that it is unable to locate the package. What is the next step i can take? 

----- Original Message -----

**Comment by nicolasjansen** [comment]
i have the same problem

**Comment by strasharo** [comment]
What error exactly are you receiving?

**Comment by nicolasjansen** [comment]
when i type sudo ./fluxion than i can see tha bully = not installed and
mdk3 allso not installed
Nicolas Jansen

**Comment by strasharo** [comment]
Are they available in the path? 
sudo which mdk3
sudo which bully

**Comment by nicolasjansen** [comment]
i have type this but it just skips it asked my password but than does
nothing

**Comment by strasharo** [comment]
In that case both binaries are not available in your path. There's an issue with their installation, which is out of the scope of fluxion. Once those are available in the path fluxion will work.
