### ISSUE TITLE
Problem with handshake capture

### ISSUE THREAD

**Issue by GeorgeSp1** [deltaxflux/fluxion#301]
### Which version of fluxion are you using?
<0.23>

### What distribution of Linux (including the version) are you running it on?
<kali rolling>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<Atheros Communications, Inc. AR9271 802.11n>

### Which is the driver for it?
<ath9k_htc>

### Does it support injection ( output of aireplay-ng -9)
<Injection is working>

### General description of your issue along with the steps to reproduce it
<Although i can select the network and select the method i want to use, i cant get the handshake. First i tried to do it using aircrack-ng but the airodump-ng windown never showed. The handshake would be from my smartphone, which reconnected to the network so the handshake should have been captured by now, but when i press check handshake is says that its not found. I also tried giving the path of a already captured handshake but didnt work too. I can provide screenshots if needed. >

**Comment by deltaxflux** [comment]
Are there any clients in the airodump window ?

**Comment by GeorgeSp1** [comment]
It doesn't show up the airodump window. I saw that it should open it from a video on YouTube. It worked with the path of a already captured handshake. The problem is when I want to capture a handshake while deauthenticating.
