### ISSUE TITLE
./fluxion-master/fluxion:line 1436:./airmon:No such file or directory

### ISSUE THREAD

**Issue by nikolachan** [deltaxflux/fluxion#305]
### Which version of fluxion are you using?
<FLUX 0.23 (rev. 105)>

### What distribution of Linux (including the version) are you running it on?
<Kali Linux 2016.2>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<Chipset:Realtek Semiconductorr Co.,Ltd. RTL8188CE 802.11b/g/n WiFi Adapter(rev 01)>

### Which is the driver for it?
<Driver: rt18192ce>

### Does it support injection ( output of aireplay-ng -9)
<yes>

### General description of your issue along with the steps to reproduce it
<I got this error on fresh installed Kali 2016.2:
 ./fluxion: line 1436: ./airmon: No such file or directory
./fluxion: line 1435: ./airmon: No such file or directory
There are no wireless cards, quit...>

**Comment by deltaxflux** [comment]
`
cd fuxion;
sudo ./fluxion`
