### ISSUE TITLE
Custom Login Page And Some Questions

### ISSUE THREAD

**Issue by paklover786** [deltaxflux/fluxion#309]
### Which version of fluxion are you using?
V 0.23 Rev105

### What distribution of Linux (including the version) are you running it on?
Kali Linux Rolling 2.0

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Tp Link 7200ND

### Which is the driver for it?
Atheros

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
I have some issues and qustions:

1:Does fake login page works on windows or linux because I have checked it on only android device.

2.Can I add a custom login page if yes then How?

3.I have a another wep network but fluxion is only scanning wpa or wpa2 available networks not open and wep secured networks

4.I want to show mikrotik fake login page to victim like this http://paklover786bot.3eeweb.com/ but the problem is when victim enter username and password that will not sent to me because in fluxion the password is first check by handshake and then sent to us.Problem is we can capture handshake on mikrotik hotspot network but username and password will not sent to us.

Are there any fixes of these problems?Sorry for my bad English/

Waiting for reply.

**Comment by deltaxflux** [comment]
Well for the handshake check you need to modify the script. Fluxion use a custom php script called check.php but I will make a tutorial how to add custom login pages soon

**Comment by marsalansiddiqui** [comment]
i'm using mikrotik for my personal network, and know you want to sniff username and passwords to access internet but fluxion is not meant to be use in this way, although i know how to capture username and password before writing on handshake file.

**Comment by marsalansiddiqui** [comment]
Another thing to remember that when you deauthenticate the real ap, you still can't get handshakes because ap is under mikrotik.

**Comment by deltaxflux** [comment]
What do you mean,  is it a mikrotik router?
