### ISSUE TITLE
Stucks at re-reading black list/ white white list

### ISSUE THREAD

**Issue by genusmig** [deltaxflux/fluxion#31]
Hello. I found out that it stop at re-reading black list/ white list and not sending deauth

My wifi chipset is rt2800 driver

**Comment by strasharo** [comment]
Could you be a little bit more specific, please?

**Comment by genusmig** [comment]
Im sorry. I think its working. Maybe its the ap that is the problem

**Comment by genusmig** [comment]
Hi again. I more problem notice. Everytime I start an attack. Without selecting 1) Start. The script starts by its own.

I would like to advice if you could option to add custom site for log in. So it will be less suspicious to other clients.

**Comment by strasharo** [comment]
First you mentioned something about blacklists, now you you're talking about a completely different topic. The start option is no longer present, please update your copy of the script.
