### ISSUE TITLE
Refused to connect

### ISSUE THREAD

**Issue by milan21** [deltaxflux/fluxion#310]
### Which version of fluxion are you using?
V 0.23 Rev105

### What distribution of Linux (including the version) are you running it on?
Wifi Slax 

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Ralink

### Which is the driver for it?
Ralink

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it

When I open any website  in fake ap using android or windows then it shows refused to connect.. Any solutions for it??

**Comment by deltaxflux** [comment]
Which android version do you use and does it work with the old dhcp client ?

**Comment by milan21** [comment]
I am using android 5.1.1 Lollipop and when I open https website it displays some error but when I open non https websites it opens and asks for password... Doesn't it work for https websites?? Most of the websites are secured ( https)

**Comment by deltaxflux** [comment]
Only the dev version support https redirection
