### ISSUE TITLE
capture portal don't resolve after second attempt [details below]

### ISSUE THREAD

**Issue by marsalansiddiqui** [deltaxflux/fluxion#311]
### Which version of fluxion are you using?
latest

### What distribution of Linux (including the version) are you running it on?
kali linux latest on raspberry pi

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Atheros  | TP-LINK TLWN722N

### Which is the driver for it?
driver builtin in os

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
i set up fluxion and it works nicely the issue is when i connect to rough ap (mine rpi) it prompts for sign in, i cancel that and open browser i head towards any site say google.com it shows login page after that i open another site say facebook.com it's not resolving to login page

Thanks.

**Comment by deltaxflux** [comment]
Https is not supported

**Comment by marsalansiddiqui** [comment]
nah, i tried with http both sites with http protocol. non-https sites also won't work.

**Comment by deltaxflux** [comment]
Well try to erase your cach

**Comment by marsalansiddiqui** [comment]
alright.
