### ISSUE TITLE
bug on fake AP tp-link ITA

### ISSUE THREAD

**Issue by SiNaPsEr0x** [deltaxflux/fluxion#313]
### Which version of fluxion are you using?
0.23 rev 105

### What distribution of Linux (including the version) are you running it on?
Linux r0x 4.8.0-kali2-amd64 #1 SMP Debian 4.8.11-1kali1 (2016-12-08) x86_64 GNU/Linux

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
ALFA 
Bus 001 Device 007: ID 0bda:8187 Realtek Semiconductor Corp. RTL8187 Wireless Adapter
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0bda Realtek Semiconductor Corp.
  idProduct          0x8187 RTL8187 Wireless Adapter
  bcdDevice            1.00
  iManufacturer           1 Manufacturer_Realtek_RTL8187_
  iProduct                2 RTL8187_Wireless
  iSerial                 3 00C0CA82FDFD
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           39
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          4 Wireless Network Card
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           3
      bInterfaceClass         0 (Defined at Interface level)
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              5 Bulk-IN,Bulk-OUT,Bulk-OUT
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  bNumConfigurations      1
Device Status:     0x0000
  (Bus Powered)

### Does it support injection ( output of aireplay-ng -9)
aireplay-ng -9 wlan0mon
16:15:59  Trying broadcast probe requests...
16:15:59  Injection is working!
16:16:00  Found 6 APs

16:16:00  Trying directed probe requests...
16:16:00  64:D1:A3:37:D9:65 - channel: 11 - 'Vodafone-26852124_EXT'
16:16:01  Ping (min/avg/max): 7.779ms/17.484ms/32.376ms Power: -57.33
16:16:01  30/30: 100%

### General description of your issue along with the steps to reproduce it
on start fakeap on tp-link ita this error... but the other it's ok!

impossibile eseguire stat di '/root/hack/fluxion/Sites/Upgrade-TP-LINK_ITA/bootstrap.min.css': File o directory non esistente
cp: impossibile eseguire stat di '/root/hack/fluxion/Sites/Upgrade-TP-LINK_ITA/bootstrap.min.js': File o directory non esistente
cp: impossibile eseguire stat di '/root/hack/fluxion/Sites/Upgrade-TP-LINK_ITA/index.html': File o directory non esistente
cp: impossibile eseguire stat di '/root/hack/fluxion/Sites/Upgrade-TP-LINK_ITA/jquery.min.js': File o directory non esistente
cp: impossibile eseguire stat di '/root/hack/fluxion/Sites/Upgrade-TP-LINK_ITA/final.html': File o directory non esistente
cp: impossibile eseguire stat di '/root/hack/fluxion/Sites/Upgrade-TP-LINK_ITA/error.html': File o directory non esistente

**Comment by deltaxflux** [comment]
Definitely take a look at it. Thanks for your report

**Comment by deltaxflux** [comment]
Confirmed let's see if I can found the folder lol
