### ISSUE TITLE
Add lesten push button wps box ? and TX power

### ISSUE THREAD

**Issue by disquette38** [deltaxflux/fluxion#314]
Is it possible to add two xterm, valid if the client presses the wps key, so in a terminal launch wpa_cli -i (interface monitor)
The terminal will listen to the networks, open a second terminal and then launch a loop
Which will allow to restart the search for activation of the WPS push button by an access point. Here the command:
while : ; do sudo wpa_cli wps_pbc any ; sleep 120 ; done &

And add TX power 30 db ?

Thank for the good projet !!!!

**Comment by deltaxflux** [comment]
I think the txpower change is not a good idea. If the chip is locked (hopefully software locked), you need to modfy iw (which isn't a problem) but you need to restart. Better you do this manualy. Take a look [here](https://github.com/strasharo/wifi_channel_unlocking). I modify the search terminal slightly but at the moment I don't have time for that

**Comment by disquette38** [comment]
Ok for the power setting, (I also power the power in manual). What do you think of listening to the WPS, it's very fast I was able to connect to a hotspot in this way :)
Any case thank you for your work !!!
Sorry / desolate for my english
