### ISSUE TITLE
Fluxion on Nethunter?

### ISSUE THREAD

**Issue by jeretc** [deltaxflux/fluxion#315]
### Hi will it be possible to port fluxion for nethunter?
<???>

**Comment by TimSchumi** [comment]
As fluxion is just a shell script, it entirely relies on the dependencies

**Comment by jeretc** [comment]
hi so i was trying to install it on nethunter but i got this messgae .. when i try to run./fluxion or ./Installer.sh 
"The script should be executed inside a X (graphical) session."

**Comment by TimSchumi** [comment]
You need to open up a vnc session, because fluxion uses multiple xterm windows. It does not work over SSH

**Comment by jeretc** [comment]
ok i got fluxion installed and running using vnc session on my nexus 5 - nethunter. It runs without errors and manage to capture the handshake. The only problem is from my laptop  when i connect to the fake AP there is no fake page or redirect to the fake page .

thanks.

**Comment by marsalansiddiqui** [comment]
clear you cache, try manually, open network manager and check if it's getting ip

**Comment by deltaxflux** [comment]
Can depend on your lighttpd and python version
