### ISSUE TITLE
Fluxion without graphical environment on NetHunter

### ISSUE THREAD

**Issue by AutinDroid** [deltaxflux/fluxion#317]
I believe that Fluxion is a great tool, but it is hard to use on the GUI (my screen isn't big enough for me to view all text). I would like to see a fluxion package for NetHunter that opens new windows in the NetHunter Terminal.

**Comment by marsalansiddiqui** [comment]
same here, i use it on raspberry pi screen size is 600x400, you can install vnc viewer to view on your laptop or desktop screen.

**Comment by AutinDroid** [comment]
I don't want to have to use vnc viewer as I do not bring my laptop with me everywhere.

**Comment by deltaxflux** [comment]
Well there are also vnc apps available for Android and I believe also for ios. I will create a no gui version but this can take a while.

**Comment by strasharo** [comment]
Pull requests are welcome.

**Comment by cyrus104** [comment]
I know this is closed but I wanted to asked if it would be easier for you to use T-Mux or Screen in the sudo no gui version.
