### ISSUE TITLE
Problem Handshake ( rev 106 )

### ISSUE THREAD

**Issue by BlackMamba19** [deltaxflux/fluxion#318]
### Which version of fluxion are you using?
<0.23> rev 106

### What distribution of Linux (including the version) are you running it on?
Kali Rolling

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Ralink RT2870/3070

### Which is the driver for it?
rt2800usb

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it

Hi, I have a problem whit handshake. In rev 105 was all right now after upgrading to 106 gives me this problem on all networks (and there are more hosts connected to each).

Problem with pyrit to capture a new handshake: 
(This happens on all networks)

![whatsapp image 2016-12-18 at 00 43 24 1](https://cloud.githubusercontent.com/assets/23263283/21293293/f79f4b1e-c51f-11e6-8936-a99eeb35fe8f.jpeg)

problem with a good handshake captured previously:

![whatsapp image 2016-12-18 at 00 43 24](https://cloud.githubusercontent.com/assets/23263283/21293307/5311463c-c520-11e6-8eaa-86de82b29051.jpeg)

and I get the same error even if you captured separately and I plug it in the path. 

Sorry for my English and thanks in advance for the help.

**Comment by deltaxflux** [comment]
I don't change something on the check handshake function.  So it is not different from version 105. If you struggle use aircrack-ng

**Comment by disquette38** [comment]
I have the same problem, but this does not come from the fluxion version (105 or 106). It is since the system maj, after apt-get upgrade && apt-get upgrade && apt-get dist-upgrade, currently 4.8.0-kali-2-amd64 # 1 SMP Debian 4.8.11-1Kali1 (2016- 12-08)
