### ISSUE TITLE
Few issues and testing results

### ISSUE THREAD

**Issue by olujche** [deltaxflux/fluxion#32]
Ok, i had few days on testing fluxion on 10+ networks and this is my impressions and problems.

1. After people get annoyed from disconnects they in most cases try out fake AP. 90% of time mobile phones like android and windows phone are used.
    1,1. After they connect they try to use apps from phone, and after some time they start browser to see if they have internet accses. This is the first problem.. DNS spoofing and loading captive portal page takes to loong. People just dont want to wait for ~10 sec for captive portal to load. Im not sure how you can make this time lower. Maybe turn off broodcast of disconnects? Im not sure, but this time needs to be lowered.
   1,2 Im not sure how to put "go to link" inside wifi connection like some companies do, so this would be great and ultimate thing to add...

2. SSID like "myssdinsidequotationmarks" wont show, But this is problem with airodump-ng, you should put \ in front of " like.... \"myssidinsidequotationmarks\" if documentation for airodump-ng is correct..

3. Some routers do channel "hop" in middle of attack to try and find clear channer.. If target AP hop to diferent channel attack fails becouse you dont do brodcast DC on right channel.

4. It would be amazing to add "rescan networks" to "select new network" page (as in number 1 for example) and to add automatic search of previous handshakes captured in /root/handshakes if they match bssid.

5. If wifi addapter is already in monitor mode before starting fluxion, it wont scan networks.

I was using most up to date kali and fluxion, installed to USB and booted from it. I got 1 wpa pass, 1 client opened network in frustration, and many more were connected on my network but becouse of slow loading speed of captive portal, they did not leave pass. If you need to add support for annother wifi addapter just for fake AP, you should.. The biggest problem right now is people not wanting to wait more then 3 sec for web page to show up.
Great work!

**Comment by strasharo** [comment]
What wireless adapter were you using for this testing?

**Comment by olujche** [comment]
external alfa adapter: AWUS036NH
Laptop i3 4010U 1.7GHZ, 4GB DDR3

I will try internal wifi network to see if it helps with loading time

**Comment by strasharo** [comment]
IIRC that one was with Ralink, right?
Which option did you choose for AP - hostapd or airbase-ng?

**Comment by olujche** [comment]
bouth.. hostapd and airbase.. Hostapd is just a bit faster.

**Comment by strasharo** [comment]
Yep, airbase-ng is slow by design, but we left it as an option mostly for the drivers incompatible with hostapd like 8187. hostapd is the recommended AP to use if it works with your adapter.

**Comment by olujche** [comment]
yea it works, Only problem is when you open browser and try "www.google.com", you need to wait at least 5 to 8 sec for login form to appear.. When someone dont have internet accses from application on phone, they will think after 3-4 sec they wont see anything and close browser.. It is small fraction of time, but very important..

**Comment by strasharo** [comment]
First part of 4) added, there's now a rescan option on the select network screen. Let me know if it works for you.

**Comment by strasharo** [comment]
5) fixed
