### ISSUE TITLE
Please fix HTTPS redirect iasue

### ISSUE THREAD

**Issue by milan21** [deltaxflux/fluxion#320]
Which version of fluxion are you using?

V 0.23 Rev105

What distribution of Linux (including the version) are you running it on?

Wi-Fi Slax

What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

Ralink

Which is the driver for it?

Ralink

Does it support injection ( output of aireplay-ng -9)

Yes

General description of your issue along with the steps to reproduce it

I think it doesn't support HTTPS redirect.
Since Google has make HTTP as not secure, all the websites are being secured by using HTTPS connection. But Fluxion doesn't support HTTPS redirect.. Please try to solve it...

**Comment by deltaxflux** [comment]
Fluxion support ssl redirection if you use the right version

**Comment by milan21** [comment]
Which version should I use??

**Comment by deltaxflux** [comment]
I don't share the version with you

**Comment by tuthieu** [comment]
I want the redirect edition,but you don't share.
Will you sell it?
