### ISSUE TITLE
can't get through with handshake

### ISSUE THREAD

**Issue by itachi66** [deltaxflux/fluxion#321]
### Which version of fluxion are you using?
0.23 rev 106

### What distribution of Linux (including the version) are you running it on?
Linux kali 4.8.0-kali2-amd64 #1 SMP Debian 4.8.11-1kali1 (2016-12-08) x86_64 GNU/Linux

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
tplink wn722n chipset : Atheros AR9271

### Which is the driver for it?
ath9k

### Does it support injection ( output of aireplay-ng -9)

 aireplay-ng -9 wlan1mon
23:31:30  Trying broadcast probe requests...
23:31:31  Injection is working!
23:31:32  Found 4 APs

23:31:32  Trying directed probe requests...
23:31:32  C4:A3:66:5E:6B:EC - channel: 9 - 'Allah Akbr'
23:31:32  Ping (min/avg/max): 1.323ms/10.918ms/22.735ms Power: -67.83
23:31:32  30/30: 100%

### General description of your issue along with the steps to reproduce it
![1](https://cloud.githubusercontent.com/assets/24657371/21329875/a20e5bf2-c643-11e6-834d-100fcfb8463c.png)

i'm sure that the handshake is good and working but i can't get it to work with fluxion i'm stuck at this screen and it's looping BTW i can't capture handshake with fluxion too i tried all networks and all death methods with no luck at all.

**Comment by xLesterGG** [comment]
getting this handshake problem as well.

**Comment by itachi66** [comment]
seems like no one cares about our issue.

**Comment by deltaxflux** [comment]
@itachi66 your right, 22 hours passed and nobody cares about it. Sure I fix this if I have time, I'm busy at the moment

**Comment by xLesterGG** [comment]
a temporary solution would be typing "NO" when asked to select the handshake, and proceed to obtaining it again.

**Comment by itachi66** [comment]
it's not someone else's .... it's my router lol
and as i mentioned above i can't do this temporary solution it's broken too
i can only capture handshake manually using aircrack-ng
thanks for your comments @xLesterGG  @deltaxflux 
i'm glad that someone cares.

**Comment by xLesterGG** [comment]
tried deleting the .cap file? tho I couldn't find the directory

**Comment by marsalansiddiqui** [comment]
Oh ho, you didn't understand. Handshakes are captured only when a user is connected to real ap and we are trying to de-authenticate them. Try when a user is connected to the ap or maybe ap is to far from you.

**Comment by disquette38** [comment]
It's the same for me since a week more system upgrade box # 318

**Comment by thiago325** [comment]
I am with this problem too,
"Handshakes are captured only when a user is connected to real ap and we are trying to de-authenticate them."
It 's the only solution but when i try to put the cap file in the moment "do you want to use this file"
i put the cap file and the fluxion says about the mac:
"Not_found"

**Comment by YouGamePlayHD** [comment]
Same problem, no Bruteforce possible.

**Comment by itachi66** [comment]
i rolled back my kali linux to 4.6.0 kernel and tried fluxion ... it's weird fluxion is working just fine.
the problem is fluxion isn't working fine with the latest kernel it always say MAC Not_Found.
@deltaxflux please take a look at this. TY

**Comment by deltaxflux** [comment]
I said I will check it. What do you expect that I'm a super hero?
