### ISSUE TITLE
Am i new into this git hub, i did clone the your repository into my local data but how can i upload all the files into  my respository

### ISSUE THREAD

**Issue by mistyez** [deltaxflux/fluxion#322]
### Which version of fluxion are you using?
<???>

### What distribution of Linux (including the version) are you running it on?
<???>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<???>

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
<???>

### General description of your issue along with the steps to reproduce it
<???>

**Comment by marsalansiddiqui** [comment]
- [ ] login to your github
- [ ] - visit: https://github.com/deltaxflux/fluxion
- [ ] click on fork

**Comment by mistyez** [comment]
Thank You sir! @marsalansiddiqui
