### ISSUE TITLE
Only one question

### ISSUE THREAD

**Issue by YouGamePlayHD** [deltaxflux/fluxion#323]
Hi,
I got a little question: Can you also connect to the Fake AP Login Site on a PC (not just on a mobile)? Love this program and I use it alot. It's a lot more likely that a victim (I just try on my own network) is using the PC instead of a mobile. Keep up the great work 👍   
As this is not an issue, I don't need to submit all the information, I think.

**Comment by marsalansiddiqui** [comment]
yes via wi-fi

**Comment by YouGamePlayHD** [comment]
So I click on the Fake-AP and then go to any page and it should work?
