### ISSUE TITLE
Cannot access /sys/class/ieee80211/ such file or directory not found

### ISSUE THREAD

**Issue by Hoanghovuong** [deltaxflux/fluxion#324]
### Which version of fluxion are you using?
<???> the defaulf download fluxion-master.zip 

### What distribution of Linux (including the version) are you running it on?
<???>kali linux 2016.2 i386
### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<???>Qualcomm Atheros AR9002WB-1 NG 
### Which is the driver for it?
<???> driver from Qualcomm Atheros
 klfltdev.sys
athr.sys
vwifibus.sys
### Does it support injection ( output of aireplay-ng -9)
<???> no

### General description of your issue along with the steps to reproduce it
<???>
I can surf the internet via built-in firefox in kali linux but when i tried: airmon -ng
it showed:
cannot access /sys/class/ieee80211/ such file or directory not found
no wlan showed in the interface
how can I turn on monitor mode Wlan0?

**Comment by Hoanghovuong** [comment]
By the way, I'm using kali linux on VMware workstation 10

**Comment by strasharo** [comment]
If your adapter doesn't support injection, then it will not work with fluxion.
