### ISSUE TITLE
I'm new to this and would like to know what is wrong.

### ISSUE THREAD

**Issue by JohnnDoe** [deltaxflux/fluxion#326]
### Which version of fluxion are you using?
Fluxion 0.23 (rev 106)

### What distribution of Linux (including the version) are you running it on?
I am using VM
OS selected: Linux 2.6/3.x/4.x 64 bit
ISO used: kali-linux-2016.1-amd64

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

LB-Link 

Chipset: RaLink Technology, Corp. MT7601U

### Which is the driver for it?

mt7601u

### Does it support injection ( output of aireplay-ng -9)
 Yep. Injection is working !

### General description of your issue along with the steps to reproduce it
I run a FakeAP atk, the four windows pop-up, no error in them. BUT when I check my wifi both in phone and laptop there was NO FakeAP  shown in the wifi list.

**Comment by marsalansiddiqui** [comment]
use external wifi adapter like tp-link tl-wn722n or alfa

**Comment by marsalansiddiqui** [comment]
antena gain size ? (dbm or dbi), if signal is not the issue check again or try another adapter.

**Comment by JohnnDoe** [comment]
This is the specifications of LB-Link:
Reciever Sensitivity: 1M---95 dbm @8% PER   ------>     135M---70dbm @10% PER
Wireless Transmit Power: 17 dbm(MAX)

**Comment by marsalansiddiqui** [comment]
Did everything installed properly when you run ./Installer.sh ? or everything is installed running ./fluxion ?

**Comment by JohnnDoe** [comment]
I am testing my own WIFI, was able to get handshake, was able to kick my android phone everytime it tries to connect, the only missing was the FakeAP which is not showing in the list. Both my pocketwifi(AP) and my phone is close to my laptop which run the fluxion through vm

**Comment by JohnnDoe** [comment]
nope. I manually use apt-get for php5,dhcp,hostppd,lighttpd

**Comment by JohnnDoe** [comment]
Do you think the problem is on fluxion? because I can manually create AP by using airbase

**Comment by marsalansiddiqui** [comment]
maybe, because when installing fluxion it will configure every app according to it so you installed manually there is some chances. Remove every app then run installer.
Remove and purge Kali-Menu:
apt-get remove --purge kali-menu && apt-get clean
Remove local applications in your profile:
rm -rf .local/share/applications
Remove Kali Menus from .config:
rm -rf .config/menus
Reboot your machine:
reboot
Reinstall Kali-Menu:
apt-get install kali-menu -y
If this doesn’t solve the menu problem, only then move to next step.
Reinstall Kali-linux-full:
apt-get install kali-linux-full -y

**Comment by JohnnDoe** [comment]
If im going to reinstall kali do I need to do this first: _apt-get install kali-linux-full -y_ ? before cloning fluxion?

**Comment by JohnnDoe** [comment]
i reinstall kali-linux , clone fluxion, run ./Installer.sh then stop with this specific 4:
Dhcpd.................Installing
Hostapd.............Installing
Lighttpd..............Installing
Php-cgi.................Installing
root@congroo:~/fluxion#




what should I do

**Comment by deltaxflux** [comment]
Well I double check it again and I can't reproduce your issue. Please note that the installing can take a while.

**Comment by whowhere** [comment]
JohnnDoe
please try
# bash Installer.sh

as it behaviour may differ from
# ./Installer.sh

At least for me I'm only able to get the installer windows open using bash
