### ISSUE TITLE
EDIT: How to run fake login page on a PC?

### ISSUE THREAD

**Issue by YouGamePlayHD** [deltaxflux/fluxion#327]
### Which version of fluxion are you using?
0.23 rev 106

### What distribution of Linux (including the version) are you running it on?
Kali GNU/Linux Rolling 64-bit (2016.2)

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Realtek Semiconductor Corp. RTL8187

### Which is the driver for it?
rtl8187

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
This is the same question, but this time I provide the information: 
In my previous ticket I asked if it's possible to access login page from a PC, too. I tried and I only get "no internet connection" error. No page. 
EDIT: I get all DNS Spoof things, my computer name and everything, but when I go e.g. to twitter.com, it loads infinitely long without showing up login page.

**Comment by deltaxflux** [comment]
Try to erase your cach. Please note that only http sites are suitable for this attack method. Here is a new instruction

**Comment by YouGamePlayHD** [comment]
It does work now if I set in the local IP, but not when I enter e.g http://www.cybersource.com.

**Comment by deltaxflux** [comment]
Doesn't effect you,  I thought you want to add login pages but as I noticed you don't want to add them

**Comment by YouGamePlayHD** [comment]
Sould it take like about 20 seconds to load up the login page on mobile or is this a speed issue?

**Comment by YouGamePlayHD** [comment]
Issue is fixed, thank you for your support.
