### ISSUE TITLE
retro compatibility 

### ISSUE THREAD

**Issue by Quest33** [deltaxflux/fluxion#33]
Hello! 

This is not an 'issue' but a request to make fluxion compatible with KaliLinux 1.1.0a (mon0). 

Here is the index of KL ISOs if someone is interested in making this happen for those of us who will not use the latest KL/Aircrack-ng. http://kambing.ui.ac.id/iso/kali/ 

Or if one of the Devs can explain to me what to modify in the code to make it work with KL1, I'll do it myself and upload it.

**Comment by deltaxflux** [comment]
Try Flux: https://github.com/deltaxflux/fluxion/blob/master/old/version.1/flux-old
You must look at the airmon-ng part
