### ISSUE TITLE
Mdk3 dosen't do enything

### ISSUE THREAD

**Issue by VasyD** [deltaxflux/fluxion#331]
### Which version of fluxion are you using?
0.23 108

### What distribution of Linux (including the version) are you running it on?
Kali linux 2016 . 2   4.8.0

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
#1 Internal                      chipset RTL8821AE
#2 afla AWUS036NHA chipset AR9271
#3 afla AWUS036H       chipset RTL8187

### Which is the driver for it?
#1 rtl8821ae
#2 ath9k_htc
#3 rtl8187

### Does it support injection ( output of aireplay-ng -9)
all 3 yes

### General description of your issue along with the steps to reproduce it
Mdk3 dosent work, i can get handshake with aircrack. And after i select web page it automatic goes in mdk3 i can't select aircrack 
Mdk3 terminal : Periodically re-reading blacklist/whitelist every 3 seconds. 
That's it one line nothing else.

**Comment by strasharo** [comment]
mdk3 is an external product and it's not being developed by the fluxion team. If you spot any issues with it feel free to contact the mdk3 developers.

**Comment by gfournier21** [comment]
Same problem here. Did you find a solution?

**Comment by VasyD** [comment]
No, i use aireplay-ng in a separate window, ps please don't rely on me, i'm a total newbie 2 weeks in linux .. so i just work around the issue, i lack the knowhow to solve problems

**Comment by gfournier21** [comment]
I did that very same thing, but I would need an extra mon interface for that.

**Comment by VasyD** [comment]
I'm lucky .. my laptops wifi supports injection plus i have 4 capable usb adapters capable .. i'm sorry

**Comment by strasharo** [comment]
In order to have mdk3 working you must be able to receive the packets sent by the clients to the access point. The difference between it and aireplay is that aireplay is sending them blindly without relying on traffic being observed.

**Comment by VasyD** [comment]
I tried with my phone and router.. so it didn't deauth me, that was my problem ...it's true if i'm not on the ap and try to connect it won't let me ..but it dosn't kick me of of my ap if i'm already connected
