### ISSUE TITLE
mon0, cut: invalid field value ‘$[12+2]’ Try 'cut --help' for more information.

### ISSUE THREAD

**Issue by BlackVoidMIke** [deltaxflux/fluxion#332]
### Which version of fluxion are you using?
108

### What distribution of Linux (including the version) are you running it on?
Kali GNU/Linux Rolling 64-bit (GNOME Version 3.22.2)

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Intel Corporation Centrino Wireless-N 1000 [Condor Peak]

### Which is the driver for it?
wlan0

### Does it support injection ( output of aireplay-ng -9)
Yes:
`04:10:50  Trying broadcast probe requests...
04:10:52  No Answer...
04:10:52  Found 2 APs

04:10:52  Trying directed probe requests...
04:10:52  CENSORED
04:10:53  Ping (min/avg/max): 1.394ms/27.588ms/118.046ms Power: -57.40
04:10:53  30/30: 100%

04:10:53  Injection is working!

04:10:53  CENSORED
04:10:54  Ping (min/avg/max): 1.445ms/10.014ms/26.571ms Power: -82.22
04:10:54  23/30:  76%
`

### General description of your issue along with the steps to reproduce it
upon choosing language,  I get the following errors: 
mon0, cut: invalid field value ‘$[12+2]’
Try 'cut --help' for more information.
cut: invalid field value ‘$[12+2]’
Try 'cut --help' for more information.
cut: invalid field value ‘$[12+2]’
Try 'cut --help' for more information.

**Comment by deltaxflux** [comment]
Cut is very susceptible for breaks.  Can you give me the output of the csv file inside the tmp folder

**Comment by BlackVoidMIke** [comment]
My folder is empty, the fluxion one. Maybe because it doesn't completely crash? but I'm concerned about it. (Probably wouldn't be there if it had no use.)

**Comment by deltaxflux** [comment]
While running the program otherwise Fluxion will delete all files

**Comment by BlackVoidMIke** [comment]
@deltaxflux sent you an email.

**Comment by deltaxflux** [comment]
Answered

**Comment by BlackVoidMIke** [comment]
I still got no response, may you please reply to my email?

**Comment by deltaxflux** [comment]
Now I have time to take a look at this, was pretty bussy

**Comment by strasharo** [comment]
Are you able to enable monitoring on that particular interface using the bundled airmon script manually?

**Comment by deltaxflux** [comment]
@strasharo he is. He even got a dump file. I only take a look at these
