### ISSUE TITLE
Enhancement: Automatic Channel change.

### ISSUE THREAD

**Issue by nkp002** [deltaxflux/fluxion#333]
# **_Enhancement_**
### Which version of fluxion are you using?
<0.23> rev 108

### What distribution of Linux (including the version) are you running it on?
<Kali linux rolling 2016.1>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<TP link tl-wn722n usb wireless adapter, external, working fine>

### Which is the driver for it?
Atheros firmware

### Does it support injection ( output of aireplay-ng -9)
Yes injection is working

### <Enhancement: Automatic Channel change. >
_On restart real ap if its channel changes, fake ap channel do not change.
So, at that condition mdk3 also fails and do not deauthenticate/dissociate clients.
Therefore, I want to suggest an enhancement that, (if possible according to me):-_

1. Since real ap and fake ap both are on the same channel, it is possible to monitor real ap with its bssid.

2.-i) When real ap shut down (If beacons stops coming from real ap), it should stop fake ap and also stop      monitoring real ap.
    ii) And now again start monitoring real ap on all channels.

3. If ap starts, we will get its channel and we can again starts fake ap on that channel.

4. Therefore, mdk3 also works

**Comment by strasharo** [comment]
https://github.com/deltaxflux/fluxion/issues/89
