### ISSUE TITLE
Add Ziggo ISP [NL]

### ISSUE THREAD

**Issue by whowhere** [deltaxflux/fluxion#334]
Hi Deltaflux,

I'd like to add a portal to your application for the Dutch Wi-Fi piggyback riders around, or those who just visit the NL and need some ;-)
It looks completely legit as the original page.

Will be adding for few more ISP's in NL as well ;-)

I really like your application it works great!
add for position: 33 or any other you like yourself ofcourse :-) :
```                        echo -e "      "$red"["$yellow"$n"$red"]"$transparent" Ziggo       [NL]";n=` expr $n + 1```
Please mind that it's missing the final ` up here, bit annoying that text between it is considered a code -.-

```
elif [ "$fluxass" = "33" ]; then
                                ZIGGO_NL
                                break

```

and... wouldn't you just use:

```
#Conten interface web
function ZIGGO_NL {
mkdir $DUMP_PATH/data &>$flux_output_device
        cp  $WORK_DIR/Sites/ZIGGO_NL/* $DUMP_PATH/data
}
```

See the files here:
https://file.town/download/efg5lkpgrulmcn7bo7asjt72j

Scan them or whatever you want, please note this zip package will be gone after 30 days.

I don't know how to create a pull request properly I'm kind a new on github.

Have fun guys!
[ZIGGO_NL.zip](https://github.com/deltaxflux/fluxion/files/679189/ZIGGO_NL.zip)

Ow you can upload here as well :dagger: 
p.s. there are some typo's in the script but.. i'm no the grammer police :D

**Comment by strasharo** [comment]
Have you checked if your template works at all prior submitting it?

**Comment by whowhere** [comment]
Yea ofcourse it works.... I'm using it myself ye, got all ziggo neighbours around me
except the cp * command, as it's just an idea
deltax knows the best way to implement it
Have you checked it at all prior commenting on it?

**Comment by strasharo** [comment]
Yes, the Herstellen button does nothing.

**Comment by dnsBlah** [comment]
Strasharo,

my apologies, I still had original's .js file in cache.

Please put `document.getElementById("form1").submit();` within ' onclick="" in index.html and the error.html

**Comment by strasharo** [comment]
Updated, thank you.
