### ISSUE TITLE
after catching it say the handshake is corrupted/  

### ISSUE THREAD

**Issue by tjnapster555** [deltaxflux/fluxion#336]
### Which version of fluxion are you using?
0.23 rev 111

### What distribution of Linux (including the version) are you running it on?
wifislax-4-12

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
tp-link  TL-WN7200ND  Ralink RT3070

### Which is the driver for it?
5.1.22.0 from official tp link page

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
lang 1
all channel search
then stop the search by ctrl+c
then select network 
then fake ap
then enter
then aircrack-ng
then 1 deauth all
then it capture the wpa handshake 
but when i click to check handshake it keep saying its corrupted

even if i use deauth using mdk3 option

**Comment by strasharo** [comment]
Use aircrack-ng to verify the handshake instead of pyrit. aircrack is less restrictive.
