### ISSUE TITLE
There are no wireless cards, quit.

### ISSUE THREAD

**Issue by tanujboy** [deltaxflux/fluxion#337]
### Which version of fluxion are you using?
FLUX 0.23 (rev.  112)

### What distribution of Linux (including the version) are you running it on?
Kali Linux 2016.2 with kernel version 4.8.0-kali2-amd64

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TP-LINK TL-WN823N (EU) V.2.0, Chipset: RTL8192EU

### Which is the driver for it?
https://github.com/Mange/rtl8192eu-linux-driver

### Does it support injection ( output of aireplay-ng -9)
root@kali:~# sudo aireplay-ng -9 wlan0
ioctl(SIOCSIWMODE) failed: Invalid argument
ioctl(SIOCSIWMODE) failed: Invalid argument
Error setting monitor mode on wlan0
root@kali:~# 

### General description of your issue along with the steps to reproduce it
I cannot get Fluxion working. It just prompts "There are no wireless cards, quit."

**Comment by whowhere** [comment]
Seems like it does not support monitor mode and/or injection.
These are required for intercepting handshake while deauthing clients on the target

**Comment by whowhere** [comment]
For myself I'm using TP-LINK WN722N for 2.4Ghz WiFi
Works out of the box on Kali as well

**Comment by strasharo** [comment]
Your wireless adapter is incompatible.
