### ISSUE TITLE
Single Terminal Window Request

### ISSUE THREAD

**Issue by BustedSec** [deltaxflux/fluxion#339]
Is there a way to get this to run in a single terminal session (like over SSH) without the need to pop up other terminals? perhaps using tmux or some other terminal multiplexer? would like to use this on nethunter as well but the need to vnc into the box to get the script to run is annoying. would like to add this script to my attack box as a well but it's normally accessed over ssh.

**Comment by cyrus104** [comment]
This has been asked for a couple of times to allow it to run on embedded devices like a Pineapple or Nethunter Phone. The devs have stated that they will work on it but are unable to provide a timeline right now.

**Comment by strasharo** [comment]
https://github.com/deltaxflux/fluxion/issues/22
