### ISSUE TITLE
intento de ayudar a cr

### ISSUE THREAD

**Issue by dynyly** [deltaxflux/fluxion#34]

**Comment by dynyly** [comment]
salu2     1 perdonad hablo en otro idioma visto las mejoras hechas falla creacion de interfaces  adjunto ejemplo para que lo vean funciona genera y manda index de manera autogenerada por el script  tengo varias ideas que me funcionan en mi version de dar soporte https pero en su version no hay manera por mas que peleo me gustaria que comentaran ...si quieren tambien les paso la creacion de certificados ssl y incluir a lighttp dejo ejemplo de como me funciona la generacion de index o interfaces                                                                                                                             ############################################# < ATAQUE > ############################################ 
 
# Select web interface that will be used
function webinterface {
	
	while true; do
		conditional_clear
		mostrarheader
		
		infoap
		echo
		echo "Seleciona  Interface"
		echo
		
		echo -e "$blue""      1)"$transparent" Elegir una interfaz"
		echo -e "$blue""      2)"$transparent" \e[1;31mExit"$transparent""
		
		echo
		echo -n "#? "
		read yn
		case $yn in
		1 ) matartodo; Menu; break;;
		2 ) matartodo; exitmode; break;;
		esac
	done
}

		 function Menu {
			while true; do

				mostrarheader
		
				echo "Seleciona una interfaz"
				echo "                                       "
				      echo -e "$blue""      1)"$transparent" Ver todas interfaces disponibles" 
				      
				      echo -e "$blue""      2)"$transparent" \e[1;31mExit"$transparent""
					echo " "
				echo -n '      #> '
				read yn
				case $yn in
				1 ) matartodo; ConnectionRESET; selection; break;;
				
				2 ) matartodo; exitmode; break;;
				* ) echo "Unknown option. Choose again"; conditional_clear ;;
			esac
		done
	}


	function ConnectionRESET {

		while true; do 
			conditional_clear
			mostrarheader
			

			infoap
			echo
			echo "SELECCIONA "
			echo
			
			echo -e "$blue""1)"$transparent" English     [ENG]NEUTRA"
			echo -e "$blue""2)"$transparent" Spanish     [ESP]NEUTRA"
			echo -e "$blue""3)"$transparent" Italian     [IT]NEUTRA"
			echo -e "$blue""4)"$transparent" French      [FR]NEUTRA"
			echo -e "$blue""5)"$transparent" Portuguese  [POR]NEUTRA"
			echo -e "$blue""6)"$transparent" German      [GER]NEUTRA"
			echo -e "$blue""7)"$transparent" LIVE-BOX"
			echo -e "$blue""8)"$transparent" Live"
			echo -e "$blue""9)"$transparent" \e[1;31mBack"$transparent""
			echo 
			echo -n "#? "
			read fluxass
			language=${webinterfaceslenguage[$line]}
			
			if [ "$fluxass" = "1" ]; then
				DIALOG_WEB_ERROR=$DIALOG_WEB_ERROR_ENG
				DIALOG_WEB_INFO=$DIALOG_WEB_INFO_ENG
				DIALOG_WEB_INPUT=$DIALOG_WEB_INPUT_ENG
				DIALOG_WEB_OK=$DIALOG_WEB_OK_ENG
				DIALOG_WEB_SUBMIT=$DIALOG_WEB_SUBMIT_ENG
				DIALOG_WEB_BACK=$DIALOG_WEB_BACK_ENG
				DIALOG_WEB_LENGHT_MIN=$DIALOG_WEB_LENGHT_MIN_ENG
				DIALOG_WEB_LENGHT_MAX=$DIALOG_WEB_LENGHT_MAX_ENG
				NEUTRA
				break

				

			elif [ "$fluxass" = "2" ]; then
				DIALOG_WEB_ERROR=$DIALOG_WEB_ERROR_ESP
				DIALOG_WEB_INFO=$DIALOG_WEB_INFO_ESP
				DIALOG_WEB_INPUT=$DIALOG_WEB_INPUT_ESP
				DIALOG_WEB_OK=$DIALOG_WEB_OK_ESP
				DIALOG_WEB_SUBMIT=$DIALOG_WEB_SUBMIT_ESP
				DIALOG_WEB_BACK=$DIALOG_WEB_BACK_ESP
				DIALOG_WEB_LENGHT_MIN=$DIALOG_WEB_LENGHT_MIN_ESP
				DIALOG_WEB_LENGHT_MAX=$DIALOG_WEB_LENGHT_MAX_ESP
				NEUTRA
				break
			elif [ "$fluxass" = "3" ]; then
				DIALOG_WEB_ERROR=$DIALOG_WEB_ERROR_IT
				DIALOG_WEB_INFO=$DIALOG_WEB_INFO_IT
				DIALOG_WEB_INPUT=$DIALOG_WEB_INPUT_IT
				DIALOG_WEB_OK=$DIALOG_WEB_OK_IT
				DIALOG_WEB_SUBMIT=$DIALOG_WEB_SUBMIT_IT
				DIALOG_WEB_BACK=$DIALOG_WEB_BACK_IT
				DIALOG_WEB_LENGHT_MIN=$DIALOG_WEB_LENGHT_MIN_IT
				DIALOG_WEB_LENGHT_MAX=$DIALOG_WEB_LENGHT_MAX_IT
				NEUTRA
				break
			elif [ "$fluxass" = "4" ]; then
				DIALOG_WEB_ERROR=$DIALOG_WEB_ERROR_FR
				DIALOG_WEB_INFO=$DIALOG_WEB_INFO_FR
				DIALOG_WEB_INPUT=$DIALOG_WEB_INPUT_FR
				DIALOG_WEB_OK=$DIALOG_WEB_OK_FR
				DIALOG_WEB_SUBMIT=$DIALOG_WEB_SUBMIT_FR
				DIALOG_WEB_BACK=$DIALOG_WEB_BACK_FR
				DIALOG_WEB_LENGHT_MIN=$DIALOG_WEB_LENGHT_MIN_FR
				DIALOG_WEB_LENGHT_MAX=$DIALOG_WEB_LENGHT_MAX_FR
				NEUTRA
				break
			elif [ "$fluxass" = "5" ]; then
				DIALOG_WEB_ERROR=$DIALOG_WEB_ERROR_POR
				DIALOG_WEB_INFO=$DIALOG_WEB_INFO_POR
				DIALOG_WEB_INPUT=$DIALOG_WEB_INPUT_POR
				DIALOG_WEB_OK=$DIALOG_WEB_OK_POR
				DIALOG_WEB_SUBMIT=$DIALOG_WEB_SUBMIT_POR
				DIALOG_WEB_BACK=$DIALOG_WEB_BACK_POR
				DIALOG_WEB_LENGHT_MIN=$DIALOG_WEB_LENGHT_MIN_POR
				DIALOG_WEB_LENGHT_MAX=$DIALOG_WEB_LENGHT_MAX_POR
				NEUTRA
				break

				elif [ "$fluxass" = "6" ]; then
				DIALOG_WEB_ERROR=$DIALOG_WEB_ERROR_GER
				DIALOG_WEB_INFO=$DIALOG_WEB_INFO_GER
				DIALOG_WEB_INPUT=$DIALOG_WEB_INPUT_GER
				DIALOG_WEB_OK=$DIALOG_WEB_OK_GER
				DIALOG_WEB_SUBMIT=$DIALOG_WEB_SUBMIT_GER
				DIALOG_WEB_BACK=$DIALOG_WEB_BACK_GER
				DIALOG_WEB_LENGHT_MIN=$DIALOG_WEB_LENGHT_MIN_GER
				DIALOG_WEB_LENGHT_MAX=$DIALOG_WEB_LENGHT_MAX_GER
				NEUTRA
				break
				
			elif [ "$fluxass" = "7" ]; then
			        MI
			        break
			        
			elif [ "$fluxass" = "8" ]; then
			        LIVE
			        break
			
			elif [ "$fluxass" = "9" ]; then
				continue
			fi
		
	done
	preattack
	attack
}


-------------------------------------------------------------------------------------------------------

######################################### < INTERFACE WEB > ########################################



# Crea contenido de la iface Mi interfaz
function MI {

mkdir $DUMP_PATH/data &>$linset_output_device

function interfaz {
echo "---TODO BASE64-----" | base64 -d >$DUMP_PATH/file.zip
	
	unzip $DUMP_PATH/file.zip -d $DUMP_PATH/data &>$linset_output_device
	rm $DUMP_PATH/file.zip &>$linset_output_device
	}
	interfaz
	}                                                                                                                                                                      si quieren les pasaria mod creada para ver mas profundamente

**Comment by strasharo** [comment]
Hello. If you want to contribute some feature, feel free to create a pull request with your suggestion. It's a little bit hard to understand your point in this form. We'll have a look at it and let you know if it's okay for us. Thank you.

**Comment by dynyly** [comment]
salu2
I have shown how do I get so self-generated index put video because the language barrier the index seems stuck some are bad because they have no image logo inside I have good html files but leave Spanish video

https://www.youtube.com/watch?v=Pbkm_VljLUc&feature=youtu.be

You can also make a cp
