### ISSUE TITLE
Can't connect to the fake AP

### ISSUE THREAD

**Issue by jeff512** [deltaxflux/fluxion#340]
### Which version of fluxion are you using?
0.23 rev 106

### What distribution of Linux (including the version) are you running it on?
Kali GNU/Linux Rolling 64-bit (2016.2)

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Realtek Semiconductor Corp. RTL8187
### Which is the driver for it?
rtl8187

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
The problem is when i got handshake, the fake AP appears, when i connect to fake AP it will automatically disconnect

**Comment by strasharo** [comment]
Since rtl8187 is not compatible with hostapd, the fake AP with that chipset is explicitly created using airbase-ng. If you're experiencing issues with it, feel free to raise a ticket to the aircrack-ng team at https://github.com/aircrack-ng/aircrack-ng/issues
