### ISSUE TITLE
Fake AP don't works

### ISSUE THREAD

**Issue by checcoux** [deltaxflux/fluxion#341]
### Which version of fluxion are you using?
0.23 rev 116

### What distribution of Linux (including the version) are you running it on?
Backbox 4.7 (based on ubuntu 16.04)
lighttpd 1.4.35 (APR 18 2016)

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Intel wifi link 5100

### Which is the driver for it?
iwlwifi iwldvm

### Does it support injection ( output of aireplay-ng -9)
00:48:43  Trying broadcast probe requests...
00:48:45  No Answer...
00:48:45  Found 1 AP

00:48:45  Trying directed probe requests...
00:48:45  C4:6E:1F:6E:81:7A - channel: 40 - 'uxnetwork 5 GHz'
00:48:51   0/30:   0%

### General description of your issue along with the steps to reproduce it
Testing fluxion for the first time, everything was going ok untill i started the fake web page. Indeed no fake ap was created.
![istantanea_2017-01-06_00-57-10](https://cloud.githubusercontent.com/assets/15678527/21702406/77f5526a-d3ab-11e6-8dd2-6b88ff3d6fa4.png)

**Comment by deltaxflux** [comment]
Well your internal wireless card doesn't support master mode
