### ISSUE TITLE
Fluxion not installing

### ISSUE THREAD

**Issue by Kronasamu** [deltaxflux/fluxion#342]
### Which version of fluxion are you using?
Fluxion 2.3

### What distribution of Linux (including the version) are you running it on?
Kali Rolling

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TP-Link WN722N
### Which is the driver for it?
?

### Does it support injection ( output of aireplay-ng -9)
n/a

### General description of your issue along with the steps to reproduce it
fluxion fails to install the Dhcpd, Hostapd Lighttpd and Php-cgi. a popup installer window will show up briefly (less than a second) then close and then the screen will display these three items as "Installing..." this is after i followed all the instructions on the wiki step by step. i belive it is unable to locate the packages for the install

**Comment by Kronasamu** [comment]
what?

**Comment by deltaxflux** [comment]
The missing packages?

**Comment by Kronasamu** [comment]
I still dont understand
