### ISSUE TITLE
Fake AP won't accept correct WIFI password

### ISSUE THREAD

**Issue by dchero** [deltaxflux/fluxion#343]
### Which version of fluxion are you using?

<Fluxion 0.23 rev.44> 

### What distribution of Linux (including the version) are you running it on?

<Kali linux 64 bit version 2016.2>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

<External Asus nano usb wireless adapter>

### Which is the driver for it?
<for VMware purposes>

### Does it support injection ( output of aireplay-ng -9)

<Yes>

### General description of your issue along with the steps to reproduce it

<Hi team, i successfully installed fluxion on my Vmare kali linux all functions are installed and working fine however on the fake log in web page (victim page), when i enter the wep or wifi password it will not go through and accept the correct wep password it will generate web page error or host unable to handle the process "http error 500"  > please help. Thanks team

**Comment by deltaxflux** [comment]
are there attemps in the pwlog folder?

**Comment by dchero** [comment]
Let me check. Thanks for the response

**Comment by dchero** [comment]
I already checked the folder and there's no password attempts. I've cleared browsers cache as well still no avail. Is there any problem with ligthttpd version?

**Comment by dchero** [comment]
I already checked the folder and there's no password attempts. I've
cleared browsers cache as well still no avail. Is there any problem with
ligthttpd version?
