### ISSUE TITLE
Fake ap not showing

### ISSUE THREAD

**Issue by michael86** [deltaxflux/fluxion#344]
### Which version of fluxion are you using?
flux 0.23 rev 116

### What distribution of Linux (including the version) are you running it on?
4.8.0-kali2-amd64

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
alfa AWUS051NH 

### Which is the driver for it?
rt2800usb
### Does it support injection ( output of aireplay-ng -9)
yes, packet injection is fine. 

3:24:58  Trying broadcast probe requests...
13:24:58  Injection is working!
13:24:59  Found 8 APs

### General description of your issue along with the steps to reproduce it
fluxion finds my router, deauths all devices and grabs the handshake. I try to set up the web interface attack using netgear english. 5 terminals pop up, one says that the AP has been started and then it just hangs there doing nothing. It doesn't start to deauth or anything else. When I scan for my fake ap via mobile (android) and my laptop, it only shows my real AP with no fake in site.

**Comment by michael86** [comment]
I've just tried creating a quick AP with airbase and run airodump to see if it was up. I could detect it on the same device but again no ap showing on other devices so guessing it may be something to do with my card instead of fluxion. Close this issue if you want.

**Comment by Vigilence** [comment]
What device are you using to test the fake AP?  Sometimes even though the fake AP is created it may not show up in the wireless list right away.  Try turning off wifi and turning it back on.  My card has the same chip and I now it supports fluxion fine.

**Comment by michael86** [comment]
I'm using my desktop, running windows 10, my htc one and my test machine running windows xp. The terminal that shows the clients connect increments the time, last night I left it running for around 10 mins just to ensure my kali machine wasn't taking it's time to start a process. Still no AP showed.. 

I'm farely new to kali and linux as a whole but have a basic understanding of the commands and how it all works. From what I've read up on, the MITM requires setting up ip tables? Does Fluxion handle this process or do I need to do that prior to running fluxion?

**Comment by michael86** [comment]
Okay so I just tried it again and the fake ap appeared on my windows 10 machine but not on my htc (android)?? No deauth attack was launched though so my computer was able to connect to the real router without a issue. 

I manually tried to connect to the fake ap which showed the encryption as open (that meant to happen?) When I tried to go to a website in browser, it pulled up a security risk message, saying that someone may be trying to steal my data (guess I know my browser is secure), when I clicked the return home button it sent me to what is ment to be the secure login page where we sniff the wpa pass from. However, the css/html was all over the place, literally was like a table within a table within a table. If I navigated to 192.168.1.1 though, it showed up perfect, I was able to click the "access" link and fluxion showed me as connected and also incremented the attempt line.

Bit confused as to why it wont show on any mobile device and as to why the deauth attack isn't launch?

**Comment by deltaxflux** [comment]
Well to make some points clear.
@michael86 
That you start with using kali linux is not a shame but I just make some points clear for you.  Deauth attacks can't get effective over a long range. If there are many devices inside the network it can take very long to deauth them all. To solve this you can increase the txpower.  

The encryption is open because fluxion generate a open network because you can't setup the network with encryption without knowing the password and if the victim don't know your password. The idea is that the victim connect to the open network. Bessides that, the errror message is at the moment normal. It pop up if the certificate is not valid signed but I will solve this too. You can click on trust if you want to skip that. If you have attemps you can see these with 
`cat /root/pwlog/[network].txt`
Any questions? Let me know.

**Comment by tuthieu** [comment]
Hi Deltaxflux,can you use Let's Encrypt to get certficate?
