### ISSUE TITLE
Login Page opens fine in browser, but doesn't look correct (issue is for all of the fake login pages)

### ISSUE THREAD

**Issue by Vigilence** [deltaxflux/fluxion#345]
### Which version of fluxion are you using?
Version 116
### What distribution of Linux (including the version) are you running it on?
Parrot OS 3.1.1

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Ralink rt2800

### Which is the driver for it?
Alfa Wireless AWUS036NH

### Does it support injection ( output of aireplay-ng -9)
Yes, and master mode.

###**Browser you are using**
Google Chrome and Firefox

###**OS you are using to test login page (Fake AP)**
Windows 10

### General description of your issue along with the steps to reproduce it
When using fluxion everything works fine.  The issue, at least on my computer (windows 10) is that when I connect to the fake AP the login page loads but it doesn't seem to load the style sheets (css).  This happens to any webpage selected including the default english one.  If I were to type google, then the page loads correctly.

Here is an example of a Xfinity page I am working on. 

**The first image is what shows up when connecting to the AP and the login page opens.**

![screenshot 212](https://cloud.githubusercontent.com/assets/22781570/21725658/64b90fdc-d407-11e6-8bfa-6404bf34225f.png)

**The second image is what the page is supposed to look like.  I can only get this page if I type google.com in the address bar.  Refreshing the page does nothing unless I head to google or another site that doesn't have https protection.**

![screenshot 211](https://cloud.githubusercontent.com/assets/22781570/21725706/9af685de-d407-11e6-8ff5-2d33ad312996.png)

If I were to connect to the AP using my android tablet, the login page loads correctly.

**Comment by deltaxflux** [comment]
Well you forgotte to add the images and the js file in the data folder

**Comment by Vigilence** [comment]
@deltaxflux if that was the case why doesn't the regular English login page load correctly?  I have to type google.com in the search bar for it to load correctly.  

Also, as stated above the webpage load fine only after I type google.com in the search bar.  Meaning that the images and files load fine.

The issue is that the webpage that opens when you connect to the fake AP doesn't load correctly.

![screenshot 215](https://cloud.githubusercontent.com/assets/22781570/21729511/6cbb4ab2-d419-11e6-9825-23dcd21a088d.png)
![screenshot 214](https://cloud.githubusercontent.com/assets/22781570/21729513/6cbde9e8-d419-11e6-9d52-e5448a4bf307.png)
![screenshot 213](https://cloud.githubusercontent.com/assets/22781570/21729512/6cbd510e-d419-11e6-9dfe-334d9732fcc9.png)



Here is what the basic one looks like when the webpage first opens.
![screenshot 216](https://cloud.githubusercontent.com/assets/22781570/21729639/dc19d8f6-d419-11e6-9d1e-fc300e3d85fe.png)


This is what it looks like after typing google.com in the search bar.
![screenshot 217](https://cloud.githubusercontent.com/assets/22781570/21729649/e7f2bf76-d419-11e6-8035-d69a5c6c9a82.png)


Something isn't right and I am trying to pinpoint what the issue is.

**Comment by deltaxflux** [comment]
Erase your cache !

**Comment by Vigilence** [comment]
@deltaxflux Thanks for the suggestion.  I should have mentioned earlier that I do erase the cache and have done so multiple times.  I will be testing a Virtual Machine of Windows 10 with the fake AP to see if I can replicate the results.

If anyone else here has seen this issue before I would to know about it.  I am trying to narrow it down and maybe resolve it.  If resolved I will put the resolution in the tutorial area.

**Comment by John19941216** [comment]
Me too
Firefox-->Inspector Element-->Console     display (**The stylesheet http://google.com/mial/bootstrap.min.css was not loaded because its MIME type, "text/html", is not "text/css".**)

What should I do? Help out!

**Comment by deltaxflux** [comment]
Looks like the site is broken.
