### ISSUE TITLE
Stands on the ssl certificate screen 

### ISSUE THREAD

**Issue by danny6690** [deltaxflux/fluxion#346]
### Which version of fluxion are you using?

0.23 rev 116
### What distribution of Linux (including the version) are you running it on?

kali 2.0

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

TP-Link TL-WN722N Atheros Communications, Inc. AR9271 802.11n

### Which is the driver for it?

ath9k_htc

### Does it support injection ( output of aireplay-ng -9)
Yes,
16:55:09  Trying broadcast probe requests...
16:55:09  Injection is working!

### General description of your issue along with the steps to reproduce it

Hi, 

I open Fluxion, choose my wireless adapter, select a network, select the handshake.
After that, when I press 1 to create a ssl certificate, the screen just stand there and nothing happen.
Even if I press 2 to search a ssl certificate, nothing happen either 

Any idea whats happening?

Thank you for your great work

**Comment by strasharo** [comment]
`export FLUX_DEBUG=1 
`
prior running the script, so you can see verbose output. Other way around would be to execute the script with bash -x ./fluxion

**Comment by deltaxflux** [comment]
Openssl requirement is missing

**Comment by danny6690** [comment]
Output of me trying to install open ssl 

apt-get install openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssl is already the newest version (1.1.0c-2).
openssl set to manually installed.
The following packages were automatically installed and are no longer required:
  espeak-data firebird2.5-common firebird2.5-common-doc gdebi-core gnome-packagekit gnome-packagekit-data hwdata imagemagick-common iproute
  libboost-atomic1.61.0 libboost-chrono1.61.0 libboost-date-time1.61.0 libboost-filesystem1.61.0 libboost-system1.61.0 libboost-thread1.61.0
  libcamel-1.2-57 libchromaprint0 libcrypto++6 libedataserver-1.2-21 libespeak1 libgeos-3.5.0 libglew1.13 libicu55 liblouis10 libmimic0
  libnm-glib-vpn1 libopencv-contrib2.4v5 libopencv-legacy2.4v5 libopencv-ml2.4v5 libosinfo-db libperl5.22 libpoppler61 libprotobuf9v5
  libradare2-0.9.9 libschroedinger-1.0-0 libvpx3 libwildmidi1 libx265-79 linux-headers-4.8.0-kali1-amd64 linux-headers-4.8.0-kali1-common
  python-clamd python-d2to1 python-defusedxml python-ipaddr python-pycryptopp python-pypdf python-soappy python-stopit python-svn python-wstools
Use 'apt autoremove' to remove them.
