### ISSUE TITLE
wifi monitor no result

### ISSUE THREAD

**Issue by scaldstack** [deltaxflux/fluxion#350]
### Which version of fluxion are you using?
0.23 rev 116

### What distribution of Linux (including the version) are you running it on?
Both Ubuntu 16.04 and Kali 2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Intel Corporation Wireless 7265 (rev  59)

### Which is the driver for it?
system inside, seems named iwlwifi?

### Does it support injection ( output of aireplay-ng -9)
No replay interface specified (after run `aireplay-ng -9` in terminal)

### General description of your issue along with the steps to reproduce it
1. terminal run `./fluxion` in fluxion dir.
2. output check result, all ok.
3. after notice, will let me choose language
4. let me choose the channal, I choose **all**
5. jump a white window ,title WIFI Monitor, begin scan wifi client. The **CH** will keep change the number in the window, but no result
6. `ctrl + c` stop, will catch no client. 
7. exit fluxion, just run `airmon-ng start wlan0` and `airodump-ng wlan0mon` in terminal, it will catch all the wifi clinet near my computer.

after test two different machine both in ubuntu 16.04 and kali 2016.2 has the same problem.

**Comment by deltaxflux** [comment]
Well I recommend to buy a external wireless card, it looks like it support monitor mode but I would be compatible with master mode ( AP)
