### ISSUE TITLE
iptables flush

### ISSUE THREAD

**Issue by rad4day** [deltaxflux/fluxion#351]
### Which version of fluxion are you using?
newest of course. Just been looking at the git repo to verfiy the existance of that bug.

### What distribution of Linux (including the version) are you running it on?
ArchLinux - doesn't matter

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
no meaning in providing this information

### Which is the driver for it?
STOP TROLLING ME PLS

### Does it support injection ( output of aireplay-ng -9)
WHY? JUST WHY!

### General description of your issue along with the steps to reproduce it
Well you're flushing the IPtables -> clearing it. This is a big security risk!

Your code: 

        echo -e ""$white"["$red"-"$white"] "$white"$general_exitmode_4"$transparent""
        iptables --flush // NOT COOL, ABSOLUTELY NOT COOL
        iptables --table nat --flush
        iptables --delete-chain // not really cool either
        iptables --table nat --delete-chain

Pls fix it. Thanx :1st_place_medal:

**Comment by deltaxflux** [comment]
Noticed

**Comment by strasharo** [comment]
It's done in order to ensure that the traffic to ports 80 and 443 is being redirected to the captive portal. If you care about the security of that particular system for real, you shouldn't be executing random scripts off the Internet, which require root access.

**Comment by deltaxflux** [comment]
@strasharo @rad4day is a contributor

**Comment by strasharo** [comment]
So what?

**Comment by deltaxflux** [comment]
@strasharo write my an email my tox id has been changed

**Comment by deltaxflux** [comment]
2f8bb4f
