### ISSUE TITLE
Better Arch Linux support

### ISSUE THREAD

**Issue by rudinskizvonimir** [deltaxflux/fluxion#352]
### Which version of fluxion are you using?
0.23

### What distribution of Linux (including the version) are you running it on?
Arch Linux (4.8.13-1-ARCH)

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter

### Which is the driver for it?
rtl8723be

### Does it support injection ( output of aireplay-ng -9)
ioctl(SIOCSIWMODE) failed: Device or resource busy
19:38:40  Trying broadcast probe requests...
19:38:40  Injection is working!
19:38:42  Found 2 APs

### General description of your issue along with the steps to reproduce it
I would like to use this script on Arch Linux but the script says my wireless card is not supported,but when I was using Kali Linux it worked perfectly.
Here is the output:
```
[i] Error: your wireless card  isn't supported  
Do you want exit? [Yes / No]:No
./fluxion: line 1660: [: -le: unary operator expected
cat: /tmp/TMPflux/dump-01.csv: No such file or directory
expr: syntax error
                        WIFI LIST 

 ID      MAC                      CHAN    SECU     PWR   ESSID

grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines:: No such file or directory
grep: ‘/tmp/TMPflux/dump-01.csv’: No such file or directory
 [1]	head: invalid number of lines: ‘/tmp/TMPflux/dump-01.csv’	 	   100%	 

 (*) Active clients

        Select target. For rescan type r
[deltaxflux@fluxion]-[~]

```

**Comment by deltaxflux** [comment]
Well I noticed this problem already.  Is it possible to start xterm terminals with root premissions 
sudo xterm

**Comment by ChrisFernandez** [comment]
+1 also arch user.

**Comment by deltaxflux** [comment]
Can you run a xterm terminal as root?

**Comment by ChrisFernandez** [comment]
I just said +1 to arch support. I am not having the issue with wireless drivers.

**Comment by deltaxflux** [comment]
@ChrisFernandez Well I don't thought that it is a wireless driver issue

**Comment by strasharo** [comment]
Are you able to enable monitoring on that particular interface using the bundled airmon script manually?

**Comment by rad4day** [comment]
Well I'm using arch too. Using iwconfig to set the device up for monitor mode fixed it for me. Just had to do it once.

**Comment by rudinskizvonimir** [comment]
Yeah I can go into monitor mode no problem,but I can't run xterm as root

**Comment by rad4day** [comment]
Which Desktop environment are you using and which version of xterm are you using? This is an already known problem. But we need more data to be able to work on a solution :/

**Comment by rudinskizvonimir** [comment]
I just switched to Linux Mint like hour ago and it works flawlessly. I was using GNOME and for xterm I don't really know.
