### ISSUE TITLE
Cant get WPA pass from "target" PC

### ISSUE THREAD

**Issue by koukoy** [deltaxflux/fluxion#353]
### Which version of fluxion are you using?
0.23

### What distribution of Linux (including the version) are you running it on?
kali-linux-2016.2-amd64  /  kali-linux-light-2016.2-i386  /  wifislax-4-12-final

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
ralink 2573 USB

### Which is the driver for it?
rt73usb

### Does it support injection ( output of aireplay-ng -9)
aireplay-ng -9 mon0
16:45:10  Trying broadcat probe requests...
16:45:10  Injection is working!
16:45:12 Found 5 APs

### General description of your issue along with the steps to reproduce it
everything work fine the page is loaded but i cant get the wpa pass from "target" pc tested on mozilla
password incorect
i tested linset on wifislax and it can verify the pass but it dont support the language that i wana use

**Comment by deltaxflux** [comment]
Are there attempts?  Read the README file

**Comment by koukoy** [comment]
I did every step on readme file. But the problem is when i put the correct pass on login page input and press the button it says wrong pass and again the same loop nothing change

**Comment by deltaxflux** [comment]
Are there Attempts?

**Comment by koukoy** [comment]
kali-linux-light-2016.2-i386

https://s29.postimg.org/o9tdvj1gn/fluxion_fail.png

https://s23.postimg.org/l4b168ql7/fluxion_fail1.png

https://s30.postimg.org/z3o3g1onl/fluxion_fail2.png

**Comment by deltaxflux** [comment]
Cat /root/pwlog/*.txt

**Comment by koukoy** [comment]
worked after 3 ./Installer.sh in a raw the problem was on installetion ty anyway
