### ISSUE TITLE
Clients cannot connect to fakeap - tested on iOS and Android

### ISSUE THREAD

**Issue by wigald** [deltaxflux/fluxion#358]
### Which version of fluxion are you using?
0.23 Rev 117

### What distribution of Linux (including the version) are you running it on?
Debian 8.7

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
ALFA AWUS036H - RTL8187 chipset

### Which is the driver for it?
rtl8187

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
Clients try to connect to the open wifi, but seems to get kicked out immediately. On iOS sometimes it works, on Android it keeps connecting and disconnecting. Tried this on Kali 2 Rolling too with no luck

**Comment by deltaxflux** [comment]
Well is it possible to get more information e.g.

Does it work with the old dhcp client in android ? 

Do you use a vpn on your device ?

Which android version do you use ?

With lighttpd and dhcp server versions do you have ?

**Comment by wigald** [comment]
Hi,

of course is it possible to get more information :)

> Does it work with the old dhcp client in android ?

Dunno what do you mean with "old" DHCP client, do I have a choice on that ?

> Do you use a vpn on your device ?

Nope

> Which android version do you use ?

4.4 and 6.0 - both with same behaviour, iOS runs with newest 10.2

> With lighttpd and dhcp server versions do you have ?

The ones provided by fluxion install script, exactly:

lighttpd: 1.4.35

dhcpd: 4.3.1


I think lighttpd and dhcpd are working well, so if you get a connection dhcpd distributes an IP adress, also the fake site from lighttpd is accessible when you're connected to the fakeap. I tried it even with a laptop, that works well, just got problems with mobile devices.

thanks.

**Comment by deltaxflux** [comment]
Well i never got this particular problem, however you can enable the old dhcp client in the developer options
