### ISSUE TITLE
Login pages do not work

### ISSUE THREAD

**Issue by kand617** [deltaxflux/fluxion#36]
It looks like the login pages option does not work. 

LoginNetgear

Any ideas on how to specify custom login pages?

**Comment by dynyly** [comment]
https://www.youtube.com/watch?v=Pbkm_VljLUc

**Comment by deltaxflux** [comment]
Yeah we hopefully fix this today, may tomorrow

**Comment by dynyly** [comment]
otra manera para no hacer video seria un cp para los  index   si no quieren que de mucho peso el script al meter index en base64 ; 
respecto a los index que tiene fluxion estan mal solo uno esta bien 
algunos index no poseen logo

**Comment by deltaxflux** [comment]
@dynyly is it possible to speak english or other languages else spain ?
If you want to constribute fell free to start a pull request. I now that it is now pretty large (base64 code), may I create some files only for the base64 stuff

**Comment by dynyly** [comment]
I am using translator sometimes does not reflect what I want to convey I would like to discuss ideas I already have a version I made I added https version of fluxion is void to the new sysctl configuration packet forwarding; I also have index.html good addition to more ideas about weight decrease file as base64 I would like to share ideas; but I do not really understand withdrawal request? I could leave code how are my ideas?

**Comment by deltaxflux** [comment]
@dynyly you can send me our ideas to my email adress, if you want to. Great Idea i will look at it if you send my it. For more informations look at my github contact page
