### ISSUE TITLE
Add multiple channels to mdk3 when in hotspot mode.

### ISSUE THREAD

**Issue by abadagada2** [deltaxflux/fluxion#361]
### Which version of fluxion are you using?
I am using fluxion version 118.
### What distribution of Linux (including the version) are you running it on?
I am using the OS Kali Linux 2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
I am using the wireless adapter rt2800usb Ralink Technology, Corp. RT2870/RT3070.

### Which is the driver for it?
This one works natively on Kali Linux without a driver.

### Does it support injection ( output of aireplay-ng -9)
This wireless adapter does support packet injection.

### General description of your issue along with the steps to reproduce it
I would just like to see mdk3 switch channels since most routers do so automatically when there is an interruption.  Another words while it's deauthing the access point to make the user switch to the new access point, allow mdk3 to switch channels so it's more effective.  Instead of just 'mdk3 mon0 -b (access point mac address)' use something like 'mdk3 mon0 (access point mac address) -c 1,6,11'

**Comment by tjnapster555** [comment]
version 118 not working correctly i cant see the security page when user connect to ap

**Comment by deltaxflux** [comment]
@abadagada2 we want a channel lock and @tjnapster555 create a new issue
