### ISSUE TITLE
websites are not working correctly in iphone

### ISSUE THREAD

**Issue by sacredsperm** [deltaxflux/fluxion#362]
### Which version of fluxion are you using?
0.23 rev 118

### What distribution of Linux (including the version) are you running it on?
Linux kali 4.8.0-kali2-amd

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TL-WN821N

### Which is the driver for it?
rtl8192cu

### Does it support injection ( output of aireplay-ng -9)
08:15:06  Trying broadcast probe requests...
08:15:06  Injection is working!
08:15:08  Found 1 AP 

08:15:08  Trying directed probe requests...
08:15:08  08:60:6E:C9:A8:93 - channel: 1 - 'ASUS'
08:15:08  Ping (min/avg/max): 1.742ms/29.708ms/50.006ms Power: -43.07
08:15:08  30/30: 100%

when i try to connect experimental network from iphone while fake ap is active, the html page is looking like below for all websites except neutrals. when the password is entered in the neutral ones, the password page comes again. also, both real and experimental networks are open now, although fluxion is closed.

https://cloud.githubusercontent.com/assets/16742086/19052279/23b65526-8984-11e6-887c-1c37a9473c57.jpg
I took this picture from another issue but the error that occured my iphone like this.

**Comment by tjnapster555** [comment]
does fluxion support dns redirection? mean , if user refresh google.com or facebook.com it take the user to fake wpa page

**Comment by sacredsperm** [comment]
when user try to connect wifi if the user chooses "use without internet" when he taps "cancel" in password page then the user is directed the fake wpa page while browsing the web browser. otherwise, the phone can't connect to the fake network by itself.

http://www.mccsd.net/imageGallery/JHaynia8/IOS/IOS%209%20captive%20portal.JPG 
again, i took this from somewhere else, but the choices in iphone like this.

**Comment by deltaxflux** [comment]
@sacredsperm The mitm does only work on the fake AP. The AP works on ios too, check out the ios issue post
