### ISSUE TITLE
Can't capture handshake automatically (If I select a .cap I captured before it works)

### ISSUE THREAD

**Issue by theoneandonly-vector** [deltaxflux/fluxion#363]
### Which version of fluxion are you using?
FLUXION 0.23 

### What distribution of Linux (including the version) are you running it on?
Linux Debian 4.8.0-kali2-amd64 #1 SMP Debian 4.8.15-1kali1 (2016-12-23) x86_64 GNU/Linux

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Atheros Communications, Inc. AR9271 802.11n

### Which is the driver for it?
ath9k_htc

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
I can't capture any handshake using the automated tool.
I can capture a handshake in the same setup using the commands manually or this wifite-version:
https://github.com/derv82/wifite2

so it works, when I select my pre-captured .cap-file.. but it won't work automatically.

**Comment by deltaxflux** [comment]
So I understand you correctly that you can't use your precaptured handshake?

**Comment by theoneandonly-vector** [comment]
no
I can use my precaptured handshake.
but I can't capture a handshake using fluxion.

Am 22.01.2017 12:01 nachm. schrieb "deltax" <notifications@github.com>:

**Comment by OoImmortaloO** [comment]
I can use my precaptured handshake.<<??
but I can't capture a handshake<<<????

<< you going to make people more confused<<<

How can you did you captured in the first place? 
You can't used "precaptured" when you "CAN'T"  Capture the handshake. You must captured handshake before you have PRECaptured".. <<

please be more detailed. 

I'll quote from my earlier  issed, posted by "Deltaflux"  

<<The handshake get only captured if you reconnect to the same network you listen to. In this case it is clear why you can't capture the hanshake. You can test it if you forgot your 5 ghz network.<<

**Comment by theoneandonly-vector** [comment]
As I already statet in the issue.
I PREcaptured the handshake using wifite from:
https://github.com/derv82/wifite2

Am 22.01.2017 6:20 nachm. schrieb "OoImmortaloO" <notifications@github.com>:

**Comment by OoImmortaloO** [comment]
sorry missed read, But isn't give any error or showing anything, if possible take few screen shot or little more detailed?  as Delta stated on my other issued post, maybe that's the reason?  did it just run and run and no captured handshake after 10+ mins?

**Comment by theoneandonly-vector** [comment]
Update:
It works! But only using deauth all (mdk3).
when I select Deauth all or Deauth target never get a handshake.

Am 22.01.2017 6:33 nachm. schrieb "OoImmortaloO" <notifications@github.com>:
