### ISSUE TITLE
Latest v0.23 rev 118 The script should be executed inside a X (graphical) session.

### ISSUE THREAD

**Issue by JustMev** [deltaxflux/fluxion#366]
I have to set in putty under ssh I have to tick x11 box to run latest fluxion on raspberry pi3 latest kali rolling
prior version 114 or 115 I didn't need to do this procedure via putty

Putty
connections --> ssh --- x11 ---> enbale

log error
--------------------------------------
root@kali:~# cd fluxion
root@kali:~/fluxion# ./fluxion
The script should be executed inside a X (graphical) session.
root@kali:~/fluxion#

**Comment by OoImmortaloO** [comment]
......... <<< do you really need to make 2 topic???

**Comment by JustMev** [comment]
not really thought it would be easier to index for other people who may have similar issue

**Comment by deltaxflux** [comment]
Use vnc

**Comment by JustMev** [comment]
Why you closing the issue without a comment?

**Comment by deltaxflux** [comment]
You miss my comment

**Comment by JustMev** [comment]
I seen vnc , but what about it saying my wifi not compatiable? Why is this issue with 118 now?
