### ISSUE TITLE
rt2800usb rev.0.23 - 118 telling me its not supported when it is suported 

### ISSUE THREAD

**Issue by JustMev** [deltaxflux/fluxion#367]
why was my last issue closed no comment

### Which version of fluxion are you using?
0.23 rev 118

### What distribution of Linux (including the version) are you running it on?
kali linux latest rolling

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

ralink rt2080/3070 rt2800 usb

### Which is the driver for it?

latest

### Does it support injection ( output of aireplay-ng -9)

yes of course

### General description of your issue along with the steps to reproduce it

als can be seen here Crashing with rt2800usb  issue #91
https://github.com/deltaxflux/fluxion/issues/91

it is telling me that wlan0 which is my rt2800 usb is not supported if you read my previous post before closing it

**Comment by OoImmortaloO** [comment]
ralink rt2080/3070 rt2800 usb <<< LOL YOU GOT KNOCK OFF ALFA

Does it support injection ( output of aireplay-ng -9)

yes of course  <<< LOL NO

**Comment by JustMev** [comment]
works with sophron script

**Comment by deltaxflux** [comment]
2 issues with the exact same problem, really?

**Comment by JustMev** [comment]
Sorry meant why you closing this thread without a comment it clearly an issue with latest  fluxion 118, 105worked

**Comment by deltaxflux** [comment]
because you create 2 issues
