### ISSUE TITLE
Fluxion On Kali nethunter Install How to 

### ISSUE THREAD

**Issue by scmdaman786** [deltaxflux/fluxion#369]
### Which version of fluxion are you using?
v(118)
### What distribution of Linux (including the version) are you running it on?
I am running on kali nethunter 

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
tp link w722n
Chipset= Atheros Communications, Inc AR9271
### Which is the driver for it?
it shows like that = ????????

### Does it support injection ( output of aireplay-ng -9)
<???>

### General description of your issue along with the steps to reproduce it
I Installed & ran fluxion on my kali nethunter in GUI mode

then run command ./fluxion to run

select language english 

no wlan showing & no interfaces loading

 thanks 
 plz tell me the steps to run fluxion on kali nethunter

**Comment by deltaxflux** [comment]
Connect your wireless card correctly and check if you see it with airmon
`airmon-ng `

**Comment by scmdaman786** [comment]
i correct it from airmon-ng but no wlan shows

**Comment by deltaxflux** [comment]
Can you explain me what you did?

**Comment by userdsp** [comment]
How to run it in GUI mode?

**Comment by deltaxflux** [comment]
start a vnc session
