### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by dmcxbluecoder** [deltaxflux/fluxion#37]
./fluxion: 52: ./fluxion: Syntax error: "(" unexpected

This happens after using sudo

**Comment by strasharo** [comment]
Just checked it and there's no such error, everything is correct on line 52. Are you running an up to date copy of the script?

**Comment by dmcxbluecoder** [comment]
so it seems that for some strange reason that I do not comprehend it was not running so I went in to the branches section copied the entire develop code and replaced it with the master one and it worked with this       https://raw.githubusercontent.com/deltaxflux/fluxion/develop/fluxion

**Comment by strasharo** [comment]
The development branch is out of date. Please, use the master branch.

**Comment by dmcxbluecoder** [comment]
![screenshot from 2016-05-08 23-57-42](https://cloud.githubusercontent.com/assets/18369901/15106374/bb3e81dc-157d-11e6-8793-70d368c9d0fe.png)

This is what it looks like

**Comment by strasharo** [comment]
Looks like your encoding is not correct. Can you try obtaining the script by using:
git clone https://github.com/deltaxflux/fluxion.git

**Comment by dmcxbluecoder** [comment]
![screenshot from 2016-05-09 00-38-50](https://cloud.githubusercontent.com/assets/18369901/15106470/7036dbac-157e-11e6-98ab-470d51430583.png)

OK I git clone  but...

**Comment by deltaxflux** [comment]
Not confirmed, which kali version do u use ? Do you clone correctly?
1) Delete folder 
$ sudo rm -rf fluxion
2) Clone git again
$ sudo git clone https://www.github.com/deltaxflux/fluxion.git

**Comment by dmcxbluecoder** [comment]
Kali Linux Rolling

**Comment by deltaxflux** [comment]
Confirmed, I found the issue, because there was a space between #!/bin/bash
So it execution with only standard features.

**Comment by Cosmic4x2** [comment]
Does not send password back to fluxion. Aircrack does not start how can I fix this .

Using FLUXION 0.23 

Thx
