### ISSUE TITLE
Fake Login issue 

### ISSUE THREAD

**Issue by kazmanarch** [deltaxflux/fluxion#370]
### Which version of fluxion are you using?

Flux 0.23 (rev 118)

### What distribution of Linux (including the version) are you running it on?

OS: ArchLinux 
Kernel x86_64 Linux 4.8.13-1-ARCH

(Same issue on Kali)

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

Realtek Semiconductor Corp. RTL8187 Wireless Adapter (Kasens G9000)
Work well

### Which is the driver for it?

[xxx@xxx Desktop]$ dmesg | grep usbcore
[    2.255500] usbcore: registered new interface driver usbfs
[    2.255511] usbcore: registered new interface driver hub
[    2.255542] usbcore: registered new device driver usb
[    2.971480] usbcore: registered new interface driver usbhid
[    4.423412] usbcore: registered new interface driver rtsx_usb
[   11.016107] usbcore: registered new interface driver btusb
[   11.025782] usbcore: registered new interface driver uvcvideo
[   11.935686] usbcore: registered new interface driver rtl8187

### Does it support injection ( output of aireplay-ng -9)

[xxx@xxx Desktop]$ sudo aireplay-ng wlp0s20u1 -9
08:25:24  Trying broadcast probe requests...
08:25:24  Injection is working!
08:25:26  Found 4 APs

### General description of your issue along with the steps to reproduce it

I'm French , sorry for my poor english ! 

When i have found handshake , i have a problem with SSL certificate 

Certificate invalid or not present, please choice
                                       
      [1] Create  a SSL certificate
      [2] Search for SSl certificate
      [3] Exit 
 
      #> 

Then type option 1 (create a SSL certificate)

Then don't appears fake login to type the password..

![capture du 2017-01-24 08-51-24](https://cloud.githubusercontent.com/assets/25311520/22238843/8a995c68-e20b-11e6-89ad-17d41f337725.png)

I have same problem on kali

**Comment by deltaxflux** [comment]
Does it appear if you type 192.168.1.1 ?

**Comment by kazmanarch** [comment]
Hi deltaflux, and thank you for response ! 

My phone is now connected to the fake AP 
But , i don't see the fake login page 
If i type 192.168.1.1 : page not found 

You can see on my new screen : FAKEDNS 192.168.1.1 and client online 192.168.1.100 ...

![capture du 2017-01-24 22-53-08](https://cloud.githubusercontent.com/assets/25311520/22270893/b61192f6-e289-11e6-8d67-1a17bb6de42c.png)

**Comment by kazmanarch** [comment]
My problem is solved :)
Ufw was the problem, turn off and fluxion run great.

**Comment by kalienthusiast** [comment]
kazmanarch I am having exactly the same issue with Fluxion. I get the handshakes but I got the same end as yourself. I tried to turn off the Ufw. But am running into problems. Can you please walk me through the commands. Sorry I am a noob. I tried to google this but its not working well for me. thanks a ton.
