### ISSUE TITLE
SSL Certificates ?? 

### ISSUE THREAD

**Issue by diler0000000000** [deltaxflux/fluxion#371]
### Which version of fluxion are you using?
<FLUXION 0.23 ver.118>

### What distribution of Linux (including the version) are you running it on?
<Kali Linux 2016.2-i386 running as Root user>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<Ralink RT2870/3070 rt2800usb>

### Does it support injection ( output of aireplay-ng -9)
<Yes>

### General description of your issue along with the steps to reproduce it
<Hello

I have proble with SSL Certificates, apart from that everything works fine when I get a handshake I get a screen like this 
![screenshot from 2017-01-24 12-51-40](https://cloud.githubusercontent.com/assets/25223677/22248311/e8196fe8-e235-11e6-9ce8-8ffaae08c005.png)

![screenshot from 2017-01-24 12-52-04](https://cloud.githubusercontent.com/assets/25223677/22248322/f67ff156-e235-11e6-8afd-36477541882e.png)
After i press 1 I get this 

![screenshot from 2017-01-24 13-00-26](https://cloud.githubusercontent.com/assets/25223677/22248337/04dddd94-e236-11e6-81af-6eb3a6e93d96.png)

there are no clients at all after even 20minutes waiting what should I do ?
AP works fine I can connect from my phone to it and login page appears but no clients can connect it to it.  It worked only once for me when client could connect to a fake AP but when I get SSL page no one can connect it :(

>

**Comment by deltaxflux** [comment]
**It is luck**. Don't be an evil

**Comment by diler0000000000** [comment]
What should I do with the SSL certificates ? Why does it appear ?
