### ISSUE TITLE
Any way to bypass login?

### ISSUE THREAD

**Issue by thomja** [deltaxflux/fluxion#373]
### Which version of fluxion are you using?
Latest, 0.23

### What distribution of Linux (including the version) are you running it on?
Kali Linux

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

Qualcomm Atheros AR9485

### Which is the driver for it?
No idea, irrelevant
### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it

So everything works great. But I noticed that one of my neighbours cameras connected to the AP. Is there anyway for me to let another client connect to the fake AP, bypass the login and perhaps go to the cameras IPv4 and login?

**Comment by deltaxflux** [comment]
It redirect following traffic:
80 http
443 ssl
So the short answer is that it is possible
