### ISSUE TITLE
Corrupted handshake

### ISSUE THREAD

**Issue by Raphsodyz** [deltaxflux/fluxion#374]
### Which version of fluxion are you using?
<118>

### What distribution of Linux (including the version) are you running it on?
<Kali Linux 32bit 2016.2>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TP-LINK TL-WN722N

### Which is the driver for it?
Idk lol

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
<When im get a wpa handshake file, it is saved at root/handshake/.cap file. Closing and opening fluxion and trying one second attack to the same AP that im have the handshake file the fluxion says that file .cap  is corrupted. How to solve it?>

**Comment by Intek13x** [comment]
Use pyrit option to capture handshake next time..

**Comment by Raphsodyz** [comment]
So, the file is not corrupted? I'm can create the web fake interface with the 'corrupted handshake' that the fluxion says, but, if it's saying for me that the .cap file is corrupted it will work if i'm put correct key?

**Comment by Intek13x** [comment]
That captured handshake is fine, but the problem is with fluxion's handshake verification method.. 
Whenever i capture handshakes with aircrack-ng, most of the times this corrupted handshake problem occurs. 
But handshakes captured by pyrit works fine for me..

P.S.- Yes, that handshake will work on inputing correct key if your handshake was captured properly.

**Comment by Raphsodyz** [comment]
Thanks a lot for ur answer bro, if deltaflux see this topic i'm hope this bug be fixed, thanks all!

**Comment by deltaxflux** [comment]
Yes by default we use pyrit to check the handshake. Try to use pyrit to verify your handshake.
