### ISSUE TITLE
Can't find the Wifi of ZTE

### ISSUE THREAD

**Issue by x-achref-x** [deltaxflux/fluxion#375]
### Which version of fluxion are you using?
0.23 the latest version.

### What distribution of Linux (including the version) are you running it on?
Kali linux 2 latest update

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Qualcom Atheros AR8151 PCI-E Gigabit Ethernet Controller

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
Fluxion run properly but i can't see the wifi point that is created by ZTE router , i don't know the problem because  i can see it in any other device or program in the same kali only in your monitor i can't .

**Comment by deltaxflux** [comment]
Buy a compatible wireless card
