### ISSUE TITLE
Fluxion Crashing on VNC Connection

### ISSUE THREAD

**Issue by defatpm** [deltaxflux/fluxion#376]
### Which version of fluxion are you using?
0.23

### What distribution of Linux (including the version) are you running it on?
kale-rolling
Version=2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Adapter: Panda Wireless PAU09
Chipset: Ralink RT2870/3070

### Which is the driver for it?
Driver=rt2800usb

### Does it support injection ( output of aireplay-ng -9)
"Injection is working!"

### General description of your issue along with the steps to reproduce it
Fluxion crashes when connected via x11vnc. Fluxion works when directly connected. More specifically:
1.   Boot rpi3
2.  SSH into kali via local network (not logged in anywhere else)
3.  Run "x11vnc -guess auth"
4.  Connect client via RealVNC Viewer
5.  cd /Fluxion
6.  Run ./Fluxion
7.   Select language (English)
8.  Select interface (wlan1 Ralink RT2870/3070)
9.  After hitting enter, complete freeze in Kali and have to reboot via unplug power source

**Comment by deltaxflux** [comment]
Try to use keep network command 
export KEEP_NETWORK=1

**Comment by defatpm** [comment]
Thank you. To clarify: run the command and then try Fluxion via VNC again?

**Comment by deltaxflux** [comment]
Yes

**Comment by defatpm** [comment]
The command ran but still experienced the same freeze.

**Comment by deltaxflux** [comment]
Make sure you do it right
`su root`
`export KEEP_NETWORK=1`
`./fluxion`

**Comment by Grygoryan13** [comment]
Доброго времени суток! Проблема: при подключении по SSH с удаленной машины с помощью Putty Fluxion нормально работает до момента поднятия ложной точки доступа, затем происходит сбой соединения и программа закрывается. В момент, когда Fluxion запущен на самой машине, к ней невозможно подключиться по SSH извне. Прошу подсказать пути решения, заранее спасибо!
