### ISSUE TITLE
Another dutch web interface

### ISSUE THREAD

**Issue by ignorcol** [deltaxflux/fluxion#378]
### Which version of fluxion are you using?
0.23

### What distribution of Linux (including the version) are you running it on?
Kali linux Rolling

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Atheros AR9271

### Which is the driver for it?
Atheros?

### Does it support injection ( output of aireplay-ng -9)
Yes

_________________________________________________________________________________

Hi, 

I'm loving your application, so I decided to contribute a bit with another web interface. Everything works, the only thing that doesn't is the transition to the final.html when the correct password is entered. Fluxion says there are clients connected and the pw shows correctly in pwlog.
 
I did the following:
Added on line **4006**: 
```
echo -e "      "$red"["$yellow"$n"$red"]"$transparent" Ziggo2016       [NL]";n=` expr $n + 1`
```

Added on **4375**:
```
			elif [ "$fluxass" = "34" ]; then
				ZIGGO2016_NL
				break
```
_(And edited the last 2 elif's so there are no double numbers)_

Added on **7359**:
```
function ZIGGO2016_NL {
	mkdir $DUMP_PATH/data &>$flux_output_device
	cp $WORK_DIR/Sites/ZIGGO2016_NL/* $DUMP_PATH/data
}
```

Here is my code:
[ZIGGO2016_NL.zip](https://github.com/deltaxflux/fluxion/files/739881/ZIGGO2016_NL.zip)

I gave the html form `action="check.php"` even though I can't find check.php anywhere. I saw this in the other NL web interfaces so I just did the same assuming this is how the password is being checked. 

So if someone could point out what causes the problem, I can fix it and it can be added :)

**PS**: _The reason I made another Ziggo webinterface is because the other one is quite old(never seen it), and it isn't responsive. This one is a more recent one and also convincing on mobile._

**Comment by deltaxflux** [comment]
I give it a try
