### ISSUE TITLE
There is no automated window to automatically connects victim to fake accespoint

### ISSUE THREAD

**Issue by scmdaman786** [deltaxflux/fluxion#379]
### Which version of fluxion are you using?
v0.23

### What distribution of Linux (including the version) are you running it on?
kali linux

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TP-LINK W722N

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it

problem is 
victim connects to fake access point ok
but the victim doesn't click on the "wifi has no internet access "popup then how we will get the password

problem to fix
victim automatically connects fake access point  & automatically open fake access point window by default

thanks

**Comment by deltaxflux** [comment]
It does this already. Can you give me some information about your setting e.g operating system of the victim

**Comment by scmdaman786** [comment]
android 5.0

On 01-Feb-2017 12:55 PM, "deltax" <notifications@github.com> wrote:

It does this already. Can you give me some information about your setting
e.g operating system of the victim

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/deltaxflux/fluxion/issues/379#issuecomment-276590098>,
or mute the thread

**Comment by deltaxflux** [comment]
Have you tried another device, and can you check if the login pages apears if you type 192.168.1.1 in your browser

**Comment by deltaxflux** [comment]
No response -> auto close ...
