### ISSUE TITLE
The Text Fills In Backwards In Password Request Form

### ISSUE THREAD

**Issue by abadagada2** [deltaxflux/fluxion#380]
### Which version of fluxion are you using?
I am using version 118.

### What distribution of Linux (including the version) are you running it on?
Kali Linux 2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Realtek Semiconductor Corp. RTL8187

### Which is the driver for it?
Works natively on Kali Linux.

### Does it support injection ( output of aireplay-ng -9)
Yes.

### General description of your issue along with the steps to reproduce it
When I log into ap and try to put in password on the form, it puts the password in backwards.  This causes the correct password to register as "wrong" when it is correct.  This happens on the english and spanish versions of the form.

**Comment by spreedated** [comment]
By "backwards" do you mean, when typed "ABCD" it outputs "DCBA"? - How did you checked this? - Tried any other(not internal) Webinterface?

**Comment by Intek13x** [comment]
Open fluxion in text editor, goto line #514, find the string "DIALOG_WEB_DIR_ENG" and replace it with "DIALOG_WEB_DIR_HE". 
Save and close. 
Then check..

**Comment by abadagada2** [comment]
Yes, it's "DCBA" when "ABCD" is typed, spreedated.  Intek13x, I'll check it out but after I try out version 122 first to see if I have the same issue.
