### ISSUE TITLE
FakeDNS Close Immediately when ATTACK

### ISSUE THREAD

**Issue by HerendraTJ** [deltaxflux/fluxion#381]
### Which version of fluxion are you using?
<118>

### What distribution of Linux (including the version) are you running it on?
<Ubuntu 16.10>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<Qualcomm Atheros>

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
<Yes>

### General description of your issue along with the steps to reproduce it
<When attack Launched, the FakeDNS Close unexpectedly>

**Comment by spreedated** [comment]
You didn't provide any information on your hardware.
118 is the rev, but I guess you have 0.23.

**Comment by deltaxflux** [comment]
@spreedated your right. @HerendraTJ read the header of the issue report
