### ISSUE TITLE
3 new Sites + SiteInstaller script

### ISSUE THREAD

**Issue by spreedated** [deltaxflux/fluxion#382]
### Which version of fluxion are you using?
0.23 / 118

### What distribution of Linux (including the version) are you running it on?
kali, latest

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TL-WN722N

### Which is the driver for it?
ath9k_htc

### Does it support injection ( output of aireplay-ng -9)
sure

### General description of your issue along with the steps to reproduce it
First things first, I've made three(actually two) new sites to expand the repertoire.
-Fritz Box (common without modelnumber, EN & DE)
-Genexis (DE, afaik only used in NL & DE)

However, I've also made a python script to easily install new sites to fluxion.
-Usage "./siteinstaller.pyc --file <filename>" (has to be a tar.gz file)
the contents will be copied to the proper folder with chmods, and the fluxion bash script will be rewritten to contain the correct functions and options.
I would love to see it being part of fluxion <3

[sites_and_installer.tar.gz](https://github.com/deltaxflux/fluxion/files/744401/sites_and_installer.tar.gz)

**Comment by flatounet** [comment]
hello ,
im looking for some site ,
but im still too noob for turn it for fluxion

im french ,im looking for these one 
http://assistance.orange.fr/livebox-modem/toutes-les-livebox-et-modems
just ask wpa key  under middle big grey line

or have you any tutoriel how to ?
web page is in php ,but all Site here are in html ...
i dont know how to ...

**Comment by deltaxflux** [comment]
@spreedated good work but I definitely don't run the installer

**Comment by spreedated** [comment]
hehe, I understand your scepsis, here is the py file.

[siteinstaller.zip](https://github.com/deltaxflux/fluxion/files/749129/siteinstaller.zip)

**Comment by deltaxflux** [comment]
Well looks better. 
Best line in the code
**Internal failure... we fucked it up**

**Comment by deltaxflux** [comment]
EDIT: and the fluxion check is a bit messy

**Comment by spreedated** [comment]
<3

however, what you think of the idea, is it a worthy contribution to your project?

**Comment by deltaxflux** [comment]
@spreedated sure...
Where are you from ?

**Comment by spreedated** [comment]
germany

**Comment by deltaxflux** [comment]
Dann lässt sich es auch sicher einrichten Deutsch zu reden

**Comment by spreedated** [comment]
hehe, klar ;)

**Comment by deltaxflux** [comment]
Der installer funktioniert gut, sogar ohne Fehler. Allerdings ist es nicht unbedingt notwendig das er nur *.tar.gz Datein unterstützt da:

- Ordner können einfach überprüft und kopiert werden können
       - Prüfen ob z.b eine index.html vorhanden ist

Vielleicht ändere ich das später nochmal. 

- Die id`s werden sauber hochgezählt und es gibt außerdem kein Syntax Fehler aber:

- Eine Suchfunktion wäre praktisch wenn es nicht im fluxion Ordner ausgeführt wird, ähnlich wie:
`import os `
`dir_path = os.path.dirname(os.path.realpath(__file__))`
- Und die oben angesprochene Dateitypen Funktion

**Comment by spreedated** [comment]
Danke für's Feedback. 

- Eine Ordnerimport Funktion wäre möglich, aber ich hatte Gedanken, dass man später die Sites als "Pakete" nachinstallieren/importieren kann. Diese könnten evtl. separat zur Verfügung gestellt werden oder nach Vorgabe selbst erstellt. - Dabei evtl. noch eine Beschreibung/How-To.

- Ein Test ob das script im fluxion Ordner ausgeführt wird, ist drin, könnte man mit deiner Lösung arbeiten.

- Was ich noch hinzufügen könnte, wäre eine generelle Prüfung vor Import, ob Ordner oder Archiv, sodass überprüft ob die drei *.html Dateien enthalten sind & später evtl. auch ob diese über die html form verfügen die auf die check.php verweist, etc.

Ich bin gerne bereit dein Projekt zu unterstützen, evtl. auch an der GUI mitzuwirken, leider bin ich github noob; wenn du mir kurz erklären könntest wie ich einen PullRequest erstelle wäre das super(ich weiß, lmgify, aber manchmal braucht man auch konkrete Antworten^^)

**Comment by deltaxflux** [comment]
- Eine nachladen von Ordnern oder Dateien sollte kein Problem sein und ein ein Guide währe hilfreich allerdings würde ich dazu tendieren die # und die abfragen raus zunehmen. 
- Außerdem ist die  Idee mit der Html Form Überprüfung gut

> Ich bin gerne bereit dein Projekt zu unterstützen, evtl. auch an der GUI mitzuwirken, leider bin ich github noob; wenn du mir kurz erklären könntest wie ich einen PullRequest erstelle wäre das super(ich weiß, lmgify, aber manchmal braucht man auch konkrete Antworten

- Es ist relativ einfach, entweder per command line oder im Webinterface

**Webinterface:** 
1. Projekt forken 
2. Dateien ändern und hochladen
3. Auf pull request klicken 
4. pull :) 


> Dein fluxion Updatescript macht nur ein "Update" von fluxion, nicht aber von dem Rest, somit entsteht ein Verweis auf evtl. nicht vorhandene "Sites"(wie die ZIGGO2016)

- Das stimmt und das Problem werde ich fixen allerdings nicht so wie die genannten Lösungsansätze da nicht git branches nicht unterstützt werden 

- Gibt es eine andere Möglichkeit außer über github zu kommunizieren? Telegram oder Email?

**Comment by spreedated** [comment]
Hab dir eine Email geschickt, schau evtl. in den Spamordner, meine Adresse landend dort gerne schon mal..

**Comment by deltaxflux** [comment]
Ich habe keine Email erhalten. Vielleicht ein Schreibfehler drin ?

**Comment by spreedated** [comment]
An deine öffentliche Mail "deltax.fluxion@gmail.com" (per copy&paste)

Ansonsten, STEAM: http://steamcommunity.com/id/spreed/

**Comment by flatounet** [comment]
hello ,
im looking for help for french provider,
i have site : http://www66.zippyshare.com/v/9KgLcvvW/file.html

but they are in php..
any link for tuto/how to turn it for fluxion ?

thank's

**Comment by deltaxflux** [comment]
Use the siteinstaller script

**Comment by flatounet** [comment]
sorry im noob here

root@kali:~/fluxion# ./siteinstaller.py --file sfr.tar.gz
Your fluxion version "0.24". 
Supported versions are 0.23

how i can fix this ?

**Comment by spreedated** [comment]
The Sites you are trying to install, doesn't contain any *.html files neither are in the correct format for fluxion. First step would be to rebuild them in HTML with the correct form-tag and redirection to the check.php. You need to do this yourself unless you find someone to build them for you.

- You need three HTML files named index.html, final.html and error.html in the root folder of the site
- index & error needs a formtag with a user & password field (also a submit button) that points at a "check.php"
- I recommend keeping all files(aswell image files) in the root directory without any subfolders

That's pretty much of it.
I might write a doc for it, but for now this should help you. Also look at the consisting sites for a example.

**Comment by flatounet** [comment]
thank's for info
