### ISSUE TITLE
Manually select interfaces 

### ISSUE THREAD

**Issue by kn0wledge** [deltaxflux/fluxion#383]
Hi,

I have 3 interfaces on my box and would like to select which one does what when i run Fluxion. 

is there a way to do that?

**Comment by Intek13x** [comment]
Only one interface is enough to do your work, but it must support packet injection/monitor mode.. 
Check it by running aireplay-ng -9 command.

**Comment by deltaxflux** [comment]
@Intek13x thanks for the fast response
