### ISSUE TITLE
Password Form Does Not Show Up Anymore

### ISSUE THREAD

**Issue by abadagada2** [deltaxflux/fluxion#384]
### Which version of fluxion are you using?
122

### What distribution of Linux (including the version) are you running it on?
Kali Linux 2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Ralink Technology, Corp. RT2870/RT3070

### Which is the driver for it?
Works natively to Kali Linux

### Does it support injection ( output of aireplay-ng -9)
Yes.

### General description of your issue along with the steps to reproduce it
Password form does not show up when victim connects to fake ap.  This happens after fake ap is made and fluxion is disconnecting the real ap.  When victim connects to fake ap, the password form does not show up at all even when victim attempts to browse the web.

**Comment by deltaxflux** [comment]
Can you provide more information like lighttpd apache and hostapd version ?
