### ISSUE TITLE
running fluxbox - issue (line 55)

### ISSUE THREAD

**Issue by mokaddict** [deltaxflux/fluxion#39]
```
root@kalibox:/home/src/fluxion# sh ./fluxion
./fluxion:` 55: ./fluxion: Syntax error: "(" unexpected
```

happen in both master and develop branch

anybody experienced the same issue?

**Comment by deltaxflux** [comment]
Not confirmed with the last commit. 
Try the latest commit 
`sudo rm -rf fluxion`
`sudo sudo git clone https://www.github.com/deltaxflux/fluxion.git`
If this **not** work 
Try to fix it by self 
`sudo apt-get update`
`sudo apt-get install dos2unix`
`sudo dos2unix fluxion`
`sudo chmod u+x fluxion`

Finally start script again 
`sudo ./fluxion`

**Comment by mokaddict** [comment]
same error

**Comment by deltaxflux** [comment]
**Well you don't have the latest update..**.
Anyway, open fluxion over gedit 
`sudo gedit fluxion`
And add this line 
`#!/bin/bash`
_**With no space or something else this must be at the beginning**_
