### ISSUE TITLE
Fluxion Tips?

### ISSUE THREAD

**Issue by Syriamanal** [deltaxflux/fluxion#390]
Should i only chose only red colored wifi names?

and how long do i have to wait for a hand shake?

**Comment by HeCosmin** [comment]
Reason that [https://github.com/deltaxflux/fluxion/issues/393](url)

**Comment by Intek13x** [comment]
Red colored AP's indicates that some devieces are connected to it. 
You would have better chances of capturing handshakes on these AP's because clients are already associated. 
The time you have to wait depends on the number of clients connected to AP and your distance from that AP.
