### ISSUE TITLE
Very wrong

### ISSUE THREAD

**Issue by HeCosmin** [deltaxflux/fluxion#393]
Orginal linset is good for deauth few seconds close return handshake perfect but your idea wrong continue flood non-stop they router frozzen can't back respond handshake problem for two times!

fix it back menu deauth few seconds stop return where code orginal by vk49!

**Comment by deltaxflux** [comment]
Nope, the handshake can be captured even if a deauth attack is running

**Comment by HeCosmin** [comment]
Yes, bad idea continues flooding can't respond back handshake. recommned just 5-10 times send deauth respond back perfect handshake. you do not know about what? unprofessional -,-

I do modified code command line send deauth 10 times!

**Comment by HeCosmin** [comment]
DEAUTHTIME="9999999999999" wtf!!!
return back
DEAUTHTIME="8"

now works perfect respond back handshake!

**Comment by deltaxflux** [comment]
Ok you are the pro

**Comment by HeCosmin** [comment]
Not pro... I am simply man!
