### ISSUE TITLE
Vietnamese version of Fluxion

### ISSUE THREAD

**Issue by 7n3w** [deltaxflux/fluxion#394]
I wanna translate Fluxion to another version for Vietnam's people. 

[fluxion_vi.txt](https://github.com/deltaxflux/fluxion/files/753023/fluxion_vi.txt)

**Comment by deltaxflux** [comment]
Yeah but what is the purpose for that?

**Comment by 7n3w** [comment]
Someone need it is translated. And i need your permission!

**Comment by deltaxflux** [comment]
You have the permissions, if you leave credits
