### ISSUE TITLE
Ssl certifica please activate

### ISSUE THREAD

**Issue by Gentech57** [deltaxflux/fluxion#395]
### Which version of fluxion are you using?
Latest 0.24 (123)

### What distribution of Linux (including the version) are you running it on?
Kali 2.0 vmware 

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Rt2800 working -

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
1.enter fluxion activate monitor - work
2. All channel - work.                                                       3.target acces point - work 4. Handshake pyrit - work 5. Ssl certifica. Not invalid. ( select 2.search certifica . no reply dont work. Search ssl.

**Comment by NeedSomeKush** [comment]
Hello,
Same problem here, deltaflux send me something to solve it, you can try it but it didn't work for me.

- Go to the directory where fluxion is installed, then open it in text editor.
- Search for the string DIALOG_WEB_DIR_ENG="rtl" , and replace it with DIALOG_WEB_DIR_HE="rtl" .
- Save and close the text editor. You're done.

Tell me if it works for you. 

Regards

**Comment by Intek13x** [comment]
Dude @NeedSomeKush the solution you're suggesting was to fix the RTL writing direction in password form that @deltaxflux had already fixed in v24 revision.123 today.  

@Gentech57 may be you should try to update openssl.

**Comment by deltaxflux** [comment]
Like @Intek13x already said, try to update your packages but please be carefull because you can easily break your kali system

**Comment by Gentech57** [comment]
already updated. @Intek13x  and certificate ınvalid or not present please choice  2. search ssl certificate no reply please fixxx

**Comment by deltaxflux** [comment]
You have to create every time a new one
