### ISSUE TITLE
Chanels switch

### ISSUE THREAD

**Issue by pierredias** [deltaxflux/fluxion#396]
### Which version of fluxion are you using?
<???> 123

### What distribution of Linux (including the version) are you running it on?
<???>Kali Linux 2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<???>tl-w722n

### Which is the driver for it?
<???>athk9

### Does it support injection ( output of aireplay-ng -9)
<???>
Yes
### General description of your issue along with the steps to reproduce it
<???>
I already try to run in another window mdk3.txt but deauth everyone who want to connect to the fake network.
Can you please make if possible one version that follow the Chanel when it change? Already try issue #89 but not work, even with 2 adapters.

**Comment by deltaxflux** [comment]
Remove the -c flag

**Comment by pierredias** [comment]
Remove from where?
"mdk3 mon0 d -b /tmp/TMPflux/mdk3.txt"

**Comment by deltaxflux** [comment]
No at line 2101

**Comment by pierredias** [comment]
I already delete -c at line 2101
It just that and now run fluxion or I must run in another window
"Mdk3 mon0 d -b........"?
Thanks for you pacient .

**Comment by deltaxflux** [comment]
No thats all

**Comment by pierredias** [comment]
I will try just now 
Thank you deltaflux 
You are big ;)

**Comment by pierredias** [comment]
In the version 124 its the same thing, correct?
