### ISSUE TITLE
ISC-DHCP-SERVER doesn't offer IP

### ISSUE THREAD

**Issue by michelelacorte** [deltaxflux/fluxion#398]
### Which version of fluxion are you using?

0.24 rev 123

### What distribution of Linux (including the version) are you running it on?

NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

Network controller: Ralink corp. RT3290 Wireless 802.11n 1T/1R PCIe

### Which is the driver for it?

driver=rt2800pci 
driverversion=4.8.0-34-generic firmware=0.37

### Does it support injection ( output of aireplay-ng -9)

No replay interface specified.

### General description of your issue along with the steps to reproduce it
Host cannot connect to fake AP because DHCP doesn't offer ip, I've tried everything but I don't know what appening, this is my dhcpd.conf file

subnet 192.268.1.0 netmask 255.255.255.0 { 
range 192.168.1.10 192.168.1.100; 
option routers 192.168.1.1; 
ddns-update-style none; 
option domain-name-servers 8.8.8.8, 8.8.4.4; 
default-lease-time 7200; 
max-lease-time 21600; 
authoritative; 
log-facility local7;
}

**Comment by deltaxflux** [comment]
Never will help ubuntu users , because I strongly recommend to use another distro
