### ISSUE TITLE
mdk3 Authentification 

### ISSUE THREAD

**Issue by KingViesel** [deltaxflux/fluxion#399]
### Which version of fluxion are you using?
<0.24 (latest)>

### What distribution of Linux (including the version) are you running it on?
<Kali 2016.2>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<Intel Corporation PRO/Wireless 4965 AG or AGN [Kedros] Network Connection (rev. 61)>

### Which is the driver for it?
<iwl4965>

### Does it support injection ( output of aireplay-ng -9)
<Injection is working>

### General description of your issue along with the steps to reproduce it
<After starting Fake AP the mdk3 window is only showing me "Periodically re-reading blacklist/whitelist ever 3 seconds". The mdk3.txt is available in at this process. Inside of it i find the MAC from the AP. 
Today I reinstalled Kali and fluxion. After that i have this issue. Before that i used fluxion last week and worked fine at this time.
Thanks for any reply>

**Comment by deltaxflux** [comment]
We are not the mdk3 developer, please contact them
