### ISSUE TITLE
Alfa Awus036ach Interface Problem

### ISSUE THREAD

**Issue by mehmetgoksu** [deltaxflux/fluxion#400]
### Which version of fluxion are you using?
FLUX 0.24 (rev.  124) 

### What distribution of Linux (including the version) are you running it on?
Linux kali 4.9.0-kali1-amd64 #1 SMP Debian 4.9.6-3kali2 (2017-01-30) x86_64 GNU/Linux

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Alfa awus036ach chipset:rtl8812au

### Which is the driver for it?
https://github.com/astsam/rtl8812au

### Does it support injection ( output of aireplay-ng -9)
![aireplay](https://cloud.githubusercontent.com/assets/20892888/22798032/2834fc98-ef09-11e6-81fd-33b78a3501a5.jpg)

### General description of your issue along with the steps to reproduce it
in select interface mode its auto pass and when its select its not working althoug it was in monitor mode and fluxion show that
```
Error: your wireless card  isn't supported  
Do you want exit? 
```
 .to do in monitor mode should be manually use 
```
ifconfig wlan0 down
iwconfig wlan0 mode monitor
ifconfig wlan0 up
```
and when its going to monitor mode its name is not changing its still wlan0 and ı aware that if we use start with aireplay-ng -9 wlan0 its auto going to monitor mode and dont need to manual .
Extra info : Airodump airbase working clear manual.

**Comment by deltaxflux** [comment]
Well I need more informations about your specific problem, it would be nice if you can join the [Gitter chat](https://gitter.im/deltaxflux/Lobby) because it is easier for me to handle this problem

**Comment by Gentech57** [comment]
Mehmet hani lan test icindi :)

**Comment by Gentech57** [comment]
Bu sorunu cözdünmü

**Comment by mehmetgoksu** [comment]
Test tabiki hayır çözülmüyor yeni nesil alfalarla test bile yapılamıyor eskileride yeni notebooklarda çalışmıyor

**Comment by Gentech57** [comment]
Knk sen mu ach yi nerden aldin

**Comment by Gentech57** [comment]
Abi amk cocuklari paraya para demiyor orjinal driver ini bile kuramiyorum sen dusun kursam dahi o bile monitor modu desteklemiyor diye biliyorum
