### ISSUE TITLE
Google blocking access to Login Page

### ISSUE THREAD

**Issue by Parshuram2** [deltaxflux/fluxion#402]
### Which version of fluxion are you using?
<124>

### What distribution of Linux (including the version) are you running it on?
<Kali 2016>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<Bus 001 Device 003: ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter>

### Which is the driver for it?
<I dont'know..The issue isn't related to it either,It seems Google made Fluxion useless>

### Does it support injection ( output of aireplay-ng -9)
<yes>

### General description of your issue along with the steps to reproduce it
< When the Victim connects to the Fake AP and tries to access Google or any other site previuosly the Wi-Fi login page was served. Now since the "Create a SSL Certificate" option came in Fluxion, Google blocks access to that login page and shows a warning stating "Your Connection is not Private and hackers are trying to steal your info and even if the Victim tries he cannot access the login page because Google advises to try after some time. So basically, everything works with Fluxion but it seems Google has identified requests made from a FakeAP?> Or does Google find a problem with the Certificate because it says something to that effect i.e Incorrect Certificate.

**Comment by deltaxflux** [comment]
Which browser do you use?

**Comment by Parshuram2** [comment]
On my 'victim' phone..it is Firefox

**Comment by deltaxflux** [comment]
do you use the sign page or do you random google

**Comment by Parshuram2** [comment]
I just try to go www.google.com...then I try other pages quora,facebook...but that Google page stays on and it has no option of browing on...only and advanced option which gives detailed warning about the hacking attempt

**Comment by Parshuram2** [comment]
It says "NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by deltaxflux** [comment]
can you provide screenshots, can we move this to gitter?

**Comment by Parshuram2** [comment]
ok we can..Just one for info I had to give...I tried again..I browsed to www.cracked.com..The log-in appeared...so it might be an issue with "https" sites?
