### ISSUE TITLE
Ap does not work

### ISSUE THREAD

**Issue by gearcapitan** [deltaxflux/fluxion#403]
### Which version of fluxion are you using?
<???>0.24

### What distribution of Linux (including the version) are you running it on?
<???>Kali Linux 2016.2 all updates

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<???>

### Which is the driver for it?
<???>realtek 8187

### Does it support injection ( output of aireplay-ng -9)
<???>

### General description of your issue along with the steps to reproduce it
<???>Once the fake ap is created, it does not disable the clients to prevent them from connecting to their original network making the ap completely useless

**Comment by deltaxflux** [comment]
It is a driver issue and not related to fluxion, the only thing I we use 2 wireless cards
