### ISSUE TITLE
HTTP(s) page shows warning! ;_;

### ISSUE THREAD

**Issue by issac7** [deltaxflux/fluxion#406]
### Which version of fluxion are you using?
<0.24?>

### What distribution of Linux (including the version) are you running it on?
<Kali-linux2.0 rolling>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<TL-WN722N>

### Which is the driver for it?
<http://www.tp-link.com/us/download/TL-WN722N.html>

### Does it support injection ( output of aireplay-ng -9)
<Yes>

### General description of your issue along with the steps to reproduce it
<When victim connects to my fluxion generated fake AP he opens https:// pages ;_; and he gets https waning ;_; that it's unsecured ;_; :-1:  will be glad if the next version of fluxion comes with proper SSLstrip>
Thanks a lot

**Comment by deltaxflux** [comment]
Yeah you can also buy me a certificate

**Comment by tuthieu** [comment]
Does it work with Let's encrypt,deltaxflux?

**Comment by issac7** [comment]
@deltaxflux, can we use free certificates ?

**Comment by deltaxflux** [comment]
@issac7 what do you mean

**Comment by strasharo** [comment]
It's normal that you receive a warning, since it's a self signed certificate. Using Let's encrypt for deceiving users would be a violation its terms of use.

**Comment by issac7** [comment]
@deltaxflux , can you build a small program inside fluxion which redirects https version to http ?!? like sslstrip buddy ?

**Comment by deltaxflux** [comment]
@issac7 no its pointless

**Comment by issac7** [comment]
Will be glad if you elaborate why

**Comment by deltaxflux** [comment]
Because we don't downgrade to http if we have https aupport

**Comment by issac7** [comment]
When victim open HTTPS page he gets warning, it kills success rate 😢
We can't wait all day till the victim opens HTTP page 😭

**Comment by deltaxflux** [comment]
Read the disclaimer

**Comment by its0x08** [comment]
@issac7 is right .. while in tools like Bettercap they use SSL stripping technique why not in here ?? Anyway the victim won't notice at all because the site victim request will never gonna open in the evil hotspot so why not?! Plus the success rate will get higher by 40%

**Comment by issac7** [comment]
Will be so glad if fluxion has ssl strip :)
