### ISSUE TITLE
"There are no wireless cards" problem with VirtualBox on MacBook Pro

### ISSUE THREAD

**Issue by VogrBurn** [deltaxflux/fluxion#407]
### Which version of fluxion are you using?
<.24>

### What distribution of Linux (including the version) are you running it on?
<Kali-Linux-2016.2-vbox-i686>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<AirPort>

### Which is the driver for it?
<Don't know, because I use it on VirtualBox>

### Does it support injection ( output of aireplay-ng -9)
<Dont'know>

### General description of your issue along with the steps to reproduce it
<When I select the language for Fluxion, it appears the "There are no wireless cards" problem. Probably because I use it with VirtualBox. The Linux distro I've installed it's the Kali for Virtual Box by offensive security>

**Comment by spreedated** [comment]
I recommend using it natively, however I got mine working on VMWare aswell.

> Which is the driver for it?

<Don't know, because I use it on VirtualBox>

Doesn't matter, the OS needs a driver. - First steps, mount your interface to the virtual box,
Watch here.... [VirtualBox mounting](http://lmgtfy.com/?q=virtualbox+mount+interface+card)

**Comment by deltaxflux** [comment]
Well I don't know is not very helpful.

**Comment by Ghostboy-287** [comment]
@VogrBurn your wireless adapter is internal or usb one? 
Are you sure that your adapter is compatible with kali linux?
take a sceenshot of `ifconfig` or `iwconfig` commands
Did you connect your wireless adapter to virtualbox [ https://www.youtube.com/watch?v=K1ETBeRQBs4 ]
