### ISSUE TITLE
[i] Error: your wireless card  isn't supported / Suggestion

### ISSUE THREAD

**Issue by Ghostboy-287** [deltaxflux/fluxion#408]
### Which version of fluxion are you using?
FLUXION 0.24 (latest one)

### What distribution of Linux (including the version) are you running it on?
kali rolling 2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
wifi-sky 10000mw Realtek RTL8187_Wireless

### Which is the driver for it?
the rtl8187 one which is installed in kali rolling 2016.2

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it

I started by installing everything needed to fluxion using the Install.sh script
Then I execute bending: ./fluxion
It verifies, everything is ok (installed)
I choose my language (1-English)
Then it asks me directly to choose a channel I choose 1-All channels
And there he told me [i] Error: your wireless card  isn't supported (while my wireless adapter is connected) 
notice:
i have the eth0 enabled too, and i think that fluxion choose eth0 by default , (while he had to ask me to choose which interface to choose (as in version 0.23))

i had to do ifconfig eth0 down every time i would to use fluxion 
It would be preferable that it ask to choose which interface or to set it directly on wlan0 and ignore eth0

thank you for reading 
thank you for your work 
we appreciate it <3

**Comment by Ghostboy-287** [comment]
![root ghost-287 -hack-tools-fluxion_003](https://cloud.githubusercontent.com/assets/17873513/22994220/681938a8-f3c6-11e6-8125-90dff6b42c73.png)

**Comment by deltaxflux** [comment]
Have you used the FLUX_ AUTO feature? Eth0 is your LAN port.

**Comment by Ghostboy-287** [comment]
sorry i dont know what is the Flux_Auto feature :/

**Comment by deltaxflux** [comment]
Does the interface appear if you type ./airmon ( inside the fluxion folder ) ?

**Comment by Ghostboy-287** [comment]
yeah it appears 
![root ghost-287 -hack-tools-fluxion_017](https://cloud.githubusercontent.com/assets/17873513/23082247/c503d81e-f558-11e6-9c40-7783c89544bb.png)

**Comment by deltaxflux** [comment]
And enable monitor mode before u select the card ?
