### ISSUE TITLE
Broken Wireless Card Detection/X11 Server

### ISSUE THREAD

**Issue by ElectronicWizard** [deltaxflux/fluxion#41]
OS: Windows 10 Insider Preview, lastest build on Fast Previews, using Linux subsystem

After spending some time manually installing dependencies, as the ./Installer.sh script failed to, and in fact just said "Not installed" for the missing dependencies, I was finally able to run ./fluxion.
However, the following is the commandline output:

[http://pastebin.com/ajFeQDuD](http://pastebin.com/ajFeQDuD)

dos2unix was run on both Installer.sh and fluxion.

**Comment by deltaxflux** [comment]
This looks very intresting. I don't have a solution. However the best solution would be if you use Kali Linux 2 (in a VM or dual boot). Lets see, I don't develop or make the Windows Version(s).

**Comment by strasharo** [comment]
Windows is not supported.
