### ISSUE TITLE
Problem no a-web redirection

### ISSUE THREAD

**Issue by limbo401** [deltaxflux/fluxion#411]
hi i'm confused about this Qs  but when i try fluxion : i try to connect with my second computer to the FAKE AP then i realize that : there is no redirection to the webpage ! you need to type default gateway to get access to it ! so any help 
i'm using : 
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

Chipset : Ralink RT2870/3070

**Comment by deltaxflux** [comment]
https://github.com/deltaxflux/fluxion/issues/398
