### ISSUE TITLE
 RPI Loss of control over a local network after selecting the false pages Web interface.

### ISSUE THREAD

**Issue by Grygoryan13** [deltaxflux/fluxion#412]
### Which version of fluxion are you using?
0.23

### What distribution of Linux (including the version) are you running it on?
Kale 2016.2
### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Adapter: Panda Wireless PAU09
Chipset: Ralink RT2870/3070

### Which is the driver for it?
Driver=rt2800usb

### Does it support injection ( output of aireplay-ng -9)
"Injection is working!"

### General description of your issue along with the steps to reproduce it
Fluxion works fine in the management directly with raspberri pi 3. When connecting via LAN (wi-fi) using teamviver remote access to the desktop falls on the stage of raising false Web interface pages and restored after the completion of fluxion. The operations for the conservation network, discussed in the next topics, for example, the command export keep Networks, does not solve the problem. The network is maintained, but the management does not take place through it. I apologize for any mistakes, English is not my native language. Thank you for your hard work!
Useful options:
`auto lo
iface lo inet loopback

auto eth0
allow-hotplug eth0
iface eth0 inet dhcp
auto wlan0
allow-hotplug wlan0
iface wlan0 inet manual
iface home inet dhcp
iface mobile inet dhcp
iface wlan1 inet manual
iface wlan1mon inet manual
iface mon0 inet manual
iface mon1 inet manual`

**Comment by strasharo** [comment]
https://github.com/deltaxflux/fluxion/issues/397
