### ISSUE TITLE
Internet connection too slow when using FLUXIN

### ISSUE THREAD

**Issue by Revokk** [deltaxflux/fluxion#416]
### Which version of fluxion are you using?
Latest one

### What distribution of Linux (including the version) are you running it on?
<Kali Linux 2.0>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
tp link tl-wn722n
tp link tl-wn823n

### Which is the driver for it?
LATEST

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
<Fluxion works perfectly for me but when i create the fake acces point internet connection on it is too slow(takes about 45 sec to get redirected to the fake site),sometimes it doesn't even wanna connect>
Thanks

**Comment by strasharo** [comment]
There's no Internet connection in the fake AP.
