### ISSUE TITLE
My Issues

### ISSUE THREAD

**Issue by its0x08** [deltaxflux/fluxion#418]
### Which version of fluxion are you using?
`FLUXION 0.24`

### What distribution of Linux (including the version) are you running it on?
```
uname -a
Linux kali 4.9.0-kali1-amd64 #1 SMP Debian 4.9.6-3kali2 (2017-01-30) x86_64 GNU/Linux
```

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
`Alfa AWUS036NH`

### Which is the driver for it?
```
airmon-ng 
phy2	wlan1		rt2800usb	Ralink Technology, Corp. RT2870/RT3070

```
### Does it support injection ( output of aireplay-ng -9)

> Of course!!

```
aireplay-ng -9 wlan0
ioctl(SIOCSIWMODE) failed: Device or resource busy
00:13:06  Trying broadcast probe requests...
00:13:06  Injection is working!
00:13:08  Found 1 AP 

00:13:08  Trying directed probe requests...
00:13:08  F0:B4:29:8C:B7:13 - channel: 3 - 'Na pare'
00:13:08  Ping (min/avg/max): 1.185ms/2.580ms/10.915ms Power: -28.03
00:13:08  30/30: 100%

```

### General description of your issue along with the steps to reproduce it

> Im a new user of the tool.. Congrats !! I just called it mother of "EvilTwin Attack" in my blog. I would like to suggest some features like full automation of the tool after the phase of choosing wifi to attack, and also to add more HTML pages and an auto selection of HTML page my knwoing the type of router from mac addres.. can be super easy `root@kali:~/Desktop/scripts/fluxion# macchanger -l |grep aa:11:22` .. The phase after you choose to use an old handshake doesnt work!!
whenever it asks and you say yes I wanna use an old handshake .. it doesnt work alse whenever there is the input to write the directory where to save ur handshakes it goes by default to /root/ in my case not to /root/Desktop/scripts/fluxion/ for example ..!!! 
Thanks!!! :+1:

**Comment by kn0wledge** [comment]
Yeah , I always get "corrupted handshake" message whenever I use an already captured handshake from a previous session.

**Comment by deltaxflux** [comment]
@its0x08 and @kn0wledge 
Use pyrit as handshake check methode. Because we take only good handshakes. Since they updated kali there is a bug with pyrit too which is solved. 

**To solve this problem use every time pyrit to check the  handshake.** 

Here is the offical bug report:
https://bugs.kali.org/view.php?id=3801

@its0x08 

> HTML pages and an auto selection of HTML page my knwoing the type of router from mac addres.. can be super easy root@kali:~/Desktop/scripts/fluxion# macchanger -l |grep aa:11:22 

Thanks for your suggestion

You can use the autorun by using following commands
```
su root
export FLUX_AUTO=1
./fluxion
