### ISSUE TITLE
Sites folder rename to "sites" in rev 125

### ISSUE THREAD

**Issue by MartinsZB** [deltaxflux/fluxion#419]
### Which version of fluxion are you using?
<0.25 rev 125>

### What distribution of Linux (including the version) are you running it on?
<Kali linux 2006.2>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<TP-Link TL-WN722N>

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
<???>

### General description of your issue along with the steps to reproduce it
In latest release (rev 125) all the additional sites is moved to "sites" (small first letter), but in fluxion there is still path to additional sites with capital S - "Sites"

**Comment by deltaxflux** [comment]
thanks I forgotte to change this

**Comment by deltaxflux** [comment]
486b65f
