### ISSUE TITLE
No deauth during attack

### ISSUE THREAD

**Issue by Parshuram2** [deltaxflux/fluxion#420]
### Which version of fluxion are you using?
<126>

### What distribution of Linux (including the version) are you running it on?
<kali2>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<RaiLink>

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
<yes>

### General description of your issue along with the steps to reproduce it
<No Deauth during attack. When I attack my network. The clients are disconnected but not contioniously as was the case before. The DEAUTH(Mdk3) window also remains empty. So deauth packets are not being sent to clients

**Comment by deltaxflux** [comment]
We are not the mdk3 support forum
