### ISSUE TITLE
No handshake in /root/handshakes folder

### ISSUE THREAD

**Issue by MartinsZB** [deltaxflux/fluxion#421]
### Which version of fluxion are you using?
<0.25 rev 126>

### What distribution of Linux (including the version) are you running it on?
<4.9.0-kali2-amd64 #1 SMP Debian 4.9.10-1kali1 (2017-02-20) x86_64 GNU/Linux>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<TP-LINK TL-WN722N Atheros Communications, Inc. AR9271 802.11n>

### Which is the driver for it?
phy0	wlan0		ath9k_htc	Atheros Communications, Inc. AR9271 802.11n

### Does it support injection ( output of aireplay-ng -9)
21:18:17  Injection is working!

### General description of your issue along with the steps to reproduce it
After upgrade to rev 126, the handshake file is not created in /root/handshakes. airodump-ng window show the handshake successfully captured, but no file created in folder. Handshake checking shows that handshake is corrupted. With manually (with airodump-ng) captured handshake everything looks working ok.

**Comment by deltaxflux** [comment]
The handshake will only stores if it is verify by fluxion

**Comment by MartinsZB** [comment]
Strange. In /tmp/TMPflux there is .cap file. If I feed it in aircrack-ng, it shows WPA (1 handshake) as expected. When I add | grep -q "1 hanshake" it returns nothing.

**Comment by MartinsZB** [comment]
Ah, ok it is "-q"

**Comment by MartinsZB** [comment]
Ok, forget it :) working as expected. My fault
