### ISSUE TITLE
fluxion Incorrectly entered passwords show

### ISSUE THREAD

**Issue by Gentech57** [deltaxflux/fluxion#423]
### Which version of fluxion are you using?
0.24

### What distribution of Linux (including the version) are you running it on?
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
rt2800usb

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
False passwords made over fake ap show

source : https://github.com/Vodker/wifimosys

**Comment by deltaxflux** [comment]
What are you trying to say

**Comment by Gentech57** [comment]
show the wrong password attempts

**Comment by Intek13x** [comment]
Did you mean password attempts?  
If that's so, then check /root/pwlog/ folder, there will be a txt file if there were any attempts over fake ap.
