### ISSUE TITLE
Changing the writings in phishing site

### ISSUE THREAD

**Issue by p32929** [deltaxflux/fluxion#425]
Originally the phishing pages in English language looks like this:

![screenshot from 2017-02-24 09-29-52](https://cloud.githubusercontent.com/assets/6418354/23289466/defefa14-fa17-11e6-8f29-41370f88cde2.png)

But I've been trying to make the page look like this:

![screenshot from 2017-02-24 09-44-17](https://cloud.githubusercontent.com/assets/6418354/23289710/a962d446-fa19-11e6-980a-8b9611e352f0.png)

I've changed it inside the html files but still looks the same when the phishing page is activated in mobile/PC...

Any solution??

**Comment by deltaxflux** [comment]
The text is different
