### ISSUE TITLE
Unexpected end of the file error

### ISSUE THREAD

**Issue by tijnar33** [deltaxflux/fluxion#426]
### Which version of fluxion are you using?
Flux 0.25(rev. 126) by deltax
### What distribution of Linux (including the version) are you running it on?
kalilinux 2016.2
### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TL-WN722N Tplink router

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
I had used the fluxion tool before in my setup. But when I opened my fluxion tool today, it shows the error like 
./fluxion: line 1183: unexpected EOF while looking for matching `"'
./fluxion: line 1184: syntax error: unexpected end of file
![screenshot from 2017-02-24 10-02-27](https://cloud.githubusercontent.com/assets/25560324/23290392/7bad097c-fa78-11e6-823f-fd473c5851dd.png)

**Comment by deltaxflux** [comment]
You changed something on the file, please delete your folder and clone it again.
