### ISSUE TITLE
Trailing spaces in ESSID are trimmed

### ISSUE THREAD

**Issue by plfort** [deltaxflux/fluxion#428]
### Which version of fluxion are you using?
0.24

### What distribution of Linux (including the version) are you running it on?
Kali 2016.2 / Linux Mint 18.1

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Not relevant

### Which is the driver for it?
Not relevant

### Does it support injection ( output of aireplay-ng -9)
Not relevant

### General description of your issue along with the steps to reproduce it
ESSID with more than 1 trailing spaces are not parsed correctly:
Example with this fake airodump file:
[example_csv.txt](https://github.com/deltaxflux/fluxion/files/801655/example_csv.txt)

Here the ESSID is "MYAP  " (6 characters, 2 trailing spaces), after selecting this AP in the function "selection" the resulting ESSID is "MYAP " (5 characters, 1 trailing space)

**Comment by deltaxflux** [comment]
It because of:
```echo $Host_SSID | sed 's/ //g' | sed 's/\[//g;s/\]//g' | sed 's/\://g;s/\://g' | sed 's/\*//g;s/\*//g' | sed 's/(//g' | sed 's/)//g'```

this removes bugs with the dhcp server (which is necessary)

**Comment by plfort** [comment]
I don't think so, the variable $Host_SSID is already trimmed. In fact, variable $ESSID in the loop is trimmed.

**Comment by plfort** [comment]
Can you reopen the ticket ?

**Comment by deltaxflux** [comment]
Yeah it do this to remove bugs with the dhcp server. It's not an issue

**Comment by plfort** [comment]
I am not talking about the $Host_SSID2 variable, but the $Host_SSID.
It is a bug because, the fake AP created has the wrong name (it has missing spaces !).

**Comment by plfort** [comment]
Moreover, I don't see the link between the SSID and the dhcp server. Can you show me which part of the code is involved ?

**Comment by deltaxflux** [comment]
line 2016 fl.

**Comment by plfort** [comment]
I don't see any reference to $Host_SSID in the dhcp section

**Comment by deltaxflux** [comment]
![image](https://cloud.githubusercontent.com/assets/17337753/23395694/4740c848-fd90-11e6-8f26-7db9dbd1a28f.png)

**Comment by plfort** [comment]
Ok so when you say "DHCP" you are talking about "HostAPD"

**Comment by deltaxflux** [comment]
My fault,

**Comment by deltaxflux** [comment]
Let me clarifying this:

**The DHCP Server**
is responsible for network configuration parameters like ip adresses

**Hostapd**
Is a daemon for the wireless AP

I trimmed spaces, brackets and "" to remove bugs with hostapd **( NOT DHCP ).** I was now wondering why I wrote something about the dhcp server anyway hope you understand my intence.

**Comment by plfort** [comment]
Ok no problem, so hostapd can't handle this type of SSID .. too bad

**Comment by deltaxflux** [comment]
Yep and special characters too
