### ISSUE TITLE
Missing Search Text in Latest Version - 127

### ISSUE THREAD

**Issue by th3c0ldh3art** [deltaxflux/fluxion#429]
### Which version of fluxion are you using?
FLUXION 0.25 - rev. 127

### What distribution of Linux (including the version) are you running it on?
Kali GNU/Linux

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Atheros AR9271

### Which is the driver for it?
ath9k

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
Missing/misplaced various help text, like chose wlan card, search text etc. for e.g see below

[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
[                                                      ]
[      FLUXION 0.25    < Fluxion Is The Future >       ]
[                                                      ]
[~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]

[i] 
                                       
      [1]           
      [2]        
      [3] Back        
                                       
[deltaxflux@fluxion]-[~]

OR

mon0, 

      [1] wlan0		Intel AC	iwlwifi 
      [2] wlan1		Atheros AR9271	ath9k

**Comment by disonesto** [comment]
Same here updated to the latest version FLUXION 0.25 - rev. 127

Having same problems, missing wording

**Comment by deltaxflux** [comment]
Which language do you use?

**Comment by disonesto** [comment]
English

**Comment by ablux** [comment]
I have exactly the same issue after updating to version 0.25 rev 127

its showing like this

  [1]           
  [2]        
  [3] Back

**Comment by deltaxflux** [comment]
I get the issue. Move inside the directory and do 
`git pull --force`

**Comment by th3c0ldh3art** [comment]
I did a manual git pull. sees good so far.

**Comment by deltaxflux** [comment]
44c5364c698441989a3ead20ffb5f97671fb8f6b
