### ISSUE TITLE
HTTPS REDIRECTION

### ISSUE THREAD

**Issue by el3ctr0** [deltaxflux/fluxion#43]
Hi, briefly , as the title says , when the victim entres to a https website it doesnt redirect him to 192.168.1.1 can you make a solution for that
thanks.

**Comment by deltaxflux** [comment]
We are working on the https direction but there are some problems

**Comment by cloverdoser** [comment]
Can you fix that?

**Comment by deltaxflux** [comment]
Hopefully I can fix that. I started already https://github.com/deltaxflux/fluxion/commit/e5904f8a4abde7af9f174b0da59a70dce8f1e304

**Comment by faroukakoul** [comment]
hello, i tried to figure out the problem but not working for me ... -_- if the victim enter to the www.google.com the script work as we wish but if he changes the".com" it bugs so i think we must use mutifunction of httpstatues :+1:  https://httpstatuses.com/  ... i'm working on it

**Comment by faroukakoul** [comment]
and if we use apache server .. will it works????
