### ISSUE TITLE
./fluxion/fluxion: line 795: ./lib/airmon/airmon: No such file or directory

### ISSUE THREAD

**Issue by vlldk** [deltaxflux/fluxion#432]
### Which version of fluxion are you using?
0.25

### Which revision of fluxion are you using?
136

### What distribution of Linux (including the version) are you running it on?
Kali GNU/Linux Rolling 64-bit, Gnome Version 3.22.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Internal Intel Centrino Advanced -N 6235 802.11a/g/n (2x2) Bluetooth v4.0 combo adapter 

### Which is the driver for it?
Unknown

### Does it support injection ( output of aireplay-ng -9)
"Injection is working!"

### General description of your issue along with the steps to reproduce it
./fluxion/fluxion: line 795: ./lib/airmon/airmon: No such file or directory
./fluxion/fluxion: line 796: ./lib/airmon/airmon: No such file or directory

### Other important information
even though i added the airmon file from the fluxion folder in a folder that i created called "airmon" in the ./lib directory it doesn't seem to work

In revision 126 i just copied the airmon file from the fluxion folder to the ./ directory which worked fine

**Comment by minanagehsalalma** [comment]
same error

**Comment by Azurelan** [comment]
exactly the same here

**Comment by styky** [comment]
Same here too, working fine this afternoon, update to 136 hit and it started failing.

**Comment by BraianNunes** [comment]
Same here!

**Comment by deltaxflux** [comment]
`git pull --force --all`

**Comment by vlldk** [comment]
Nope, same error - i deleted the fluxion folder, cloned the git again and ran ./fluxion/install/install.sh. Didn't solve my problem

**Comment by vlldk** [comment]
Solved it - i copied the 'lib' folder from the 'fluxion' folder to ./ directory and that fixed the problem

**Comment by deltaxflux** [comment]
Well I change the path to make it look cleaner and I thought that git pull apply all changes but I'm wrong. Copy the airmon to lib/airmon/airmon

**Comment by vlldk** [comment]
Yea i did - the lib folder is now in the root directory. Maybe change the path fluxion is looking for airmon to ./fluxion/lib/airmon?

**Comment by cdman2013** [comment]
same here ,   no dir lib on /fluxion  

on fluxion directory i' have only this:
-rw-r--r--   add.py
-rwxr-xr-x  airmon
-rwxr-xr-x  arch-install
-rw-r--r--   BullyOutput.txt
-rwxr-xr-x  fluxion
-rwxr-xr-x  Installer.sh
-rw-r--r--   LICENSE
drwxr-xr-x logos
-rw-r--r--   README.md
-rw-r--r--   ReaverOutput.txt
-rw-r--r--   remove.py
drwxr-xr-x  Sites

**Comment by uandro202** [comment]
contact me if you want to know the solution

**Comment by dedmod666** [comment]
@uandro202 what's the fix. Email me: dedmod666@gmail.com
