### ISSUE TITLE
Connection maintained but VNC and SSH sessions crashed until quitting Fluxion

### ISSUE THREAD

**Issue by defatpm** [deltaxflux/fluxion#433]
### Fill in the answers for all of the questions below, OTHERWISE YOUR TICKET WILL BE INSTANTLY CLOSED.

Which version of fluxion are you using?

0.24

### What distribution of Linux (including the version) are you running it on?

kali-rolling
Version=2016.2

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

Adapter: Panda Wireless PAU09
Chipset: Ralink RT2870/3070

Which is the driver for it?

Driver=rt2800usb

### Does it support injection ( output of aireplay-ng -9)

"Injection is working!"

### General description of your issue along with the steps to reproduce it

•  Fluxion started from remote machine on wlan0 connection (wlan0 is hosting the  x11vnc  and SSH sessions; wlan0 connection is maintained and VNC session works until last step)

•  Fluxion is using "wlan1" compatible adapter

•  At the last step (launching FakeAP), Fluxion continues to run as expected on host machine; however, the x11vnc and SSH sessions crash. The host machine still maintains wlan0 connection to local network

•  Upon quitting Fluxion on host machine, the x11vnc and SSH sessions can be reinitiated

**Comment by Intek13x** [comment]
Run this command - 
export KEEP_NETWORK=1 
Before running the fluxion.

**Comment by defatpm** [comment]
I run that command before running fluxion, accross multiple attempts, and it does not change the outcome at the last step.

**Comment by deltaxflux** [comment]
```
su root
export FLUX_KEEP=1
./fluxion```

**Comment by defatpm** [comment]
@deltaxflux that command did not change the result. Thank you looking into the issue, though. I will update if I find any work around.

**Comment by its0x08** [comment]
the command worked for me ;) !

**Comment by defatpm** [comment]
@its0x08 referring to FLUX_KEEP=1 or KEEP_NETWORK=1?

**Comment by deltaxflux** [comment]
KEEP_NETWORK=1

**Comment by defatpm** [comment]
@Intek13x what VNC package are you using? For me, that command kept fluxion up until the last step, rather than crash at the beginning.
