### ISSUE TITLE
it doesn't deauthenticate the clients after the ap restart cause of channel changing....any help

### ISSUE THREAD

**Issue by minanagehsalalma** [deltaxflux/fluxion#434]
### Which version of fluxion are you using?
0.25

### Which revision of fluxion are you using?
129
### What distribution of Linux (including the version) are you running it on?
wifislax64-1.0 final version

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
tp-link wl-722n          -  chipset :atheros ar9271  
### Which is the driver for it?
laptop   
### Does it support injection ( output of aireplay-ng -9)
03:09:10  Trying broadcast probe requests...
03:09:12  No Answer...
03:09:12  Found 3 APs

03:09:12  Trying directed probe requests...
03:09:12  88:E3:AB:xx:xx:xx - channel: 5 - ''
03:09:12  Ping (min/avg/max): 1.193ms/13.110ms/30.682ms Power: -54.77
03:09:12  30/30: 100%

03:09:12  Injection is working!

03:09:12  88:E3:AB:AC:xx:xx - channel: 5 - ''
03:09:13  Ping (min/avg/max): 11.710ms/22.452ms/37.697ms Power: -55.70
03:09:13  30/30: 100%

03:09:13  88:E3:AB:AC:xx:xx - channel: 5 - 'Cxxxa'
03:09:13  Ping (min/avg/max): 10.234ms/23.313ms/40.369ms Power: -55.83
03:09:13  30/30: 100%
 
### General description of your issue along with the steps to reproduce it

1- ./install.sh
then ./fluxion

### Other important information
nothing

**Comment by deltaxflux** [comment]
I added a channel log to make deauth more effective.

**Comment by minanagehsalalma** [comment]
hey bro the problem isn't fixed .... it's still not deauth the clients after channel change

**Comment by deltaxflux** [comment]
Hey, there is a reason why I don't change this

**Comment by minanagehsalalma** [comment]
when the router restart the channel change it s an automatic process.. i want the script to auto detect the channel change by running airodump-ng every three minutes or when there are no  clients to deauth   ... can you do this

**Comment by deltaxflux** [comment]
No

**Comment by minanagehsalalma** [comment]
WHY BRO WHY 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by minanagehsalalma** [comment]
the script will be awesome if you did this 😉😉😉😉😉😉😉😉😉
