### ISSUE TITLE
the fake ap sends http://go.microsoft.com/fwlink/?LinkID=219472&clcid=0x409  as fake page  .... and  doesn't check the password if it s wrong or right  and any other url that has any thing after .domian name like this  http://www.msn.com/en-us/?refurl=%2feg%2f%3focid%3dwispr%26pc%3du477 ......  any ideas 

### ISSUE THREAD

**Issue by minanagehsalalma** [deltaxflux/fluxion#435]
Fill in the answere for all of the questions below, OTHERWISE YOUR TICKET WILL BE INSTANTLY CLOSED.

Which version of fluxion are you using?

0.25

Which revision of fluxion are you using?

136

What distribution of Linux (including the version) are you running it on?

wifislax64-1.0 final version

What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.

tp-link wl-722n - chipset :atheros ar9271

Which is the driver for it?

laptop

Does it support injection ( output of aireplay-ng -9)

03:09:10 Trying broadcast probe requests...
03:09:12 No Answer...
03:09:12 Found 3 APs

03:09:12 Trying directed probe requests...
03:09:12 88:E3:AB:xx:xx:xx - channel: 5 - ''
03:09:12 Ping (min/avg/max): 1.193ms/13.110ms/30.682ms Power: -54.77
03:09:12 30/30: 100%

03:09:12 Injection is working!

03:09:12 88:E3:AB:AC:xx:xx - channel: 5 - ''
03:09:13 Ping (min/avg/max): 11.710ms/22.452ms/37.697ms Power: -55.70
03:09:13 30/30: 100%

03:09:13 88:E3:AB:AC:xx:xx - channel: 5 - 'Cxxxa'
03:09:13 Ping (min/avg/max): 10.234ms/23.313ms/40.369ms Power: -55.83
03:09:13 30/30: 100%

General description of your issue along with the steps to reproduce it

1- ./install.sh
then ./fluxion

Other important information

this problem only in laptop or desktop pc not phones 

.... and the page be like it designed in just bad html not a normal you can see this in the photo number one and two and in these it don t Receives
the password ... in the photo number 3 & 4 it do what it expected to do it works too good ..... any ideas ??? 
![1](https://cloud.githubusercontent.com/assets/20546638/23378508/0330d85e-fd3c-11e6-8b8c-8166c44982b7.png) 
![3](https://cloud.githubusercontent.com/assets/20546638/23378509/03543826-fd3c-11e6-8aca-96f67ef8e9cb.png)
![4](https://cloud.githubusercontent.com/assets/20546638/23378701/c33896be-fd3c-11e6-9eef-1c86d67f1068.png)
![2](https://cloud.githubusercontent.com/assets/20546638/23378784/1e5677fa-fd3d-11e6-9876-f250707f5de0.png)

**Comment by deltaxflux** [comment]
So what is the problem ?

**Comment by minanagehsalalma** [comment]
the pages with bad html does not receive the password although it is http not https you can see the url of it to understand the problem well..................... when i connect to the fake ap with my laptop it give http://go.microsoft.com/fwlink/?LinkID=219472&clcid=0x409 as fake page and it doesn't receive the password and have bad html .... i want  the script it to receive password  ... ... what is the meaning of the script if it did not receive the password with the general fake page  ----- here is the url of the pages that not receive the password ... 1- http://movizland.com/movies/فيلم-arachnicide-2014-مترجم-بجودة-1080p-web-dl/ 2- http://go.microsoft.com/fwlink/?LinkID=219472&clcid=0x409   .... .and that just an example ... almost all pages have this problem  .... please reopen and fix the issues

**Comment by deltaxflux** [comment]
I don't think so

**Comment by minanagehsalalma** [comment]
but i explained the problem to you.... i am so sad to read that 😢😢😢😢😢😢😢😢😢😭😭😭😭😭😭😭😭😭😭
