### ISSUE TITLE
[Feature request] Display entered password whether it is right or wrong

### ISSUE THREAD

**Issue by nisc3** [deltaxflux/fluxion#436]
### Which version of fluxion are you using?
0.24

### What distribution of Linux (including the version) are you running it on?
Kali Linux on Raspberry Pi 3

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TP-Link TL-WN722N 

### Which is the driver for it?
ath9k

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
Is it possible to display password (or whatever the victim has entered) in a separate window? I can see attempts done but it is nice to have a separate window to display them.

**Comment by deltaxflux** [comment]
You can already looked for the entered passwords to do this:
`cat /root/pwlog/YOUR_WIFI.txt`

**Comment by nisc3** [comment]
Is it possible to display them on a separate window?

**Comment by nisc3** [comment]
Also why monitor mode is mon0 but not wlan0mon? Is there any difference between them?
