### ISSUE TITLE
fluxion line 765 No such file or directory

### ISSUE THREAD

**Issue by vinnyamp** [deltaxflux/fluxion#437]
Fluxion version:
**0.25 rev 136**

Linux distribution:
**Kali Linux 2**

Wireless adapter:
**AWUS036NHA**

Driver:
**ath9k_htc - Atheros Communications, Inc. - AR9271 802.11n**

Injection Mode:
**Yes**

**Issue:**
When I start fluxion with ```./fluxion``` I get the error below after selecting the interface language, it was working fine before I update to the latest rev 136.
![image](https://cloud.githubusercontent.com/assets/4457878/23398541/bccb9724-fd7b-11e6-864d-182ca40f12f7.png)

**Comment by deltaxflux** [comment]
`mv airmon lib/airmon`
