### ISSUE TITLE
Pause fakeAP when victim power off his router

### ISSUE THREAD

**Issue by nisc3** [deltaxflux/fluxion#438]
### Which version of fluxion are you using?
0.24

### What distribution of Linux (including the version) are you running it on?
Kali Linux on Raspberry pi

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Tplink TLwn722n

### Which is the driver for it?
ath9k

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
Is it possible to pause fakeAP when victim power off his router or reboots router and continue attack when victim is back online. 

### Other important information
This is good because victim thinks that the network is from his router only. If fake AP continues to run when victim is offline, he will never going to enter the password.

**Comment by deltaxflux** [comment]
Maybe I add a timeout but back to your Idee. 
Which event should start the fakeAP again?

**Comment by nisc3** [comment]
I don't know much about wifi terminology. But a scan to search that network? Beacons or data packet of that network?

My idea is to pause hostapd and not the fakeDNS or the deauth attack.
Is it possible to implement this sort of functionality? Any limitations?

**Comment by deltaxflux** [comment]
If you disable hostapd you will shutdown the complete fake AP

**Comment by nisc3** [comment]
Is there any other way around to make it possible?

**Comment by deltaxflux** [comment]
maybe a timeout is the best option so it will end after 1 hour

**Comment by disquette38** [comment]
For my part I do it in manual, adding the lines --uptime (airmon-ng)

**Comment by deltaxflux** [comment]
That doesn't make sense

**Comment by nisc3** [comment]
Why it is not possible to automate the process of starting hostapd?
