### ISSUE TITLE
Small issue.

### ISSUE THREAD

**Issue by omarzidan97** [deltaxflux/fluxion#44]
Hello,
Thank you so much for the huge effort.
just a small problem,
after running "./fluxion" then "./Installer.sh", the same issue remains ... 
Dhcpd...........Not installed 
Hostapd.........Not installed
Lighttpd........Not installed
Php5-cgi........Not installed

thanks in advance.

**Comment by deltaxflux** [comment]
So you think that this check is useless. There isn't a huge different between with and  & without check.

**Comment by omarzidan97** [comment]
nope, I meant the same issue exists before and after using it.

**Comment by strasharo** [comment]
What distribution are you running it on?

**Comment by omarzidan97** [comment]
Kali Linux 2016.1

**Comment by strasharo** [comment]
Can you paste the output from "bash -x ./Installer.sh", please?

**Comment by Cosmic4x2** [comment]
Cannot install php5-cgi on a fresh Kali install I tried installing php7-cgi the program does run creates AP the client side does get the Spoofed HTML  but does not send password back to aircrack.

**Comment by freeroute** [comment]
The same problem was last week. I installed the missing php5-cgi from the kali.2 repository.

**Comment by Cosmic4x2** [comment]
Can you send me a link for that repository

**Comment by Cosmic4x2** [comment]
Hey got it thanks....

**Comment by Cosmic4x2** [comment]
Nice.. Does not seem to work on chrome...
