### ISSUE TITLE
help fluxion 2

### ISSUE THREAD

**Issue by kizito12** [deltaxflux/fluxion#441]
hello!!!i installed fluxion in my kali 2 by wget https://raw.githubusercontent.com/deltaxflux/fluxion/master/install/install.sh && bash install.sh,but i don't now how to start fluxion.please help me.
![capture d ecran de 2017-03-01 04-29-45](https://cloud.githubusercontent.com/assets/26103509/23444898/2e4250ca-fe38-11e6-8408-20e12f3de6e1.png)

**Comment by Goodman01** [comment]
Try :
$ fluxion

**Comment by imrf** [comment]
anyone knows how to fix this
          ┌──────────────────┤ Fluxion Disclaimer ├──────────────────┐
          │                                                          │ 
          │ Fluxion is intended to be used for legal security        │ 
          │ purposes only, and you should only use it to protect     │ 
          │ networks/hosts you own or have permission to test. Any   │ 
          │ other use is not the responsibility of the developer(s). │ 
          │ Be sure that you understand and are complying with the   │ 
          │ Fluxion licenses and laws in your area.  In other words, │ 
          │ don't be stupid, don't be an asshole and use this tool   │ 
          │ responsibly and legally.                                 │ 
          │                                                          │ 
          │                          <Ok>                            │ 
          │

**Comment by imrf** [comment]
@kizito12  look.. open new terminal , type this codes 
cd Desktop
cd fluxion
,/fluxion
then you can start it easily ..  just type the number of what u want to choose
