### ISSUE TITLE
Does not redirect on the gateway

### ISSUE THREAD

**Issue by Sfire6** [deltaxflux/fluxion#442]
### Which version of fluxion are you using?
v0.25

### Which revision of fluxion are you using?
rev. 136

### What distribution of Linux (including the version) are you running it on?
kali linux 2.0

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
BCM4331 802.11a/b/g/n

### Which is the driver for it?
b43-firmware

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
Doesn't redirect on the gateway. Tried on android phone, chrome browser. I've tried to put the gateway manually and worked just fine. Could be https the problem?

### Other important information
_

**Comment by CyberEyE007** [comment]
when i connect fake access point to Auto redirect on the browser are not working... in mobile

**Comment by Sfire6** [comment]
@CyberEyE007, every mobile, are you sure? I've tried only android.

**Comment by Sfire6** [comment]
@deltaxflux , thank you for closing the thread without even replying.

**Comment by deltaxflux** [comment]
Your welcome
