### ISSUE TITLE
Creating a shortcut in the sidebar

### ISSUE THREAD

**Issue by Labzz** [deltaxflux/fluxion#45]
Issue priority = 0 because it isn't related to the program. 
sudo gnome-desktop-item-edit ~/*fluxion*/ --create-new
sudo mv *fluxion.desktop /usr/share/applications/

And you don't have an Icon for the program yet? (prefer 256x256) ^-^

But it wont start from bash, What do i've to add in the execute line from the fluxion.desktop file? 

i thought about something like the following: "fluxion;${SHELL:-bash}". Can someone help me further?

Hope to hear you soon, thanks in advance.

**Comment by strasharo** [comment]
Just launch it from terminal like everyone does.
