### ISSUE TITLE
Is there anyone to make it work on mac os x?

### ISSUE THREAD

**Issue by xxf1995** [deltaxflux/fluxion#46]
I tried to install it on Kali. But I installed Kali as a virtual machine using VMware and can't scan for Wi-Fi AP properly.

**Comment by xxf1995** [comment]
I did some research, people say a usb Wi-Fi adapter is required. Is that so?

**Comment by strasharo** [comment]
You'll need to attach a *supported* USB wireless adapter to your VM.
http://www.aircrack-ng.org/doku.php?id=compatibility_drivers

**Comment by Sidharthoo7** [comment]
You need surely a wifi adapter for this here are some best packet-injection or  packet-capture enabled wireless adapters : 
TP-Link TL-WN722N 
TENDA TE-W311MI Wireless
Atheros AR9271
Ralink RT3070
Ralink RT3572
Realtek 8187L
Alfa AWUS051NH
Alfa AWUSO36NH
Alfa AWUS036NHA

My best one is TP-Link TL-WN722N and it is giving nice output to me so will suggest this one.
