### ISSUE TITLE
Fake AP : target entries not sent back.

### ISSUE THREAD

**Issue by Dhacan** [deltaxflux/fluxion#51]
Hi,
I've a little problem using fluxion. Everything works fine until the target enters his password.
Fake AP is running but nothing what the target enters is sent back. The target will still access to internet when entering the good password (through fake AP).
However, FakeDNS doesn't show any activity when the target try to reach a website.
Attack is done on last stable Kali through VMware with a key capable of injection (ethernet cable on the physical computer). Target is using an integrated wifi adapter.
Thank you.

**Comment by Dhacan** [comment]
Might be stupid but didn't i check the target DNS was set on "manual"...
However target fake AP is known as "SSID 2" (same name 2) so even if the signal is stronger, it won't automatically connect to it (Win 10) as the original SSID is displayed too.

**Comment by deltaxflux** [comment]
Well it is clear that the client woudn't connect automaticaly because  the Fake AP don't have a password, ( the authy type is diffrent ). So if you need more detailed information about wifi stuff whatever contact me
