### ISSUE TITLE
Can't find any clients

### ISSUE THREAD

**Issue by wmatthews** [deltaxflux/fluxion#53]
I have a Ralink RT2870/3070 - rt2800usb. When I am just using aircrack-ng and all the other tools without fluxion it all works perfectly. I can put it into monitor mode and see clients connected to their ap's. When I try it using fluxion it never see any clients.

It works almost perfectly with my internal wifi card. Just can't get anyone to connect to my DHCPd Server. I have a feeling it is from limitations of the Intel 6235 - iwlwifi. I know it is crap. No powerful enough to get people to connect to my AP instead of their own.

Any suggestions you can give me to help me out a little bit?

**Comment by ApatheticEuphoria** [comment]
If power is the issue you probably have 3 options.
1.buy a more powerful card.
2.consider using a wireless repeater or range extender.
3.(illegal depending on what country you live in) Up the txpower on your wireless card.(requires changes to crda and regulatory bin.)

**Comment by wmatthews** [comment]
Thanks for the speedy reply. I see now that it is my Gentoo laptop that is the problem. It is all working just fine on my server. Just have to figure out what it is on my laptop.

**Comment by strasharo** [comment]
@wmatthews , so you were using a rt2800usb inside a physical machine (not a VM), right? Were you experiencing any crashes while fluxion was bringing the interface in monitor mode?
