### ISSUE TITLE
grep error when choosing to scan all channels

### ISSUE THREAD

**Issue by divjl** [deltaxflux/fluxion#56]
Hello.

I'm using Kali-Rolling (2016.1) and a TL-WN722N adapter.

When I try to crack WPA, the AP scan fails depending on the channels that I choose. I got this error after pressing CTRL+C on the window running airodump-ng:

```
expr: syntax error
                        WIFI LIST 

 ID      MAC                      CHAN    SECU     PWR    ESSID

grep: /tmp/TMPflux/dump-01.csv:: No such file or directory
grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines: No such file or directory
  1)	head: /tmp/TMPflux/dump-01.csv: invalid number of lines	 	 	  100%	 

 (* )Active clients

        Select target. For rescan type r
      #>
```

It happens if I choose "All channels" in the previous screen. It also happens if I choose some specific channels (channel 1 seems to be the most problematic).

I some rare occasions it works even if I choose "All channels"

If I try other channels (6 for example), it never happens.

**Comment by deltaxflux** [comment]
Do you use a native debian version ?
If please use 1) kali 2 or kali 2016.1 
or you can try the old version: [https://github.com/deltaxflux/fluxion/tree/master/old/version.2](url)

**Comment by divjl** [comment]
As I mentioned, I'm using Kali-Rolling (2016.1).

**Comment by deltaxflux** [comment]
Well one of my friend has the same issue. The problem cold be that your WIFI card don't support the >>WIFI Monitor<< mode, try if your wifi card support that by running: 
`sudo airmon-ng check kill `
Kill the pids e.g. sudo kill 1234
`sudo kill [pid]`
Enable monitor mode by running:
`sudo airmon-ng start [interface]`
_e.g. sudo airmon-ng start wlan0_

**Comment by divjl** [comment]
I don't think that is the problem. I'm using a TL-WN722N adapter which is widely known for being a reliable card for pentesting. Besides, it works fine with airmon-ng.
