### ISSUE TITLE
SSL/HTTPS bug ????

### ISSUE THREAD

**Issue by cloverdoser** [deltaxflux/fluxion#57]
You were able to fix the access ssl web yet?

**Comment by deltaxflux** [comment]
No, https://github.com/deltaxflux/fluxion/issues/43 
But I hopefully I’m able to fix that

**Comment by filzstift** [comment]
hi, there is a linset mod with integrated ssl. maybe this does help implementing it to fluxion?
http://pokoxemo.blogspot.de/2016/05/como-hackear-redes-wpawpa2-con-linset.html

**Comment by tuthieu** [comment]
Does the new Fluxion support HTTPS redirect?

**Comment by deltaxflux** [comment]
Yes but not for u :D take a look at the branch branch

**Comment by tuthieu** [comment]
I used both master branch and developer branch.But HTTPS doesn't work?

**Comment by deltaxflux** [comment]
It does work if you know how

**Comment by tuthieu** [comment]
Can you teach me how to use it?
What Linux edition do you use?

**Comment by deltaxflux** [comment]
Like the branch already says is it for devs, if you don't know how it is your problem.

**Comment by tuthieu** [comment]
Hi Deltax
I have an old fluxion.I changed the new fluxion webinterface to certssl to create certificate.
I use the old version but the fake ssl doesn't support anymore.So I use the new edition but when I open both http and https.It doesn't show Login page.
Can you guide me?
Thanks you.Sorry for my bad English.
