### ISSUE TITLE
hi when i select an interface "wlan0" then i press 1 the system just hang. pls help

### ISSUE THREAD

**Issue by junann30** [deltaxflux/fluxion#58]
![untitled](https://cloud.githubusercontent.com/assets/20052326/16267981/1812d856-3895-11e6-9c13-3e2b90ab4adf.jpg)

**Comment by junann30** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20052326/16267640/93ef2198-3893-11e6-807c-13c69bc7ca8c.png)

**Comment by deltaxflux** [comment]
You can use the old version flux or update kali

**Comment by junann30** [comment]
sorry im newbie in kali can you pls tell me how to use that link or download the file?

git clone https://github.com/deltaxflux/fluxion/tree/master/old/version.2            is this the command?

**Comment by jh0001** [comment]
Hi @deltaxflux , I have the same problem. I  try to update kali but also hung. I try to use the old version. but It tell me "There is no wireless cards".

![image](https://cloud.githubusercontent.com/assets/21150757/17835192/723e7d86-6792-11e6-917d-68f53c6ecba3.png)

**Comment by deltaxflux** [comment]
What is if you enable the Monitor mode with airmon manually ? 
`sudo airmon-ng `
`sudo airmon-ng start [wlan device]`

**Comment by jh0001** [comment]
I think this is the problem. This process will run event I restart the system.

![image](https://cloud.githubusercontent.com/assets/21150757/17841863/aa3320d0-684f-11e6-821f-0044262e9bdd.png)
