### ISSUE TITLE
Using AFLA card crashes machine.

### ISSUE THREAD

**Issue by chocolatebars** [deltaxflux/fluxion#62]
Crash happends because of line 1022:
`
rmmod -f "$WIFIDRIVER" &>$flux_output_device 2>&1`

This command causes the machine to crash.

**Comment by deltaxflux** [comment]
I need the more details. Which card do you use? What crashes? 
Please send me an email

**Comment by chocolatebars** [comment]
Sorry, very new to github.
Please tell me where I could find your E-Mail address.

Anyways, details you requested below.

It only occurs with my
`Card:	 ALFA AWUS036NH. 
Driver:	rt2800usb.
Chipset:	Ralink Technology, Corp. RT2870/RT3070
`

If I would specify any error logs or somethings, I'd love to. Please point me to where these logs are.
Also; I tried running without the rmmod -f, and the script still works perfectly.

Kind Regarts.

**Comment by deltaxflux** [comment]
_Well it can make this script unstable. But I have never done experience with ALFA cards, so I don't have any chances to confirm the issue. Rmmod remove kernel modules (with the force option). However you can start to create a pull request (fork -> fix the issue -> pull)_

**There are no logs in the normal mode. If you want you:in the developer mode** 
`export FLUX_DEBUG=1`

If you want more details, contact me 
**Here is my offical email adress: deltax.fluxion@gmail.com**

**Comment by strasharo** [comment]
@chocolatebars , were you using fluxion inside a VM of some sort?
