### ISSUE TITLE
Error in Wifi List

### ISSUE THREAD

**Issue by Vodker** [deltaxflux/fluxion#63]
In new version (rev. 39) ESSID not shows in Wifi List and attack is not possible.
![sin titulo-1](https://cloud.githubusercontent.com/assets/19956680/16682161/4c6b6ae4-44f9-11e6-9684-19c50119bf80.jpg)

**Comment by jeanmartin77** [comment]
By my side - Same version on Raspberry PI 3 and Alfa modem - I have WPR and ESSIS column with all infos.
