### ISSUE TITLE
Not Working Correctly?

### ISSUE THREAD

**Issue by omerbadawy11** [deltaxflux/fluxion#64]
Hello, 
when i type (1) for crack wifi
i get 
/root/Downloads/fluxion-master/fluxion: line 970: ./airmon: No such file or directory
/root/Downloads/fluxion-master/fluxion: line 971: ./airmon: No such file or directory
There are no wireless cards, quit...
any help?
Thanks.

**Comment by faroukakoul** [comment]
cd /root/Downloads/fluxion-master/ 
chmod +x airmon 

and it will work ;)

**Comment by deltaxflux** [comment]
move in the directory before you start fluxion
