### ISSUE TITLE
Wanna Some Help here 

### ISSUE THREAD

**Issue by hemwahdan** [deltaxflux/fluxion#65]
After installed fluxion tool
and run it 
airodump can't read any clients 
i try kail terminal but it work on terminal found clients 
in tool don't get handshake and don't read clients 
sorry for bad english

**Comment by deltaxflux** [comment]
Which kali version do you use?

**Comment by hemwahdan** [comment]
Kali Linux Rolling 2016.1
BCM43228 wifi card 
i try with intel wifi card , worked well 
but with BCM43228 wifi card  don't found any clients in airodump-ng , i tried in kail terminal found clients and get handshake
