### ISSUE TITLE
Doesnt check for passwords :(

### ISSUE THREAD

**Issue by princeofguilty** [deltaxflux/fluxion#67]
Fluxion worked grate, my problem with linset was about the DHCP, so no one could open my network because it cant obtain ip address, but in fluxion i connected to my hotspot and entered my real password but i didnt get anythink on fluxion, it tells me the number of attempts but when i tried the real password it didnt tell me that it got the real password

**Comment by princeofguilty** [comment]
on terminal i typed apt-get install dhcpd and now its working xD

**Comment by deltaxflux** [comment]
Well there should be now a txt located in /root/pwlog/ 

you can open this with
`cat /root/pwlog/[name].txt ` 

For more details contact me deltax.fluxion@gmail.com

**Comment by deltaxflux** [comment]
It will only stop if the password is correct
