### ISSUE TITLE
Check.php not found

### ISSUE THREAD

**Issue by okbabsh** [deltaxflux/fluxion#68]
I've started everything and everything is working fine and even better than linset but when i connect to the network and enter the password it show page not found and it means "check.php" page, the first fluxion check shows everything is OK! and green < but i only have this issue, and the password never comes back to me because of check.php not found

**Comment by okbabsh** [comment]
keep in mind that i've tried installing dhcpd again with apt but nothing seems to be working pleaaase help me

**Comment by deltaxflux** [comment]
so you don't setup fluxion corrrectly. Search for debs. and install it with sudo dpkg -i [name.deb]
