### ISSUE TITLE
2 major issues found

### ISSUE THREAD

**Issue by ssepa001** [deltaxflux/fluxion#70]
Hi, 

Awesome program you created here. I was messing around with it and found 2 big issues:

1. Downloaded revision 43 but the updater thought the newest revision is 41? so it downgraded to 41. 

2. When the user enters password on the fake site I get : check.php was no found / unable to connect.

Keep up the good work!

**Comment by deltaxflux** [comment]
The first issue is fixed, I will take a closer look for the second one.

**Comment by deltaxflux** [comment]
You don't install the php5-cgi correctly.

**Comment by deltaxflux** [comment]
You don't install the php5-cgi correctly.
