### ISSUE TITLE
Fake web does start on iMac with Safari?

### ISSUE THREAD

**Issue by aquilabianca8** [deltaxflux/fluxion#71]
I tryed the attack and type password on fake browser in Windows and work; but the same process in Safari (iMac) don't work: don't appear fake web..
Please help me..

**Comment by deltaxflux** [comment]
Not confirmed, I don't have a mac / hackingtosh.

**Comment by aquilabianca8** [comment]
Thanks anyway

Il giorno 05 ago 2016, alle ore 12:13, deltax <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Not confirmed, I don't have a mac / hackingtosh.

-

**Comment by deltaxflux** [comment]
Please wait for more information. I will ask on HF

**Comment by aquilabianca8** [comment]
What is “HF”?
Sorry but this is my first time to write in this forum; moreover my english is not very well..

My hardware:
Fluxion on kali Linux 2.0 USB live persistence, with external wifi card Alfa model AWUS036NHA (Atheros AR9271 chipset)

1) Start attak on this machine and work.

2) Then i tried to connect on the fake AP with iMac 27” 5k (SO El Capitan), but the fake AP don’t start..


Il giorno 05 ago 2016, alle ore 12:21, deltax <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Please wait for more information. I will ask on HF

**Comment by deltaxflux** [comment]
_Then I tried to connect to the fake AP with iMac 27” 5k (SO El Capitan), but the fake AP don’t start.._

It is confusing to read this anyway I don't understand you. Start the fake AP?  Can you connect to this ? And how do you connect if it isn't started? Do you mean you have problems with loading the web page what so ever? 

HF is a big forum: [http://hackforums.net/](url)

**Comment by aquilabianca8** [comment]
I have got two personal computer:

Computer A) PC Windows, with Kali linux live usb persistence Fluxion installed, with usb Wi-Fi card Alfa atheros AR9271 chipset;

Computer B) iMac with Mac OS X El Capitan

1) I start Fluxion on my computer A and works well: start FAKEDNS, start DHCP and MDK3 to deauth clients.

2) Then i try to test the process with my computer B, therefore i open the browser (Safari) but it doesn't open (appear message error: connection lost) therefore don't appear the fake AP interface to write in Wi-Fi password..

Do you understand?

Il giorno 06 ago 2016, alle ore 08:27, deltax <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Then I tried to connect to the fake AP with iMac 27" 5k (SO El Capitan), but the fake AP don't start..

It is confusing to read this anyway I don't understand you. Start the fake AP? Can you connect to this ? And how do you connect if it isn't started? Do you mean you have problems with loading the web page what so ever?

HF is a big forum: http://hackforums.net/<url>

-

**Comment by deltaxflux** [comment]
Well Hopefully you know that you need to connect manually to the fake AP?
