### ISSUE TITLE
Client Online... but no Password recovered?

### ISSUE THREAD

**Issue by Schwarzhund** [deltaxflux/fluxion#73]
Using FakeAP option in Fluxion 0.23:
- 1 AWUS036NH
- No Ethernet Connection

Handshake is successful.
Deauth seems to work (MDK3).
DHCP & FAKEDNS appear active? (please see images below).
But no Password.

What part is not working?
(Is Eth0 connection requuired?)

Vielen Dank!
![fakedns](https://cloud.githubusercontent.com/assets/20869864/17454889/70361c26-5b5b-11e6-8952-2fb0bad2fd37.JPG)

![dhcp](https://cloud.githubusercontent.com/assets/20869864/17454894/8f4635b0-5b5b-11e6-8cb8-00c1383859bd.JPG)

**Comment by deltaxflux** [comment]
Well if you have attempts,( look at the right top windows ). You should check the pwlog. 

**Check out if you have a text file:** 
`ls /root/pwlog/`

**Open the file with cat or nano**
`cat /root/pwlog/[name].txt`
