### ISSUE TITLE
Php5-cgi is not installed

### ISSUE THREAD

**Issue by Spaceport-2507** [deltaxflux/fluxion#74]
Package php5-cgi is not available and has no installation candidate

**Comment by chanakyacool** [comment]
its not supported install php PHP 7.0.9-1 ur problem will be solved

**Comment by Spaceport-2507** [comment]
@chanakyacool  Nothing happens

root@Kalilinux1:~# apt-get install php7.0.9-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.0.9-1
E: Couldn't find any package by glob 'php7.0.9-1'
E: Couldn't find any package by regex 'php7.0.9-1'
root@Kalilinux1:~# cd fluxion
root@Kalilinux1:~/fluxion# apt-get install php7.0.9-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.0.9-1
E: Couldn't find any package by glob 'php7.0.9-1'
E: Couldn't find any package by regex 'php7.0.9-1'

**Comment by deltaxflux** [comment]
## **First of all we need to modify the sources.list**

`sudo nano /etc/apt/sources.list`

**Than add this line :**

deb http://ftp.de.debian.org/debian/ jessie main contrib

**It can looks like this:**

deb http://http.kali.org/kali kali-rolling main non-free contrib
deb http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu lucid main

#Debian
deb http://ftp.de.debian.org/debian/ jessie main contrib

**Download key and add key:**
`curl https://debgen.simplylinux.ch/txt/jessie/gpg_e00a2b3f751ae92de06f69c527d8fde28f56d923.txt | sudo tee /etc/apt/gpg_keys.txt`

**Update your sources:**
`sudo apt-get update`

**Install packets**
`sudo apt-get install php5-cgi`
`sudo apt-get install isc-dhcp-server`

**Comment by deltaxflux** [comment]
I will change the installer
