### ISSUE TITLE
i type password on browser , but still no file on /root/pwlog/ created

### ISSUE THREAD

**Issue by SamkunSama** [deltaxflux/fluxion#75]
Hello Team
my browser on phone is asking for password i type it and type enter but still asking to type again ,  no file on /root/pwlog/ created

**Comment by deltaxflux** [comment]
Do have correctly php5-cgi installed?

**Comment by SamkunSama** [comment]
is there a way to check if its correctly installed am using wifislax 4.11.1

**Comment by deltaxflux** [comment]
**I thought that there are packets issues in wifislax 4.11.1 <** 
I recommend that you install wifislax 4.12 rc3, kali or a native debian. Or you update your packets manually.

**Comment by SamkunSama** [comment]
ok will try that thanks! will let u know of the result

**Comment by deltaxflux** [comment]
Fine

**Comment by devrajashwin** [comment]
iam suing kali-rolling , (updated)
and i have same problem 
i cant see any file inside of                  root/pwlog/(empty)

**Comment by deltaxflux** [comment]
Install php5-cgi
Run thr installer, I updates fluxion. 
`sudo git pull`

**Comment by devrajashwin** [comment]
ok will check it now and will reply u after testing sir,
thankyou for ur support

**Comment by devrajashwin** [comment]
sir just check this ihave screen shot ,
in this after the vitcm redirected to login page and he enter the  password ,after that nothing happens in fluxion terminals
![screenshot from 2016-08-07 20-30-41](https://cloud.githubusercontent.com/assets/20875171/17463166/febfb98e-5caf-11e6-9549-90f54dab7b28.png)

**Comment by deltaxflux** [comment]
Well I tested it again today and I had success. Please note that there _is maybe a problem with PHP 7.0.9-1_. Please remove it. Furthermore the pwlog file get created **if** you have any attempts.  
I personally tested it today on 3 different devices (android 6.01; windows 8, deepin) 
![bildschirmfoto_2016-08-07_18-30-06](https://cloud.githubusercontent.com/assets/17337753/17463940/1b7efa8a-5cd3-11e6-8cc3-1693be8a47d6.png)
![bildschirmfoto_2016-08-07_18-31-47](https://cloud.githubusercontent.com/assets/17337753/17463941/1ccb979a-5cd3-11e6-904e-b1c08263afe4.png)
![bildschirmfoto_2016-08-07_19-03-12](https://cloud.githubusercontent.com/assets/17337753/17463942/1d4b0700-5cd3-11e6-966b-c9e6f7aa0281.png)

**Comment by devrajashwin** [comment]
sir thank-you so much for help i will try once again

**Comment by deltaxflux** [comment]
No problem :)

**Comment by markcoronado** [comment]
I'm having the exact same problem as devrajashwin, nothing happens after the victem enters the password.
I have php7.0.cgi installed & would like to try it with php5.cgi but I haven't been able to find the file anywhere. Could you advise me where to get it please, & any special instructions on how to install it.

**Comment by SamkunSama** [comment]
i tried on Kali linux, but i have this issue :+1:  root@kali:~# apt-get install php5-cgi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package php5-cgi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'php5-cgi' has no installation candidate

**Comment by markcoronado** [comment]
That is the exact same problem I’m having. What version of kali are you using? I’m using 2016.1 

Please let me know if you find a solution.

I’ve been searching all over the web & found many that are having this problem but no solution.

I’ll let you know if I find one.

**Comment by markcoronado** [comment]
I finally found out how to install the php5-cgi
I added these to my source list.
deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free
# For source package access, uncomment the following line
# deb-src http://http.kali.org/kali sana main non-free contrib
# deb-src http://security.kali.org/kali-security sana/updates main contrib non-free
After that i ran apt-get update
apt-get -f install
then apt-get install php5=cgi
And I finally got it installed but it didn't solve my problem,
I'm still not receiving the password after it is entered.

**Comment by SamkunSama** [comment]
yes that's nice that you found out that, i fixed the issue now, you need to unistall PHP7    

using :
sudo apt-get purge php7*

then try to reinstall php5-cgi

**Comment by SamkunSama** [comment]
root@kali:~# my   /etc/apt/sources.list


deb http://http.kali.org/kali kali-rolling main non-free contrib


deb http://repo.kali.org/kali kali-rolling main non-free contrib

deb http://security.debian.org/debian-security wheezy/updates main

deb http://ftp.de.debian.org/debian wheezy main

**Comment by deltaxflux** [comment]
With the new Installer you can install php5-cgi
