### ISSUE TITLE
New design 

### ISSUE THREAD

**Issue by deltaxflux** [deltaxflux/fluxion#76]
This is _not_ a real issue. I have created two different designs. Which you like more ?

1. Old

![bildschirmfoto_2016-08-07_20-40-59](https://cloud.githubusercontent.com/assets/17337753/17464468/b9e6a694-5cdf-11e6-9de4-af4eed892879.png)

2. New

![bildschirmfoto_2016-08-07_20-41-42](https://cloud.githubusercontent.com/assets/17337753/17464473/c4a27ad6-5cdf-11e6-9665-916f842c3362.png)

**Comment by freeroute** [comment]
For me the new design is better.

**Comment by gitby2** [comment]
The first one!

**Comment by carbon3180** [comment]
New is good.
