### ISSUE TITLE
Login Page No.1 issue

### ISSUE THREAD

**Issue by gitby2** [deltaxflux/fluxion#77]
The setup works with all, but one Login Page: "Page 1- English [ENG] (NEUTRA)."
When is page is used, no attempts are recorded or logged - including the correct ones.

**Comment by deltaxflux** [comment]
Php7 installed

**Comment by gitby2** [comment]
I've added a source from one of your posts; but, How can I install Php7?. Using the instructions from others (apt-get install php7*) packages are not found. On Kali

**Comment by devrajashwin** [comment]
downgrade it php5.6
its work fine ,

**Comment by deltaxflux** [comment]
Well if you have php7-cgi installed, the login site don't get generated correctly.  Of you have it remove it with:
`sudo apt-get remove php7.0-cgi`
And install the php5-cgi
`sudo apt-get install php5-cgi`
You can also run  updated  installer version.  You shut be fine. Fluxion does work on Kali 2 / 2016 and eifislax 4.12 rc 2 or higher

**Comment by gitby2** [comment]
Hey Deltaxflux,

Thank you for the response. I have php5-cgi (version 5.6.24) installed. Php7 is not installed and I'm running Kali2.

All the sites from the 'Sites' folder run fine; but all the 'Neutra' capture pages are not recording attempts - including the correct ones.

Hope this clarifies.

**Comment by deltaxflux** [comment]
Hello gitby2,

There might be a problem with your php-cgi version. I use php-5.6.20 and it works well (The other sites won't get generated). Try this version otherwise I have no idea why it couldn't work. 

However He had the same issue: https://github.com/deltaxflux/fluxion/issues/75

**Comment by markcoronado** [comment]
How do you check to see what version of php5 is installed?

**Comment by deltaxflux** [comment]
Type:
` sudo dpkg -l | grep "php"`

or if you have php5-cgi installed 
` sudo dpkg -l | grep "php5-cgi`

**Comment by sohrab96** [comment]
hi. i can't install php5-cgi. when i type "sudo apt-get install php5-cgi" , i get this error:

**Comment by deltaxflux** [comment]
The problem is that you dont't have even php5-cgi installed 
`sudo apt-get install php-cgi`
or 
`sudo apt-get install php5-cgi`
or 
`sudo apt-get install php7-cgi`
or run the installer
`sudo ./Installer`
