### ISSUE TITLE
not automatically conneting to fake ap

### ISSUE THREAD

**Issue by devrajashwin** [deltaxflux/fluxion#78]
sir ,
i have 1 problem to tell u ,
-for ur info  its absolutely working fine and deauth the users ,
and also giving the hand shake ,
1>but its is not automatically connecting to the fake ap 
2> i have to manually connect to fake ap to gain the hand shake ,
3> its is not displaying the login page as soon as i refresh  page i have use the ip fo router to the it will display the login page asking password 
so plz help me sir ,

note:- but before its was working fine ,
automatically display the login page for password as soon as i refreshed it

**Comment by deltaxflux** [comment]
Well you can't automatically redirect the client to fake AP because some responds are not equl

- Same BSSID and same SSID but
- Not the same "wireless security mode" (WPA / 2 whatever)
- If not every part is equal the device don't get connected to the fake AP automatically because the response isn't equal 

Manually connect to the Fake AP to get a handshake ? (you mean password))

3 Issue not known I will take a look, tell me your specs (Browser, operating system: you ; victim; wireless card)

**Comment by devrajashwin** [comment]
ok sir

**Comment by d7ape** [comment]
deltaflux, 

I just installed this awesome application today, and I am having the same problem listed here. Everything works beautifully, however there is no redirection to the login page- also xx.xx.xx.1 does not render a login page. 

if you guys are working on this, let me know! 

One of the best mutli use wifi hacking tools- great job guys!

**Comment by Nicohack** [comment]
I have the same problem @d7ape has : no redirection to the login page, dhcp and dns works well but no login page to see (i.e. 192.168.1.1 for example returns ERR_CONNECTION_RESET on chrome). Can you give us some advices? Thank you for your work   @deltaxflux.

**Comment by Vigilence** [comment]
Same issue.

**Comment by SumanElecto** [comment]
i too have a same problem as fake ap does get connected auromatically. i have to put manually router default address to get the login page except this issue it worked good so far.

**Comment by TheWalkingM3m3** [comment]
Same problem here I'm rolling raspbian on raspberry pi, all works fine but when I connect to the fake-ap with my android and visit a website it redirects me to 192.168.1.1 and displays a 404 not found page. Any solutions yet?

**Comment by deltaxflux** [comment]
Create a new issue with your specific problem

**Comment by deltaxflux** [comment]
Create a new issue with your specific problem
