### ISSUE TITLE
Looking for a person to translate some strings to Chinese

### ISSUE THREAD

**Issue by huigesv123** [deltaxflux/fluxion#82]
add chinese web site

**Comment by deltaxflux** [comment]
Hello @huigesv123 
Feel free to share chinese login pages if you can or commit a chinise translation for fluxion

**Comment by devrajashwin** [comment]
any improvement has been done in ,
in this project ,
so the victim can automaticaly redirect to the login page ,,
or auto matically get connceted to fake ap created by this appliction

**Comment by deltaxflux** [comment]
@devrajashwin 

I don't know if you understand the problem correctly. @huigesv123 wants that I add  chinise web pages.  If you don't know how auto connect works, take a closer look at the issue board

**Comment by huigesv123** [comment]
I mean that can the web injector  add a login page in chinese for victim.😄

**Comment by deltaxflux** [comment]
@huigesv123  are you from china? You have no idea how this acctually works

**Comment by strasharo** [comment]
Can someone (a native speaker) translate the following strings to Chinese, please?

#EN
DIALOG_WEB_INFO_ENG="For security reasons, enter the <b>"$Host_ENC"</b> key to access the Internet"
DIALOG_WEB_INPUT_ENG="Enter your WPA password:"
DIALOG_WEB_SUBMIT_ENG="Submit"
DIALOG_WEB_ERROR_ENG="<b><font color=\"red\" size=\"3\">Error</font>:</b> The entered password is <b>NOT</b> correct!</b>"
DIALOG_WEB_OK_ENG="Your connection will be restored in a few moments."
DIALOG_WEB_BACK_ENG="Back"
DIALOG_WEB_LENGHT_MIN_ENG="The password must be more than 7 characters"
DIALOG_WEB_LENGHT_MAX_ENG="The password must be less than 64 characters"

**Comment by l0xz** [comment]
Does anyone know how to translate the normal Neutra login form to another language? - cannot find the file to edit it.

**Comment by strasharo** [comment]
It's embedded in the main script. If you want to contribute some language, just translate the strings above and I can add it.

**Comment by l0xz** [comment]
Here is it in Romanian: 
`DIALOG_WEB_INFO_ZH="Din motive de securitate, introduceți cheia WPA pentru a avea acces la Internet"
DIALOG_WEB_INPUT_ZH="Parola WPA:"
DIALOG_WEB_SUBMIT_ZH="Trimite"
DIALOG_WEB_ERROR_ZH="Eroare: Parola introdusa NU este corecta!"
DIALOG_WEB_OK_ZH="Conexiunea la Internet va porni in cateva momente."
DIALOG_WEB_BACK_ZH="Inapoi"
DIALOG_WEB_LENGHT_MIN_ZH="Parola trebuie să fie mai mare de 7 de caractere"
DIALOG_WEB_LENGHT_MAX_ZH="Parola trebuie să fie mai mică de 64 de caractere"`

**Comment by strasharo** [comment]
Romanian added, enjoy. ;-) All contributions are welcome. If you manage to collect a Hungarian one just let me know and I'll add it as well.

**Comment by l0xz** [comment]
Hungarian here:

DIALOG_WEB_INFO_ZH="Biztonsági okokból adja meg a WPA kulcsot az internet eléréséhez"
DIALOG_WEB_INPUT_ZH="Jelszó WPA:"
DIALOG_WEB_SUBMIT_ZH="Küld"
DIALOG_WEB_ERROR_ZH="Hiba: A megadott jelszó helytelen!"
DIALOG_WEB_OK_ZH="Az Internet kapcsolat indul egy pillanatra."
DIALOG_WEB_BACK_ZH="Visza"
DIALOG_WEB_LENGHT_MIN_ZH="Jelszó nem lehet kevesebb, mint 7 karakter"
DIALOG_WEB_LENGHT_MAX_ZH="A jelszó kevesebb mint 64 karakter kell legyen"

**Comment by strasharo** [comment]
Added. :ok_hand:

**Comment by strasharo** [comment]
@juanxito91:

Could you, please, translate these to Spanish:
DIALOG_WEB_INFO_ENG="For security reasons, enter the <b>WPA</b> key to access the Internet"
DIALOG_WEB_INPUT_ENG="Enter your WPA password:"
DIALOG_WEB_SUBMIT_ENG="Submit"
DIALOG_WEB_ERROR_ENG="<b><font color=\"red\" size=\"3\">Error</font>:</b> The entered password is <b>NOT</b> correct!</b>"
DIALOG_WEB_OK_ENG="Your connection will be restored in a few moments."
DIALOG_WEB_BACK_ENG="$general_back"
DIALOG_WEB_LENGHT_MIN_ENG="The password must be more than 7 characters"
DIALOG_WEB_LENGHT_MAX_ENG="The password must be less than 64 characters"


Thanks.

**Comment by juanxito91** [comment]
Done, @strasharo 

**SPANISH:**

DIALOG_WEB_INFO_ENG="Por razones de seguridad, teclea tu clave WPA para acceder a internet"
DIALOG_WEB_INPUT_ENG="Teclea tu contraseña WPA:"
DIALOG_WEB_SUBMIT_ENG="Enviar"
DIALOG_WEB_ERROR_ENG="Error: La contraseña introducida NO es correcta"
DIALOG_WEB_OK_ENG="Tu conexión será restaurada en unos pocos minutos"
DIALOG_WEB_BACK_ENG="Atrás"
DIALOG_WEB_LENGHT_MIN_ENG="La contraseña debe ser más de 7 caracteres"
DIALOG_WEB_LENGHT_MAX_ENG="La contraseña debe ser menos de 64 caracteres"

**Comment by strasharo** [comment]
Thanks. :)

**Comment by NikosVlagoidis** [comment]
Greek Translation:

DIALOG_WEB_INFO_ZH="Για λόγους ασφάλειας, εισάγετε το WPA κωδικό για να έχετε πρόσβαση στο Internet"
DIALOG_WEB_INPUT_ZH="Εισάγετε τον WPA κωδικό:"
DIALOG_WEB_SUBMIT_ZH="Εισαγωγή"
DIALOG_WEB_ERROR_ZH="Λάθος: Ο κωδικός ΔΕΝ είναι σωστός!"
DIALOG_WEB_OK_ZH="Η συνδεσή σας θα αποκατασταθεί σε λίγα λεπτά"
DIALOG_WEB_BACK_ZH="Πίσω"
DIALOG_WEB_LENGHT_MIN_ZH="Ο κωδικός πρέπει να είναι πάνω από 7 χαρακτήρες"
DIALOG_WEB_LENGHT_MAX_ZH="Ο κωδικός πρέπει να είναι λιγότερο από 64 χαρακτήρες"

**Comment by strasharo** [comment]
Ευχαριστώ @NikosVlagoidis . Θα προσθέσω την μετάφραση αργότερα. :ok_hand:

**Comment by edwardyeung** [comment]
DIALOG_WEB_INFO_ENG="为了您的安全考量, 请输入 <b>WPA</b> 密码以重新连接网络"
DIALOG_WEB_INPUT_ENG="输入您的WPA密码:"
DIALOG_WEB_SUBMIT_ENG="连接"
DIALOG_WEB_ERROR_ENG="<b><font color=\"red\" size=\"3\">Error</font>:</b> 您输入的密码 <b>错误</b>!</b>"
DIALOG_WEB_OK_ENG="您的无线网络将会在短时间内恢复"
DIALOG_WEB_BACK_ENG="返回"
DIALOG_WEB_LENGHT_MIN_ENG="密码最少要有8个字符!"
DIALOG_WEB_LENGHT_MAX_ENG="密码必须少于64个字符!"

**Comment by deltaxflux** [comment]
Thank you

**Comment by strasharo** [comment]
Thanks @edwardyeung . I noticed that you left the "Error" word in English. Can you, please, translate that to Chinese as well?
Currently we have it as:
`DIALOG_WEB_ERROR_ZH="Error: 您输入的密码 <b>错误!"
`

**Comment by edwardyeung** [comment]
`DIALOG_WEB_ERROR_ZH="出错了: 您输入的密码<b> 错误</b>!" `

**Comment by strasharo** [comment]
Thanks, updated.

**Comment by strasharo** [comment]
@edwardyeung can you, please, translate this one as well:
`DIALOG_WEB_ERROR_MSG_ENG="This field is required."`

Thank you.

**Comment by edwardyeung** [comment]
`DIALOG_WEB_ERROR_MSG_ENG="此处不能为空"`

**Comment by Re4mstr** [comment]
I don't know if this is wanted, but I took the liberty to translate it to Norwegian.

DIALOG_WEB_INFO_ZH="Av sikkerhetsmessige årsaker må WPA-nøkkelen skrives inn for å få tilgang til internett"
DIALOG_WEB_INPUT_ZH="Skriv inn ditt WPA-passord:"
DIALOG_WEB_SUBMIT_ZH="Send inn"
DIALOG_WEB_ERROR_ZH="Feilmelding: Passordet du skrev inn er IKKE riktig!"
DIALOG_WEB_OK_ZH="Din tilkobling vil snart bli gjenopprettet."
DIALOG_WEB_BACK_ZH="Tilbake"
DIALOG_WEB_LENGHT_MIN_ZH="Passordet må inneholde mer enn 7 tegn"
DIALOG_WEB_LENGHT_MAX_ZH="Passordet må inneholde maksimalt 64 tegn"

**Comment by strasharo** [comment]
Thanks @edwardyeung & @Re4mstr , I'll add them later today.

**Comment by strasharo** [comment]
@Re4mstr Could you, please, also translate this line:
`DIALOG_WEB_ERROR_MSG_ENG="This field is required."`
Thank you.

**Comment by Re4mstr** [comment]
DIALOG_WEB_ERROR_MSG_ENG="Dette feltet er nødvendig."

**Comment by strasharo** [comment]
Thank you. :+1:
