### ISSUE TITLE
keep getting logged out 

### ISSUE THREAD

**Issue by Dee1463** [deltaxflux/fluxion#83]
I'm not sure what the problem is I run the script and it starts up just fine I get to select my wifi adapter sometimes even a step further. Next thing that happens is I get forced back to the kali log in screen. Has anyone else had this issue? Is it just something I'm doing wrong? I would be really grateful for any help I could get. fluxion really looks amazing I really wanna try it out.

**Comment by devrajashwin** [comment]
just ,
use 
apt-get -f install 
apt-get update , /--fix-missing
apt-get upgrade  & apt-get dist-upgrade,
i hope this works after doing all these,
or just check ur sourece list 
gedit /etc/apt/source.list

**Comment by Dee1463** [comment]
Okay I will give this a try thank you very much for the help.

**Comment by deltaxflux** [comment]
@Dee1463 

I have never done this experience like that and I don't think that is a script problem. However which kali do you use? 

Flux / Fluxion is tested on: Kali 1 / Kali 2 / Kali 2.014 / Deepin / native Debian 8 / Wifilax 4.12 / Wifislax 4.13

@devrajashwin I don't think that is a dependency problem

**Comment by Dee1463** [comment]
Kali 2.014 I don't know what else to do everything is updated my source list is just the way it's supposed to be everything looks fine. I load the script choose my adapter then as soon as I select the option for all channels the screen goes black and then back at the damn log in screen.

**Comment by deltaxflux** [comment]
What is if you a custom channel.

**Comment by Dee1463** [comment]
well that's strange it worked, but when I started to use the deauth FUCKING log in screen damn that sucks.

**Comment by devrajashwin** [comment]
i need  to know if any new changes made or any new improvement is done in this project ,
like ,
1>  auto re-connect to fake same ap created by this application (like after deauth  them for there router and automatically get connect to the fake ap)
2>  redirect them to login page automatically (directlly)
 @deltaxflux

**Comment by deltaxflux** [comment]
Well you can't automatically redirect the client to fake AP because some responds are not equl

- Same BSSID and same SSID but

- Not the same "wireless security mode" (WPA / 2 whatever)

- If not every "part" is equal the device don't get connected to the fake AP automatically because the response isn't equal

You ignored me right? 

1.  Auto connect to the Fake AP is not possible

2. Redirection is working
