### ISSUE TITLE
wc: /tmp/TMPflux/dump-01.csv: No such file or directory

### ISSUE THREAD

**Issue by ouikoto** [deltaxflux/fluxion#84]
error encountered im currently using kali rolling

wc: /tmp/TMPflux/dump-01.csv: No such file or directory
./fluxion: line 1144: [: -le: unary operator expected
cat: /tmp/TMPflux/dump-01.csv: No such file or directory
expr: syntax error
                        WIFI LIST

 ID      MAC                      CHAN    SECU     PWR   WPS ESSID

grep: /tmp/TMPflux/dump-01.csv:: No such file or directory
grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines: No such file or directory

**Comment by deltaxflux** [comment]
So you had this issue after scanning ?. I'm not quite sure If your wifi card support monitoring. Fluxion is tested on a clean installed kali.

**Comment by ouikoto** [comment]
I have this wireless

02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 10)

thank you for the reply

**Comment by ouikoto** [comment]
or maybe do we have a list for the supported wif icard thanks again

**Comment by freeroute** [comment]
I have the same issue on Nethunter with Nexus 7. Other 2 PCs with OS kali
rolling working fine.

**Comment by strasharo** [comment]
Are you able to start monitor mode manually with airmon-ng and inject using aireplay-ng -9 ?

**Comment by freeroute** [comment]
Yes. Injection working.

**Comment by strasharo** [comment]
I was asking @ouikoto since he opened the initial issue. I performed a brief search and it looks like RTL8723BE is not capable of injection.

**Comment by ouikoto** [comment]
Thanks you so much strasharo looks like wifi card is not supported

aireplay-ng -9 wlan0
08:55:14  Trying broadcast probe requests...
08:55:16  No Answer...
08:55:16  Found 0 APs
