### ISSUE TITLE
Alfa AWUS051NH with ralink RT3572 chipset

### ISSUE THREAD

**Issue by kushujus** [deltaxflux/fluxion#85]
Kali linux stops working/stuck when i chose this adapter from the list.

**Comment by strasharo** [comment]
Are you able to switch the adapter manually do monitor mode and is it able to inject using aireplay-ng -9 ?

**Comment by kushujus** [comment]
yes, i can to switch this adapter to monitor mode manually, but i did non try to inject frames.

**Comment by kushujus** [comment]
i will try and let you know

**Comment by kushujus** [comment]
root@XXXXXX:~# aireplay-ng -9 wlan1mon
20:16:57  Trying broadcast probe requests...
20:16:59  No Answer...
20:16:59  Found 2 APs

20:16:59  Trying directed probe requests...
20:16:59  XX:XX:XX:XX:XX:XX - channel: 11 - 'BTHubX-XXXX'
20:17:05   0/30:   0%

20:17:05  XX:XX:XX:XX:XX:XX - channel: 9 - 'upXXXXXXXX'
20:17:11   0/30:   0%

**Comment by deltaxflux** [comment]
The problem is that interface don't support injection. Here what it look like if it is supported

06:48:03  Trying broadcast probe requests...
**06:48:03  Injection is working!**
06:48:05  Found 3 APs
...
