### ISSUE TITLE
php7-cgi

### ISSUE THREAD

**Issue by kushujus** [deltaxflux/fluxion#86]
If fluxion not working with php7-cgi, how to downgrade to php5-cgi? Because php5-cgi is not available...

**Comment by deltaxflux** [comment]
Use debian repos and deinstall php7-cgi

**Comment by strasharo** [comment]
Fluxion is already compatible with PHP 7, I fixed check.php

**Comment by Schwarzhund** [comment]
Does this mean that fluxion is **ONLY** compatible with **PHP7** now, _and no longer with **php5**_?

**Comment by deltaxflux** [comment]
Both work php5 and php7

**Comment by Vigilence** [comment]
The script still calls for php5 during startup.

![screenshot 118](https://cloud.githubusercontent.com/assets/16742086/19027067/c7cfd6c6-88fa-11e6-8102-6cd0c804ebd8.png)
