### ISSUE TITLE
Upgrade pages

### ISSUE THREAD

**Issue by JunaidShafi** [deltaxflux/fluxion#87]
Upgrade tplink page is not in menu as it has most outstanding interface in all pages

**Comment by JunaidShafi** [comment]
Of pages we wish to show people

**Comment by deltaxflux** [comment]
Yeah that's true, I will remove the page because I don't like the it and I feel more comfortable with creating my own one

**Comment by JunaidShafi** [comment]
Can u tell me how can i activate that page because that is a general one and i would like to use it
