### ISSUE TITLE
[SOLVED] fluxion kills internet connection when setting desired interface to managed

### ISSUE THREAD

**Issue by totial** [deltaxflux/fluxion#90]
Hello, first of all i love this program. you did an amazing job!!
Im using a remote pc accessing it with teamviewer. To get an internet connection i had to add an usb card to my remote pc. Im also able to use airodump with just one wifi card in monitor mode (iwconfig wlan0 mode monitor). Doing it this way i dont lose my internet connection and can stay connected over teamviewer. I could also do airmon-ng check kill and then airmon-ng start wlan0 but that kills my internet connection. So im wondering if there is a way to make fluxion to configure the desired wlanx in monitor mode without killing dhcp, wpa_supplicant, etc?
cheers

**Comment by strasharo** [comment]
It can be achieved, however you'll need to perform some additional configuration in the OS in order to prevent NetworkManager from trying to manage the interfaces used by fluxion. One way to achieve this (there are others for sure, but that's what I'm using usually) is not add the following lines to /etc/network/interfaces in Kali:

> iface wlan0 inet manual
> iface mon0 inet manual

You must define all of the wireless interface you're using, plus the monitor interface that's being created by fluxion (fluxion uses a custom airmon script, which is creating the monitor interfaces as monX instead of wlanXmon). This way NetworkManager ignores these interfaces and doesn't interfere with them while fluxion works.
After adding the configuration above, you can comment out the lines in fluxion which kill dhcp and stop NetworkManager, so your connection doesn't get dropped. 

Hope this helps.

**Comment by totial** [comment]
Ok, great. for now this is my interfaces configuration file (im on raspberry witch uses debian if im not wrong):

```
`auto lo
iface lo inet loopback

#iface eth0 inet manual
iface eth0 inet dhcp

allow-hotplug wlan0
auto wlan0
iface wlan0 inet dhcp
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf`

#wlan1 is the usb interface for auditioning purposes. its not managed my any service!
```
The interface im using for auditioning is the wlan1. I can put it in monitor mode with iwconfig or airmon and everything works perfect without NetworkManager interfering. (i dont need to airmon-ng check kill to avoid "fixed channel: -1" and that kind of troubles) 
Now i have to find the lines in fluxion wich kill dhcp and stop networkmanager. I watched the code without being sure witch one they are. 
Are they this ones from line nr 1041?
line 1037:
`readarray -t softwaremolesto < <(./airmon check $PREWIFI | tail -n +8 | grep -v "on interface" | awk '{ print $2 }')`
`...`
and later in line 1041 i guess it kills all services wich could interfere with aricrack tools:
`for molesto in "${softwaremolesto[@]}"; do
	killall "$molesto" &>$flux_output_device
done`

As its called "software molesto" i guess we dont want it 
If someone have a better understanding of the program please let me know
thanks

**Comment by totial** [comment]
Ok so just tried commenting that 3 lines and everything works as a charm. Finally I also commented the lines which restart NetworkManager when exiting the tool. That way i dont get disconnected for some seconds.
Thank for your help

**Comment by ReneTejeda** [comment]
can you please tell me the lines you modified ?  i commented lines 1037 and 1041, and i'm getting a error when i select "scan for all channels" 

thanks.

**Comment by totial** [comment]
Just comment the 3 consecutive lines from 1041. (Leave 1037 uncommented as it just collect info about the processes which are going to be killed later in 1041).  Be aware this avoid killing services which in some linux distributions interfere with aircrack tools like aireplay (error => fixed channel: -1).  I recommend you to test this tools without running "airmon-ng check kill" before using fluxion.  Hope this helps

**Comment by ReneTejeda** [comment]
ok, i still getting the error:

> > wc: /tmp/TMPflux/dump-01.csv: no such file or directory
> ./fluxion: line 1144: [: -le: unary operator expected
>  cat: /tmp/TMPflux/dump-01.csv: no such file or directory
> expr: syntax error

i have this line commented :
`for molesto in "${softwaremolesto[@]}"; do killall "$molesto" &>$flux_output_device done`
`sleep 0.5 `
`modprobe "$WIFIDRIVER" &>$flux_ouput_device 2`

i'm using raspbian on raspberry pi 3

thanks

**Comment by totial** [comment]
You should open a new thread as that error has nothing to do with loosing the internet connection.

**Comment by strasharo** [comment]
Added an environment variable to keep the network.

`export KEEP_NETWORK=1`
