### ISSUE TITLE
Crashing with rt2800usb

### ISSUE THREAD

**Issue by drpau** [deltaxflux/fluxion#91]
it appears that the current rolling release and version 43 (and also 44 as i just updated) of fluxion is causing me issues.

Im not able to pinpoint it but i am able to relpicate it each time.

I am running latest release (apt-get update / upgrade / dist-update) and also running version 44 of fluxion

i have a laptop with 3 interface cards. eth0 / wlan0 /wlan1

eth0 is attached to my current router and has internet access
wlan1 is an external Ralink RT2870/3070 rt2800usb wireless card.

Fluxion in the past has worked however now, when i:
./fluxion
select english
select wlan1 (Ralink RT2870/3070 rt2800usb)
it freezes my laptop.

only way to resolve is to hard boot it and start again.

I cant see easily due to not having the knowledge what the script does when selecting the interface card but am happy to work through any testing / reporting needed.

Thanks

//edit:
when going through the same motions selecting wlan0 as the interface fluxion does not crash. (Atheros AR9285 ath9k). Unfortunately this isnt a very well powered card. my RALink is an external yagi and obviously the antenna of choice.

**Comment by strasharo** [comment]
Are you able to bring the interface manually in monitor mode and confirm that it is able to inject using aireplay-ng -9?

**Comment by drpau** [comment]
yes - doing manual injection works fine - please note that in version 23 (which was the last version i used of fluxion before all the additional languages were added, it was working).

here is output of airmon-ng

airmon-ng 

PHY	Interface	Driver		Chipset

phy3	wlan0mon	rt2800usb	Ralink Technology, Corp. RT2870/RT3070

**Comment by deltaxflux** [comment]
Well I don't change sometime in the setinterface function. So did you update packets? Or did you change something anywhere else?

**Comment by drpau** [comment]
i regularly update (apt-get update / upgrade / dist-upgrade). other than that i do not install packages manually.

Is there a way of reinstalling all the dependencies incase one didnt install correctly even though reporting?

Keep in mind that the other wireless card i have on this laptop works fine.  its ONLY when selecting the RA card that it freezes.

**Comment by strasharo** [comment]
In fluxion on line 1049 you have a rmmod statement and on 1056 you have a modprobe. Can you, please, try commenting those lines out to see if that helps avoid the crashes?

**Comment by drpau** [comment]
on my fluxion i dont have what you mentioned on the particular lines however i have found this which is similarly
line 1039: rmmod -f "$WIFIDRIVER" &>$flux_output_device 2>&1
line 1046: modprobe "$WIFIDRIVER" &>$flux_output_device 2>&1

both have been commented out - will test and edit comment with result.

**Comment by strasharo** [comment]
The reason for the lines not matching might be that you're running an outdated version. Please update it regularly via a git pull. :) 

Anyway, could you, please, confirm the exact model of the wireless adapter, that was causing this behaviour?

**Comment by drpau** [comment]
thanks - i have just done another git pull tonight to get the latest release and will report back and test.

as for exact model, i am not 100% sure on how to provide that hwoever this is the link to the product. http://danets.com/turbotenna/UsbYagi.php

**Comment by drpau** [comment]
thanks - i have just done another git pull tonight to get the latest release and will report back and test.

as for exact model, i am not 100% sure on how to provide that however this is the link to the product. http://danets.com/turbotenna/UsbYagi.php

//edit
i am on version 0.23 release 54 and the same crash happened when selecting my network card

**Comment by Vigilence** [comment]
This issue still exists as per #161 .

**Comment by strasharo** [comment]
Have you tried to remove the rmmod and modprobe statements?

**Comment by Vigilence** [comment]
Currently waiting for VMware tools to install before I go ahead and edit the lines.  Will be a minute or so more.

**Comment by strasharo** [comment]
So @Vigilence , as far as I understood commenting out those 2 lines fixed the issue for you, right?
Could you, please, provide me with the output of airmon-ng being launched without any arguments?

**Comment by Vigilence** [comment]
As per strasharos suggestion editing the following lines in the main fluxion script

rmmod -f "$WIFIDRIVER" &>$flux_output_device 2>&1
modprobe "$WIFIDRIVER" &>$flux_output_device 2>&1

by putting a # in front of each line temporarily fixes the issue.

#rmmod -f "$WIFIDRIVER" &>$flux_output_device 2>&1
#modprobe "$WIFIDRIVER" &>$flux_output_device 2>&1

I would propose adding this resolution to the wiki until its resolved coding wise.

**Comment by strasharo** [comment]
@drpau Could you, please, provide me with the output of airmon-ng for the problematic card?

**Comment by strasharo** [comment]
@Vigilence what's the output from airmon-ng?

**Comment by Vigilence** [comment]
Hi strasharo, the solution indeed worked as suggested.  

Here is the output of airmon without any arguments added.


![screenshot 110](https://cloud.githubusercontent.com/assets/16742086/19023046/ce414276-88b2-11e6-9f78-85708128a34e.png)

**Comment by strasharo** [comment]
Which of the two cards is showing the issue the rtl8187 one or rt2800usb?

**Comment by Vigilence** [comment]
The one that works with no issues is the rtl8187, the one that requires editing the script is the rt2800usb.

**Comment by strasharo** [comment]
Okay, so far we have two reported crashes with rt2800usb running inside a vmware VM. @drpau could you, please, confirm if you're using rt2800usb as well and if you were running it in a VM?

**Comment by drpau** [comment]
i am not running it in a VM. it is a dedicated machine

**Comment by rundemblue** [comment]
Hi @strasharo - I have confirmed that it is working when we comment out the two lines.
Running on
- VM (Kali Linux 3 - 4.7.5)
- rt2800USB

**Comment by strasharo** [comment]
Can someone pull the latest version and confirm if it fixes the issue with rt2800usb drivers?

**Comment by drpau** [comment]
can confirm - 0.23 rev 58:
does not crash kali 2.0 (rolling updates and all) on a dedicated laptop.

**Comment by JustMev** [comment]
I have the same issue with rev0.23 / 118 fluxion latest telling me that ralink 2780/3070 rt2800USB is not compatible old version was compatible running on raspberry pi 3 with kali linux latest rolling I will try comment out those 2 lines and report back

**Comment by JustMev** [comment]
after I comment out those 2 lines following error

Rev0.23 - 118
lfluxion.py - line 1520 - rmmod -f "$WIFIDRIVER" &>$flux_output_device 2>&1
Line 1533 - modprobe "$WIFIDRIVER" &>$flux_output_device 2>&1
-------------------------------------------------------------------------------------------------------
after comminting error below
--------------------------------------------------------------------------------------------------------

                     FLUX 0.23 (rev.  118) by  deltax
            Page: https://github.com/deltaxflux/fluxion
                              Latest rev. [118]

./fluxion: line 1521: syntax error near unexpected token `fi'
./fluxion: line 1521: `         fi'
root@kali:~/fluxion#
