### ISSUE TITLE
dhcp not allowing connections

### ISSUE THREAD

**Issue by almandin** [deltaxflux/fluxion#93]
Hello,
Fluxion is awesome, though, when setting up the fake AP, the dhcp do not deliver ip addresses to the clients trying to connect to it :/ (it is not possible to connect to the fake ap)

The dhcpd.conf generated by fluxion is the following : 
##################################################
authoritative;
default-lease-time 600;
max-lease-time 7200;
subnet 192.168.1.128 netmask 255.255.255.128 {
option subnet-mask 255.255.255.128;
option broadcast-address 192.168.1.255;
option routers 192.168.1.129;
option domain-name-servers 8.8.8.8;
range 192.168.1.130 192.168.1.140;
}
##################################################
Everything looks fine, any idea ?
Thank you very much

**Comment by strasharo** [comment]
Can you confirm that the dhcd process is running at all?
Also what wireless adapter are you using?

**Comment by eduardogt** [comment]
Verifies that the adapter with which these trying to connect this in DHCP Automatic and not static.
