### ISSUE TITLE
Ability to Customize SSID

### ISSUE THREAD

**Issue by darklord81** [deltaxflux/fluxion#94]
Given the new Facebook Portal that's now part of fluxion, it would be great if the user had an option to create a customized SSID instead of just mimicing other SSID's in the area. 

Customised SSID could be anything the user wants. Eg.  FreeWifi, Public Wifi, etc.

In addition, the option to mimic an Open SSID and use a FB Portal while deauthing the original AP(s) would be great.

**Comment by deltaxflux** [comment]
This feature is moved to Ares. For more details checkout my other project ares.
