### ISSUE TITLE
FakeAP (Hostapd) Issue

### ISSUE THREAD

**Issue by orphee225** [deltaxflux/fluxion#95]
Hi,
First of all, thanks for this prgm.

When the FakeAP attack is launched, victim can connect and go to login page where he puts his WPA key. But from this moment on, nothing happens. His web browser says that the required page can't be loaded. For exemple, I can see in his url bar : yahoo.com/check.php.

Nothing in fluxion's opened consoles.

I'm on KALI LINUX 2.0 (SANA).

Any idea ?

**Comment by strasharo** [comment]
Can you, please, try updating fluxion? Yesterday I fixed an issue which was causing similar behaviour.

**Comment by orphee225** [comment]
Ok @strasharo, thanks for your job. I cracked my first WPA Key lol.
![screenshot from 2016-09-03 17 53 47](https://cloud.githubusercontent.com/assets/21972335/18226751/eec6c7fe-7210-11e6-9740-46381fb3235c.png)

**Comment by strasharo** [comment]
The issue is no longer present, right?

**Comment by orphee225** [comment]
Right !

**Comment by orphee225** [comment]
Hi !
After few days using your wonderful Fluxion, I noticed that we can get WPA keys only from connected client's browsers. In the case of android users that only connect from FacebookAPP or InstagramAPP... is there a way to send them to their mobile's web browser ? 
or just make a kind of popup window in order to let them type the wpa key ?
