### ISSUE TITLE
Installer.sh halt on systemd mostly.

### ISSUE THREAD

**Issue by iUniqu3** [deltaxflux/fluxion#96]
Hey, @first great work! I tryed to install @kali rolling release. It is an oracle vm machine. I can provide screenshots next time. I try it out again later, deep in the night by me here. Now more to the problem. Script is going well until first systemd log entry. Then I just aborted the screen and it kept on going. The script halt multiple times after that, mostly @systemd. After all the installation goes kinda well and I can run fluxion. Kinda crazy, it seems to work!

**Comment by strasharo** [comment]
The dependency installer has nothing to do with systemd. If you have some package problem in your operating system, that's out of the scope of fluxion.

**Comment by deltaxflux** [comment]
[](url)
