### ISSUE TITLE
HALT?

### ISSUE THREAD

**Issue by iUniqu3** [deltaxflux/fluxion#98]
http://imgur.com/a/vp6rI http://imgur.com/a/OSdrb this is how the halt is looking like. Can you just tell me what I do wrong on a clean updated KALI system to get this stuff? I can only exit it and it goes on. Why is systemd and dbus halting? Sorry when I bother you. If it is again my fault @kali, I stop asking. Just please give me a hint what is going on?

EDIT: unattended upgrades where this come from? Can't find it in your Installer.

**Comment by strasharo** [comment]
It appears that you have some issues in your OS environment and troubleshooting it is completely out of our scope. If the installer script is not working for you, just install the missing dependencies manually via apt-get, they're all present in the default kali repositories.

**Comment by iUniqu3** [comment]
Sounds good. I try what you say. I just mail this to the Kali Team.
